'use client';
import{useState}from'react';
import{buildLegalKnowledgeGraph,LEGAL_KNOWLEDGE_SCENARIOS,type LegalKnowledgeScenarioId}from'../../../../../../packages/release/src/legal-knowledge-graph-engine';
import s from'../legal-memory.module.css';

const ids:LegalKnowledgeScenarioId[]=['MEMORY-CONNECTED','AUTHORITY-UNVERIFIED','ACCESS-RESTRICTED','CONFLICTING-OUTCOME','LESSON-UNREVIEWED'];
const memory=[['01','MATTER'],['02','AUTHORITY'],['03','ARGUMENT'],['04','DOCUMENT'],['05','EXPERT'],['06','OUTCOME'],['07','WORKFLOW'],['08','LESSON']];

export default function FirmMemoryStory(){const[index,setIndex]=useState(0),id=ids[index],result=buildLegalKnowledgeGraph(LEGAL_KNOWLEDGE_SCENARIOS[id]);return <section className={s.story} data-graph-state={id}><header className={s.status} role="status" aria-live="polite" aria-atomic="true"><small>MEMORY STATE {index+1}/5 · {id}</small><h2>{result.status}</h2><p>{result.nonClaims[0]}</p></header><ol className={s.memoryPath} aria-label="Institutional legal memory pathway">{memory.map(([number,stage])=><li key={stage}><span aria-hidden="true">{number}</span><b>{stage}</b><i aria-hidden="true"/></li>)}</ol><div className={s.storyAction}><button type="button" onClick={()=>setIndex(value=>(value+1)%ids.length)}>ASSEMBLE NEXT CONNECTION</button><p>{result.relationships[0]??'The fixed graph has no recorded relationship.'}</p></div><div className={s.memoryEquation} aria-label="Reusable legal knowledge requires governed states"><span>PROVENANCE</span><b aria-hidden="true">+</b><span>CURRENT-LAW CHECK</span><b aria-hidden="true">+</b><span>ACCESS REVIEW</span><b aria-hidden="true">+</b><span>REUSE AUTHORITY</span></div><aside className={s.warning}><h3>Institutional memory is not institutional permission.</h3><p>Being able to find a document or relationship does not establish privilege, confidentiality, citation validity, current law, relevance, access, disclosure authority, or permission to reuse.</p></aside><p className={s.note}>Synthetic fixtures only; no real client, matter, person, or protected information. No legal advice, representation, attorney-client relationship, privilege determination, confidentiality determination, current-law validation, citation checking, or inference that reuse is authorized.</p></section>}
