'use client';
import {useMemo,useState} from 'react';
import s from './service-path.module.css';
type Mode='BASELINE'|'MORE REPEATABLE'|'MORE JUDGMENT'|'CUT THE WASTE';
type Lane='AUTOMATE'|'KEEP HUMAN'|'REMOVE';
const modes:Mode[]=['BASELINE','MORE REPEATABLE','MORE JUDGMENT','CUT THE WASTE'];
const base=[
 {name:'Collect intake',lane:'AUTOMATE' as Lane},{name:'Interpret unusual facts',lane:'KEEP HUMAN' as Lane},{name:'Copy status twice',lane:'REMOVE' as Lane},{name:'Schedule follow-up',lane:'AUTOMATE' as Lane},{name:'Approve exception',lane:'KEEP HUMAN' as Lane}
];
function transform(mode:Mode){return base.map(step=>{if(mode==='MORE REPEATABLE'&&step.name==='Schedule follow-up')return {...step,lane:'AUTOMATE' as Lane};if(mode==='MORE REPEATABLE'&&step.name==='Interpret unusual facts')return {...step,lane:'KEEP HUMAN' as Lane};if(mode==='MORE JUDGMENT'&&step.name==='Collect intake')return {...step,lane:'KEEP HUMAN' as Lane};if(mode==='MORE JUDGMENT'&&step.name==='Schedule follow-up')return {...step,lane:'KEEP HUMAN' as Lane};if(mode==='CUT THE WASTE'&&step.name==='Copy status twice')return {...step,lane:'REMOVE' as Lane};return step})}
export default function ServicePathSplit(){const [mode,setMode]=useState<Mode>('BASELINE');const steps=useMemo(()=>transform(mode),[mode]);return <div className={s.app}><div className={s.controls} role="group" aria-label="Service path scenario">{modes.map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m}</button>)}</div><section className={s.stage} aria-live="polite"><header><span>SERVICE PATH / {mode}</span><h2>One service. Three different futures.</h2><p>Software is not the destination for every repeated step. Change the conditions and watch the path separate.</p></header><div className={s.flow}>{steps.map((step,i)=><article key={step.name} data-lane={step.lane}><small>{String(i+1).padStart(2,'0')}</small><strong>{step.name}</strong><span>{step.lane}</span></article>)}</div><div className={s.lanes}>{(['AUTOMATE','KEEP HUMAN','REMOVE'] as Lane[]).map(lane=><article key={lane} data-lane={lane}><h3>{lane}</h3>{steps.filter(x=>x.lane===lane).map(x=><p key={x.name}>{x.name}</p>)}</article>)}</div></section><section className={s.argument}><span>THE POINT</span><h2>Do not turn the whole service into software.</h2><p>Separate the repeated work first. Encode stable rules. Preserve expert judgment where consequence, ambiguity, and exceptions matter. Remove steps whose only purpose is to maintain the old process.</p></section></div>}
