'use client';
import { FormEvent, useState } from 'react';
import { ProtocolResult, type ReviewAssessment, type ReviewDimension } from '@rn/results';

const riskOptions=['Low — internal assistance with limited consequence','Moderate — output informs a consequential workflow','High — output may materially affect a person, right, safety, money, access, or legal position'];
const examples=[['Legal','Draft legal research or analysis'],['People','Applicant, employee, student, or benefit decision'],['Health','Clinical-adjacent summary or recommendation'],['Operations','Internal workflow recommendation'],['Other','Another AI-assisted decision']];

export function HumanReviewForm(){
  const [mode,setMode]=useState<'quick'|'design'>('quick');
  const [assessment,setAssessment]=useState<ReviewAssessment|null>(null);
  function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault();const fd=new FormData(e.currentTarget);const val=(k:string)=>String(fd.get(k)||'').trim();const risk=val('risk');
    const dims:ReviewDimension[]=[];const gaps:string[]=[];const add=(key:string,label:string,score:0|1|2,note:string,gap?:string)=>{dims.push({key,label,score,note});if(score<2&&gap)gaps.push(gap)};
    add('competence','Reviewer competence',val('reviewerQuality')==='qualified'?2:val('reviewerQuality')==='some'?1:0,val('reviewerQuality')==='qualified'?'Qualified role identified':val('reviewerQuality')==='some'?'Some expertise, unclear sufficiency':'No qualified reviewer', 'Name a reviewer with enough domain and system competence to challenge the output.');
    add('timing','Timing',val('timing')==='before'?2:val('timing')==='conditional'?1:0,val('timing')==='before'?'Before consequential action':val('timing')==='conditional'?'Only under some conditions':'After or undefined','Move review before the consequential action, with explicit triggers for exceptions.');
    add('evidence','Evidence access',val('evidenceAccess')==='full'?2:val('evidenceAccess')==='partial'?1:0,val('evidenceAccess')==='full'?'Underlying evidence available':val('evidenceAccess')==='partial'?'Partial evidence available':'Output only','Give the reviewer the inputs, sources, context, uncertainty, and conflicting evidence needed to judge the output.');
    add('authority','Authority',val('authority')==='stop'?2:val('authority')==='recommend'?1:0,val('authority')==='stop'?'Can change or stop outcome':val('authority')==='recommend'?'Can recommend only':'No practical authority','Give the reviewer practical authority to reject, revise, override, stop, or escalate.');
    add('escalation','Escalation',val('escalation')==='defined'?2:val('escalation')==='informal'?1:0,val('escalation')==='defined'?'Defined fallback path':val('escalation')==='informal'?'Informal escalation':'No escalation path','Define what happens when the reviewer disagrees, uncertainty remains, or the system fails.');
    add('record','Review record',val('recording')==='structured'?2:val('recording')==='basic'?1:0,val('recording')==='structured'?'Decision + rationale recorded':val('recording')==='basic'?'Basic record only':'No review record','Record reviewer, evidence inspected, decision, changes, rationale, escalation, and final outcome.');
    add('capacity','Practical capacity',val('capacity')==='yes'?2:val('capacity')==='strained'?1:0,val('capacity')==='yes'?'Time and workload support challenge':val('capacity')==='strained'?'Review capacity is strained':'Rubber-stamping likely','Give reviewers enough time, usable interfaces, manageable workload, and incentives to disagree.');
    add('testing','Control testing',val('testing')==='measured'?2:val('testing')==='adHoc'?1:0,val('testing')==='measured'?'Overrides and outcomes measured':val('testing')==='adHoc'?'Ad hoc review of effectiveness':'Never tested','Track overrides, disagreements, errors, complaints, escalations, and outcomes to test whether review works.');
    let score=dims.reduce((n,d)=>n+d.score,0);const maxScore=16;const grade:ReviewAssessment['grade']=score>=13?'Strong':score>=8?'Partial':'Weak';
    const priorities=[...gaps];if(risk.startsWith('High')){const timing=dims.find(d=>d.key==='timing')!;const authority=dims.find(d=>d.key==='authority')!;const evidence=dims.find(d=>d.key==='evidence')!;if(timing.score<2)priorities.unshift('HIGH-CONSEQUENCE USE: review should ordinarily occur before the consequential action, not after it.');if(authority.score<2)priorities.unshift('HIGH-CONSEQUENCE USE: a reviewer without power to change or stop the outcome is a weak safeguard.');if(evidence.score<2)priorities.unshift('HIGH-CONSEQUENCE USE: reviewers need sufficient evidence and context to independently assess the output.');}
    const detail=(k:string,f:string)=>val(k)||f;const protocol=`REVIEW OBJECT\n${detail('decision',detail('example','Not specified'))}\n\nCONSEQUENCE CONTEXT\n${risk||'Not specified'}\n${detail('impact','Affected person, right, safety issue, financial consequence, workflow, or downstream decision: not specified.')}\n\nREVIEWER\n${detail('reviewer','Role not specified')} — ${dims[0].note}\n\nREVIEW TRIGGER\n${dims[1].note}${val('trigger')?` — ${val('trigger')}`:''}\n\nEVIDENCE\n${dims[2].note}${val('evidence')?` — ${val('evidence')}`:''}\n\nSTANDARD\n${detail('standard','No explicit decision standard specified.')}\n\nAUTHORITY\n${dims[3].note}\n\nFAILURE / ESCALATION\n${dims[4].note}${val('failure')?` — ${val('failure')}`:''}\n\nREVIEW RECORD\n${dims[5].note}\n\nPRACTICAL CAPACITY\n${dims[6].note}\n\nCONTROL TESTING\n${dims[7].note}\n\nIMPLEMENTATION TEST\nCan a qualified person understand enough of the system and decision context to critically assess the output, intervene before consequence, change or stop the outcome when warranted, escalate uncertainty, and leave evidence that the review actually happened?`;
    setAssessment({score,maxScore,grade,gaps,priorities:[...new Set(priorities)],dimensions:dims,protocol});setTimeout(()=>document.getElementById('generated-protocol')?.scrollIntoView({behavior:'smooth',block:'start'}),0);
  }
  return <><div className="mode-switch" role="group" aria-label="Assessment mode"><button type="button" className={mode==='quick'?'active':''} onClick={()=>setMode('quick')}><strong>60-second Quick Check</strong><span>Diagnose an existing workflow</span></button><button type="button" className={mode==='design'?'active':''} onClick={()=>setMode('design')}><strong>Design the Control</strong><span>Turn the diagnosis into a protocol</span></button></div><form className="form-panel oversight-form" onSubmit={submit}><div className="form-intro"><div className="eyebrow">{mode==='quick'?'Is the human actually a control?':'Design the control, not the slogan'}</div><p>{mode==='quick'?'Choose what is true today. You will get a dimensional diagnosis and the three gaps to fix first.':'Add the implementation details needed to turn the diagnostic into a usable review protocol.'} Nothing you enter is sent anywhere; this prototype runs in your browser.</p></div>
    <Section n="01" title="Decision" hint="Start with a real AI-assisted decision or output."><Select name="example" label="Use case" options={['Choose…',...examples.map(x=>`${x[0]} — ${x[1]}`)]}/><Field name="decision" label="Describe it in your own words (optional)" placeholder="e.g. AI drafts research that an attorney may rely on"/><Select name="risk" label="Consequence level" options={riskOptions}/>{mode==='design'&&<Area name="impact" label="Who or what could be affected if this is wrong?"/>}</Section>
    <Section n="02" title="The human" hint="Competence and practical capacity matter as much as presence."><Select name="reviewerQuality" label="Reviewer competence" options={['Choose…','qualified — Domain-qualified and understands relevant system limitations','some — Some relevant expertise; sufficiency is unclear','none — No defined qualification']}/>{mode==='design'&&<Field name="reviewer" label="Reviewer role" placeholder="e.g. supervising attorney with subject-matter competence"/>}<Select name="capacity" label="Can they realistically perform the review?" options={['Choose…','yes — Enough time, information, workload capacity, and freedom to disagree','strained — Review is possible but time/workload/interface creates pressure','no — Review is nominal or likely to become rubber-stamping']}/></Section>
    <Section n="03" title="Review moment" hint="Review after consequence is not the same safeguard as review before it."><Select name="timing" label="When does review happen?" options={['Choose…','before — Before the consequential action or external use','conditional — Only when a threshold, exception, or sample triggers review','after — After the action, or timing is undefined']}/>{mode==='design'&&<Field name="trigger" label="Exact trigger" placeholder="Before filing; below confidence threshold; before adverse action…"/>}</Section>
    <Section n="04" title="What the reviewer can know" hint="A reviewer cannot challenge what they cannot inspect."><Select name="evidenceAccess" label="Evidence access" options={['Choose…','full — Inputs, sources/context, output, uncertainty/conflicts are available','partial — Some supporting information is available','none — Reviewer mostly sees the AI output']}/>{mode==='design'&&<><Area name="evidence" label="Evidence set"/><Area name="standard" label="Decision standard"/></>}</Section>
    <Section n="05" title="Power" hint="Can the human actually alter what happens?"><Select name="authority" label="Reviewer authority" options={['Choose…','stop — Can reject, revise, override, stop, or escalate','recommend — Can recommend but another actor/system decides','observe — Can observe/comment but cannot change outcome']}/><Select name="escalation" label="When review fails" options={['Choose…','defined — Defined second review, manual fallback, stop, incident, or escalation path','informal — People know who to ask but the path is not designed','none — No defined fallback']}/>{mode==='design'&&<Area name="failure" label="Failure / escalation procedure"/>}</Section>
    <Section n="06" title="Proof and learning" hint="Meaningful oversight should leave evidence and be tested."><Select name="recording" label="Review record" options={['Choose…','structured — Reviewer, evidence, decision, rationale, override/escalation, and outcome are recorded','basic — Approval/rejection or timestamp only','none — No durable review record']}/><Select name="testing" label="Is the control itself evaluated?" options={['Choose…','measured — Overrides, disagreements, errors, complaints, escalations, and outcomes are reviewed','adHoc — Problems are discussed when noticed','never — Review effectiveness is not evaluated']}/></Section>
    <div className="submit-zone"><button className="btn btn-large" type="submit">{mode==='quick'?'Diagnose my human review →':'Build my review protocol →'}</button><span>8 dimensions · 16 points · no account required</span></div></form>{assessment&&<ProtocolResult assessment={assessment}/>}</>;
}
function Section({n,title,hint,children}:{n:string;title:string;hint:string;children:React.ReactNode}){return <fieldset className="form-section"><legend><span>{n}</span><strong>{title}</strong><em>{hint}</em></legend>{children}</fieldset>}
function Field({name,label,placeholder}:{name:string;label:string;placeholder?:string}){return <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} placeholder={placeholder}/></div>}
function Area({name,label,placeholder}:{name:string;label:string;placeholder?:string}){return <div className="field"><label htmlFor={name}>{label}</label><textarea id={name} name={name} placeholder={placeholder}/></div>}
function Select({name,label,options}:{name:string;label:string;options:string[]}){return <div className="field"><label htmlFor={name}>{label}</label><select id={name} name={name} defaultValue={options[0]}>{options.map(x=><option key={x}>{x}</option>)}</select></div>}
