'use client';
import { FormEvent, useState } from 'react';
import { ProtocolResult, type ReviewAssessment, type ReviewDimension } from '@rn/results';

const riskOptions=['Low — a mistake would be annoying but probably easy to fix','Moderate — a mistake could meaningfully affect a person, team, or decision','High — a mistake could affect safety, money, rights, access, health, school, work, or a legal outcome'];
const examples=['School or education decision','Hiring, workplace, or benefits decision','Health or care-related recommendation','Legal research, drafting, or case work','Business or operations decision','Content, moderation, or recommendation system','Something else'];

export function HumanReviewForm(){
  const [mode,setMode]=useState<'quick'|'design'>('quick');
  const [assessment,setAssessment]=useState<ReviewAssessment|null>(null);
  function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault();const fd=new FormData(e.currentTarget);const val=(k:string)=>String(fd.get(k)||'').trim();const risk=val('risk');
    const dims:ReviewDimension[]=[];const gaps:string[]=[];const add=(key:string,label:string,score:0|1|2,note:string,gap?:string)=>{dims.push({key,label,score,note});if(score<2&&gap)gaps.push(gap)};
    add('competence','Right person',val('reviewerQuality')==='qualified'?2:val('reviewerQuality')==='some'?1:0,val('reviewerQuality')==='qualified'?'Reviewer has the knowledge needed':val('reviewerQuality')==='some'?'Reviewer has some relevant knowledge':'No clear qualification','Choose a reviewer who understands both the subject matter and the important limits of the AI system.');
    add('timing','Right time',val('timing')==='before'?2:val('timing')==='conditional'?1:0,val('timing')==='before'?'Review happens before action':val('timing')==='conditional'?'Review happens only sometimes':'Review is late or undefined','Move review before the important action whenever the outcome could be hard to undo.');
    add('evidence','Enough information',val('evidenceAccess')==='full'?2:val('evidenceAccess')==='partial'?1:0,val('evidenceAccess')==='full'?'Reviewer can see the important evidence':val('evidenceAccess')==='partial'?'Reviewer can see only some evidence':'Reviewer mostly sees the AI answer','Give the reviewer enough context, source material, uncertainty, and conflicting information to judge the AI output for themselves.');
    add('authority','Real power',val('authority')==='stop'?2:val('authority')==='recommend'?1:0,val('authority')==='stop'?'Reviewer can change or stop the outcome':val('authority')==='recommend'?'Reviewer can only recommend a change':'Reviewer cannot change the outcome','Give the reviewer actual power to reject, revise, override, stop, or escalate the outcome.');
    add('escalation','Backup plan',val('escalation')==='defined'?2:val('escalation')==='informal'?1:0,val('escalation')==='defined'?'Clear backup path exists':val('escalation')==='informal'?'People improvise when something goes wrong':'No backup path','Define what happens when the reviewer disagrees, is unsure, or thinks the AI may be wrong.');
    add('record','Proof review happened',val('recording')==='structured'?2:val('recording')==='basic'?1:0,val('recording')==='structured'?'Review and reasoning are recorded':val('recording')==='basic'?'Only a basic approval/rejection is recorded':'No durable record','Keep a record of who reviewed, what they saw, what they decided, why, and whether anything changed.');
    add('capacity','Time to think',val('capacity')==='yes'?2:val('capacity')==='strained'?1:0,val('capacity')==='yes'?'Reviewer has enough time and support':val('capacity')==='strained'?'Review is rushed or difficult':'Review is likely to be a rubber stamp','Give reviewers enough time, manageable workload, and a usable interface so they can genuinely disagree.');
    add('testing','Check whether review works',val('testing')==='measured'?2:val('testing')==='adHoc'?1:0,val('testing')==='measured'?'Review outcomes are checked over time':val('testing')==='adHoc'?'Problems are checked only when noticed':'Nobody checks whether the review helps','Track disagreements, overrides, mistakes, complaints, escalations, and outcomes so you can tell whether human review is actually helping.');
    const score=dims.reduce((n,d)=>n+d.score,0);const maxScore=16;const grade:ReviewAssessment['grade']=score>=13?'Strong':score>=8?'Partial':'Weak';
    const priorities=[...gaps];if(risk.startsWith('High')){const timing=dims.find(d=>d.key==='timing')!;const authority=dims.find(d=>d.key==='authority')!;const evidence=dims.find(d=>d.key==='evidence')!;if(timing.score<2)priorities.unshift('Because this could seriously affect someone, review should usually happen before the important action—not after it.');if(authority.score<2)priorities.unshift('Because this could seriously affect someone, the reviewer needs real power to change or stop the outcome.');if(evidence.score<2)priorities.unshift('Because this could seriously affect someone, the reviewer needs enough information to make an independent judgment.');}
    const detail=(k:string,f:string)=>val(k)||f;const protocol=`WHAT IS BEING REVIEWED\n${detail('decision',detail('example','Not specified'))}\n\nHOW MUCH COULD A MISTAKE MATTER?\n${risk||'Not specified'}\n${detail('impact','Who or what could be affected: not specified.')}\n\nWHO REVIEWS IT?\n${detail('reviewer','Role not specified')} — ${dims[0].note}\n\nWHEN DOES REVIEW HAPPEN?\n${dims[1].note}${val('trigger')?` — ${val('trigger')}`:''}\n\nWHAT CAN THE REVIEWER SEE?\n${dims[2].note}${val('evidence')?` — ${val('evidence')}`:''}\n\nWHAT STANDARD ARE THEY USING?\n${detail('standard','No explicit standard specified.')}\n\nWHAT CAN THEY DO?\n${dims[3].note}\n\nWHAT HAPPENS IF THEY DISAGREE OR ARE UNSURE?\n${dims[4].note}${val('failure')?` — ${val('failure')}`:''}\n\nWHAT RECORD IS KEPT?\n${dims[5].note}\n\nDO THEY HAVE TIME TO THINK?\n${dims[6].note}\n\nDOES ANYONE CHECK WHETHER THE REVIEW WORKS?\n${dims[7].note}\n\nFINAL TEST\nCan a real person understand enough to judge the AI output, act before the important consequence, change or stop the outcome when needed, ask for help when unsure, and leave a record showing what happened?`;
    setAssessment({score,maxScore,grade,gaps,priorities:[...new Set(priorities)],dimensions:dims,protocol});setTimeout(()=>document.getElementById('generated-protocol')?.scrollIntoView({behavior:'smooth',block:'start'}),0);
  }
  return <><div className="mode-switch" role="group" aria-label="Assessment mode"><button type="button" className={mode==='quick'?'active':''} onClick={()=>setMode('quick')}><strong>Quick Check</strong><span>Plain-language path · about 60 seconds</span></button><button type="button" className={mode==='design'?'active':''} onClick={()=>setMode('design')}><strong>Detailed Design</strong><span>More fields for professional or technical use</span></button></div><form className="form-panel oversight-form" onSubmit={submit}><div className="form-intro"><div className="eyebrow">{mode==='quick'?'No AI expertise needed':'More detail, same core questions'}</div><p>{mode==='quick'?'Pick the answer that is closest to what happens today. If you are not sure, that uncertainty is useful information too. You will get a simple diagnosis and the three things to fix first.':'Add the details your team would need to turn the diagnosis into an actual review process.'} Your answers stay in this browser.</p></div>
    <Section n="01" title="What is the AI helping with?" hint="Choose the closest example. You do not need to use technical terms."><Select name="example" label="Closest example" options={['Choose one…',...examples]}/><Field name="decision" label="Optional: describe your situation in your own words" placeholder="Example: AI ranks job applicants before a person looks at them"/><Select name="risk" label="If the AI is wrong, how much could it matter?" options={['Choose one…',...riskOptions]}/>{mode==='design'&&<Area name="impact" label="Who or what could be affected?" placeholder="People, rights, money, safety, access, deadlines, legal position…"/>}</Section>
    <Section n="02" title="Who checks the AI?" hint="A human reviewer only helps if they know enough and have enough time to think."><Select name="reviewerQuality" label="Does the reviewer know enough to spot a bad answer?" options={['Choose one…','qualified — Yes. They know the subject and the important limits of the AI.','some — Somewhat. They have relevant knowledge, but important gaps remain.','none — No clear training, qualification, or subject-matter knowledge is required.']}/>{mode==='design'&&<Field name="reviewer" label="Reviewer role" placeholder="Example: teacher, supervising attorney, nurse, hiring manager"/>}<Select name="capacity" label="Do they have enough time and support to really review it?" options={['Choose one…','yes — Yes. They have time, information, manageable workload, and freedom to disagree.','strained — Sometimes. The review can be rushed, overloaded, or hard to perform.','no — No. The human is likely to approve quickly without a real check.']}/></Section>
    <Section n="03" title="When do they check it?" hint="A review that happens after the important action may be too late."><Select name="timing" label="When does human review happen?" options={['Choose one…','before — Before the important action or decision happens.','conditional — Only for some cases, such as risky or unusual ones.','after — After the action, or nobody has clearly decided when review happens.']}/>{mode==='design'&&<Field name="trigger" label="What exactly triggers review?" placeholder="Example: before sending, before denial, below a confidence threshold"/>}</Section>
    <Section n="04" title="What can the reviewer see?" hint="People cannot challenge an AI answer if the answer is all they are allowed to see."><Select name="evidenceAccess" label="How much information can the reviewer inspect?" options={['Choose one…','full — The important inputs, sources, context, uncertainty, and conflicting information are available.','partial — Some supporting information is available, but not enough for a fully independent check.','none — The reviewer mostly sees the AI answer itself.']}/>{mode==='design'&&<><Area name="evidence" label="What information should the reviewer see?"/><Area name="standard" label="What rule or standard should they use to decide whether the AI is right?"/></>}</Section>
    <Section n="05" title="Can they change what happens?" hint="A reviewer without real authority may only create the appearance of oversight."><Select name="authority" label="What can the reviewer actually do?" options={['Choose one…','stop — Reject, change, override, pause, stop, or escalate the outcome.','recommend — Recommend a change, but someone or something else has the final say.','observe — Comment or approve, but cannot meaningfully change the outcome.']}/><Select name="escalation" label="What happens if the reviewer thinks something is wrong?" options={['Choose one…','defined — There is a clear second review, manual fallback, stop, incident, or escalation path.','informal — People know who they might ask, but the process is not clearly designed.','none — There is no clear backup plan.']}/>{mode==='design'&&<Area name="failure" label="Describe the backup or escalation path"/>}</Section>
    <Section n="06" title="Can you prove the review happened—and learn from it?" hint="A useful review process leaves a record and gets better when problems appear."><Select name="recording" label="What gets recorded?" options={['Choose one…','structured — Who reviewed, what they saw, what they decided, why, and what changed.','basic — Only something simple, such as approved/rejected or a timestamp.','none — No durable record of the review.']}/><Select name="testing" label="Does anyone check whether human review is actually helping?" options={['Choose one…','measured — Yes. Disagreements, overrides, mistakes, complaints, escalations, and outcomes are reviewed.','adHoc — Sometimes, when someone notices a problem.','never — No. The review process itself is not evaluated.']}/></Section>
    <div className="submit-zone"><button className="btn btn-large" type="submit">{mode==='quick'?'Check my human review →':'Build the detailed review plan →'}</button><span>Plain language first · deeper detail optional · no account</span></div></form>{assessment&&<ProtocolResult assessment={assessment}/>}</>;
}
function Section({n,title,hint,children}:{n:string;title:string;hint:string;children:React.ReactNode}){return <fieldset className="form-section"><legend><span>{n}</span><strong>{title}</strong><em>{hint}</em></legend>{children}</fieldset>}
function Field({name,label,placeholder}:{name:string;label:string;placeholder?:string}){return <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} placeholder={placeholder}/></div>}
function Area({name,label,placeholder}:{name:string;label:string;placeholder?:string}){return <div className="field"><label htmlFor={name}>{label}</label><textarea id={name} name={name} placeholder={placeholder}/></div>}
function Select({name,label,options}:{name:string;label:string;options:string[]}){return <div className="field"><label htmlFor={name}>{label}</label><select id={name} name={name} defaultValue={options[0]}>{options.map(x=><option key={x} value={x}>{x}</option>)}</select></div>}
