import Link from 'next/link';
import {notFound} from 'next/navigation';
import s from '../../001/story.module.css';

const records:Record<string,{title:string;making:string[];method:string[];evidence:string[];limits:string[]}>={
 '001':{title:'Human Review Design Framework',making:['Started as a form that assumed governance vocabulary.','Became a quick/deep diagnostic with broad-comprehension copy.','Moved into the Exhibition system and added interactive B-Web.','Certification added exact provenance, dimension-level source basis, adversarial fixtures, privacy/support records and a first-class LinkedIn film.'],method:['Simplify the interface without simplifying the hidden system.','Treat human presence, timing, evidence, authority, escalation and records as separate control questions.','Classify source-derived rules separately from product heuristics.'],evidence:['NIST AI RMF 1.0 — mapped sections in the Evidence page/manifest.','Regulation (EU) 2024/1689 Arts. 13–14.','UK ICO Artificial intelligence audit toolkit — Human review.'],limits:['Composite score/thresholds are product heuristics, not compliance rules.','A designed control can still fail in practice.','Applicability depends on jurisdiction, sector and use case.']},
 '002':{title:'Multi-Audience Meaning Architecture',making:['Started as deterministic register adaptation.','Separated source truth, claim graph, transformation and independent anchor/drift audit.','Added optional browser-managed local generation/translation, provenance, export and share state.','Rejected an opaque CDN NLI model until a pinned/versioned evaluator can be governed.'],method:['Preserve the source-of-truth object before rewriting.','Keep generation and verification separate.','Use anchor checks as drift alarms, not semantic-equivalence proof.','Make limited browser AI progressive enhancement, not first-value dependency.'],evidence:['The preservation score and anchor contract are product/engineering heuristics.','Browser AI availability is technical capability, not evidence that a rewrite is correct.'],limits:['Passing checks cannot prove semantic or cultural equivalence.','Consequential multilingual/domain communication requires competent human review.','Share links can expose source text to anyone who receives the URL.']},
 '003':{title:'Unserved Decision Discovery Framework',making:['Deliberately began with an inspectable heuristic instead of an AI claim of product-market fit.','Separated situation, unresolved decision, information substitutes and four structural signals.','Added optional browser-local AI only as a hypothesis challenger.','Added portable JSON record and explicit Build 004 evidence/retrieval dependency.'],method:['Name the decision people still cannot make.','Inventory what information already exists.','Test recurrence, consequence, ambiguity and fragmentation.','Treat product ideas as hypotheses until real-world evidence validates them.'],evidence:['The four signals and formula are product-discovery heuristics created for this build.','No external methodology is claimed as validation of the score.'],limits:['Score does not prove demand, willingness to pay or solution correctness.','External evidence/search intentionally belongs to Build 004 rather than being duplicated.']}
};
export function generateStaticParams(){return Object.keys(records).map(id=>({id}))}
export default async function RecordPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const r=records[id];if(!r)notFound();return <main className={s.page}><header className={s.mast}><Link href={`/100-builds/${id}`}>← BUILD {id}</Link><span>PUBLIC BUILD RECORD</span></header><section className={s.hero}><span>MAKING · METHOD · EVIDENCE · LIMITS</span><h1>{r.title}</h1><p>This is the public record behind the artifact: what changed, what another person can reuse, what supports the system, and what the build is not entitled to claim.</p></section><section className={s.cards}><article><b>MAKING</b><h2>What changed</h2>{r.making.map(x=><p key={x}>{x}</p>)}</article><article><b>METHOD</b><h2>What travels</h2>{r.method.map(x=><p key={x}>{x}</p>)}</article><article><b>EVIDENCE</b><h2>What supports it</h2>{r.evidence.map(x=><p key={x}>{x}</p>)}</article><article><b>LIMITS</b><h2>What it cannot claim</h2>{r.limits.map(x=><p key={x}>{x}</p>)}</article></section>{id==='001'&&<section className={s.takeaway}><Link href="/100-builds/001/evidence">Open the full claim-to-source evidence map →</Link></section>}</main>}
