'use client';
import {useMemo,useState} from 'react';
import s from './manual-intelligence.module.css';

type Source={id:number;title:string;issuer:string;url:string;date:string;checked:string;version:string;locator:string;kind:string;notes:string};
type ClaimStatus='unverified'|'verified'|'contradicted'|'uncertain';
type Claim={id:number;text:string;sourceId:number;status:ClaimStatus;verificationNote:string};
const protocol=[
 ['COLLECT','Capture the source itself, issuer or author, publication/version, dates, location, relevant section or page, and why it belongs in the research set.'],
 ['SEPARATE','Write the analyst claim separately from the source record so interpretation never masquerades as provenance.'],
 ['VERIFY','Resolve each claim as verified, contradicted, uncertain or still unverified before it can enter a brief.']
];
const seedSources:Source[]=[{id:1,title:'Example primary source',issuer:'Example issuer',url:'https://example.org/source',date:'2026-08-15',checked:'2026-08-15',version:'Example version',locator:'Example section',kind:'primary',notes:'Replace this demonstration record with the source you actually reviewed.'}];
const seedClaims:Claim[]=[{id:1,text:'This is a demonstration claim and is not verified evidence.',sourceId:1,status:'unverified',verificationNote:''}];
export default function ManualIntelligenceEngine(){
 const [sources,setSources]=useState<Source[]>(seedSources);const [claims,setClaims]=useState<Claim[]>(seedClaims);
 const [title,setTitle]=useState('');const [issuer,setIssuer]=useState('');const [url,setUrl]=useState('');const [date,setDate]=useState('');const [checked,setChecked]=useState('');const [version,setVersion]=useState('');const [locator,setLocator]=useState('');const [kind,setKind]=useState('primary');const [notes,setNotes]=useState('');
 const [claimText,setClaimText]=useState('');const [claimSource,setClaimSource]=useState(1);const [announcement,setAnnouncement]=useState('');
 const verified=useMemo(()=>claims.filter(c=>c.status==='verified'),[claims]);const contradicted=useMemo(()=>claims.filter(c=>c.status==='contradicted'),[claims]);const uncertain=useMemo(()=>claims.filter(c=>c.status==='uncertain'),[claims]);const open=useMemo(()=>claims.filter(c=>c.status==='unverified'),[claims]);
 function clearSourceDraft(){setTitle('');setIssuer('');setUrl('');setDate('');setChecked('');setVersion('');setLocator('');setKind('primary');setNotes('')}
 function addSource(){if(!title.trim()||!checked){setAnnouncement('Source not added. Enter a source title and checked or retrieved date.');return}const id=Math.max(0,...sources.map(x=>x.id))+1;const sourceTitle=title.trim();setSources(prev=>[...prev,{id,title:sourceTitle,issuer:issuer.trim(),url:url.trim(),date,checked,version:version.trim(),locator:locator.trim(),kind,notes:notes.trim()}]);clearSourceDraft();if(!sources.length)setClaimSource(id);setAnnouncement(`Source ${id} added: ${sourceTitle}.`)}
 function addClaim(){if(!claimText.trim()){setAnnouncement('Claim not added. Enter an analyst claim.');return}if(!sources.some(x=>x.id===claimSource)){setAnnouncement('Claim not added. Add and select a supporting source first.');return}const id=Math.max(0,...claims.map(x=>x.id))+1;setClaims(prev=>[...prev,{id,text:claimText.trim(),sourceId:claimSource,status:'unverified',verificationNote:''}]);setClaimText('');setAnnouncement(`Claim ${id} added as unverified.`)}
 function setClaimStatus(id:number,status:ClaimStatus){let applied:ClaimStatus=status;setClaims(prev=>prev.map(c=>{if(c.id!==id)return c;if(status==='verified'&&!c.verificationNote.trim()){applied='unverified';return {...c,status:'unverified'}}return {...c,status}}));setAnnouncement(applied==='unverified'&&status==='verified'?`Claim ${id} remains unverified until a verification note is recorded.`:`Claim ${id} status changed to ${applied}.`)}
 function updateVerificationNote(id:number,value:string){let demoted=false;setClaims(prev=>prev.map(c=>{if(c.id!==id)return c;demoted=c.status==='verified'&&!value.trim();return {...c,verificationNote:value,status:demoted?'unverified':c.status}}));if(!value.trim())setAnnouncement(`Claim ${id} verification note cleared; any verified state is removed.`)}
 function removeSource(id:number){const removed=sources.find(x=>x.id===id);const dependentCount=claims.filter(c=>c.sourceId===id).length;setSources(prev=>prev.filter(x=>x.id!==id));setClaims(prev=>prev.filter(c=>c.sourceId!==id));const next=sources.find(x=>x.id!==id);setClaimSource(next?.id||0);setAnnouncement(`Source ${id}${removed?`: ${removed.title}`:''} removed${dependentCount?` with ${dependentCount} dependent claim${dependentCount===1?'':'s'}`:''}.`)}
 function reset(){setSources([]);setClaims([]);clearSourceDraft();setClaimText('');setClaimSource(0);setAnnouncement('Research record reset. Start by adding a source.')}
 function exportRecord(){const data={schemaVersion:'004.1.0',exportedAt:new Date().toISOString(),protocol:'manual intelligence engine',sources,claims,brief:{verified:verified.map(c=>c.text),contradictions:contradicted.map(c=>c.text),uncertainties:uncertain.map(c=>c.text),open:open.map(c=>c.text)}};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download='manual-intelligence-record.json';a.click();URL.revokeObjectURL(href);setAnnouncement('Research record exported as JSON.')}
 return <div className={s.app}>
  <section className={s.panel}><span>01 / COLLECTION PROTOCOL</span><h2>Make the method explicit before adding more sources.</h2><div className={s.protocol}>{protocol.map(([h,p])=><article key={h}><b>{h}</b><p>{p}</p></article>)}</div></section>
  {announcement&&<p className={s.statusLine} role="status" aria-live="polite">{announcement}</p>}
  <section className={s.panel}><span>02 / SOURCE REGISTER</span><h2>Collect evidence as evidence.</h2><div className={s.form}><label>Source title *<input aria-label="Source title" required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Issuer / author<input aria-label="Issuer or author" value={issuer} onChange={e=>setIssuer(e.target.value)}/></label><label>Source URL or location<input aria-label="Source URL or location" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Publication / version<input aria-label="Publication or version" value={version} onChange={e=>setVersion(e.target.value)}/></label><label>Source / publication date<input aria-label="Source date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Checked / retrieved date *<input aria-label="Checked or retrieved date" required type="date" value={checked} onChange={e=>setChecked(e.target.value)}/></label><label>Relevant section / page / locator<input aria-label="Relevant section page or locator" value={locator} onChange={e=>setLocator(e.target.value)}/></label><label>Source type<select aria-label="Source type" value={kind} onChange={e=>setKind(e.target.value)}><option value="primary">Primary</option><option value="secondary">Secondary</option><option value="dataset">Dataset</option><option value="interview">Interview / observation</option><option value="other">Other</option></select></label><label className={s.full}>Collection note<textarea aria-label="Collection note" rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><p className={s.empty}>A source needs a title and checked/retrieved date before it can enter the register. Other provenance fields remain explicit so “unknown” is visible rather than buried in a note.</p><div className={s.actions}><button className={s.primary} onClick={addSource}>ADD SOURCE</button></div><div className={s.sources}>{sources.map(src=><article className={s.sourceCard} key={src.id}><header><div><small>SOURCE {String(src.id).padStart(2,'0')}</small><h3>{src.title}</h3></div><button onClick={()=>removeSource(src.id)} aria-label={`Remove ${src.title}`}>REMOVE</button></header>{src.url&&<p>{src.url}</p>}{src.notes&&<p>{src.notes}</p>}<div className={s.meta}><span>{src.kind}</span>{src.issuer&&<span>issuer: {src.issuer}</span>}{src.version&&<span>version: {src.version}</span>}{src.date&&<span>source: {src.date}</span>}<span>checked: {src.checked}</span>{src.locator&&<span>locator: {src.locator}</span>}</div></article>)}</div></section>
  <section className={s.panel}><span>03 / VERIFICATION QUEUE</span><h2>Claims do not inherit credibility from proximity to a source.</h2>{sources.length?<><div className={s.form}><label className={s.full}>Analyst claim<textarea aria-label="Analyst claim" rows={3} value={claimText} onChange={e=>setClaimText(e.target.value)}/></label><label>Supporting source<select aria-label="Supporting source" value={claimSource} onChange={e=>setClaimSource(Number(e.target.value))}>{sources.map(src=><option key={src.id} value={src.id}>{src.id}. {src.title}</option>)}</select></label></div><div className={s.actions}><button className={s.primary} onClick={addClaim}>ADD TO QUEUE</button></div></>:<p className={s.empty}>Add at least one source before creating a claim.</p>}<div className={s.queueHead}><span>CLAIMS</span><b className={s.count}>{claims.length} TOTAL · {verified.length} VERIFIED</b></div><div className={s.claimGrid}>{claims.map(c=>{const src=sources.find(x=>x.id===c.sourceId);return <article className={s.claimCard} key={c.id}><header><div><small>CLAIM {String(c.id).padStart(2,'0')} · SOURCE {c.sourceId}</small><h3>{c.text}</h3></div><span className={s.status}>{c.status}</span></header><p>Source: {src?.title||'Source removed'}</p><textarea aria-label={`Verification note for claim ${c.id}`} rows={3} placeholder="What did you check? What supports or limits this status?" value={c.verificationNote} onChange={e=>updateVerificationNote(c.id,e.target.value)}/><p className={s.empty}>A verification note is required before this claim can be marked verified.</p><label>Status <select aria-label={`Status for claim ${c.id}`} value={c.status} onChange={e=>setClaimStatus(c.id,e.target.value as ClaimStatus)}><option value="unverified">Unverified</option><option value="verified" disabled={!c.verificationNote.trim()}>Verified</option><option value="contradicted">Contradicted</option><option value="uncertain">Uncertain</option></select></label></article>})}</div></section>
  <section className={s.brief}><span>04 / INTELLIGENCE BRIEF</span><h2>Only cleared claims become findings.</h2><div className={s.briefGrid}><article><h3>Verified findings</h3>{verified.length?<ul>{verified.map(c=><li key={c.id}>{c.text}</li>)}</ul>:<p>No verified findings yet.</p>}</article><article><h3>Contradictions</h3>{contradicted.length?<ul>{contradicted.map(c=><li key={c.id}>{c.text}</li>)}</ul>:<p>No contradictions recorded.</p>}</article><article><h3>Uncertainty</h3>{uncertain.length?<ul>{uncertain.map(c=><li key={c.id}>{c.text}</li>)}</ul>:<p>No uncertainty recorded.</p>}</article><article><h3>Open verification</h3>{open.length?<ul>{open.map(c=><li key={c.id}>{c.text}</li>)}</ul>:<p>No unresolved claims.</p>}</article></div><div className={s.actions}><button className={s.export} onClick={exportRecord}>EXPORT RESEARCH RECORD</button><button onClick={reset}>RESET / START OVER</button></div></section>
  <p className={s.notice}><strong>Boundary:</strong> this tool structures research work; it does not verify a source for you, infer that a claim is true, or convert an analyst judgment into evidence. A claim reaches the brief only when a human reviewer records what they checked and explicitly marks it verified.</p>
 </div>
}
