export type CaseId='ALLOWED'|'EXPIRED'|'PURPOSE'|'SHARE'|'PROHIBITED'|'INFERENCE'|'REVOKED'|'DELETE';
export type Action='RECALL'|'SHARE'|'INFER'|'FORGET';
export type Disposition='INVALID_RECORD'|'FORGET_REQUESTED'|'PROHIBITED_MEMORY'|'EXPIRED'|'PURPOSE_MISMATCH'|'ACTION_DENIED'|'INFERENCE_UNCONFIRMED'|'AVAILABLE_FOR_DECLARED_USE';
export type MemoryRecord={id:string;label:string;class:'ALLOWED'|'SENSITIVE'|'PROHIBITED';purpose:string;permissions:readonly Action[];createdOn:string;expiresOn:string;inferenceConfirmed:boolean;shareGranted:boolean;revoked:boolean;value:string};
export type Input={fixtureId:'SYNTHETIC-MEMORY-POLICY-091';caseId:CaseId;action:Action;simulateForget:boolean;records:readonly MemoryRecord[];admission:{syntheticOnly:true;liveMemory:false;externalEffects:false;realPeople:false}};
export type Result={disposition:Disposition;caseId:CaseId|null;action:Action|null;gates:readonly {name:string;decision:'PASS'|'BLOCK'|'NOT_RUN';reason:string}[];receipt:Readonly<Record<string,unknown>>;nonClaims:readonly string[];asOf:typeof AS_OF};
export const AS_OF='2026-08-22T12:00:00.000Z' as const;
const freeze=<T>(v:T):T=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v as Record<string,unknown>))freeze(x)}return v};
const rec=(id:string,label:string,kind:MemoryRecord['class'],purpose:string,permissions:Action[],expiresOn:string,value:string,extra:Partial<MemoryRecord>={}):MemoryRecord=>freeze({id,label,class:kind,purpose,permissions,createdOn:'2026-08-01',expiresOn,inferenceConfirmed:true,shareGranted:false,revoked:false,value,...extra});
export const RECORDS=freeze([
rec('M-ALLOW','Confirmed workshop preference','ALLOWED','workshop-planning',['RECALL'],'2026-12-31','prefers morning sessions'),
rec('M-EXPIRED','Expired scheduling preference','ALLOWED','workshop-planning',['RECALL'],'2026-08-20','old Tuesday preference'),
rec('M-PURPOSE','Purpose-bound contact preference','ALLOWED','newsletter',['RECALL'],'2026-12-31','email only'),
rec('M-SHARE','Private project note','SENSITIVE','project-alpha',['RECALL','SHARE'],'2026-12-31','internal project marker'),
rec('M-PROHIBITED','Prohibited sensitive detail','PROHIBITED','none',[],'2026-12-31','never retain this detail'),
rec('M-INFER','Unconfirmed derived preference','SENSITIVE','workshop-planning',['INFER'],'2026-12-31','probably dislikes travel',{inferenceConfirmed:false}),
rec('M-REVOKED','Revoked consent record','ALLOWED','workshop-planning',['RECALL'],'2026-12-31','superseded preference',{revoked:true}),
rec('M-DELETE','Forget request target','SENSITIVE','workshop-planning',['FORGET'],'2026-12-31','local rehearsal value')
] as const);
export const DEFAULT_ACTION:Record<CaseId,Action>=freeze({ALLOWED:'RECALL',EXPIRED:'RECALL',PURPOSE:'RECALL',SHARE:'SHARE',PROHIBITED:'RECALL',INFERENCE:'INFER',REVOKED:'RECALL',DELETE:'FORGET'});
const ids:Record<CaseId,string>=freeze({ALLOWED:'M-ALLOW',EXPIRED:'M-EXPIRED',PURPOSE:'M-PURPOSE',SHARE:'M-SHARE',PROHIBITED:'M-PROHIBITED',INFERENCE:'M-INFER',REVOKED:'M-REVOKED',DELETE:'M-DELETE'});
const base=freeze({fixtureId:'SYNTHETIC-MEMORY-POLICY-091',records:RECORDS,admission:{syntheticOnly:true,liveMemory:false,externalEffects:false,realPeople:false}} as const);
export const PRESETS=freeze(Object.fromEntries((Object.keys(ids)as CaseId[]).map(caseId=>[caseId,freeze({...base,caseId,action:DEFAULT_ACTION[caseId],simulateForget:false})])) as unknown as Record<CaseId,Input>);
const nonClaims=freeze(['REMEMBERED DOES NOT MEAN TRUE','RECALL PERMISSION IS NOT SHARE PERMISSION','EXPIRED IS NOT FORGOTTEN','A FORGET RECEIPT DOES NOT VERIFY ERASURE','NO CHATGPT MEMORY, MESSAGES, ACCOUNTS, FILES, CONTACTS, LIVE AGENTS, OR EXTERNAL EFFECTS']);
const invalid=():Result=>freeze({disposition:'INVALID_RECORD',caseId:null,action:null,gates:[],receipt:{status:'REJECTED'},nonClaims,asOf:AS_OF});
export function evaluate(candidate:unknown):Result{try{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const o=candidate as Input,p=PRESETS[o.caseId];if(!p||typeof o.simulateForget!=='boolean'||JSON.stringify(o)!==JSON.stringify({...p,simulateForget:o.simulateForget}))return invalid();const r=p.records.find(x=>x.id===ids[o.caseId])!;let d:Disposition='AVAILABLE_FOR_DECLARED_USE',why='Declared use is permitted.';if(o.action==='FORGET')d='FORGET_REQUESTED',why=o.simulateForget?'Local rehearsal receipt created; erasure remains unverified.':'Forget request is ready for local simulation.';else if(r.class==='PROHIBITED'||r.revoked)d='PROHIBITED_MEMORY',why=r.revoked?'Consent was revoked; use is prohibited.':'Policy prohibits retention and use.';else if(r.expiresOn<'2026-08-22')d='EXPIRED',why='Retention window ended.';else if(o.caseId==='PURPOSE')d='PURPOSE_MISMATCH',why='Requested purpose differs from the grant.';else if(!r.permissions.includes(o.action)||(o.action==='SHARE'&&!r.shareGranted))d='ACTION_DENIED',why='This action lacks an explicit grant.';else if(o.action==='INFER'&&!r.inferenceConfirmed)d='INFERENCE_UNCONFIRMED',why='Derived inference is not confirmed as fact.';const pass=d==='AVAILABLE_FOR_DECLARED_USE';const gates=freeze([{name:'RETENTION + CONSENT',decision:(d==='PROHIBITED_MEMORY'||d==='EXPIRED')?'BLOCK':'PASS',reason:why},{name:'PURPOSE + ACTION',decision:(d==='PURPOSE_MISMATCH'||d==='ACTION_DENIED')?'BLOCK':(d==='PROHIBITED_MEMORY'||d==='EXPIRED')?'NOT_RUN':'PASS',reason:why},{name:'INFERENCE + SHARE',decision:d==='INFERENCE_UNCONFIRMED'?'BLOCK':pass?'PASS':'NOT_RUN',reason:why}]) as Result['gates'];const minimized=d==='PROHIBITED_MEMORY'||d==='FORGET_REQUESTED';return freeze({disposition:d,caseId:o.caseId,action:o.action,gates,receipt:{recordId:r.id,status:d,content:minimized?'WITHHELD':pass?r.value:'NOT_DISCLOSED',erasureVerified:false,externalEffect:false},nonClaims,asOf:AS_OF})}catch{return invalid()}}
export function buildExport(candidate:unknown){const result=evaluate(candidate);return freeze({build:'091',schemaVersion:'build-091.v1',policyVersion:'memory-policy.v1',canonical:{title:'Agent Memory Governance System',publicTitle:'What Is This AI Allowed to Remember?',uses:['023','024','029','058','067'],creates:'cap:091'},artifacts:['Memory Policy Engine','Retention & Scope Controls'],syntheticOnly:true,externalEffects:false,result})}