export type TeamMember={id:string;name:string;kind:'human'|'ai';roleContractId:string;supervisorId:string|null;capacity:number;costPerRun:number;dependencies:string[];escalationRouteId:string;traceId:string;stopPolicyId:string};
export type TeamResult={status:'TEAM READY'|'TEAM GAPS';gaps:string[];bottlenecks:string[];totalCostPerRun:number;engineVersion:string};
export const AI_TEAM_ENGINE_VERSION='043.2.0';
export const TEAM_MEMBER_CONTRACT={
 'HUMAN-1':{kind:'human',roleContractId:'ROLE-HUMAN-1',supervisorId:null,escalationRouteId:'',traceId:'',stopPolicyId:''},
 'AI-1':{kind:'ai',roleContractId:'ROLE-042-SCOUT',supervisorId:'HUMAN-1',escalationRouteId:'ROUTE-019-TEAM',traceId:'TRACE-039-TEAM',stopPolicyId:'STOP-040-TEAM'},
 'AI-2':{kind:'ai',roleContractId:'ROLE-042-CHALLENGE',supervisorId:'HUMAN-1',escalationRouteId:'ROUTE-019-TEAM',traceId:'TRACE-039-TEAM',stopPolicyId:'STOP-040-TEAM'},
 'AI-3':{kind:'ai',roleContractId:'ROLE-042-DRAFT',supervisorId:'HUMAN-1',escalationRouteId:'ROUTE-019-TEAM',traceId:'TRACE-039-TEAM',stopPolicyId:'STOP-040-TEAM'}
}as const;
export const TEAM_CONTROL_VERSIONS={role:'042.2.0',escalation:'019.1.0',trace:'039.2.0',stop:'040.3.0'}as const;
export function inspectTeam(members:TeamMember[]):TeamResult{
 const gaps:string[]=[];const bottlenecks:string[]=[];if(!members.length)gaps.push('At least one declared member is required.');
 const counts=new Map<string,number>();for(const m of members)counts.set(m.id,(counts.get(m.id)||0)+1);if([...counts.values()].some(n=>n!==1)||members.some(m=>!m.id.trim()))gaps.push('Every member requires a unique nonempty identity.');
 const ids=new Set(members.map(m=>m.id));for(const m of members){const expected=TEAM_MEMBER_CONTRACT[m.id as keyof typeof TEAM_MEMBER_CONTRACT];if(!expected||!m.name.trim()||m.kind!==expected.kind||m.roleContractId!==expected.roleContractId)gaps.push(`Member identity or role contract mismatch: ${m.id||'unnamed'}.`);if(!Number.isInteger(m.capacity)||m.capacity<1||!Number.isFinite(m.costPerRun)||m.costPerRun<0)gaps.push(`Invalid capacity or cost: ${m.id||'unnamed'}.`);if(new Set(m.dependencies).size!==m.dependencies.length||m.dependencies.some(d=>!ids.has(d)||d===m.id))gaps.push(`Invalid or duplicate dependency: ${m.id||'unnamed'}.`);if(m.kind==='ai'){if(!expected||m.supervisorId!==expected.supervisorId||m.escalationRouteId!==expected.escalationRouteId||m.traceId!==expected.traceId||m.stopPolicyId!==expected.stopPolicyId)gaps.push(`AI supervision or control binding mismatch: ${m.id}.`);const supervisor=members.find(x=>x.id===m.supervisorId);if(!supervisor||supervisor.kind!=='human')gaps.push(`AI member lacks direct declared human supervision: ${m.id}.`)}else if(m.supervisorId!==null||m.escalationRouteId||m.traceId||m.stopPolicyId)gaps.push(`Human fixture record contains an undeclared AI control grant: ${m.id}.`)}
 const graph=new Map(members.map(m=>[m.id,m.dependencies]));const state=new Map<string,0|1|2>();function visit(id:string):boolean{const s=state.get(id)||0;if(s===1)return true;if(s===2)return false;state.set(id,1);for(const dep of graph.get(id)||[])if(visit(dep))return true;state.set(id,2);return false}if([...ids].some(visit))gaps.push('Team dependencies must be acyclic.');
 for(const m of members){const demand=members.filter(x=>x.dependencies.includes(m.id)).length;if(demand>m.capacity)bottlenecks.push(`${m.id} receives ${demand} handoffs with capacity ${m.capacity}.`)}if(bottlenecks.length)gaps.push('Declared handoff demand exceeds member capacity.');
 const costsValid=members.every(m=>Number.isFinite(m.costPerRun)&&m.costPerRun>=0);return{status:gaps.length?'TEAM GAPS':'TEAM READY',gaps:[...new Set(gaps)],bottlenecks,totalCostPerRun:costsValid?members.reduce((n,m)=>n+m.costPerRun,0):0,engineVersion:AI_TEAM_ENGINE_VERSION}
}
