export type ScenarioId='KALO'|'CANOPY'|'TIDE'|'WEAVE'|'ROOT';
type Actor={id:string;label:string;role:string;contribution:string};
type Flow={id:string;from:string;to:string;kind:string;points:number};
type Commitment={id:string;beneficiary:string;promise:string;target:number;observed:number|null;status:'MET'|'PARTIAL'|'UNMET'|'UNKNOWN'};
export type Scenario={id:ScenarioId;label:string;product:string;actors:readonly Actor[];flows:readonly Flow[];commitments:readonly Commitment[]};
export type BenefitInput={fixtureId:'SYNTHETIC-BENEFIT-SHARING-084';scenarioId:ScenarioId;scenarios:readonly Scenario[];admission:{syntheticOnly:true;fixedOnly:true;realPeople:false;realCommunities:false;realAgreements:false;realMoney:false;rightsDetermined:false;fairnessDetermined:false}};
export type BenefitResult={status:string;scenario:Scenario|null;totals:readonly {actorId:string;received:number;contributed:number}[];gaps:readonly string[];audit:readonly string[];nonClaims:readonly string[];engineVersion:typeof VERSION};
export const VERSION='084.1.0' as const;
const make=(id:ScenarioId,label:string,product:string,p:string):Scenario=>{const actors=Object.freeze([{id:p+'-KS',label:label+' knowledge source',role:'KNOWLEDGE-SOURCE',contribution:'Invented knowledge contribution'},{id:p+'-CO',label:label+' community',role:'COMMUNITY',contribution:'Invented stewardship and context'},{id:p+'-CR',label:'Synthetic creator',role:'CREATOR',contribution:'Invented product design'},{id:p+'-FU',label:'Synthetic funder',role:'FUNDER',contribution:'Invented capital'},{id:p+'-OP',label:'Synthetic operator',role:'OPERATOR',contribution:'Invented operations'},{id:p+'-DI',label:'Synthetic distributor',role:'DISTRIBUTOR',contribution:'Invented distribution'}]);const flows=Object.freeze([{id:p+'-F1',from:p+'-KS',to:p+'-CR',kind:'KNOWLEDGE',points:80},{id:p+'-F2',from:p+'-CO',to:p+'-CR',kind:'GOVERNANCE',points:40},{id:p+'-F3',from:p+'-FU',to:p+'-OP',kind:'FINANCIAL',points:60},{id:p+'-F4',from:p+'-OP',to:p+'-DI',kind:'FINANCIAL',points:35},{id:p+'-F5',from:p+'-DI',to:p+'-CR',kind:'FINANCIAL',points:75},{id:p+'-F6',from:p+'-CR',to:p+'-CO',kind:'BENEFIT',points:12},{id:p+'-F7',from:p+'-CR',to:p+'-KS',kind:'RIGHT',points:5}]);const commitments=Object.freeze([{id:p+'-C1',beneficiary:p+'-CO',promise:'Share recurring benefit',target:20,observed:12,status:'PARTIAL'},{id:p+'-C2',beneficiary:p+'-KS',promise:'Record attribution',target:1,observed:0,status:'UNMET'},{id:p+'-C3',beneficiary:p+'-CO',promise:'Provide governance seat',target:1,observed:null,status:'UNKNOWN'}] as Commitment[]);return Object.freeze({id,label,product,actors,flows,commitments})};
export const SCENARIOS:readonly Scenario[]=Object.freeze([make('KALO','Kalo partnership','Synthetic wellness product','KA'),make('CANOPY','Canopy partnership','Synthetic learning tool','CA'),make('TIDE','Tide collaboration','Synthetic media property','TI'),make('WEAVE','Weave collaboration','Synthetic dataset','WE'),make('ROOT','Root partnership','Synthetic consumer product','RO')]);
const base={fixtureId:'SYNTHETIC-BENEFIT-SHARING-084',scenarios:SCENARIOS,admission:{syntheticOnly:true,fixedOnly:true,realPeople:false,realCommunities:false,realAgreements:false,realMoney:false,rightsDetermined:false,fairnessDetermined:false}} as const;
export const PRESETS=Object.freeze(Object.fromEntries(SCENARIOS.map(s=>[s.id,Object.freeze({...base,scenarioId:s.id})])) as Record<ScenarioId,BenefitInput>);
const invalid=():BenefitResult=>({status:'INVALID',scenario:null,totals:[],gaps:['INVALID OR UNADMITTED SYNTHETIC INPUT'],audit:[],nonClaims:['NO REAL RIGHTS, VALUE, FAIRNESS, COMPENSATION, CONTRACT, OR LEGAL DETERMINATION'],engineVersion:VERSION});
export function mapBenefits(candidate:unknown):BenefitResult{try{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const o=candidate as Record<string,unknown>,preset=PRESETS[o.scenarioId as ScenarioId];if(!preset||JSON.stringify(o)!==JSON.stringify(preset))return invalid();const s=preset.scenarios.find(x=>x.id===preset.scenarioId)!;const totals=s.actors.map(a=>({actorId:a.id,received:s.flows.filter(f=>f.to===a.id).reduce((n,f)=>n+f.points,0),contributed:s.flows.filter(f=>f.from===a.id).reduce((n,f)=>n+f.points,0)}));return{status:s.id+' BENEFIT FLOW MAPPED',scenario:s,totals,gaps:s.commitments.filter(c=>c.status!=='MET').map(c=>c.id+' · '+c.status+' · '+c.promise),audit:['VALIDATED EXACT FROZEN FIXTURE','PRESERVED ACTOR, FLOW, COMMITMENT, METRIC, AND EVIDENCE LINKS','LEFT UNKNOWN COMMITMENTS UNKNOWN','NO FAIRNESS, RIGHTS, OWNERSHIP, CONSENT, CONTRACT, OR LEGAL DETERMINATION'],nonClaims:['FICTIONAL ACTORS, FLOWS, COMMITMENTS, AND POINTS ONLY','SYNTHETIC POINTS ARE NOT MONEY, VALUE, EQUITY, ROYALTIES, DAMAGES, OR COMPENSATION','A GAP IS A REVIEW SIGNAL, NOT PROOF OF WRONGDOING OR ENTITLEMENT'],engineVersion:VERSION}}catch{return invalid()}}
