export type EvidenceCaseId='EVIDENCE-CEDAR'|'EVIDENCE-HARBOR'|'EVIDENCE-LATTICE'|'EVIDENCE-MESA'|'EVIDENCE-ORBIT';
export type Audience='PUBLIC READER'|'CLINICAL EDUCATOR'|'POLICY ANALYST'|'PRODUCT TEAM'|'PATIENT ADVOCATE';
export type TruthAnchor={sourceId:string;title:string;sourceType:string;sourceQuality:string;claim:string;population:string;interventionOrExposure:string;comparison:string;outcome:string;limitations:readonly string[];uncertainty:string;asOf:string;syntheticStatus:'SYNTHETIC-SOURCE-CHECKED'};
export type TranslationCase={caseId:EvidenceCaseId;audience:Audience;truthAnchor:TruthAnchor;translatedExplanation:string;caveats:readonly string[];preservedFields:readonly string[]};
export type TranslationInput={fixtureId:'SYNTHETIC-CANNABIS-EVIDENCE-078';caseId:EvidenceCaseId;cases:readonly TranslationCase[];inherited:{audienceProfiles:'cap:002';telemetryGuardrails:'cap:031';evidenceSupport:'cap:051';sourceProvenance:'cap:058'};admission:{syntheticOnly:true;fixedAudiencePerCase:true;realPatientData:false;realProductData:false;realLawClaim:false;legalAdvice:'NONE';clinicalAdvice:'NONE';diagnosisTreatmentDosageClaim:false;safetyEffectivenessClaim:false;complianceDetermined:false}};
export type TranslationResult={status:`${EvidenceCaseId} TRANSLATION`|'INVALID';translation:TranslationCase|null;alerts:readonly string[];audit:readonly string[];nonClaims:readonly string[];engineVersion:typeof EVIDENCE_TRANSLATION_ENGINE_VERSION};
export const EVIDENCE_TRANSLATION_ENGINE_VERSION='078.1.0' as const;
const PRESERVED=Object.freeze(['SOURCE TYPE','SOURCE QUALITY','CLAIM','POPULATION','INTERVENTION OR EXPOSURE','COMPARISON','OUTCOME','LIMITATIONS','UNCERTAINTY','AS-OF DATE'] as const);
const anchor=(sourceId:string,title:string,sourceType:string,sourceQuality:string,claim:string,population:string,interventionOrExposure:string,comparison:string,outcome:string,limitations:readonly string[],uncertainty:string,asOf:string):TruthAnchor=>Object.freeze({sourceId,title,sourceType,sourceQuality,claim,population,interventionOrExposure,comparison,outcome,limitations:Object.freeze(limitations),uncertainty,asOf,syntheticStatus:'SYNTHETIC-SOURCE-CHECKED'});
export const EVIDENCE_TRANSLATION_CASES:readonly TranslationCase[]=Object.freeze([
 {caseId:'EVIDENCE-CEDAR',audience:'PUBLIC READER',truthAnchor:anchor('SYN-078-CE-01','Cedar Controlled Fixture','SYNTHETIC CONTROLLED STUDY','RANDOMIZED FIXTURE; SMALL SAMPLE; NO REAL PARTICIPANTS','Within this fixture, Group Cedar recorded a different short-term score than Group Pine.','48 fictional adult records','Fictional standardized cannabis exposure C','Fictional inactive comparison P','Mean synthetic score difference at day 7','Small fixture; seven-day window; self-report outcome; no replication','Direction is fixed in the fixture; magnitude and applicability outside it are unknown.','2044-01-15'),translatedExplanation:'In this invented study, one fictional group reported a different seven-day score. That result belongs only to this small synthetic fixture and does not establish what cannabis does for any person.',caveats:Object.freeze(['NOT REAL RESEARCH OR A HEALTH CLAIM','SMALL SYNTHETIC SAMPLE AND SHORT WINDOW','NO SAFETY, EFFECTIVENESS, TREATMENT, OR DOSAGE INFERENCE']),preservedFields:PRESERVED},
 {caseId:'EVIDENCE-HARBOR',audience:'CLINICAL EDUCATOR',truthAnchor:anchor('SYN-078-HA-01','Harbor Observation Fixture','SYNTHETIC OBSERVATIONAL DATASET','UNCONTROLLED FIXTURE; INCOMPLETE FOLLOW-UP; NO REAL PATIENTS','The fixture contains an association between recorded exposure category and a follow-up response field.','73 fictional records with 51 follow-ups','Self-selected fictional cannabis exposure category','No assigned comparison; descriptive categories only','Synthetic follow-up response distribution','No random assignment; missing follow-up; unmeasured confounding; invented measures','Association is preserved, but causation, clinical importance, and generalizability are unknown.','2044-02-02'),translatedExplanation:'For teaching purposes, this fictional dataset illustrates an association, not a causal or clinically actionable finding. Missing follow-up and self-selection prevent treatment, dosage, safety, or effectiveness conclusions.',caveats:Object.freeze(['NO REAL PATIENTS OR CLINICAL EVIDENCE','ASSOCIATION DOES NOT ESTABLISH CAUSATION','NOT FOR DIAGNOSIS, TREATMENT, DOSAGE, OR SAFETY DECISIONS']),preservedFields:PRESERVED},
 {caseId:'EVIDENCE-LATTICE',audience:'POLICY ANALYST',truthAnchor:anchor('SYN-078-LA-01','Lattice Fictional Rule Record','SYNTHETIC LEGAL TEXT','SINGLE FICTIONAL SOURCE; NO JURISDICTION; NOT LAW','The invented clause assigns a reporting step to a fictional registry operator.','One fictional administrative system','Synthetic reporting clause','Earlier synthetic fixture version','A reporting step appears in the later fixture version','No real authority, jurisdiction, implementation evidence, enforcement record, or legal status','Textual difference is fixed; legal effect, implementation, compliance, and outcomes are unknown.','2044-02-18'),translatedExplanation:'The invented text adds a reporting step to a fictional workflow. It is useful only to demonstrate evidence translation; it says nothing about current law, compliance, implementation, enforcement, or policy outcomes.',caveats:Object.freeze(['FICTIONAL TEXT — NOT CURRENT LAW','NO LEGAL ADVICE OR COMPLIANCE DETERMINATION','NO IMPLEMENTATION, ENFORCEMENT, RIGHTS, OR OUTCOME INFERENCE']),preservedFields:PRESERVED},
 {caseId:'EVIDENCE-MESA',audience:'PRODUCT TEAM',truthAnchor:anchor('SYN-078-ME-01','Mesa Label Consistency Fixture','SYNTHETIC PRODUCT QUALITY TABLE','BENCH FIXTURE; THREE FICTIONAL LOTS; NO MARKETED PRODUCT','Three fictional lots contain differing label-to-record variance values.','Three fictional noncommercial lot records','Synthetic labeled cannabis sample M','Fixture reference values','Recorded variance differs across the three fictional lots','Tiny fixture; invented assay; no consumer use; no safety or performance endpoint','The fixture demonstrates variance display only; product quality, safety, identity, and effectiveness are unknown.','2044-03-01'),translatedExplanation:'This invented bench table shows that three fictional records vary from their reference values. It can test a product-team interface, but cannot establish the identity, quality, safety, consistency, or effectiveness of any real product.',caveats:Object.freeze(['NO REAL PRODUCT, LOT, ASSAY, OR CONSUMER DATA','VARIANCE IS NOT A SAFETY OR QUALITY DETERMINATION','NO PRODUCT RECOMMENDATION OR EFFECTIVENESS CLAIM']),preservedFields:PRESERVED},
 {caseId:'EVIDENCE-ORBIT',audience:'PATIENT ADVOCATE',truthAnchor:anchor('SYN-078-OR-01','Orbit Experience Archive Fixture','SYNTHETIC PATIENT-REPORTED ARCHIVE','QUALITATIVE FIXTURE; FIVE INVENTED ACCOUNTS; NO REAL PEOPLE','The fictional accounts describe different experiences and unresolved access questions.','Five invented narrative records','Varied fictional cannabis-related contexts','No common comparison','Themes in synthetic experience narratives','Very small purposive fixture; invented narratives; no validated measure; no clinical verification','The fixture preserves experience diversity; prevalence, causation, typicality, and clinical meaning are unknown.','2044-03-12'),translatedExplanation:'These five invented accounts show how different cannabis-related experiences and access questions can be preserved without turning stories into medical conclusions. They cannot tell anyone what is typical, safe, effective, or appropriate.',caveats:Object.freeze(['NO REAL PEOPLE OR PATIENT TESTIMONY','EXPERIENCE THEMES DO NOT ESTABLISH PREVALENCE OR CAUSATION','NOT MEDICAL ADVICE OR A PRODUCT, TREATMENT, OR DOSAGE RECOMMENDATION']),preservedFields:PRESERVED}
]);
const base={fixtureId:'SYNTHETIC-CANNABIS-EVIDENCE-078',cases:EVIDENCE_TRANSLATION_CASES,inherited:{audienceProfiles:'cap:002',telemetryGuardrails:'cap:031',evidenceSupport:'cap:051',sourceProvenance:'cap:058'},admission:{syntheticOnly:true,fixedAudiencePerCase:true,realPatientData:false,realProductData:false,realLawClaim:false,legalAdvice:'NONE',clinicalAdvice:'NONE',diagnosisTreatmentDosageClaim:false,safetyEffectivenessClaim:false,complianceDetermined:false}} as const;
export const EVIDENCE_TRANSLATION_PRESETS:Readonly<Record<EvidenceCaseId,TranslationInput>>=Object.freeze(Object.fromEntries(EVIDENCE_TRANSLATION_CASES.map(x=>[x.caseId,Object.freeze({...base,caseId:x.caseId})])) as Record<EvidenceCaseId,TranslationInput>);
const invalid=():TranslationResult=>({status:'INVALID',translation:null,alerts:['INVALID OR UNADMITTED SYNTHETIC INPUT','NO TRANSLATION PRODUCED'],audit:[],nonClaims:['NO REAL PATIENT, PRODUCT, LEGAL, CLINICAL, DIAGNOSIS, TREATMENT, DOSAGE, SAFETY, EFFECTIVENESS, CURRENT-LAW, OR COMPLIANCE CLAIM'],engineVersion:EVIDENCE_TRANSLATION_ENGINE_VERSION});
function evaluate(candidate:unknown):TranslationResult{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const object=candidate as Record<string,unknown>;const preset=EVIDENCE_TRANSLATION_PRESETS[object.caseId as EvidenceCaseId];if(!preset||JSON.stringify(object)!==JSON.stringify(preset))return invalid();const translation=preset.cases.find(x=>x.caseId===preset.caseId)!;return{status:`${translation.caseId} TRANSLATION`,translation,alerts:['SYNTHETIC EVIDENCE TRANSLATION ONLY','AUDIENCE LANGUAGE CHANGES; TRUTH ANCHORS AND CAVEATS DO NOT'],audit:['VALIDATED EXACT FROZEN FIXTURE','PRESERVED SOURCE TYPE, QUALITY, CLAIM, POPULATION, EXPOSURE, COMPARISON, OUTCOME, LIMITATIONS, UNCERTAINTY, AND AS-OF DATE','PRESERVED AUDIENCE CAVEATS','NO SOURCE UPGRADING, CLAIM EXPANSION, LIMIT REMOVAL, OR REAL-WORLD INFERENCE'],nonClaims:['NO REAL PATIENT OR PRODUCT DATA','NO LEGAL OR CLINICAL ADVICE','NO DIAGNOSIS, TREATMENT, DOSAGE, SAFETY, EFFECTIVENESS, CURRENT-LAW, OR COMPLIANCE CLAIM'],engineVersion:EVIDENCE_TRANSLATION_ENGINE_VERSION}}
export function translateCannabisEvidence(candidate:unknown):TranslationResult{try{return evaluate(candidate)}catch{return invalid()}}
