export type AccessContext={location:string;budget:number;travelLimitKm:number;mobility:'standard'|'limited';eligibility:'unknown'|'eligible'|'ineligible';clinician:'available'|'waitlist'|'unavailable';supply:'available'|'limited'|'unavailable'};
export type AccessStep={id:string;label:string;cost:number;distanceKm:number;requiresEligibility?:boolean;requiresClinician?:boolean;requiresSupply?:boolean;accessible?:boolean;alternatives:string[]};
export type JourneyResult={status:'ROUTE AVAILABLE'|'BLOCKED'|'NEEDS VERIFICATION';route:string[];barriers:string[];totalCost:number;totalDistanceKm:number;engineVersion:string};
export const CANNABIS_CARE_ACCESS_ENGINE_VERSION='045.2.0';
export const CARE_STEP_CONTRACT={
 LEARN:{label:'Understand the pathway',requiresEligibility:false,requiresClinician:false,requiresSupply:false},
 VERIFY:{label:'Verify eligibility',requiresEligibility:true,requiresClinician:false,requiresSupply:false},
 CLINICIAN:{label:'Reach a clinician',requiresEligibility:false,requiresClinician:true,requiresSupply:false},
 SUPPLY:{label:'Locate lawful supply',requiresEligibility:false,requiresClinician:false,requiresSupply:true},
 RECORDS:{label:'Keep consent and records',requiresEligibility:false,requiresClinician:false,requiresSupply:false}
}as const;
const IDS=Object.keys(CARE_STEP_CONTRACT)as Array<keyof typeof CARE_STEP_CONTRACT>;const money=(n:number)=>Number.isFinite(n)&&n>=0&&Math.round(n*100)===n*100;const distance=(n:number)=>Number.isFinite(n)&&n>=0;
export function routeCare(context:AccessContext,steps:AccessStep[]):JourneyResult{
 const hard:string[]=[];const verify:string[]=[];const counts=new Map<string,number>();const contextValid=!!context.location.trim()&&money(context.budget)&&distance(context.travelLimitKm)&&['standard','limited'].includes(context.mobility)&&['unknown','eligible','ineligible'].includes(context.eligibility)&&['available','waitlist','unavailable'].includes(context.clinician)&&['available','limited','unavailable'].includes(context.supply);if(!contextValid)hard.push('INVALID CONTEXT');
 for(const step of steps)counts.set(step.id,(counts.get(step.id)||0)+1);if(steps.length!==IDS.length||IDS.some(id=>counts.get(id)!==1))hard.push('INVALID ROUTE IDENTITY');
 let cents=0,totalDistanceKm=0;for(const step of steps){const expected=CARE_STEP_CONTRACT[step.id as keyof typeof CARE_STEP_CONTRACT];const alternativesValid=step.alternatives.length>0&&step.alternatives.every(x=>x.trim())&&new Set(step.alternatives.map(x=>x.trim().toLocaleLowerCase('en-US'))).size===step.alternatives.length;if(!expected||step.label!==expected.label||!!step.requiresEligibility!==expected.requiresEligibility||!!step.requiresClinician!==expected.requiresClinician||!!step.requiresSupply!==expected.requiresSupply||!money(step.cost)||!distance(step.distanceKm)||!alternativesValid){hard.push(`INVALID STEP: ${step.id||'UNNAMED'}`);continue}cents+=Math.round(step.cost*100);totalDistanceKm+=step.distanceKm;if(step.requiresEligibility){if(context.eligibility==='ineligible')hard.push(`${step.label}: ELIGIBILITY BLOCK`);if(context.eligibility==='unknown')verify.push(`${step.label}: VERIFY ELIGIBILITY`)}if(step.requiresClinician){if(context.clinician==='unavailable')hard.push(`${step.label}: CLINICIAN UNAVAILABLE`);if(context.clinician==='waitlist')verify.push(`${step.label}: CLINICIAN WAITLIST`)}if(step.requiresSupply){if(context.supply==='unavailable')hard.push(`${step.label}: SUPPLY UNAVAILABLE`);if(context.supply==='limited')verify.push(`${step.label}: SUPPLY LIMITED`)}if(context.mobility==='limited'&&step.accessible===false)hard.push(`${step.label}: MOBILITY BARRIER`)}
 const totalCost=cents/100;if(contextValid&&totalCost>context.budget)hard.push(`COST GAP: ${(totalCost-context.budget).toFixed(2)}`);if(contextValid&&totalDistanceKm>context.travelLimitKm)hard.push(`TRAVEL GAP: ${(totalDistanceKm-context.travelLimitKm).toFixed(1)} KM`);
 const barriers=[...new Set([...hard,...verify])];const status=hard.length?'BLOCKED':verify.length?'NEEDS VERIFICATION':'ROUTE AVAILABLE';return{status,route:hard.length?[]:IDS.filter(id=>counts.get(id)===1),barriers,totalCost:hard.some(x=>x.startsWith('INVALID'))?0:totalCost,totalDistanceKm:hard.some(x=>x.startsWith('INVALID'))?0:totalDistanceKm,engineVersion:CANNABIS_CARE_ACCESS_ENGINE_VERSION}
}
