export type CaseId='WITHIN_PERSON'|'POPULATION'|'SINGLE_OBSERVATION'|'SMALL_CELL'|'CONSENT_MISMATCH'|'WITHDRAWN_CONSENT'|'PROHIBITED_INFERENCE'|'MISSING_PROVENANCE'|'STALE_EVIDENCE'|'CONFOUNDED_CONTEXT'|'CONFLICTING_RESPONSES'|'CROSS_PERSON_PREDICTION';
export type Mode='INDIVIDUAL'|'POPULATION';
export type Disposition='INVALID_RECORD'|'INDIVIDUAL_PATTERN_OBSERVED'|'POPULATION_ASSOCIATION_OBSERVED'|'INSUFFICIENT_LONGITUDINAL_EVIDENCE'|'REIDENTIFICATION_BLOCKED'|'CONSENT_SCOPE_BLOCKED'|'WITHDRAWN_NO_REUSE'|'PROHIBITED_INFERENCE'|'PROVENANCE_MISSING'|'STALE_EVIDENCE'|'ASSOCIATION_WITH_LIMITS'|'DISAGREEMENT_PRESERVED'|'PERSONALIZATION_PROHIBITED';
export type Case96={id:CaseId;label:string;mode:Mode;consent:'VALID'|'MISMATCH'|'WITHDRAWN';smallCell:boolean;prohibited:boolean;provenance:boolean;fresh:boolean;repeats:number;confounded:boolean;conflicting:boolean;crossPerson:boolean;privateMarker?:string};
export type Input={fixtureId:'SYNTHETIC-CANNABIS-EXPERIENCE-096';caseId:CaseId;mode:Mode;removeContext:boolean;cases:readonly Case96[];admission:{syntheticOnly:true;noMedicalAdvice:true;noDosing:true;noPurchaseAdvice:true;externalEffects:false;realPeople:false}};
export type Result={disposition:Disposition;caseId:CaseId|null;mode:Mode|null;gates:readonly {name:string;state:'PASS'|'BLOCK'|'NOT_RUN';reason:string}[];constellation:readonly {type:string;state:string}[];pattern:string|null;uncertainty:readonly string[];nonClaims:readonly string[];asOf:typeof AS_OF};
export const AS_OF='2026-08-22T12:00:00.000Z' as const;
const freeze=<T>(v:T):T=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v as Record<string,unknown>))freeze(x)}return v};
const row=(id:CaseId,label:string,mode:Mode,extra:Partial<Case96>={}):Case96=>freeze({id,label,mode,consent:'VALID',smallCell:false,prohibited:false,provenance:true,fresh:true,repeats:3,confounded:false,conflicting:false,crossPerson:false,...extra});
export const CASES=freeze([
row('WITHIN_PERSON','Repeated within-person observations','INDIVIDUAL'),row('POPULATION','Adequate fictional aggregate','POPULATION'),row('SINGLE_OBSERVATION','One observation','INDIVIDUAL',{repeats:1}),row('SMALL_CELL','Population cell below privacy threshold','POPULATION',{smallCell:true,privateMarker:'HIDDEN-CANNABIS-CELL-96'}),row('CONSENT_MISMATCH','Consent purpose mismatch','INDIVIDUAL',{consent:'MISMATCH',privateMarker:'PRIVATE-EXPERIENCE-96'}),row('WITHDRAWN_CONSENT','Consent withdrawn','INDIVIDUAL',{consent:'WITHDRAWN',privateMarker:'WITHDRAWN-NARRATIVE-96'}),row('PROHIBITED_INFERENCE','Diagnosis or dosing request','INDIVIDUAL',{prohibited:true}),row('MISSING_PROVENANCE','Composition provenance missing','INDIVIDUAL',{provenance:false}),row('STALE_EVIDENCE','Superseded composition record','INDIVIDUAL',{fresh:false}),row('CONFOUNDED_CONTEXT','Setting and timing confounded','INDIVIDUAL',{confounded:true}),row('CONFLICTING_RESPONSES','Divergent experiences preserved','POPULATION',{conflicting:true}),row('CROSS_PERSON_PREDICTION','Apply population result to person','POPULATION',{crossPerson:true})
]as const);
const base=freeze({fixtureId:'SYNTHETIC-CANNABIS-EXPERIENCE-096',cases:CASES,admission:{syntheticOnly:true,noMedicalAdvice:true,noDosing:true,noPurchaseAdvice:true,externalEffects:false,realPeople:false}}as const);
export const PRESETS=freeze(Object.fromEntries(CASES.map(x=>[x.id,freeze({...base,caseId:x.id,mode:x.mode,removeContext:false})]))as unknown as Record<CaseId,Input>);
const nonClaims=freeze(['EXPERIENCE IS NOT CAUSATION','MISSING IS NOT ZERO; NOT OBSERVED IS NOT ABSENT','INDIVIDUAL PATTERN IS NOT A POPULATION PATTERN','POPULATION PATTERN IS NOT A PERSONAL PREDICTION','NO DIAGNOSIS, DOSING, IMPAIRMENT, DEPENDENCE, INTERACTION, SAFETY, TREATMENT, PURCHASE, PRODUCT, OR LEGALITY ADVICE','JURISDICTION UNSPECIFIED—NO LEGALITY DETERMINATION','NO REAL PEOPLE, PRODUCTS, LABS, ACCOUNTS, HISTORIES, STORAGE, TRACKING, OR EXTERNAL EFFECTS']);
const invalid=():Result=>freeze({disposition:'INVALID_RECORD',caseId:null,mode:null,gates:[],constellation:[],pattern:null,uncertainty:[],nonClaims,asOf:AS_OF});
export function learn(candidate:unknown):Result{try{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const o=candidate as Input,p=PRESETS[o.caseId];if(!p||!['INDIVIDUAL','POPULATION'].includes(o.mode)||typeof o.removeContext!=='boolean'||JSON.stringify(o)!==JSON.stringify({...p,mode:o.mode,removeContext:o.removeContext}))return invalid();const x=p.cases.find(c=>c.id===o.caseId)!;let d:Disposition=x.mode==='INDIVIDUAL'?'INDIVIDUAL_PATTERN_OBSERVED':'POPULATION_ASSOCIATION_OBSERVED',block=-1,why='DESCRIPTIVE_ASSOCIATION_WITH_UNCERTAINTY';if(x.prohibited){d='PROHIBITED_INFERENCE';block=0;why='MEDICAL_DOSING_OR_PREDICTION_USE_BLOCKED'}else if(x.consent==='MISMATCH'){d='CONSENT_SCOPE_BLOCKED';block=1;why='PURPOSE_BOUND_CONSENT_MISMATCH'}else if(x.consent==='WITHDRAWN'){d='WITHDRAWN_NO_REUSE';block=1;why='CONSENT_WITHDRAWN'}else if(x.smallCell){d='REIDENTIFICATION_BLOCKED';block=2;why='POPULATION_CELL_BELOW_PRIVACY_THRESHOLD'}else if(!x.provenance){d='PROVENANCE_MISSING';block=3;why='COMPOSITION_SOURCE_UNVERIFIED'}else if(!x.fresh){d='STALE_EVIDENCE';block=4;why='COMPOSITION_OR_CONTEXT_VERSION_SUPERSEDED'}else if(x.repeats<2){d='INSUFFICIENT_LONGITUDINAL_EVIDENCE';block=5;why='REPEATED_OBSERVATIONS_REQUIRED'}else if(x.crossPerson||o.mode!==x.mode){d='PERSONALIZATION_PROHIBITED';block=6;why='SCOPE_TRANSFER_NOT_ALLOWED'}else if(x.confounded||o.removeContext){d='ASSOCIATION_WITH_LIMITS';block=7;why='CONTEXT_REQUIRED_FOR_INTERPRETATION'}else if(x.conflicting){d='DISAGREEMENT_PRESERVED';block=7;why='DIVERGENT_RESPONSES_NOT_AVERAGED_AWAY'}const names=['PROHIBITED PURPOSE','CONSENT + SCOPE','PRIVACY THRESHOLD','PROVENANCE','FRESHNESS','LONGITUDINAL SUFFICIENCY','INDIVIDUAL / POPULATION SEPARATION','CONTEXT + CONFOUNDING','PATTERN'];const gates=freeze(names.map((name,i)=>({name,state:(block<0?'PASS':i<block?'PASS':i===block?'BLOCK':'NOT_RUN')as 'PASS'|'BLOCK'|'NOT_RUN',reason:i===block?why:block<0?'SATISFIED':'NOT_EVALUATED_AFTER_FIRST_BLOCK'})));const hidden=!!x.privateMarker;const constellation=hidden?freeze([{type:'RESTRICTED EXPERIENCE',state:'WITHHELD'}]):freeze(['COMPOSITION','FORMAT','CONTEXT','TIME','SUBJECTIVE RESPONSE','TOLERABILITY','EVIDENCE'].map(type=>({type,state:o.removeContext&&type==='CONTEXT'?'MISSING':block<0?'OBSERVED':'LIMITED'})));const safe=d==='INDIVIDUAL_PATTERN_OBSERVED'||d==='POPULATION_ASSOCIATION_OBSERVED'||d==='ASSOCIATION_WITH_LIMITS'||d==='DISAGREEMENT_PRESERVED';return freeze({disposition:d,caseId:hidden?null:o.caseId,mode:hidden?null:o.mode,gates,constellation,pattern:safe?'CO-OCCURRED_IN_SYNTHETIC_RECORDS':null,uncertainty:freeze(['No causal conclusion.','No transfer across people or populations.','Composition labels do not predict response.']),nonClaims,asOf:AS_OF})}catch{return invalid()}}
export function buildExport(candidate:unknown){const result=learn(candidate);return freeze({build:'096',schemaVersion:'build-096.v1',canonical:{title:'Cannabis Experience Intelligence System',publicTitle:'Learn From Cannabis Experience Without Reducing People to Labels',uses:['049','052','053','058'],creates:'cap:096'},artifacts:['Experience Knowledge Graph','Response Pattern Engine'],syntheticOnly:true,externalEffects:false,result})}