export type JurisdictionId = 'JURISDICTION-EMBER' | 'JURISDICTION-HARBOR' | 'JURISDICTION-LATTICE' | 'JURISDICTION-MESA' | 'JURISDICTION-ORBIT';
export type ComparativeQueryId = 'Q-WHO-MAY-ACT' | 'Q-WHAT-AUTHORITY' | 'Q-WHEN-EFFECTIVE';
export type SourceStatus = 'SUPPORTED-BY-SYNTHETIC-SOURCES' | 'CONFLICT-IN-SYNTHETIC-SOURCES' | 'UNKNOWN-IN-SYNTHETIC-FIXTURE';
export type SyntheticSourceRecord = { id: string; title: string; locator: string; issuedOn: string; effectiveOn: string | null; asOf: string; proposition: string; status: 'SYNTHETIC-SOURCE-CHECKED' };
export type SyntheticJurisdiction = { id: JurisdictionId; label: string; registryAsOf: string; sources: readonly SyntheticSourceRecord[] };
export type ComparativeQuery = { id: ComparativeQueryId; label: string; concreteQuestion: string; field: 'ACTOR' | 'AUTHORITY' | 'EFFECTIVE_DATE' };
export type RegulatoryIntelligenceInput = { fixtureId: 'SYNTHETIC-CROSS-JURISDICTION-076'; queryId: ComparativeQueryId; jurisdictions: readonly SyntheticJurisdiction[]; queries: readonly ComparativeQuery[]; inherited: { sourceRegistry: 'cap:028'; evidenceDates: 'cap:029'; policyLandscape: 'cap:058'; comparisonMethod: 'cap:059'; implementationTracker: 'cap:069'; designOntology: 'cap:075' }; admission: { syntheticOnly: true; fixedSourcesOnly: true; realLawClaim: false; legalAdvice: 'NONE'; globalCoverageClaim: false; completenessClaim: false } };
export type ComparativeRow = { jurisdictionId: JurisdictionId; jurisdictionLabel: string; answer: string | null; status: SourceStatus; sourceRecords: readonly SyntheticSourceRecord[]; effectiveOn: string | null; asOf: string; conflict: string | null; unknown: string | null };
export type RegulatoryIntelligenceResult = { status: `${ComparativeQueryId} COMPARISON` | 'INVALID'; query: ComparativeQuery | null; rows: readonly ComparativeRow[]; diffFields: readonly string[]; alerts: readonly string[]; audit: readonly string[]; nonClaims: readonly string[]; engineVersion: typeof REGULATORY_INTELLIGENCE_ENGINE_VERSION };

export const REGULATORY_INTELLIGENCE_ENGINE_VERSION = '076.1.0' as const;
const source = (id:string,title:string,locator:string,issuedOn:string,effectiveOn:string|null,asOf:string,proposition:string): SyntheticSourceRecord => Object.freeze({id,title,locator,issuedOn,effectiveOn,asOf,proposition,status:'SYNTHETIC-SOURCE-CHECKED'});
export const REGULATORY_INTELLIGENCE_JURISDICTIONS: readonly SyntheticJurisdiction[] = Object.freeze([
 {id:'JURISDICTION-EMBER',label:'Ember',registryAsOf:'2042-04-18',sources:Object.freeze([source('SYN-076-EM-01','Ember Framework § 4','§4(a)','2041-11-02','2042-02-01','2042-04-18','REGISTERED ORGANIZATIONS MAY ACT UNDER CENTRAL AUTHORITY'),source('SYN-076-EM-02','Ember Implementation Notice','¶12','2042-01-12','2042-02-01','2042-04-18','CENTRAL OFFICE ISSUES OPERATING AUTHORITY')])},
 {id:'JURISDICTION-HARBOR',label:'Harbor',registryAsOf:'2042-04-16',sources:Object.freeze([source('SYN-076-HA-01','Harbor Enabling Text','Art. 7','2041-12-08','2042-03-15','2042-04-16','LICENSED INDIVIDUALS MAY ACT UNDER SHARED AUTHORITY'),source('SYN-076-HA-02','Harbor Circular 3','p. 6','2042-02-20','2042-03-15','2042-04-16','REGIONAL AND CENTRAL OFFICES SHARE AUTHORITY')])},
 {id:'JURISDICTION-LATTICE',label:'Lattice',registryAsOf:'2042-04-17',sources:Object.freeze([source('SYN-076-LA-01','Lattice Code § 9','§9(b)','2041-10-30','2042-01-20','2042-04-17','ACCREDITED COOPERATIVES MAY ACT UNDER LOCAL AUTHORITY'),source('SYN-076-LA-02','Lattice Rulebook','Rule 9.4','2042-01-04','2042-01-20','2042-04-17','LOCAL BOARDS ISSUE OPERATING AUTHORITY')])},
 {id:'JURISDICTION-MESA',label:'Mesa',registryAsOf:'2042-04-15',sources:Object.freeze([source('SYN-076-ME-01','Mesa Act § 11','§11(c)','2041-12-19','2042-05-01','2042-04-15','PERMITTED ENTITIES MAY ACT UNDER INDEPENDENT AUTHORITY'),source('SYN-076-ME-02','Mesa Transition Bulletin','item 5','2042-03-01','2042-06-01','2042-04-15','PERMITTED ENTITIES MAY ACT AFTER TRANSITION')])},
 {id:'JURISDICTION-ORBIT',label:'Orbit',registryAsOf:'2042-04-14',sources:Object.freeze([source('SYN-076-OR-01','Orbit Framework','cl. 6','2042-01-09',null,'2042-04-14','ELIGIBLE NETWORKS MAY ACT; AUTHORITY NOT SPECIFIED'),source('SYN-076-OR-02','Orbit Draft Notice','note 2','2042-03-22',null,'2042-04-14','ACTOR AND EFFECTIVE DATE REMAIN UNSPECIFIED')])},
]);
export const REGULATORY_INTELLIGENCE_QUERIES: readonly ComparativeQuery[] = Object.freeze([
 {id:'Q-WHO-MAY-ACT',label:'Who may act?',concreteQuestion:'Who may act under the synthetic rule?',field:'ACTOR'},
 {id:'Q-WHAT-AUTHORITY',label:'What authority controls?',concreteQuestion:'Which synthetic authority controls operation?',field:'AUTHORITY'},
 {id:'Q-WHEN-EFFECTIVE',label:'When is it effective?',concreteQuestion:'When does the synthetic rule become effective?',field:'EFFECTIVE_DATE'},
]);
const base={fixtureId:'SYNTHETIC-CROSS-JURISDICTION-076',jurisdictions:REGULATORY_INTELLIGENCE_JURISDICTIONS,queries:REGULATORY_INTELLIGENCE_QUERIES,inherited:{sourceRegistry:'cap:028',evidenceDates:'cap:029',policyLandscape:'cap:058',comparisonMethod:'cap:059',implementationTracker:'cap:069',designOntology:'cap:075'},admission:{syntheticOnly:true,fixedSourcesOnly:true,realLawClaim:false,legalAdvice:'NONE',globalCoverageClaim:false,completenessClaim:false}} as const;
export const REGULATORY_INTELLIGENCE_PRESETS: Readonly<Record<ComparativeQueryId,RegulatoryIntelligenceInput>>=Object.freeze({'Q-WHO-MAY-ACT':Object.freeze({...base,queryId:'Q-WHO-MAY-ACT'}),'Q-WHAT-AUTHORITY':Object.freeze({...base,queryId:'Q-WHAT-AUTHORITY'}),'Q-WHEN-EFFECTIVE':Object.freeze({...base,queryId:'Q-WHEN-EFFECTIVE'})});
const invalid=():RegulatoryIntelligenceResult=>({status:'INVALID',query:null,rows:[],diffFields:[],alerts:['INVALID OR UNADMITTED SYNTHETIC INPUT','NO COMPARISON PRODUCED'],audit:[],nonClaims:['NO REAL-LAW, LEGAL-ADVICE, COMPLIANCE, COMPLETENESS, AUTHORITY, OR GLOBAL-COVERAGE CLAIM'],engineVersion:REGULATORY_INTELLIGENCE_ENGINE_VERSION});
const answers:Record<ComparativeQueryId,Record<JurisdictionId,string|null>>={
 'Q-WHO-MAY-ACT':{'JURISDICTION-EMBER':'REGISTERED ORGANIZATIONS','JURISDICTION-HARBOR':'LICENSED INDIVIDUALS','JURISDICTION-LATTICE':'ACCREDITED COOPERATIVES','JURISDICTION-MESA':'PERMITTED ENTITIES','JURISDICTION-ORBIT':null},
 'Q-WHAT-AUTHORITY':{'JURISDICTION-EMBER':'CENTRAL OFFICE','JURISDICTION-HARBOR':'SHARED REGIONAL AND CENTRAL OFFICES','JURISDICTION-LATTICE':'LOCAL BOARDS','JURISDICTION-MESA':'INDEPENDENT AUTHORITY','JURISDICTION-ORBIT':null},
 'Q-WHEN-EFFECTIVE':{'JURISDICTION-EMBER':'2042-02-01','JURISDICTION-HARBOR':'2042-03-15','JURISDICTION-LATTICE':'2042-01-20','JURISDICTION-MESA':null,'JURISDICTION-ORBIT':null},
};
function evaluate(candidate:unknown):RegulatoryIntelligenceResult{
 if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid(); const object=candidate as Record<string,unknown>; const preset=REGULATORY_INTELLIGENCE_PRESETS[object.queryId as ComparativeQueryId]; if(!preset||JSON.stringify(object)!==JSON.stringify(preset))return invalid();
 const query=preset.queries.find(item=>item.id===preset.queryId)!; const rows=preset.jurisdictions.map(j=>{const answer=answers[preset.queryId][j.id]; const mesaConflict=preset.queryId==='Q-WHEN-EFFECTIVE'&&j.id==='JURISDICTION-MESA'; const unknown=answer===null&&!mesaConflict; return {jurisdictionId:j.id,jurisdictionLabel:j.label,answer,status:mesaConflict?'CONFLICT-IN-SYNTHETIC-SOURCES':unknown?'UNKNOWN-IN-SYNTHETIC-FIXTURE':'SUPPORTED-BY-SYNTHETIC-SOURCES',sourceRecords:j.sources,effectiveOn:preset.queryId==='Q-WHEN-EFFECTIVE'?(mesaConflict?null:j.sources[0].effectiveOn):j.sources[0].effectiveOn,asOf:j.registryAsOf,conflict:mesaConflict?'SYNTHETIC SOURCES DISAGREE: 2042-05-01 / 2042-06-01':null,unknown:unknown?'FIXED SYNTHETIC FIXTURE DOES NOT SUPPLY THIS ANSWER':null} as ComparativeRow});
 return {status:`${preset.queryId} COMPARISON`,query,rows,diffFields:['ANSWER','SOURCE LOCATOR','ISSUED ON','EFFECTIVE ON','AS OF','CONFLICT','UNKNOWN'],alerts:['SYNTHETIC SOURCE-LEVEL COMPARISON ONLY','SIMILAR LABELS DO NOT ESTABLISH EQUIVALENT LAW'],audit:['VALIDATED EXACT FROZEN FIXTURE','PRESERVED FIVE-JURISDICTION SOURCE ORDER','PRESERVED SOURCE LOCATORS AND DATES','PRESERVED CONFLICTS AND UNKNOWNS','NO IMPUTATION OR REAL-LAW LOOKUP'],nonClaims:['NO CURRENT-LAW OR REAL-JURISDICTION CLAIM','NO LEGAL ADVICE OR COMPLIANCE DETERMINATION','NO COMPLETE, AUTHORITATIVE, OR GLOBAL COVERAGE CLAIM'],engineVersion:REGULATORY_INTELLIGENCE_ENGINE_VERSION};
}
export function compareJurisdictionLaw(candidate:unknown):RegulatoryIntelligenceResult{try{return evaluate(candidate)}catch{return invalid()}}
