export type CaseId='ACCESSIBLE_BASELINE'|'UNCERTAIN_WAIT'|'REPEATED_DISCLOSURE'|'SENSORY_LOAD'|'PARTICIPATION_BARRIER'|'SMALL_SAMPLE'|'STALE_OBSERVATION'|'CONSENT_BLOCK'|'REIDENTIFICATION_RISK'|'PROHIBITED_INFERENCE'|'MISSING_PROVENANCE'|'CONFLICTING_REPORTS';
export type Disposition='INVALID_RECORD'|'AVAILABLE_WITH_LIMITS'|'INSUFFICIENT_EVIDENCE'|'STALE_EVIDENCE'|'CONSENT_SCOPE_BLOCKED'|'REIDENTIFICATION_BLOCKED'|'PROHIBITED_INFERENCE'|'PROVENANCE_MISSING'|'DISAGREEMENT_PRESERVED';
export type Dimension='STRESS_CONDITIONS'|'ATTENTION_DEMANDS'|'DIGNITY_PRIVACY'|'SENSORY_LOAD'|'CONTROL_CHOICE'|'PARTICIPATION_RECOURSE';
export type Case95={id:CaseId;label:string;restricted:boolean;consentValid:boolean;reidentificationRisk:boolean;prohibitedInference:boolean;provenance:boolean;fresh:boolean;sample:'SUFFICIENT'|'SMALL'|'CONFLICTING';stages:readonly string[];dimensions:readonly Dimension[];evidenceType:'DOCUMENT'|'OBSERVATION'|'PARTICIPANT_REPORT';repairable:boolean;privateMarker?:string};
export type Input={fixtureId:'SYNTHETIC-GOVERNANCE-OBSERVATORY-095';caseId:CaseId;applyRepair:boolean;cases:readonly Case95[];admission:{syntheticOnly:true;noBiometrics:true;noDiagnosis:true;externalEffects:false;realPeople:false}};
export type Result={disposition:Disposition;caseId:CaseId|null;gates:readonly {name:string;state:'PASS'|'BLOCK'|'NOT_RUN';reason:string}[];journey:readonly {stage:string;state:string}[];findings:readonly {dimension:Dimension;finding:string;evidenceType:string}[];nonClaims:readonly string[];asOf:typeof AS_OF};
export const AS_OF='2026-08-22T12:00:00.000Z' as const;
const freeze=<T>(v:T):T=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v as Record<string,unknown>))freeze(x)}return v};
const stages=freeze(['RULE OR PROCESS','SPACE OR CHANNEL','WAIT','HANDOFF','RECOURSE']);
const row=(id:CaseId,label:string,dimensions:Dimension[],extra:Partial<Case95>={}):Case95=>freeze({id,label,restricted:false,consentValid:true,reidentificationRisk:false,prohibitedInference:false,provenance:true,fresh:true,sample:'SUFFICIENT',stages,dimensions,evidenceType:'OBSERVATION',repairable:true,...extra});
export const CASES=freeze([
row('ACCESSIBLE_BASELINE','Predictable accessible intake',['CONTROL_CHOICE','PARTICIPATION_RECOURSE']),row('UNCERTAIN_WAIT','Unexplained extended wait',['STRESS_CONDITIONS','ATTENTION_DEMANDS']),row('REPEATED_DISCLOSURE','Repeated disclosure across handoffs',['DIGNITY_PRIVACY','CONTROL_CHOICE']),row('SENSORY_LOAD','High sensory load; no alternate channel',['SENSORY_LOAD','PARTICIPATION_RECOURSE']),row('PARTICIPATION_BARRIER','Complex language and format barrier',['ATTENTION_DEMANDS','PARTICIPATION_RECOURSE']),row('SMALL_SAMPLE','Single participant report',['STRESS_CONDITIONS'],{sample:'SMALL',evidenceType:'PARTICIPANT_REPORT'}),row('STALE_OBSERVATION','Superseded observation window',['CONTROL_CHOICE'],{fresh:false}),row('CONSENT_BLOCK','Purpose-bound consent mismatch',['DIGNITY_PRIVACY'],{consentValid:false,privateMarker:'WITHHELD-NARRATIVE-95'}),row('REIDENTIFICATION_RISK','Cross-context join risk',['DIGNITY_PRIVACY'],{reidentificationRisk:true,privateMarker:'HIDDEN-CELL-95'}),row('PROHIBITED_INFERENCE','Unsupported biometric diagnosis',['STRESS_CONDITIONS'],{prohibitedInference:true,privateMarker:'FAKE-DIAGNOSIS-95'}),row('MISSING_PROVENANCE','Observation without source chain',['SENSORY_LOAD'],{provenance:false}),row('CONFLICTING_REPORTS','Conflicting lived-condition reports',['CONTROL_CHOICE','DIGNITY_PRIVACY'],{sample:'CONFLICTING',evidenceType:'PARTICIPANT_REPORT'})
]as const);
const base=freeze({fixtureId:'SYNTHETIC-GOVERNANCE-OBSERVATORY-095',cases:CASES,admission:{syntheticOnly:true,noBiometrics:true,noDiagnosis:true,externalEffects:false,realPeople:false}}as const);
export const PRESETS=freeze(Object.fromEntries(CASES.map(x=>[x.id,freeze({...base,caseId:x.id,applyRepair:false})]))as unknown as Record<CaseId,Input>);
const nonClaims=freeze(['INSTITUTIONAL CONDITIONS ARE NOT BODY MEASUREMENTS','SELF-REPORT IS NOT DIAGNOSIS','ASSOCIATION IS NOT CAUSATION','MISSING IS NOT ZERO; NOT OBSERVED IS NOT ABSENT','NO BIOMETRICS, HEALTH INFERENCE, TRAUMA DETECTION, HUMAN RANKING, OR MEDICAL ADVICE','NO REAL PEOPLE, INSTITUTIONS, RECORDS, TRACKING, STORAGE, OR EXTERNAL EFFECTS']);
const invalid=():Result=>freeze({disposition:'INVALID_RECORD',caseId:null,gates:[],journey:[],findings:[],nonClaims,asOf:AS_OF});
export function observe(candidate:unknown):Result{try{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const o=candidate as Input,p=PRESETS[o.caseId];if(!p||typeof o.applyRepair!=='boolean'||JSON.stringify(o)!==JSON.stringify({...p,applyRepair:o.applyRepair}))return invalid();const x=p.cases.find(c=>c.id===o.caseId)!;let d:Disposition='AVAILABLE_WITH_LIMITS',block=-1,why='BOUNDED_INSTITUTIONAL_CONDITION';if(x.prohibitedInference){d='PROHIBITED_INFERENCE';block=0;why='NO_DIAGNOSTIC_OR_BIOMETRIC_INFERENCE'}else if(!x.consentValid){d='CONSENT_SCOPE_BLOCKED';block=1;why='PURPOSE_BOUND_CONSENT_MISMATCH'}else if(x.reidentificationRisk){d='REIDENTIFICATION_BLOCKED';block=2;why='SMALL_CELL_OR_CROSS_CONTEXT_JOIN_RISK'}else if(!x.provenance){d='PROVENANCE_MISSING';block=3;why='SOURCE_CHAIN_ABSENT'}else if(!x.fresh){d='STALE_EVIDENCE';block=4;why='OBSERVATION_WINDOW_SUPERSEDED'}else if(x.sample==='SMALL'){d='INSUFFICIENT_EVIDENCE';block=5;why='ONE_REPORT_CANNOT_SUPPORT_INSTITUTION_COMPARISON'}else if(x.sample==='CONFLICTING'){d='DISAGREEMENT_PRESERVED';block=6;why='CONFLICTING_REPORTS_NOT_AVERAGED_AWAY'}const names=['PROHIBITED INFERENCE','CONSENT + PURPOSE','REIDENTIFICATION','PROVENANCE','FRESHNESS','SAMPLE','COMPARABILITY'];const gates=freeze(names.map((name,i)=>({name,state:(block<0?'PASS':i<block?'PASS':i===block?'BLOCK':'NOT_RUN')as 'PASS'|'BLOCK'|'NOT_RUN',reason:i===block?why:block<0?'SATISFIED':'NOT_EVALUATED_AFTER_FIRST_BLOCK'})));const blocked=block>=0;const journey=blocked?freeze([{stage:'WITHHELD OR LIMITED JOURNEY',state:'NOT RENDERED'}]):freeze(x.stages.map(stage=>({stage,state:o.applyRepair&&x.repairable?'SYNTHETIC PROCESS REPAIR APPLIED':'OBSERVED CONDITION'})));const findings=blocked?freeze([]):freeze(x.dimensions.map(dimension=>({dimension,finding:o.applyRepair?'PROTECTIVE_CONDITION_IN_FROZEN_REHEARSAL':x.id==='ACCESSIBLE_BASELINE'?'PROTECTIVE_CONDITION':'DOCUMENTED_CONCERN_WITH_LIMITS',evidenceType:x.evidenceType})));return freeze({disposition:d,caseId:blocked&&x.privateMarker?null:o.caseId,gates,journey,findings,nonClaims,asOf:AS_OF})}catch{return invalid()}}
export function buildExport(candidate:unknown){const result=observe(candidate);return freeze({build:'095',schemaVersion:'build-095.v1',canonical:{title:'Nervous-System-Aware Governance Observatory',publicTitle:'What Does Governance Do to a Human Body?',uses:['030','048','050','053','058','069','071'],creates:'cap:095'},artifacts:['NSAG Indicator Framework','Observatory Dataset'],syntheticOnly:true,externalEffects:false,result})}