export type ReportingPacketId='REPORT-CEDAR'|'REPORT-HARBOR'|'REPORT-LATTICE'|'REPORT-MESA'|'REPORT-ORBIT';
export type SourceKind='PUBLISHED-STORY'|'INTERVIEW-NOTE'|'FIELD-OBSERVATION'|'PUBLIC-RECORD'|'READER-QUESTION';
export type AssetKind='DATASET'|'TOOL'|'TRACKER'|'TIMELINE'|'PUBLIC-RESOURCE';
export type ReportingSource={id:string;kind:SourceKind;title:string;summary:string;observedOn:string;asOf:string;rightsStatus:'FICTIONAL-CLEARED';confidentiality:'PUBLIC-SYNTHETIC';verification:'SYNTHETIC-SOURCE-CHECKED'};
export type InfrastructureAsset={id:string;kind:AssetKind;label:string;purpose:string;sourceIds:readonly string[];fields:readonly string[];limitations:readonly string[];status:'CANDIDATE-NOT-PUBLISHED'};
export type Opportunity={id:string;assetId:string;need:string;intendedUsers:string;maintenanceRequirement:string;evidenceGap:string;priority:'UNASSESSED';decision:'HUMAN-REVIEW-REQUIRED'};
export type ReportingPacket={id:ReportingPacketId;label:string;storyQuestion:string;sources:readonly ReportingSource[];assets:readonly InfrastructureAsset[];opportunities:readonly Opportunity[];unknowns:readonly string[]};
export type InfrastructureInput={fixtureId:'SYNTHETIC-REPORTING-INFRASTRUCTURE-080';reportId:ReportingPacketId;packets:readonly ReportingPacket[];inherited:{contentProvenance:'cap:057';sourceProvenance:'cap:058';interviewGraph:'cap:062';researchRepository:'cap:063'};admission:{syntheticOnly:true;fixedSourcesOnly:true;realPeopleData:false;confidentialData:false;publishingAuthorized:false;rightsClearedForRealUse:false;factualClaim:false;legalAdvice:'NONE';clinicalAdvice:'NONE';priorityDecision:false}};
export type InfrastructureResult={status:`${ReportingPacketId} INFRASTRUCTURE PIPELINE`|'INVALID';packet:ReportingPacket|null;pipeline:{sourceIds:readonly string[];assetIds:readonly string[];opportunityIds:readonly string[];edges:readonly {from:string;to:string;relation:'SUPPORTS'|'ENTERS-QUEUE'}[]};alerts:readonly string[];audit:readonly string[];nonClaims:readonly string[];engineVersion:typeof REPORTING_INFRASTRUCTURE_ENGINE_VERSION};
export const REPORTING_INFRASTRUCTURE_ENGINE_VERSION='080.1.0' as const;
const source=(id:string,kind:SourceKind,title:string,summary:string,observedOn:string,asOf:string):ReportingSource=>Object.freeze({id,kind,title,summary,observedOn,asOf,rightsStatus:'FICTIONAL-CLEARED',confidentiality:'PUBLIC-SYNTHETIC',verification:'SYNTHETIC-SOURCE-CHECKED'});
const asset=(id:string,kind:AssetKind,label:string,purpose:string,sourceIds:readonly string[],fields:readonly string[],limitations:readonly string[]):InfrastructureAsset=>Object.freeze({id,kind,label,purpose,sourceIds:Object.freeze(sourceIds),fields:Object.freeze(fields),limitations:Object.freeze(limitations),status:'CANDIDATE-NOT-PUBLISHED'});
const opportunity=(id:string,assetId:string,need:string,intendedUsers:string,maintenanceRequirement:string,evidenceGap:string):Opportunity=>Object.freeze({id,assetId,need,intendedUsers,maintenanceRequirement,evidenceGap,priority:'UNASSESSED',decision:'HUMAN-REVIEW-REQUIRED'});
const makePacket=(id:ReportingPacketId,label:string,topic:string,prefix:string,date:string,unknowns:readonly string[]):ReportingPacket=>{
 const sources=Object.freeze([
  source(`SRC-${prefix}-STORY`,'PUBLISHED-STORY',`${label} synthetic story`,`Invented reporting summary about ${topic}.`,date,date),
  source(`SRC-${prefix}-INTERVIEW`,'INTERVIEW-NOTE',`${label} fictional interview note`,`Invented attributed themes; no real speaker or quotation.`,date,date),
  source(`SRC-${prefix}-FIELD`,'FIELD-OBSERVATION',`${label} synthetic field note`,`Invented place and workflow observation; no real location.`,date,date),
  source(`SRC-${prefix}-RECORD`,'PUBLIC-RECORD',`${label} fictional record`,`Invented tabular record with no legal or official status.`,date,date),
  source(`SRC-${prefix}-QUESTION`,'READER-QUESTION',`${label} synthetic reader question`,`Invented question asking how the reported system changes over time.`,date,date)
 ]);
 const ids=sources.map(x=>x.id); const assets=Object.freeze([
  asset(`AST-${prefix}-DATA`,'DATASET',`${label} structured source table`,'Represent the five fictional reporting sources as portable rows.',ids,['SOURCE ID','SOURCE KIND','TITLE','SUMMARY','OBSERVED ON','AS OF','RIGHTS','VERIFICATION'],['Fictional fixture only','Not exhaustive','No real-world verification']),
  asset(`AST-${prefix}-TOOL`,'TOOL',`${label} question explorer`,'Let a user inspect which synthetic source addresses each fixed question.',ids,['QUESTION','SOURCE ID','SUPPORTED ELEMENT','UNKNOWN'],['Fixed questions only','No inference','No recommendations']),
  asset(`AST-${prefix}-TRACKER`,'TRACKER',`${label} update tracker`,'Expose dated changes and unresolved gaps in the fictional packet.',ids,['SOURCE ID','AS OF','UPDATE STATE','GAP'],['No live feed','No automatic verification','Unknowns remain unknown']),
  asset(`AST-${prefix}-TIME`,'TIMELINE',`${label} reporting timeline`,'Order fictional observations and records without claiming causation.',ids,['SOURCE ID','OBSERVED ON','SOURCE KIND','EVENT SUMMARY'],['Dates are synthetic','Sequence is not causation','No completeness claim']),
  asset(`AST-${prefix}-GUIDE`,'PUBLIC-RESOURCE',`${label} source-reading guide`,'Explain how to inspect provenance, rights, limits, and update needs.',ids,['SOURCE ID','PROVENANCE','RIGHTS','LIMITATION','NEXT REVIEW'],['Demonstration only','Not professional advice','Not published by the engine'])
 ]);
 const opportunities=Object.freeze(assets.map((a,i)=>opportunity(`OPP-${prefix}-${i+1}`,a.id,`Test whether ${a.label.toLowerCase()} answers the fixed reader need.`,'FICTIONAL PUBLIC-INTEREST USERS','Named human owner, review cadence, correction path, and archive policy','No real user, demand, accuracy, impact, maintenance, or rights evidence')));
 return Object.freeze({id,label,storyQuestion:`What reusable infrastructure could responsibly emerge from reporting on ${topic}?`,sources,assets,opportunities,unknowns:Object.freeze(unknowns)});
};
export const REPORTING_PACKETS:readonly ReportingPacket[]=Object.freeze([
 makePacket('REPORT-CEDAR','Cedar access report','a fictional access pathway','CE','2046-01-12',['REAL USER NEED IS UNKNOWN','MAINTENANCE OWNER IS UNKNOWN']),
 makePacket('REPORT-HARBOR','Harbor handoff report','a fictional cross-organization handoff','HA','2046-01-26',['CORRECTION VOLUME IS UNKNOWN','LONG-TERM ARCHIVE COST IS UNKNOWN']),
 makePacket('REPORT-LATTICE','Lattice records report','a fictional fragmented records system','LA','2046-02-09',['REAL DATA AVAILABILITY IS UNKNOWN','INTEROPERABILITY NEED IS UNKNOWN']),
 makePacket('REPORT-MESA','Mesa implementation report','a fictional implementation gap','ME','2046-02-23',['REAL POLICY STATUS IS UNKNOWN','UPDATE CADENCE IS UNKNOWN']),
 makePacket('REPORT-ORBIT','Orbit reader-questions report','a fictional cluster of public questions','OR','2046-03-08',['REAL AUDIENCE DEMAND IS UNKNOWN','PUBLICATION RIGHTS ARE NOT ESTABLISHED FOR REAL USE'])
]);
const base={fixtureId:'SYNTHETIC-REPORTING-INFRASTRUCTURE-080',packets:REPORTING_PACKETS,inherited:{contentProvenance:'cap:057',sourceProvenance:'cap:058',interviewGraph:'cap:062',researchRepository:'cap:063'},admission:{syntheticOnly:true,fixedSourcesOnly:true,realPeopleData:false,confidentialData:false,publishingAuthorized:false,rightsClearedForRealUse:false,factualClaim:false,legalAdvice:'NONE',clinicalAdvice:'NONE',priorityDecision:false}} as const;
export const REPORTING_INFRASTRUCTURE_PRESETS:Readonly<Record<ReportingPacketId,InfrastructureInput>>=Object.freeze(Object.fromEntries(REPORTING_PACKETS.map(p=>[p.id,Object.freeze({...base,reportId:p.id})])) as Record<ReportingPacketId,InfrastructureInput>);
const invalid=():InfrastructureResult=>({status:'INVALID',packet:null,pipeline:{sourceIds:[],assetIds:[],opportunityIds:[],edges:[]},alerts:['INVALID OR UNADMITTED SYNTHETIC INPUT','NO INFRASTRUCTURE PIPELINE PRODUCED'],audit:[],nonClaims:['NO REAL REPORTING, PEOPLE, RECORDS, RIGHTS, PUBLICATION, FACTUAL, LEGAL, CLINICAL, DEMAND, IMPACT, OR PRIORITY CLAIM'],engineVersion:REPORTING_INFRASTRUCTURE_ENGINE_VERSION});
function evaluate(candidate:unknown):InfrastructureResult{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const object=candidate as Record<string,unknown>;const preset=REPORTING_INFRASTRUCTURE_PRESETS[object.reportId as ReportingPacketId];if(!preset||JSON.stringify(object)!==JSON.stringify(preset))return invalid();const packet=preset.packets.find(p=>p.id===preset.reportId)!;const edges=[...packet.assets.flatMap(a=>a.sourceIds.map(s=>({from:s,to:a.id,relation:'SUPPORTS' as const}))),...packet.opportunities.map(o=>({from:o.assetId,to:o.id,relation:'ENTERS-QUEUE' as const}))];return{status:`${packet.id} INFRASTRUCTURE PIPELINE`,packet,pipeline:{sourceIds:packet.sources.map(s=>s.id),assetIds:packet.assets.map(a=>a.id),opportunityIds:packet.opportunities.map(o=>o.id),edges},alerts:['SYNTHETIC REPORTING-TO-INFRASTRUCTURE DEMONSTRATION ONLY','CANDIDATES REQUIRE HUMAN RIGHTS, EVIDENCE, DEMAND, MAINTENANCE, AND PUBLICATION REVIEW'],audit:['VALIDATED EXACT FROZEN FIXTURE','PRESERVED SOURCE KIND, TITLE, SUMMARY, DATES, RIGHTS, CONFIDENTIALITY, VERIFICATION, AND SOURCE LINKS','PRESERVED ASSET LIMITATIONS, OPPORTUNITY GAPS, UNKNOWNS, AND HUMAN REVIEW','NO PUBLICATION, PRIORITIZATION, CLAIM VERIFICATION, OR REAL-WORLD INFERENCE'],nonClaims:['NO REAL PEOPLE, INTERVIEWS, FIELDWORK, RECORDS, READERS, OR CONFIDENTIAL MATERIAL','NO RIGHTS CLEARANCE OR PUBLICATION AUTHORIZATION FOR REAL USE','NO FACTUAL, LEGAL, CLINICAL, DEMAND, IMPACT, OR PRIORITY DETERMINATION'],engineVersion:REPORTING_INFRASTRUCTURE_ENGINE_VERSION}}
export function extractReportingInfrastructure(candidate:unknown):InfrastructureResult{try{return evaluate(candidate)}catch{return invalid()}}
