export type CaseId='STRAIGHT_THROUGH'|'TOOL_TIMEOUT'|'RETRIES_EXHAUSTED'|'APPROVAL_PENDING'|'APPROVAL_DENIED'|'AUTH_DENIED'|'STALE_APPROVAL'|'MALFORMED_EVENT'|'MEMORY_BLOCK'|'EVIDENCE_BLOCK'|'DUPLICATE_EVENT';
export type Command='RUN'|'APPROVE'|'REJECT'|'RETRY'|'ESCALATE';
export type Disposition='INVALID_RECORD'|'COMPLETED'|'RETRY_AVAILABLE'|'ESCALATED'|'APPROVAL_PENDING'|'APPROVAL_DENIED'|'AUTHORIZATION_BLOCKED'|'STALE_APPROVAL_BLOCKED'|'EVENT_REJECTED'|'MEMORY_POLICY_BLOCKED'|'EVIDENCE_BLOCKED'|'DUPLICATE_IGNORED';
export type NodeState='PASS'|'BLOCK'|'PENDING'|'RETRIED'|'ESCALATED'|'NOT_RUN';
export type Node={id:string;kind:'EVENT'|'PERSON'|'AGENT'|'TOOL'|'APPROVAL'|'EVIDENCE'|'TERMINAL';owner:string;dependsOn:readonly string[]};
export type Fixture={id:CaseId;label:string;workflowId:string;eventId:string;payloadDigest:string;approverRole:string;approvalExpiresOn:string;policyVersion:'orchestration-policy.v1';nodes:readonly Node[]};
export type Input={fixtureId:'SYNTHETIC-ORCHESTRATION-092';caseId:CaseId;command:Command;fixtures:readonly Fixture[];admission:{syntheticOnly:true;externalEffects:false;liveAgents:false;realPeople:false}};
export type Result={disposition:Disposition;caseId:CaseId|null;command:Command|null;trace:readonly {sequence:number;nodeId:string;state:NodeState;attempt:number;reasonCode:string;externalEffect:false}[];approvalReceipt:Readonly<Record<string,unknown>>|null;availableCommands:readonly Command[];nonClaims:readonly string[];asOf:typeof AS_OF};
export const AS_OF='2026-08-22T12:00:00.000Z' as const;
const freeze=<T>(v:T):T=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v as Record<string,unknown>))freeze(x)}return v};
const nodes=freeze([{id:'N-EVENT',kind:'EVENT',owner:'Event intake',dependsOn:[]},{id:'N-AGENT',kind:'AGENT',owner:'Preparation agent',dependsOn:['N-EVENT']},{id:'N-MEMORY',kind:'EVIDENCE',owner:'Memory policy',dependsOn:['N-AGENT']},{id:'N-EVIDENCE',kind:'EVIDENCE',owner:'Verification gate',dependsOn:['N-MEMORY']},{id:'N-TOOL',kind:'TOOL',owner:'Tool registry',dependsOn:['N-EVIDENCE']},{id:'N-APPROVAL',kind:'APPROVAL',owner:'Qualified workflow approver',dependsOn:['N-TOOL']},{id:'N-DONE',kind:'TERMINAL',owner:'Orchestration runtime',dependsOn:['N-APPROVAL']}] as const);
const ids=['STRAIGHT_THROUGH','TOOL_TIMEOUT','RETRIES_EXHAUSTED','APPROVAL_PENDING','APPROVAL_DENIED','AUTH_DENIED','STALE_APPROVAL','MALFORMED_EVENT','MEMORY_BLOCK','EVIDENCE_BLOCK','DUPLICATE_EVENT']as const;
export const FIXTURES=freeze(ids.map((id,i)=>({id,label:id.replaceAll('_',' '),workflowId:'WF-092-'+String(i+1).padStart(2,'0'),eventId:'EV-'+String(i+1).padStart(2,'0'),payloadDigest:'sha256:synthetic-'+String(i+1).padStart(2,'0'),approverRole:'Qualified workflow approver',approvalExpiresOn:id==='STALE_APPROVAL'?'2026-08-20':'2026-12-31',policyVersion:'orchestration-policy.v1',nodes})) as readonly Fixture[]);
const base=freeze({fixtureId:'SYNTHETIC-ORCHESTRATION-092',fixtures:FIXTURES,admission:{syntheticOnly:true,externalEffects:false,liveAgents:false,realPeople:false}}as const);
export const PRESETS=freeze(Object.fromEntries(ids.map(caseId=>[caseId,freeze({...base,caseId,command:'RUN'})]))as unknown as Record<CaseId,Input>);
const nonClaims=freeze(['FICTIONAL LOCAL REHEARSAL ONLY','A DISPLAYED APPROVAL IS SIMULATED','A RETRY DOES NOT PROVE DELIVERY','COMPLETION MEANS ONLY THAT THE FROZEN MODEL REACHED ITS TERMINAL STATE','NO REAL PEOPLE, AGENTS, TOOLS, APPROVALS, MESSAGES, ACCOUNTS, CREDENTIALS, QUEUES, PUBLISHING, OR EXTERNAL EFFECTS']);
const invalid=():Result=>freeze({disposition:'INVALID_RECORD',caseId:null,command:null,trace:[],approvalReceipt:null,availableCommands:[],nonClaims,asOf:AS_OF});
const allowed:Command[]=['RUN','APPROVE','REJECT','RETRY','ESCALATE'];
export function orchestrate(candidate:unknown):Result{try{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const o=candidate as Input,p=PRESETS[o.caseId];if(!p||!allowed.includes(o.command)||JSON.stringify(o)!==JSON.stringify({...p,command:o.command}))return invalid();let d:Disposition='COMPLETED',stop=7,reason='WORKFLOW_COMPLETE',attempt=1,commands:Command[]=[];if(o.caseId==='MALFORMED_EVENT')d='EVENT_REJECTED',stop=0,reason='UNKNOWN_EVENT_SCHEMA';else if(o.caseId==='MEMORY_BLOCK')d='MEMORY_POLICY_BLOCKED',stop=2,reason='CAP_091_DENIED';else if(o.caseId==='AUTH_DENIED')d='AUTHORIZATION_BLOCKED',stop=4,reason='TOOL_CAPABILITY_DENIED';else if(o.caseId==='EVIDENCE_BLOCK')d='EVIDENCE_BLOCKED',stop=3,reason='CAP_090_VERIFICATION_FAILED';else if(o.caseId==='STALE_APPROVAL')d='STALE_APPROVAL_BLOCKED',stop=5,reason='APPROVAL_BINDING_EXPIRED';else if(o.caseId==='APPROVAL_PENDING'){d=o.command==='APPROVE'?'COMPLETED':o.command==='REJECT'?'APPROVAL_DENIED':'APPROVAL_PENDING';stop=d==='COMPLETED'?7:5;reason=d==='COMPLETED'?'SIMULATED_APPROVAL_BOUND':'EXPLICIT_APPROVAL_REQUIRED';commands=d==='APPROVAL_PENDING'?['APPROVE','REJECT']:[]}else if(o.caseId==='APPROVAL_DENIED')d='APPROVAL_DENIED',stop=5,reason='SIMULATED_APPROVAL_REJECTED';else if(o.caseId==='TOOL_TIMEOUT'){d=o.command==='RETRY'?'COMPLETED':'RETRY_AVAILABLE';stop=d==='COMPLETED'?7:4;reason=d==='COMPLETED'?'BOUNDED_RETRY_SUCCEEDED':'SYNTHETIC_TIMEOUT';attempt=d==='COMPLETED'?2:1;commands=d==='RETRY_AVAILABLE'?['RETRY']:[]}else if(o.caseId==='RETRIES_EXHAUSTED'){d=o.command==='ESCALATE'?'ESCALATED':'ESCALATED';stop=4;reason='RETRY_BUDGET_EXHAUSTED';attempt=3;commands=[]}else if(o.caseId==='DUPLICATE_EVENT')d='DUPLICATE_IGNORED',stop=0,reason='IDEMPOTENCY_KEY_SEEN';const f=p.fixtures.find(x=>x.id===o.caseId)!;const trace=freeze(f.nodes.map((n,i)=>({sequence:i+1,nodeId:n.id,state:(i>stop?'NOT_RUN':i===stop&&d!=='COMPLETED'?(d==='APPROVAL_PENDING'?'PENDING':d==='ESCALATED'?'ESCALATED':d==='RETRY_AVAILABLE'?'RETRIED':'BLOCK'):'PASS')as NodeState,attempt:i===4?attempt:1,reasonCode:i===stop?reason:'DEPENDENCY_SATISFIED',externalEffect:false})));const approvalReceipt=(o.caseId==='APPROVAL_PENDING'&&o.command==='APPROVE')?freeze({workflowId:f.workflowId,nodeId:'N-APPROVAL',payloadDigest:f.payloadDigest,approverRole:f.approverRole,policyVersion:f.policyVersion,expiresOn:f.approvalExpiresOn,simulated:true,externalEffect:false}):null;return freeze({disposition:d,caseId:o.caseId,command:o.command,trace,approvalReceipt,availableCommands:freeze(commands),nonClaims,asOf:AS_OF})}catch{return invalid()}}
export function buildExport(candidate:unknown){const r=orchestrate(candidate);return freeze({build:'092',schemaVersion:'build-092.v1',policyVersion:'orchestration-policy.v1',canonical:{title:'AI Orchestration Layer for Businesses',publicTitle:'Make the Work Move Across People, AI and Software',uses:['019','020','040','042','043','068','090','091'],creates:'cap:092'},artifacts:['Orchestration Runtime','Tool Registry','Human Approval Bus'],syntheticOnly:true,externalEffects:false,result:r})}