export type TelemetryEventId='pageView'|'featureUsed'|'taskCompleted'|'errorCode'|'searchTerms'|'preciseLocation'|'fullIp'|'sessionReplay'|'freeText';
export type DecisionId='navigationRepair'|'featurePriority'|'taskSuccess'|'reliabilityRepair';
export type TelemetryEvent={id:TelemetryEventId;insight:number;privacy:number;identifiability:number;purposes:DecisionId[];retentionDays:number;aggregation:'row'|'daily-count';linkableKeys:number;sensitiveInference:boolean;requires:TelemetryEventId[];optionalMeasurement:boolean};
export type EvidenceRef={id:string;title:string;url:string;checkedAt:string;scope:'guidance'|'procedure'|'decision-record'};
export type PrivacyBehaviorInput={events:TelemetryEvent[];enabled:TelemetryEventId[];requiredDecisions:DecisionId[];purposeRegistry:Record<DecisionId,string>;consentChoiceAvailable:boolean;legalBasisDocumented:boolean;deletionProcedureTested:boolean;changeTraceId:string;evidence:EvidenceRef[];assessedAt:string};
export type Finding={id:string;kind:'control'|'dependency'|'purpose'|'retention'|'linkability'|'inference'|'evidence';message:string;events:TelemetryEventId[]};
export type PrivacyBehaviorAssessment={status:'CONTROL BLOCKED'|'PLAN GAPS'|'DECLARED MINIMUM SET';insightCoverage:number;privacyLoad:number;identifiability:number;findings:Finding[];enabled:TelemetryEventId[];minimumSet:TelemetryEventId[];engineVersion:string;limitations:string[]};
export const PRIVACY_BEHAVIOR_ENGINE_VERSION='031.2.0';
export const EVENT_ORDER:TelemetryEventId[]=['pageView','featureUsed','taskCompleted','errorCode','searchTerms','preciseLocation','fullIp','sessionReplay','freeText'];
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));const validDate=(x:string)=>/^\d{4}-\d{2}-\d{2}$/.test(x)&&!Number.isNaN(Date.parse(`${x}T00:00:00Z`));
export function deriveMinimumSet(events:TelemetryEvent[],required:DecisionId[]){const remaining=new Set(required),selected:TelemetryEventId[]=[];for(const event of EVENT_ORDER.map(id=>events.find(e=>e.id===id)).filter((x):x is TelemetryEvent=>Boolean(x))){if(event.purposes.some(p=>remaining.has(p))){selected.push(event.id);event.purposes.forEach(p=>remaining.delete(p))}}return{events:selected,uncovered:[...remaining]}}
export function assessPrivacyBehavior(input:PrivacyBehaviorInput):PrivacyBehaviorAssessment{
 const findings:Finding[]=[];const enabled=EVENT_ORDER.filter(id=>input.enabled.includes(id));const selected=enabled.map(id=>input.events.find(e=>e.id===id)).filter((x):x is TelemetryEvent=>Boolean(x));const minimum=deriveMinimumSet(input.events,input.requiredDecisions);
 if(!input.legalBasisDocumented)findings.push({id:'control:legal-basis',kind:'control',message:'Document and review an applicable legal basis separately from consent; this engine cannot choose one.',events:[]});
 if(selected.some(e=>e.optionalMeasurement)&&!input.consentChoiceAvailable)findings.push({id:'control:consent-choice',kind:'control',message:'Optional measurement needs a usable choice where consent is the asserted basis; consent does not replace purpose or legal-basis review.',events:selected.filter(e=>e.optionalMeasurement).map(e=>e.id)});
 if(!input.deletionProcedureTested)findings.push({id:'control:deletion',kind:'control',message:'Record a tested deletion/expiry procedure; a retention number does not prove deletion occurred.',events:enabled});
 if(!input.changeTraceId.trim())findings.push({id:'control:trace',kind:'control',message:'Link plan changes to an evidence-bearing Build 029 trace.',events:[]});
 if(!validDate(input.assessedAt))findings.push({id:'control:date',kind:'control',message:'Provide a valid assessment date for deterministic replay.',events:[]});
 const evidenceIds=new Set<string>();for(const e of [...input.evidence].sort((a,b)=>a.id.localeCompare(b.id))){const age=Date.parse(`${input.assessedAt}T00:00:00Z`)-Date.parse(`${e.checkedAt}T00:00:00Z`);if(evidenceIds.has(e.id)||!e.id||!e.title||!/^https:\/\//.test(e.url)||!validDate(e.checkedAt)||age<0||age>366*86400000)findings.push({id:`evidence:${e.id||'invalid'}`,kind:'evidence',message:'Evidence needs a unique ID, title, HTTPS provenance, scope, and review date within 366 days.',events:[]});evidenceIds.add(e.id)}if(!input.evidence.length)findings.push({id:'evidence:missing',kind:'evidence',message:'No inspectable evidence was supplied.',events:[]});
 for(const decision of input.requiredDecisions)if(!input.purposeRegistry[decision]?.trim())findings.push({id:`purpose:${decision}`,kind:'purpose',message:`Name the product decision for ${decision}; an event label is not a purpose.`,events:[]});
 for(const event of selected){for(const dep of event.requires)if(!enabled.includes(dep))findings.push({id:`dependency:${event.id}:${dep}`,kind:'dependency',message:`${event.id} requires ${dep} for the declared interpretation; remove it or enable the dependency.`,events:[event.id,dep]});if(!event.purposes.some(p=>input.requiredDecisions.includes(p)))findings.push({id:`purpose:${event.id}`,kind:'purpose',message:`${event.id} does not support a required named decision.`,events:[event.id]});if(event.retentionDays>30)findings.push({id:`retention:${event.id}`,kind:'retention',message:`${event.id} declares ${event.retentionDays} days; justify or reduce beyond the derived 30-day review threshold.`,events:[event.id]});if(event.linkableKeys>0)findings.push({id:`linkability:${event.id}`,kind:'linkability',message:`${event.id} remains linkable through ${event.linkableKeys} key(s); aggregation alone is not anonymity.`,events:[event.id]});if(event.sensitiveInference)findings.push({id:`inference:${event.id}`,kind:'inference',message:`${event.id} may support sensitive or unexpected inference; remove it or require specialist review and controls.`,events:[event.id]})}
 const highRisk=selected.filter(e=>e.identifiability>=70||e.privacy>=80);if(highRisk.length>=2)findings.push({id:'linkability:combination',kind:'linkability',message:'The selected high-risk combination can increase singling-out and inference beyond per-event scores.',events:highRisk.map(e=>e.id)});
 const covered=new Set(selected.flatMap(e=>e.purposes));const insightCoverage=clamp(100*input.requiredDecisions.filter(d=>covered.has(d)).length/(input.requiredDecisions.length||1));const privacyLoad=selected.length?clamp(Math.max(...selected.map(e=>e.privacy))*.7+selected.reduce((s,e)=>s+e.privacy,0)/selected.length*.3):0;const identifiability=selected.length?clamp(Math.max(...selected.map(e=>e.identifiability))+(selected.reduce((s,e)=>s+e.linkableKeys,0)>1?10:0)):0;
 const controls=findings.some(f=>f.kind==='control'||f.kind==='evidence');const exactMinimum=enabled.join('|')===minimum.events.join('|')&&!minimum.uncovered.length;
 return{status:controls?'CONTROL BLOCKED':findings.length||!exactMinimum?'PLAN GAPS':'DECLARED MINIMUM SET',insightCoverage,privacyLoad,identifiability,findings,enabled,minimumSet:minimum.events,engineVersion:PRIVACY_BEHAVIOR_ENGINE_VERSION,limitations:['Scores are derived ordinal planning signals, not measured privacy, identifiability, benefit, legal risk, or actual user behavior.','Purpose, consent, and legal basis are distinct; this tool does not determine whether any basis or consent is valid.','Retention and deletion fields describe a plan, not proof that production systems aggregate, expire, delete, or honor rights.','Aggregation does not guarantee anonymity; linkage, rare combinations, free text, location, identifiers, and sensitive inference require contextual review.']};
}
