export type EvidenceRecordId='RECORD-CEDAR'|'RECORD-HARBOR'|'RECORD-LATTICE'|'RECORD-MESA'|'RECORD-ORBIT';
export type NavigationQuestionId='Q-PREPARATION-OUTCOME'|'Q-CONTEXT-SUPPORT'|'Q-IMPLEMENTATION-EVIDENCE';
export type Applicability='DIRECT-FOR-SYNTHETIC-QUESTION'|'PARTIAL-FOR-SYNTHETIC-QUESTION'|'OUTSIDE-SYNTHETIC-QUESTION';
export type EvidenceRecord={id:EvidenceRecordId;title:string;sourceType:string;qualityBasis:string;claim:string;population:string;context:string;outcome:string;limitations:readonly string[];uncertainty:string;asOf:string;sourceLocator:string;syntheticStatus:'SYNTHETIC-SOURCE-CHECKED'};
export type NavigationQuestion={id:NavigationQuestionId;label:string;question:string;population:string;context:string;outcome:string;evidenceTypes:readonly string[]};
export type NavigationInput={fixtureId:'SYNTHETIC-PSYCHEDELIC-EVIDENCE-079';questionId:NavigationQuestionId;records:readonly EvidenceRecord[];questions:readonly NavigationQuestion[];inherited:{retrieval:'cap:028';provenance:'cap:058';researchRepository:'cap:063'};admission:{syntheticOnly:true;fixedQuestionsOnly:true;fixedSourcesOnly:true;realPeopleData:false;realClinicalEvidence:false;legalAdvice:'NONE';clinicalAdvice:'NONE';diagnosisTreatmentDosageClaim:false;safetyEffectivenessClaim:false;applicabilityDecision:false}};
export type EvidenceMapRow={record:EvidenceRecord;applicability:Applicability;applicabilityReason:string;matchedParameters:readonly string[];unmatchedParameters:readonly string[];unknowns:readonly string[]};
export type NavigationResult={status:`${NavigationQuestionId} EVIDENCE MAP`|'INVALID';question:NavigationQuestion|null;rows:readonly EvidenceMapRow[];facets:readonly string[];alerts:readonly string[];audit:readonly string[];nonClaims:readonly string[];engineVersion:typeof EVIDENCE_NAVIGATION_ENGINE_VERSION};
export const EVIDENCE_NAVIGATION_ENGINE_VERSION='079.1.0' as const;
const rec=(id:EvidenceRecordId,title:string,sourceType:string,qualityBasis:string,claim:string,population:string,context:string,outcome:string,limitations:readonly string[],uncertainty:string,asOf:string,sourceLocator:string):EvidenceRecord=>Object.freeze({id,title,sourceType,qualityBasis,claim,population,context,outcome,limitations:Object.freeze(limitations),uncertainty,asOf,sourceLocator,syntheticStatus:'SYNTHETIC-SOURCE-CHECKED'});
export const EVIDENCE_NAVIGATION_RECORDS:readonly EvidenceRecord[]=Object.freeze([
 rec('RECORD-CEDAR','Cedar Preparation Fixture','SYNTHETIC CONTROLLED STUDY','RANDOMIZED FIXTURE; SMALL SAMPLE; INVENTED MEASURE','The two fictional preparation conditions contain different day-14 experience-score fields.','FICTIONAL ADULT RECORDS','STRUCTURED PREPARATION SESSION','DAY-14 EXPERIENCE SCORE',['Small fixture','Short follow-up','Invented self-report measure','No replication'],'Direction is fixed only in the fixture; magnitude, causation, safety, and real-world applicability are unknown.','2045-01-11','SYN-079-CE-01 §4'),
 rec('RECORD-HARBOR','Harbor Context Archive','SYNTHETIC QUALITATIVE ARCHIVE','SIX INVENTED INTERVIEWS; THEMATIC FIXTURE; NO REAL PEOPLE','Fictional accounts describe different support needs across two invented settings.','SIX FICTIONAL ADULT ACCOUNTS','COMMUNITY SUPPORT SETTINGS','DESCRIBED SUPPORT NEEDS',['Tiny purposive fixture','No comparison group','Invented narratives','No clinical verification'],'Themes are preserved; prevalence, typicality, causation, and clinical meaning are unknown.','2045-01-22','SYN-079-HA-01 lines 18–34'),
 rec('RECORD-LATTICE','Lattice Follow-Up Table','SYNTHETIC OBSERVATIONAL DATASET','UNCONTROLLED FIXTURE; MISSING FOLLOW-UP; NO REAL PARTICIPANTS','Recorded follow-up differs across fictional context categories.','82 FICTIONAL RECORDS; 57 FOLLOW-UPS','VARIED SUPPORT CONTEXTS','FOLLOW-UP COMPLETION FIELD',['No random assignment','Missing follow-up','Unmeasured confounding','Invented categories'],'Association is visible in the fixture; causation and generalizability are unknown.','2045-02-03','SYN-079-LA-01 table 2'),
 rec('RECORD-MESA','Mesa Implementation Notes','SYNTHETIC IMPLEMENTATION CASE SERIES','THREE FICTIONAL SITES; DESCRIPTIVE OPERATIONS RECORD','Three invented sites record different onboarding and referral states.','THREE FICTIONAL SERVICE SITES','IMPLEMENTATION WORKFLOW','ONBOARDING AND REFERRAL STATES',['No clinical outcomes','No common baseline','Three invented sites','No effectiveness measure'],'Operational differences are fixed; feasibility, quality, access, safety, and outcomes are unknown.','2045-02-17','SYN-079-ME-01 cases A–C'),
 rec('RECORD-ORBIT','Orbit Review Scaffold','SYNTHETIC EVIDENCE SYNTHESIS','METHOD DEMONSTRATION; FIVE INVENTED INPUTS; NO META-ANALYSIS','The scaffold groups five fictional sources by question and limitation.','NOT APPLICABLE — SYNTHESIS FIXTURE','MULTIPLE FICTIONAL CONTEXTS','EVIDENCE-GAP CATEGORIES',['Invented inputs','No quantitative pooling','No validated review protocol','No real corpus search'],'The grouping is deterministic; completeness, source quality, and substantive conclusions are unknown.','2045-03-01','SYN-079-OR-01 appendix A')
]);
export const EVIDENCE_NAVIGATION_QUESTIONS:readonly NavigationQuestion[]=Object.freeze([
 {id:'Q-PREPARATION-OUTCOME',label:'Preparation and day-14 outcome',question:'What synthetic evidence addresses preparation context and a day-14 experience outcome?',population:'FICTIONAL ADULT RECORDS',context:'STRUCTURED PREPARATION SESSION',outcome:'DAY-14 EXPERIENCE SCORE',evidenceTypes:Object.freeze(['SYNTHETIC CONTROLLED STUDY','SYNTHETIC OBSERVATIONAL DATASET'])},
 {id:'Q-CONTEXT-SUPPORT',label:'Context and support needs',question:'What synthetic evidence describes support needs across contexts?',population:'FICTIONAL ADULT ACCOUNTS OR RECORDS',context:'SUPPORT CONTEXTS',outcome:'DESCRIBED OR RECORDED SUPPORT NEEDS',evidenceTypes:Object.freeze(['SYNTHETIC QUALITATIVE ARCHIVE','SYNTHETIC OBSERVATIONAL DATASET'])},
 {id:'Q-IMPLEMENTATION-EVIDENCE',label:'Implementation evidence',question:'What synthetic evidence addresses implementation workflow states?',population:'FICTIONAL SERVICE SITES',context:'IMPLEMENTATION WORKFLOW',outcome:'ONBOARDING AND REFERRAL STATES',evidenceTypes:Object.freeze(['SYNTHETIC IMPLEMENTATION CASE SERIES'])}
]);
const base={fixtureId:'SYNTHETIC-PSYCHEDELIC-EVIDENCE-079',records:EVIDENCE_NAVIGATION_RECORDS,questions:EVIDENCE_NAVIGATION_QUESTIONS,inherited:{retrieval:'cap:028',provenance:'cap:058',researchRepository:'cap:063'},admission:{syntheticOnly:true,fixedQuestionsOnly:true,fixedSourcesOnly:true,realPeopleData:false,realClinicalEvidence:false,legalAdvice:'NONE',clinicalAdvice:'NONE',diagnosisTreatmentDosageClaim:false,safetyEffectivenessClaim:false,applicabilityDecision:false}} as const;
export const EVIDENCE_NAVIGATION_PRESETS:Readonly<Record<NavigationQuestionId,NavigationInput>>=Object.freeze(Object.fromEntries(EVIDENCE_NAVIGATION_QUESTIONS.map(q=>[q.id,Object.freeze({...base,questionId:q.id})])) as Record<NavigationQuestionId,NavigationInput>);
const qualification:Record<NavigationQuestionId,Record<EvidenceRecordId,[Applicability,string,string[],string[],string[]]>>={
 'Q-PREPARATION-OUTCOME':{
  'RECORD-CEDAR':['DIRECT-FOR-SYNTHETIC-QUESTION','Population, context, outcome, and admitted evidence type match the fixed question.',['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],[],['REAL-WORLD APPLICABILITY']],
  'RECORD-HARBOR':['OUTSIDE-SYNTHETIC-QUESTION','Narrative support contexts do not supply the requested preparation comparison or day-14 outcome.',['POPULATION'],['CONTEXT','OUTCOME','EVIDENCE TYPE'],['COMPARABLE DAY-14 MEASURE']],
  'RECORD-LATTICE':['PARTIAL-FOR-SYNTHETIC-QUESTION','Observational records share an admitted type but not the preparation context or requested outcome.',['POPULATION','EVIDENCE TYPE'],['CONTEXT','OUTCOME'],['CAUSAL RELATIONSHIP']],
  'RECORD-MESA':['OUTSIDE-SYNTHETIC-QUESTION','Implementation sites do not address the specified population, context, or outcome.',[],['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],['CLINICAL OUTCOME']],
  'RECORD-ORBIT':['PARTIAL-FOR-SYNTHETIC-QUESTION','The synthesis scaffold may expose gaps but contains no matching underlying real evidence.',['QUESTION GROUPING'],['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],['CORPUS COMPLETENESS']]},
 'Q-CONTEXT-SUPPORT':{
  'RECORD-CEDAR':['PARTIAL-FOR-SYNTHETIC-QUESTION','Preparation is a context, but the fixture does not describe support needs.',['POPULATION','CONTEXT'],['OUTCOME','EVIDENCE TYPE'],['SUPPORT-NEED MEASURE']],
  'RECORD-HARBOR':['DIRECT-FOR-SYNTHETIC-QUESTION','Fictional accounts, support settings, themes, and admitted qualitative type match.',['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],[],['PREVALENCE','TYPICALITY']],
  'RECORD-LATTICE':['PARTIAL-FOR-SYNTHETIC-QUESTION','Support contexts and records match partially; outcome is follow-up completion rather than stated need.',['POPULATION','CONTEXT','EVIDENCE TYPE'],['OUTCOME'],['REASON FOR MISSING FOLLOW-UP']],
  'RECORD-MESA':['OUTSIDE-SYNTHETIC-QUESTION','Service workflow states do not describe individual support needs.',['CONTEXT'],['POPULATION','OUTCOME','EVIDENCE TYPE'],['INDIVIDUAL EXPERIENCE']],
  'RECORD-ORBIT':['PARTIAL-FOR-SYNTHETIC-QUESTION','The scaffold can group limitations but supplies no matching evidence itself.',['QUESTION GROUPING'],['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],['CORPUS COMPLETENESS']]},
 'Q-IMPLEMENTATION-EVIDENCE':{
  'RECORD-CEDAR':['OUTSIDE-SYNTHETIC-QUESTION','A controlled-study fixture does not address implementation workflow.',['NONE'],['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],['IMPLEMENTATION STATE']],
  'RECORD-HARBOR':['OUTSIDE-SYNTHETIC-QUESTION','Narrative settings do not supply site workflow states.',['NONE'],['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],['SITE WORKFLOW']],
  'RECORD-LATTICE':['OUTSIDE-SYNTHETIC-QUESTION','Follow-up records do not address service-site implementation states.',['NONE'],['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],['IMPLEMENTATION STATE']],
  'RECORD-MESA':['DIRECT-FOR-SYNTHETIC-QUESTION','Fictional sites, implementation context, workflow states, and evidence type match.',['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],[],['FEASIBILITY','QUALITY','OUTCOMES']],
  'RECORD-ORBIT':['PARTIAL-FOR-SYNTHETIC-QUESTION','The scaffold can display implementation gaps but supplies no matching evidence itself.',['QUESTION GROUPING'],['POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE'],['CORPUS COMPLETENESS']]}
};
const invalid=():NavigationResult=>({status:'INVALID',question:null,rows:[],facets:[],alerts:['INVALID OR UNADMITTED SYNTHETIC INPUT','NO EVIDENCE MAP PRODUCED'],audit:[],nonClaims:['NO REAL CLINICAL, PATIENT, DIAGNOSIS, TREATMENT, DOSAGE, SAFETY, EFFECTIVENESS, LEGAL, OR APPLICABILITY CLAIM'],engineVersion:EVIDENCE_NAVIGATION_ENGINE_VERSION});
function evaluate(candidate:unknown):NavigationResult{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const object=candidate as Record<string,unknown>;const preset=EVIDENCE_NAVIGATION_PRESETS[object.questionId as NavigationQuestionId];if(!preset||JSON.stringify(object)!==JSON.stringify(preset))return invalid();const question=preset.questions.find(q=>q.id===preset.questionId)!;const rows=preset.records.map(record=>{const q=qualification[preset.questionId][record.id];return{record,applicability:q[0],applicabilityReason:q[1],matchedParameters:Object.freeze(q[2]),unmatchedParameters:Object.freeze(q[3]),unknowns:Object.freeze(q[4])}});return{status:`${question.id} EVIDENCE MAP`,question,rows,facets:['QUESTION','POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE','QUALITY BASIS','APPLICABILITY','LIMITATIONS','UNCERTAINTY','AS-OF DATE'],alerts:['SYNTHETIC EVIDENCE NAVIGATION ONLY','APPLICABILITY LABELS DESCRIBE FIXTURE MATCHING, NOT REAL-WORLD SUITABILITY'],audit:['VALIDATED EXACT FROZEN FIXTURE','PRESERVED FIVE-RECORD SOURCE ORDER','PRESERVED SOURCE TYPE, QUALITY BASIS, CLAIM, POPULATION, CONTEXT, OUTCOME, LIMITATIONS, UNCERTAINTY, AS-OF DATE, AND LOCATOR','PRESERVED OUT-OF-SCOPE RESULTS AND UNKNOWNS','NO NUMERIC SCORING, RANKING, IMPUTATION, OR REAL-WORLD APPLICABILITY DECISION'],nonClaims:['NO REAL PEOPLE, PATIENT, CLINICAL, PRODUCT, OR LEGAL EVIDENCE','NO MEDICAL OR LEGAL ADVICE','NO DIAGNOSIS, TREATMENT, DOSAGE, SAFETY, EFFECTIVENESS, OR OUTCOME CLAIM'],engineVersion:EVIDENCE_NAVIGATION_ENGINE_VERSION}}
export function navigatePsychedelicEvidence(candidate:unknown):NavigationResult{try{return evaluate(candidate)}catch{return invalid()}}
