export type ScenarioId='READY_PATH'|'PROMISE_DUE'|'PERMISSION_LIMITED'|'PRIVATE_CONTEXT'|'PROOF_MISMATCH';
export type Disposition='INVALID_RECORD'|'HOLD_PRIVATE_CONTEXT'|'CLOSE_OPEN_LOOP'|'REQUEST_PERMISSION'|'FIND_RELEVANT_PROOF'|'NEEDS_HUMAN_REVIEW'|'NURTURE_RELATIONSHIP'|'PREPARE_SCOPING_CALL'|'DRAFT_PROPOSAL_SIMULATION';
export type Gate='PRIVACY'|'OPEN_LOOP'|'PERMISSION'|'PROOF'|'HUMAN_REVIEW';
export type RelationshipRecord={id:ScenarioId;personId:string;personName:string;organization:string;context:string;consent:'CONTACT_OK'|'LIMITED'|'DO_NOT_CONTACT';sensitivity:'STANDARD'|'PRIVATE';valueGiven:string;valueReceived:string;lastVerified:'2026-08-21';commitment:string|null;commitmentDue:string|null;commitmentComplete:boolean;opportunity:string;stage:'OBSERVED'|'QUALIFYING'|'INVITED';permissionScope:string;proposedAction:string;proofBuild:string|null;proofCapability:string|null;requiredCapability:string;proofPublic:boolean;conflict:boolean;communicationSummary:string};
export type Input={fixtureId:'SYNTHETIC-RELATIONSHIP-NETWORK-088';scenarioId:ScenarioId;simulateDraft:boolean;records:readonly RelationshipRecord[];admission:{syntheticOnly:true;liveMessaging:false;liveCRM:false;proposalSending:false;peopleScoring:false}};
export type Result={status:string;record:RelationshipRecord|null;disposition:Disposition;blockingGates:readonly Gate[];nextAction:string;rationale:string;path:readonly string[];reciprocity:readonly string[];overdueCommitments:readonly string[];proposalPreview:string|null;nonClaims:readonly string[];version:typeof VERSION};
export const VERSION='088.1.0' as const;
const freeze=<T>(v:T):T=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v as Record<string,unknown>))freeze(x)}return v};
const make=(id:ScenarioId,personName:string,organization:string,context:string,consent:RelationshipRecord['consent'],sensitivity:RelationshipRecord['sensitivity'],valueGiven:string,valueReceived:string,commitment:string|null,commitmentDue:string|null,commitmentComplete:boolean,opportunity:string,stage:RelationshipRecord['stage'],permissionScope:string,proposedAction:string,proofBuild:string|null,proofCapability:string|null,requiredCapability:string,proofPublic:boolean,conflict:boolean,communicationSummary:string):RelationshipRecord=>freeze({id,personId:'person-'+id.toLowerCase(),personName,organization,context,consent,sensitivity,valueGiven,valueReceived,lastVerified:'2026-08-21',commitment,commitmentDue,commitmentComplete,opportunity,stage,permissionScope,proposedAction,proofBuild,proofCapability,requiredCapability,proofPublic,conflict,communicationSummary});
export const RECORDS=freeze([
make('READY_PATH','Mara Vale','Northline Studio','Met at a fictional creator systems forum','CONTACT_OK','STANDARD','Shared a public workflow map','Invited to a scoping conversation',null,null,true,'Coordinate a multi-channel editorial operation','INVITED','Scoping conversation','Prepare a scoping call','087','CREATOR CONTENT OPERATIONS','CREATOR CONTENT OPERATIONS',true,false,'Inbound invitation to discuss operating workflow'),
make('PROMISE_DUE','Jon Bell','Civic Field Lab','Community roundtable follow-up','CONTACT_OK','STANDARD','Promised a resource introduction','Shared a community research brief','Send the promised introduction','2026-08-18',false,'Explore a future research collaboration','QUALIFYING','Resource follow-up','Pursue collaboration','080','PUBLIC RESEARCH INFRASTRUCTURE','PUBLIC RESEARCH INFRASTRUCTURE',true,false,'Roundtable ended with a specific follow-up promise'),
make('PERMISSION_LIMITED','Ari Chen','Signal University','Warm introduction for one informational conversation','LIMITED','STANDARD','Shared an informational call','Explained a program need',null,null,true,'Offer a paid audience workshop','QUALIFYING','One informational conversation only','Send a sales proposal','082','AUDIENCE INTELLIGENCE','AUDIENCE INTELLIGENCE',true,false,'Introduction scope excludes a pitch'),
make('PRIVATE_CONTEXT','Sol Reyes','Care Commons','Private contributor conversation','CONTACT_OK','PRIVATE','Listened and protected context','Shared a fictional private care story',null,null,true,'Use story as public proof','INVITED','Private conversation only','Attach story to proposal','083','SAFE PUBLIC DERIVATIVES','SAFE PUBLIC DERIVATIVES',false,true,'Private story withheld from public output'),
make('PROOF_MISMATCH','Nia Ford','Bright Goods','Public brand operations conversation','CONTACT_OK','STANDARD','Shared a public resource','Named an operations gap',null,null,true,'Improve brand content operations','INVITED','Scoping conversation','Prepare a scoping call','079','EVIDENCE RETRIEVAL','CREATOR CONTENT OPERATIONS',true,false,'Need is clear but attached proof is unrelated')
] as const);
const base=freeze({fixtureId:'SYNTHETIC-RELATIONSHIP-NETWORK-088',records:RECORDS,admission:{syntheticOnly:true,liveMessaging:false,liveCRM:false,proposalSending:false,peopleScoring:false}} as const);
export const PRESETS=freeze(Object.fromEntries(RECORDS.map(r=>[r.id,freeze({...base,scenarioId:r.id,simulateDraft:false})])) as unknown as Record<ScenarioId,Input>);
const nonClaims=freeze(['RELATIONSHIP CONTEXT IS NOT CONSENT','AN INTRODUCTION IS NOT PERMISSION TO PITCH','A PUBLIC BUILD IS NOT PROOF OF FIT','NO PERSON-WORTH, REVENUE, CONVERSION, OR RESPONSE-LIKELIHOOD SCORE','NO MESSAGE, CRM UPDATE, MEETING, OR PROPOSAL IS SENT']);
const invalid=():Result=>freeze({status:'INVALID',record:null,disposition:'INVALID_RECORD',blockingGates:[],nextAction:'Restore an exact frozen synthetic fixture.',rationale:'Input was not admitted.',path:[],reciprocity:[],overdueCommitments:[],proposalPreview:null,nonClaims,version:VERSION});
export function evaluate(candidate:unknown):Result{try{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const o=candidate as Input,p=PRESETS[o.scenarioId];if(!p||typeof o.simulateDraft!=='boolean'||JSON.stringify(o)!==JSON.stringify({...p,simulateDraft:o.simulateDraft}))return invalid();const r=p.records.find(x=>x.id===p.scenarioId)!;const gates:Gate[]=[];let disposition:Disposition='NURTURE_RELATIONSHIP',next='Preserve context and wait for a concrete reciprocal need.',why='No safe concrete opportunity action is due.';if(r.sensitivity==='PRIVATE'){gates.push('PRIVACY');disposition='HOLD_PRIVATE_CONTEXT';next='Keep private context out of proof and request explicit human review.';why='Private context cannot become opportunity evidence.'}else if(r.commitment&&!r.commitmentComplete){gates.push('OPEN_LOOP');disposition='CLOSE_OPEN_LOOP';next='Complete the promised introduction before pursuing opportunity value.';why='A due commitment outranks opportunity pursuit.'}else if(r.consent!=='CONTACT_OK'){gates.push('PERMISSION');disposition='REQUEST_PERMISSION';next='Ask whether the relationship may extend beyond the original informational scope.';why='Relationship context does not expand permission.'}else if(!r.proofPublic||r.proofCapability!==r.requiredCapability){gates.push('PROOF');disposition='FIND_RELEVANT_PROOF';next='Attach a public-safe build that demonstrates the required capability.';why='Relationship strength cannot substitute for relevant proof.'}else if(r.conflict){gates.push('HUMAN_REVIEW');disposition='NEEDS_HUMAN_REVIEW';next='Pause for human conflict and accuracy review.';why='A declared conflict blocks action.'}else if(r.stage==='INVITED'){disposition=o.simulateDraft?'DRAFT_PROPOSAL_SIMULATION':'PREPARE_SCOPING_CALL';next=o.simulateDraft?'Review the fictional draft; nothing is sent.':'Prepare questions and confirm scope for the invited conversation.';why='Permission, commitments, privacy and relevant proof gates are clear.'}const publicPath=r.sensitivity==='PRIVATE'?[r.personId,r.organization,'PRIVATE CONTEXT WITHHELD',next]:[r.personId,r.organization,r.context,r.opportunity,r.proofBuild?'Build '+r.proofBuild:'NO PROOF',next];return freeze({status:r.id+' SYNTHETIC RELATIONSHIP RECORD',record:r.sensitivity==='PRIVATE'?freeze({...r,communicationSummary:'WITHHELD',context:'PRIVATE CONTEXT WITHHELD',valueGiven:'WITHHELD',valueReceived:'WITHHELD',opportunity:'WITHHELD',proofBuild:null,proofCapability:null}):r,disposition,blockingGates:gates,nextAction:next,rationale:why,path:publicPath,reciprocity:r.sensitivity==='PRIVATE'?['WITHHELD','WITHHELD']:[r.valueGiven,r.valueReceived],overdueCommitments:r.commitment&&!r.commitmentComplete?[r.commitment+' · due '+r.commitmentDue]:[],proposalPreview:disposition==='DRAFT_PROPOSAL_SIMULATION'?'Fictional scoping proposal preview · human review required':null,nonClaims,version:VERSION})}catch{return invalid()}}
export function buildExport(input:Input){const result=evaluate(input);return freeze({build:'088',version:VERSION,canonical:{title:'Your Network Is Not a Contact List',uses:['011','020','061'],creates:'cap:088'},artifacts:['Relationship Memory','Opportunity Pipeline'],admission:base.admission,input:{fixtureId:input.fixtureId,scenarioId:input.scenarioId,simulateDraft:input.simulateDraft},result})}