export type ReleaseGateId='consequenceClassification'|'workflowRiskTrace'|'decisionEvidence'|'inclusiveTesting'|'privacyMeasurement'|'fallback'|'stopEscalation'|'incidentOwner';
export type Evidence={id:string;sourceBuild:'012'|'013'|'020'|'030'|'031'|'local';scope:string;method:string;outcome:'pass'|'fail'|'inconclusive';checkedAt:string;expiresAt:string;revokedAt?:string};
export type ReleaseGate={id:ReleaseGateId;required:boolean;severity:'critical'|'high';passed:boolean;evidence:Evidence|null;owner:string;residualRisk:'low'|'medium'|'high'|'unknown'};
export type RollbackRecord={feasible:boolean;tested:boolean;testId:string;checkedAt:string;recoveryMinutes:number};
export type ApprovalRecord={recorded:boolean;approver:string;authorityScope:string;checkedAt:string;expiresAt:string;revokedAt?:string};
export type ReleaseReadinessInput={gates:ReleaseGate[];releaseId:string;systemVersion:string;consequentialScope:string;changeTraceId:string;assessedAt:string;rollback:RollbackRecord;approval:ApprovalRecord};
export type ReleaseReadinessResult={status:'BLOCKED'|'READINESS RECORD COMPLETE';blockers:string[];passed:number;required:number;highestResidualRisk:'low'|'medium'|'high'|'unknown';engineVersion:string;limitations:string[]};
export const RELEASE_READINESS_ENGINE_VERSION='032.2.0';
export const GATE_ORDER:ReleaseGateId[]=['consequenceClassification','workflowRiskTrace','decisionEvidence','inclusiveTesting','privacyMeasurement','fallback','stopEscalation','incidentOwner'];
const dependency:Record<ReleaseGateId,Evidence['sourceBuild']>={consequenceClassification:'012',workflowRiskTrace:'013',decisionEvidence:'020',inclusiveTesting:'030',privacyMeasurement:'031',fallback:'local',stopEscalation:'local',incidentOwner:'local'};
const date=(x:string)=>/^\d{4}-\d{2}-\d{2}$/.test(x)&&!Number.isNaN(Date.parse(`${x}T00:00:00Z`));
export function assessReleaseReadiness(input:ReleaseReadinessInput):ReleaseReadinessResult{const blockers:string[]=[];if(!input.releaseId.trim())blockers.push('Assign a release identifier.');if(!input.systemVersion.trim())blockers.push('Pin the complete system and model version.');if(!input.consequentialScope.trim())blockers.push('Describe affected decisions, people, operators, environment, and consequence boundary.');if(!input.changeTraceId.trim())blockers.push('Link an evidence-bearing Build 029-compatible change trace.');if(!date(input.assessedAt))blockers.push('Record a valid assessment date.');const ids=new Set<string>();for(const id of GATE_ORDER){const matches=input.gates.filter(g=>g.id===id);if(matches.length!==1){blockers.push(`${id}: gate must appear exactly once.`);continue}const gate=matches[0];if(!gate.required)blockers.push(`${id}: required consequential-use gate cannot be downgraded.`);if(!gate.passed)blockers.push(`${id}: test result is not pass.`);if(gate.residualRisk==='high'||gate.residualRisk==='unknown')blockers.push(`${id}: residual risk is ${gate.residualRisk}.`);const e=gate.evidence;if(!e){blockers.push(`${id}: evidence missing.`);continue}if(ids.has(e.id)||!e.id.trim())blockers.push(`${id}: evidence ID missing or duplicated.`);ids.add(e.id);if(e.sourceBuild!==dependency[id])blockers.push(`${id}: evidence must identify dependency ${dependency[id]}.`);if(!e.scope.trim()||!e.method.trim())blockers.push(`${id}: evidence scope and method are required.`);if(e.outcome!=='pass')blockers.push(`${id}: evidence outcome is ${e.outcome}.`);if(!date(e.checkedAt)||!date(e.expiresAt)||e.checkedAt>input.assessedAt||e.expiresAt<input.assessedAt)blockers.push(`${id}: evidence dates are invalid, future-checked, or expired.`);if(e.revokedAt)blockers.push(`${id}: evidence was revoked at ${e.revokedAt}.`);if(!gate.owner.trim())blockers.push(`${id}: accountable evidence owner missing.`)}
 const extra=input.gates.filter(g=>!GATE_ORDER.includes(g.id));if(extra.length)blockers.push('Unregistered gates cannot substitute for required gates.');const r=input.rollback;if(!r.feasible||!r.tested||!r.testId.trim()||!date(r.checkedAt)||r.checkedAt>input.assessedAt||r.recoveryMinutes<=0)blockers.push('Rollback requires a feasible, timed, identified, completed test no later than assessment.');const a=input.approval;if(!a.recorded||!a.approver.trim()||!a.authorityScope.trim()||!date(a.checkedAt)||!date(a.expiresAt)||a.checkedAt>input.assessedAt||a.expiresAt<input.assessedAt||a.revokedAt)blockers.push('Human review requires named approver, bounded authority, valid dates, and no revocation; it is still not deployment authorization.');const severity={low:0,medium:1,high:2,unknown:3};const highest=[...input.gates].sort((x,y)=>severity[y.residualRisk]-severity[x.residualRisk])[0]?.residualRisk||'unknown';const required=GATE_ORDER.length;const passed=GATE_ORDER.filter(id=>{const g=input.gates.find(x=>x.id===id);return g?.passed&&g.evidence?.outcome==='pass'}).length;return{status:blockers.length?'BLOCKED':'READINESS RECORD COMPLETE',blockers:[...new Set(blockers)],passed,required,highestResidualRisk:highest,engineVersion:RELEASE_READINESS_ENGINE_VERSION,limitations:['Completeness is not approval, deployment authorization, safety certification, legal compliance, or evidence validation.','Synthetic evidence demonstrates schema behavior only; production tests, affected-person input, security review, and authorized release governance remain external.','A passing historical test can expire, be revoked, become inapplicable after change, or fail to represent real operating conditions.']}}
