export type SocialCorpusId='CORPUS-CEDAR'|'CORPUS-HARBOR'|'CORPUS-LATTICE'|'CORPUS-MESA'|'CORPUS-ORBIT';
export type SyntheticPost={id:string;text:string;postedOn:string;context:string;author:'FICTIONAL-PUBLIC-ACCOUNT';verification:'SYNTHETIC-RECORD-CHECKED'};
export type Alternative={id:string;label:string;reportedGap:string;status:'FIXTURE-MENTION-ONLY'};
export type Candidate={id:string;kind:'PRODUCT-HYPOTHESIS'|'POLICY-HYPOTHESIS';label:string;condition:string;status:'HUMAN-VALIDATION-REQUIRED'};
export type SocialCorpus={id:SocialCorpusId;label:string;decision:string;posts:readonly SyntheticPost[];affectedContext:string;alternatives:readonly Alternative[];contradictions:readonly string[];missingEvidence:readonly string[];candidates:readonly Candidate[]};
export type SocialListeningInput={fixtureId:'SYNTHETIC-SOCIAL-LISTENING-081';corpusId:SocialCorpusId;corpora:readonly SocialCorpus[];inherited:{unservedDecision:'cap:003';retrieval:'cap:028';researchRepository:'cap:063'};admission:{syntheticOnly:true;fixedPostsOnly:true;networkRetrieval:false;realPeopleData:false;identityInference:false;demographicInference:false;protectedTraitInference:false;sentimentInference:false;needValidated:false;priorityDecision:false}};
export type NeedHypothesis={corpusId:SocialCorpusId;decision:string;signalStatus:'CORROBORATED-IN-SYNTHETIC-FIXTURE';needStatus:'HYPOTHESIS-NOT-VALIDATED';repeatedPostIds:readonly string[];affectedContext:string;alternatives:readonly Alternative[];contradictions:readonly string[];missingEvidence:readonly string[];candidates:readonly Candidate[];validationWorkflow:readonly {stage:string;state:'FIXTURE-COMPLETE'|'HUMAN-RESEARCH-REQUIRED';evidence:string}[]};
export type SocialListeningResult={status:`${SocialCorpusId} NEED HYPOTHESIS`|'INVALID';hypothesis:NeedHypothesis|null;alerts:readonly string[];audit:readonly string[];nonClaims:readonly string[];engineVersion:typeof SOCIAL_LISTENING_ENGINE_VERSION};
export const SOCIAL_LISTENING_ENGINE_VERSION='081.1.0' as const;
const post=(id:string,text:string,postedOn:string,context:string):SyntheticPost=>Object.freeze({id,text,postedOn,context,author:'FICTIONAL-PUBLIC-ACCOUNT',verification:'SYNTHETIC-RECORD-CHECKED'});
const alt=(id:string,label:string,reportedGap:string):Alternative=>Object.freeze({id,label,reportedGap,status:'FIXTURE-MENTION-ONLY'});
const cand=(id:string,kind:Candidate['kind'],label:string,condition:string):Candidate=>Object.freeze({id,kind,label,condition,status:'HUMAN-VALIDATION-REQUIRED'});
const corpus=(id:SocialCorpusId,label:string,prefix:string,date:string,decision:string,context:string,phrases:readonly string[],alternatives:readonly Alternative[],contradictions:readonly string[],missingEvidence:readonly string[],candidates:readonly Candidate[]):SocialCorpus=>Object.freeze({id,label,decision,posts:Object.freeze(phrases.map((text,i)=>post(`POST-${prefix}-${i+1}`,text,date,`SYNTHETIC ${label.toUpperCase()} THREAD`))),affectedContext:context,alternatives:Object.freeze(alternatives),contradictions:Object.freeze(contradictions),missingEvidence:Object.freeze(missingEvidence),candidates:Object.freeze(candidates)});
export const SOCIAL_LISTENING_CORPORA:readonly SocialCorpus[]=Object.freeze([
 corpus('CORPUS-CEDAR','Cedar schedule thread','CE','2047-01-08','How can a person compare changing appointment windows without checking several pages?','FICTIONAL PEOPLE TRYING TO COORDINATE A TIME-SENSITIVE APPOINTMENT',['I checked three pages and still cannot tell which window is current.','The calendar and notice show different times.','I keep repeating the same comparison each morning.','A saved update date would help me know what changed.','I found a phone line, but it repeats one page.','Has anyone found one place that shows the current window?'],[alt('ALT-CE-1','Multiple fixture pages','Dates differ across the invented pages'),alt('ALT-CE-2','Fictional phone line','Does not resolve the synthetic discrepancy')],['One post says a single page was sufficient for that fictional context.'],['REAL FREQUENCY','REAL CONSEQUENCE','SOURCE OWNERSHIP','UPDATE AUTHORITY','USER RESEARCH'],[cand('CAN-CE-1','PRODUCT-HYPOTHESIS','Source-dated comparison view','Only if real users, source authority, accessibility, maintenance, and correction needs are validated'),cand('CAN-CE-2','POLICY-HYPOTHESIS','Common update-label practice','Only if responsible organizations and affected people validate the problem and authority')]),
 corpus('CORPUS-HARBOR','Harbor handoff thread','HA','2047-01-19','Who owns the next step after a fictional referral crosses organizations?','FICTIONAL PEOPLE NAVIGATING A CROSS-ORGANIZATION HANDOFF',['I sent the packet but cannot see who owns it now.','Both offices point me to the other one.','The confirmation says received but not what happens next.','I need a named next step, not another general inbox.','The status changed without explaining who can act.','Is there a way to see the handoff rather than call twice?'],[alt('ALT-HA-1','General fixture inbox','No named synthetic owner'),alt('ALT-HA-2','Two fictional status pages','Handoff states do not align')],['One fictional post reports a successful direct handoff.'],['REAL FAILURE RATE','REAL RESPONSIBILITY RULES','CONSENT AND PRIVACY NEEDS','ORGANIZATIONAL AUTHORITY','USER RESEARCH'],[cand('CAN-HA-1','PRODUCT-HYPOTHESIS','Consent-aware handoff receipt','Only after validating real roles, permissions, privacy, records, and exception handling'),cand('CAN-HA-2','POLICY-HYPOTHESIS','Named handoff-ownership convention','Only after legal, operational, and affected-person review')]),
 corpus('CORPUS-LATTICE','Lattice records thread','LA','2047-02-02','How can a person tell whether two fictional records refer to the same requirement?','FICTIONAL PEOPLE COMPARING INCONSISTENT RECORD LABELS',['These two names look similar, but I cannot tell if they mean the same thing.','The older record uses a different label.','Search returns both versions without explaining the relationship.','I need the source and change date beside each result.','One result may be a duplicate, but I cannot verify it.','Where is the relationship between the old and new terms recorded?'],[alt('ALT-LA-1','Keyword fixture search','Returns labels without relationship evidence'),alt('ALT-LA-2','Static fictional glossary','Does not preserve change history')],['A fictional participant says the labels were easy to distinguish.'],['REAL DUPLICATE RATE','AUTHORITATIVE IDENTIFIERS','CHANGE HISTORY','USER COMPREHENSION','USER RESEARCH'],[cand('CAN-LA-1','PRODUCT-HYPOTHESIS','Evidence-linked term relationship view','Only if authoritative identifiers, provenance, versioning, and user need are validated'),cand('CAN-LA-2','POLICY-HYPOTHESIS','Record-label version convention','Only if record owners and affected users establish feasibility and authority')]),
 corpus('CORPUS-MESA','Mesa eligibility thread','ME','2047-02-16','What information is missing when a fictional eligibility answer cannot be applied?','FICTIONAL PEOPLE TRYING TO UNDERSTAND A GENERAL ELIGIBILITY RULE',['The page says who may qualify but not which facts change the answer.','I cannot tell what date the rule reflects.','The example does not match my fictional situation.','The answer needs its source and limits beside it.','I found a checklist, but it does not explain unknown facts.','Where should a person go when the general rule is not enough?'],[alt('ALT-ME-1','General fixture explainer','Does not resolve individual facts'),alt('ALT-ME-2','Synthetic checklist','Does not expose unknowns or escalation')],['Two fictional posts say the general explanation answered their question.'],['REAL LEGAL STANDARD','REAL FACT PATTERNS','AUTHORIZED GUIDANCE','ESCALATION ROUTE','USER RESEARCH'],[cand('CAN-ME-1','PRODUCT-HYPOTHESIS','Source-and-unknown explainer','Only as non-advice after qualified review of scope, escalation, freshness, and accessibility'),cand('CAN-ME-2','POLICY-HYPOTHESIS','Plain-language source-date standard','Only if authoritative owners and affected users validate need and implementation')]),
 corpus('CORPUS-ORBIT','Orbit interruption thread','OR','2047-03-01','How can unfinished work survive a fictional interruption without losing context?','FICTIONAL PEOPLE RESUMING A MULTI-STEP PUBLIC WORKFLOW',['The session ended and I cannot tell which step was saved.','I had to enter the same fictional details again.','The page remembers completion but not my unresolved question.','I need a clear resume point after a connection loss.','The confirmation does not say what remains unfinished.','Can the workflow preserve context without collecting extra data?'],[alt('ALT-OR-1','Fixture progress marker','Does not preserve the unresolved synthetic question'),alt('ALT-OR-2','Invented email receipt','Shows submission but not resumable state')],['One fictional post reports no interruption or data loss.'],['REAL ABANDONMENT RATE','MINIMUM NECESSARY DATA','SECURITY MODEL','OFFLINE REQUIREMENTS','USER RESEARCH'],[cand('CAN-OR-1','PRODUCT-HYPOTHESIS','Minimal resumable-state record','Only after privacy, security, accessibility, offline, deletion, and user-control validation'),cand('CAN-OR-2','POLICY-HYPOTHESIS','Interruption-recovery service standard','Only if responsible entities and affected people validate authority and burden')])
]);
const base={fixtureId:'SYNTHETIC-SOCIAL-LISTENING-081',corpora:SOCIAL_LISTENING_CORPORA,inherited:{unservedDecision:'cap:003',retrieval:'cap:028',researchRepository:'cap:063'},admission:{syntheticOnly:true,fixedPostsOnly:true,networkRetrieval:false,realPeopleData:false,identityInference:false,demographicInference:false,protectedTraitInference:false,sentimentInference:false,needValidated:false,priorityDecision:false}} as const;
export const SOCIAL_LISTENING_PRESETS:Readonly<Record<SocialCorpusId,SocialListeningInput>>=Object.freeze(Object.fromEntries(SOCIAL_LISTENING_CORPORA.map(c=>[c.id,Object.freeze({...base,corpusId:c.id})])) as Record<SocialCorpusId,SocialListeningInput>);
const invalid=():SocialListeningResult=>({status:'INVALID',hypothesis:null,alerts:['INVALID OR UNADMITTED SYNTHETIC INPUT','NO NEED HYPOTHESIS PRODUCED'],audit:[],nonClaims:['NO REAL PEOPLE, PUBLIC CONVERSATION, IDENTITY, DEMOGRAPHIC, PROTECTED-TRAIT, SENTIMENT, NEED, DEMAND, TREND, PRIORITY, PRODUCT, OR POLICY CLAIM'],engineVersion:SOCIAL_LISTENING_ENGINE_VERSION});
function evaluate(candidate:unknown):SocialListeningResult{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const object=candidate as Record<string,unknown>;const preset=SOCIAL_LISTENING_PRESETS[object.corpusId as SocialCorpusId];if(!preset||JSON.stringify(object)!==JSON.stringify(preset))return invalid();const c=preset.corpora.find(x=>x.id===preset.corpusId)!;const hypothesis:NeedHypothesis={corpusId:c.id,decision:c.decision,signalStatus:'CORROBORATED-IN-SYNTHETIC-FIXTURE',needStatus:'HYPOTHESIS-NOT-VALIDATED',repeatedPostIds:c.posts.map(p=>p.id),affectedContext:c.affectedContext,alternatives:c.alternatives,contradictions:c.contradictions,missingEvidence:c.missingEvidence,candidates:c.candidates,validationWorkflow:[{stage:'CLASSIFY REPEATED DECISION',state:'FIXTURE-COMPLETE',evidence:'SIX FIXED SYNTHETIC POSTS'},{stage:'BOUND AFFECTED CONTEXT',state:'FIXTURE-COMPLETE',evidence:c.affectedContext},{stage:'INVENTORY MENTIONED ALTERNATIVES',state:'FIXTURE-COMPLETE',evidence:`${c.alternatives.length} FIXED ALTERNATIVES`},{stage:'SEEK CONTRADICTION',state:'FIXTURE-COMPLETE',evidence:`${c.contradictions.length} FIXED CONTRADICTION RECORD`},{stage:'VALIDATE REAL NEED, CONSEQUENCE, DEMAND, AND ALTERNATIVES',state:'HUMAN-RESEARCH-REQUIRED',evidence:c.missingEvidence.join(' / ')},{stage:'DECIDE PRODUCT OR POLICY RESPONSE',state:'HUMAN-RESEARCH-REQUIRED',evidence:'NO DECISION AUTHORIZED'}]};return{status:`${c.id} NEED HYPOTHESIS`,hypothesis,alerts:['SYNTHETIC CONVERSATION FIXTURE ONLY','REPETITION IS A SIGNAL, NOT PROOF OF NEED, DEMAND, PREVALENCE, PRIORITY, OR TREND'],audit:['VALIDATED EXACT FROZEN FIXTURE','PRESERVED POST TEXT, DATE, CONTEXT, ALTERNATIVES, CONTRADICTIONS, MISSING EVIDENCE, AND CANDIDATE CONDITIONS','PRESERVED HYPOTHESIS AND HUMAN-VALIDATION STATES','NO SCRAPING, IDENTITY LINKAGE, PROFILING, SENTIMENT, DEMOGRAPHIC, PROTECTED-TRAIT, SCORE, RANK, OR REAL-WORLD INFERENCE'],nonClaims:['NO REAL PEOPLE OR PUBLIC-CONVERSATION DATA','NO VERIFIED REAL NEED, DEMAND, PREVALENCE, TREND, PRIORITY, PRODUCT, OR POLICY CLAIM','NO IDENTITY, DEMOGRAPHIC, PROTECTED-TRAIT, OR SENTIMENT INFERENCE'],engineVersion:SOCIAL_LISTENING_ENGINE_VERSION}}
export function classifyUnmetNeed(candidate:unknown):SocialListeningResult{try{return evaluate(candidate)}catch{return invalid()}}
