export type AgentAction='CONTINUE'|'ASK'|'ABSTAIN'|'FALLBACK'|'ESCALATE'|'STOP';
export type ControlRecord={id:string;build:'019'|'032'|'038'|'039';version:string;scope:string;evidenceId:string;reviewedAt:string;expiresAt:string;revoked:boolean};
export type StopInput={consequence:'low'|'medium'|'high';uncertainty:number;evidenceCompleteness:number;toolFailed:boolean;requiredTool:boolean;humanAvailable:boolean;safeFallback:boolean;fallbackVerified:boolean;timeCritical:boolean;policyVersion:string;policyReviewedAt:string;policyExpiresAt:string;records:ControlRecord[]};
export type StopResult={action:AgentAction;reasons:string[];blockers:string[];status:'CONTROL GAPS'|'MODELED ACTION SELECTED';engineVersion:string;ruleId:string};
export const STOP_ESCALATE_ENGINE_VERSION='040.2.0';
const REQUIRED_BUILDS=['019','032','038','039'] as const;
const ISO=/^\d{4}-\d{2}-\d{2}$/;
function blocked(reason:string):StopResult{return{action:'STOP',reasons:['The bounded fixture cannot select an action.'],blockers:[reason],status:'CONTROL GAPS',engineVersion:STOP_ESCALATE_ENGINE_VERSION,ruleId:'BLOCK'};}
export function decideAgentAction(input:StopInput):StopResult{
 if(!Number.isFinite(input.uncertainty)||input.uncertainty<0||input.uncertainty>100||!Number.isFinite(input.evidenceCompleteness)||input.evidenceCompleteness<0||input.evidenceCompleteness>100)return blocked('Uncertainty and evidence completeness must be finite values from 0 to 100.');
 if(!input.policyVersion.trim()||!ISO.test(input.policyReviewedAt)||!ISO.test(input.policyExpiresAt)||input.policyReviewedAt>input.policyExpiresAt||input.policyExpiresAt<'2026-08-20')return blocked('A current, versioned policy contract is required.');
 if(input.records.length!==REQUIRED_BUILDS.length||new Set(input.records.map(r=>r.build)).size!==REQUIRED_BUILDS.length)return blocked('Exactly one inherited control record from Builds 019, 032, 038, and 039 is required.');
 for(const build of REQUIRED_BUILDS){const r=input.records.find(x=>x.build===build);if(!r||!r.id.trim()||!r.version.trim()||!r.scope.trim()||!r.evidenceId.trim()||!ISO.test(r.reviewedAt)||!ISO.test(r.expiresAt)||r.reviewedAt>r.expiresAt||r.expiresAt<'2026-08-20'||r.revoked)return blocked(`Build ${build} control record is missing, stale, revoked, or out of scope.`);}
 if(input.toolFailed&&input.requiredTool){if(input.safeFallback&&input.fallbackVerified)return{action:'FALLBACK',reasons:['A required tool failed; the declared verified fallback is selected.'],blockers:[],status:'MODELED ACTION SELECTED',engineVersion:STOP_ESCALATE_ENGINE_VERSION,ruleId:'R1-REQUIRED-TOOL'};return{action:'STOP',reasons:['A required tool failed without a verified fallback.'],blockers:[],status:'MODELED ACTION SELECTED',engineVersion:STOP_ESCALATE_ENGINE_VERSION,ruleId:'R1-REQUIRED-TOOL'};}
 if(input.consequence==='high'&&(input.uncertainty>=40||input.evidenceCompleteness<80)){return{action:input.humanAvailable?'ESCALATE':'ABSTAIN',reasons:['High consequence requires stronger evidence and lower uncertainty; urgency does not relax this boundary.'],blockers:[],status:'MODELED ACTION SELECTED',engineVersion:STOP_ESCALATE_ENGINE_VERSION,ruleId:'R2-HIGH-CONSEQUENCE'};}
 if(input.evidenceCompleteness<50)return{action:input.humanAvailable?'ASK':'ABSTAIN',reasons:['Evidence is too incomplete to continue.'],blockers:[],status:'MODELED ACTION SELECTED',engineVersion:STOP_ESCALATE_ENGINE_VERSION,ruleId:'R3-EVIDENCE'};
 if(input.uncertainty>=70)return{action:input.humanAvailable?'ESCALATE':'ABSTAIN',reasons:['Uncertainty exceeds the declared policy boundary.'],blockers:[],status:'MODELED ACTION SELECTED',engineVersion:STOP_ESCALATE_ENGINE_VERSION,ruleId:'R4-UNCERTAINTY'};
 return{action:'CONTINUE',reasons:['The declared synthetic fixture remains within this versioned policy boundary.'],blockers:[],status:'MODELED ACTION SELECTED',engineVersion:STOP_ESCALATE_ENGINE_VERSION,ruleId:'R5-CONTINUE'};
}
