export type WorkPacketId='WORK-CEDAR'|'WORK-HARBOR'|'WORK-LATTICE'|'WORK-MESA'|'WORK-ORBIT';
export type FragmentClass='PUBLIC-SYNTHETIC'|'CONFIDENTIAL-SYNTHETIC'|'THIRD-PARTY-RESTRICTED'|'PERSONAL-SYNTHETIC'|'INTERNAL-SYNTHETIC';
export type RightsState='OWNED-SYNTHETIC'|'RIGHTS-NOT-CLEARED'|'CONSENT-NOT-GRANTED'|'INTERNAL-ONLY';
export type WorkFragment={id:string;classification:FragmentClass;rightsState:RightsState;content:string;provenance:string;purpose:string;status:'SYNTHETIC-FRAGMENT-CHECKED'};
export type ContentDerivative={id:string;kind:'INSIGHT'|'METHOD'|'VISUAL'|'TEACHING-MATERIAL';title:string;publicDraft:string;sourceFragmentIds:readonly string[];removedDetailCategories:readonly string[];limitations:readonly string[];rightsReview:'HUMAN-REVIEW-REQUIRED';confidentialityReview:'HUMAN-REVIEW-REQUIRED';publicationStatus:'DRAFT-HUMAN-APPROVAL-REQUIRED'};
export type WorkPacket={id:WorkPacketId;label:string;workType:string;fragments:readonly WorkFragment[];derivatives:readonly ContentDerivative[];unknowns:readonly string[]};
export type CaptureInput={fixtureId:'SYNTHETIC-WORK-CONTENT-083';packetId:WorkPacketId;packets:readonly WorkPacket[];inherited:{dataMinimization:'cap:024';contentProvenance:'cap:057';ipCapture:'cap:060';reportingInfrastructure:'cap:080'};admission:{syntheticOnly:true;fixedFragmentsOnly:true;realConfidentialData:false;realPersonalData:false;thirdPartyContentUse:false;publicationAuthorized:false;rightsClearedForRealUse:false;consentGrantedForRealUse:false;legalPrivilegeDetermined:false;safeToPublishDetermined:false}};
export type CaptureResult={status:`${WorkPacketId} SAFE DERIVATIVES`|'INVALID';packetSummary:{id:WorkPacketId;label:string;workType:string}|null;admittedFragmentIds:readonly string[];blocked:readonly {fragmentId:string;classification:FragmentClass;reason:string}[];derivatives:readonly ContentDerivative[];alerts:readonly string[];audit:readonly string[];nonClaims:readonly string[];engineVersion:typeof WORK_CONTENT_ENGINE_VERSION};
export const WORK_CONTENT_ENGINE_VERSION='083.1.0' as const;
const fragment=(id:string,classification:FragmentClass,rightsState:RightsState,content:string,provenance:string,purpose:string):WorkFragment=>Object.freeze({id,classification,rightsState,content,provenance,purpose,status:'SYNTHETIC-FRAGMENT-CHECKED'});
const derivative=(id:string,kind:ContentDerivative['kind'],title:string,publicDraft:string,sourceFragmentIds:readonly string[]):ContentDerivative=>Object.freeze({id,kind,title,publicDraft,sourceFragmentIds:Object.freeze(sourceFragmentIds),removedDetailCategories:Object.freeze(['CONFIDENTIAL DETAIL','THIRD-PARTY MATERIAL','PERSONAL DETAIL','INTERNAL DECISION DETAIL']),limitations:Object.freeze(['Synthetic demonstration only','Not evidence of project outcome','Requires fresh rights, confidentiality, accuracy, context, and publication review']),rightsReview:'HUMAN-REVIEW-REQUIRED',confidentialityReview:'HUMAN-REVIEW-REQUIRED',publicationStatus:'DRAFT-HUMAN-APPROVAL-REQUIRED'});
const packet=(id:WorkPacketId,label:string,prefix:string,workType:string,method:string,lesson:string):WorkPacket=>{
 const safe1=`FRAG-${prefix}-PUB-1`,safe2=`FRAG-${prefix}-PUB-2`;const fragments=Object.freeze([
  fragment(safe1,'PUBLIC-SYNTHETIC','OWNED-SYNTHETIC',method,`${label} invented method note`,'DEMONSTRATE A GENERIC METHOD'),
  fragment(safe2,'PUBLIC-SYNTHETIC','OWNED-SYNTHETIC',lesson,`${label} invented retrospective`,'DEMONSTRATE A GENERIC LESSON'),
  fragment(`FRAG-${prefix}-CONF`,'CONFIDENTIAL-SYNTHETIC','RIGHTS-NOT-CLEARED',`[${prefix} SYNTHETIC CONFIDENTIAL DETAIL WITHHELD]`,`${label} placeholder confidential record`,'FILTER TEST ONLY'),
  fragment(`FRAG-${prefix}-3P`,'THIRD-PARTY-RESTRICTED','RIGHTS-NOT-CLEARED',`[${prefix} SYNTHETIC THIRD-PARTY MATERIAL WITHHELD]`,`${label} placeholder third-party record`,'FILTER TEST ONLY'),
  fragment(`FRAG-${prefix}-PER`,'PERSONAL-SYNTHETIC','CONSENT-NOT-GRANTED',`[${prefix} SYNTHETIC PERSONAL DETAIL WITHHELD]`,`${label} placeholder personal record`,'FILTER TEST ONLY'),
  fragment(`FRAG-${prefix}-INT`,'INTERNAL-SYNTHETIC','INTERNAL-ONLY',`[${prefix} SYNTHETIC INTERNAL DECISION WITHHELD]`,`${label} placeholder internal record`,'FILTER TEST ONLY')
 ]);
 const derivatives=Object.freeze([derivative(`DER-${prefix}-INS`,'INSIGHT',`${label}: bounded insight`,`A fictional project suggests documenting assumptions before mapping reusable outputs.`,[safe2]),derivative(`DER-${prefix}-MET`,'METHOD',`${label}: generic method`,`A synthetic method separates source inventory, restrictions, safe abstractions, review, and release.`,[safe1,safe2]),derivative(`DER-${prefix}-VIS`,'VISUAL',`${label}: process visual`,`A proposed visual shows two admitted fragments entering four human-reviewed derivative paths.`,[safe1]),derivative(`DER-${prefix}-TEA`,'TEACHING-MATERIAL',`${label}: teaching prompt`,`Ask which details a public explanation needs—and which must remain absent—before drafting.`,[safe1,safe2])]);
 return Object.freeze({id,label,workType,fragments,derivatives,unknowns:Object.freeze(['REAL RIGHTS ARE UNKNOWN','REAL CONFIDENTIALITY DUTIES ARE UNKNOWN','REAL CONSENT IS UNKNOWN','REAL ACCURACY AND CONTEXT ARE UNKNOWN','PUBLICATION DECISION IS UNMADE'])});
};
export const WORK_CONTENT_PACKETS:readonly WorkPacket[]=Object.freeze([
 packet('WORK-CEDAR','Cedar research workflow','CE','SYNTHETIC RESEARCH WORK','Map the question, source, claim, limit, and update state before drafting.','The invented workflow became clearer when unknowns stayed visible.'),
 packet('WORK-HARBOR','Harbor service workflow','HA','SYNTHETIC SERVICE WORK','Separate repeatable steps from expert judgment and prohibited automation.','The fictional handoff failed when ownership was implied rather than recorded.'),
 packet('WORK-LATTICE','Lattice legal workflow','LA','SYNTHETIC LEGAL-OPERATIONS WORK','Keep fictional authority, facts, interpretation, review, and approval in separate layers.','The invented example improved when no legal conclusion was exported.'),
 packet('WORK-MESA','Mesa implementation workflow','ME','SYNTHETIC IMPLEMENTATION WORK','Trace each fictional policy change into actors, systems, dates, dependencies, and unknowns.','The fixture showed that an effective date alone did not establish readiness.'),
 packet('WORK-ORBIT','Orbit product workflow','OR','SYNTHETIC PRODUCT WORK','Connect each proposed feature to a bounded decision, evidence need, limitation, and owner.','The invented artifact stayed reusable because its source links were preserved.')
]);
const base={fixtureId:'SYNTHETIC-WORK-CONTENT-083',packets:WORK_CONTENT_PACKETS,inherited:{dataMinimization:'cap:024',contentProvenance:'cap:057',ipCapture:'cap:060',reportingInfrastructure:'cap:080'},admission:{syntheticOnly:true,fixedFragmentsOnly:true,realConfidentialData:false,realPersonalData:false,thirdPartyContentUse:false,publicationAuthorized:false,rightsClearedForRealUse:false,consentGrantedForRealUse:false,legalPrivilegeDetermined:false,safeToPublishDetermined:false}} as const;
export const WORK_CONTENT_PRESETS:Readonly<Record<WorkPacketId,CaptureInput>>=Object.freeze(Object.fromEntries(WORK_CONTENT_PACKETS.map(p=>[p.id,Object.freeze({...base,packetId:p.id})])) as Record<WorkPacketId,CaptureInput>);
const invalid=():CaptureResult=>({status:'INVALID',packetSummary:null,admittedFragmentIds:[],blocked:[],derivatives:[],alerts:['INVALID OR UNADMITTED SYNTHETIC INPUT','NO DERIVATIVES PRODUCED'],audit:[],nonClaims:['NO REAL CONFIDENTIAL, PERSONAL, PRIVILEGED, THIRD-PARTY, RIGHTS, CONSENT, ACCURACY, SAFETY, OR PUBLICATION DETERMINATION'],engineVersion:WORK_CONTENT_ENGINE_VERSION});
const blockReason:Record<Exclude<FragmentClass,'PUBLIC-SYNTHETIC'>,string>={'CONFIDENTIAL-SYNTHETIC':'CONFIDENTIAL CLASSIFICATION — CONTENT NOT COPIED','THIRD-PARTY-RESTRICTED':'THIRD-PARTY RIGHTS NOT CLEARED — CONTENT NOT COPIED','PERSONAL-SYNTHETIC':'CONSENT NOT GRANTED — CONTENT NOT COPIED','INTERNAL-SYNTHETIC':'INTERNAL-ONLY CLASSIFICATION — CONTENT NOT COPIED'};
function evaluate(candidate:unknown):CaptureResult{if(!candidate||typeof candidate!=='object'||Array.isArray(candidate))return invalid();const object=candidate as Record<string,unknown>;const preset=WORK_CONTENT_PRESETS[object.packetId as WorkPacketId];if(!preset||JSON.stringify(object)!==JSON.stringify(preset))return invalid();const p=preset.packets.find(x=>x.id===preset.packetId)!;const admitted=p.fragments.filter(f=>f.classification==='PUBLIC-SYNTHETIC'&&f.rightsState==='OWNED-SYNTHETIC').map(f=>f.id);const blocked=p.fragments.filter(f=>f.classification!=='PUBLIC-SYNTHETIC').map(f=>({fragmentId:f.id,classification:f.classification,reason:blockReason[f.classification as Exclude<FragmentClass,'PUBLIC-SYNTHETIC'>]}));if(p.derivatives.some(d=>d.sourceFragmentIds.some(id=>!admitted.includes(id))))return invalid();return{status:`${p.id} SAFE DERIVATIVES`,packetSummary:{id:p.id,label:p.label,workType:p.workType},admittedFragmentIds:admitted,blocked,derivatives:p.derivatives,alerts:['SYNTHETIC WORK-TO-CONTENT DEMONSTRATION ONLY','DRAFTS REQUIRE HUMAN RIGHTS, CONFIDENTIALITY, CONSENT, ACCURACY, CONTEXT, AND PUBLICATION REVIEW'],audit:['VALIDATED EXACT FROZEN FIXTURE','ADMITTED ONLY PUBLIC-SYNTHETIC + OWNED-SYNTHETIC FRAGMENT IDS','RETURNED BLOCKED IDS, CLASSIFICATIONS, AND REASONS WITHOUT BLOCKED CONTENT','PRESERVED DERIVATIVE SOURCE LINKS, REMOVED-DETAIL CATEGORIES, LIMITATIONS, AND HUMAN REVIEW GATES','NO PUBLICATION, RIGHTS CLEARANCE, PRIVILEGE, CONFIDENTIALITY, CONSENT, OR SAFE-TO-PUBLISH DETERMINATION'],nonClaims:['NO REAL WORK, CLIENT, MATTER, PATIENT, PERSON, ORGANIZATION, OR THIRD-PARTY MATERIAL','NO LEGAL PRIVILEGE, CONFIDENTIALITY, PRIVACY, RIGHTS, CONSENT, ACCURACY, OR PUBLICATION DETERMINATION','NO CLAIM THAT ANY REAL WORK IS SAFE TO DISCLOSE OR PUBLISH'],engineVersion:WORK_CONTENT_ENGINE_VERSION}}
export function captureSafeContent(candidate:unknown):CaptureResult{try{return evaluate(candidate)}catch{return invalid()}}
