'use client';
import{useState}from'react';
import{buildPersonalKnowledgeModel,PERSONAL_KNOWLEDGE_SCENARIOS,type PersonalKnowledgeScenarioId}from'../../../../../../packages/release/src/personal-knowledge-model-engine';
import s from'../personal-model.module.css';

const ids:PersonalKnowledgeScenarioId[]=['MODEL-BOUNDARIES-CLEAR','CONSENT-WITHHELD','CONTEXT-EXPIRED','OWNERSHIP-UNDECLARED','INFERENCE-BLOCKED'];
const layers=[['01','DECLARED'],['02','INFERRED'],['03','CONTEXT'],['04','PERMISSION'],['05','OWNERSHIP'],['06','LIMIT']];

export default function PersonalBoundaryStory(){const[index,setIndex]=useState(0),id=ids[index],result=buildPersonalKnowledgeModel(PERSONAL_KNOWLEDGE_SCENARIOS[id]);return <section className={s.story} data-model-state={id}><header className={s.status} role="status" aria-live="polite" aria-atomic="true"><small>BOUNDARY STATE {index+1}/5 · {id}</small><h2>{result.status}</h2><p>{result.nonClaims[0]}</p></header><ol className={s.path} aria-label="Personal model boundary pathway">{layers.map(([number,stage])=><li key={stage}><span aria-hidden="true">{number}</span><b>{stage}</b><i aria-hidden="true"/></li>)}</ol><div className={s.storyAction}><button type="button" onClick={()=>setIndex(value=>(value+1)%ids.length)}>FORM NEXT BOUNDARY</button><p>{result.connections[0]??'No usable synthetic connection is recorded.'}</p></div><div className={s.equation} aria-label="A bounded personal model separates declaration, inference, context, permission, ownership and limits"><span>DECLARATION</span><b aria-hidden="true">≠</b><span>INFERENCE</span><b aria-hidden="true">·</b><span>CONTEXT</span><b aria-hidden="true">·</b><span>PERMISSION</span><b aria-hidden="true">·</b><span>LIMIT</span></div><aside className={s.warning}><h3>Recognition is not ownership.</h3><p>A digital representation does not verify identity or establish consent validity, legal rights, truth, authority, ownership, permission, or authorization. Expired, withheld, undeclared, and inferred states stay held.</p></aside><p className={s.note}>Synthetic fixtures only; no real data, persistence, tracking, or surveillance. No identity verification, ownership determination, consent determination, psychological profile, truth claim, authority claim, or authorization claim.</p></section>}
