export default {
'072':{title:'Why Does Access Change by Island?',proposition:'Preserve local difference.',scenes:[['BUILD 072','ONE POLICY. MANY REALITIES.','Islands experience access differently.'],['PLACE','CHANGE THE PATH','Connect providers, transport, supply, infrastructure, and administration.'],['COMPARE','SAME RULE. DIFFERENT CONSTRAINTS.','Never flatten local barriers.'],['CULTURE','DO NOT CLAIM AUTHORITY','Representation requires consent and relationship.'],['BOUNDARY','MAP ≠ LAW OR CARE','Keep unknowns visible.'],['SAVE','PRESERVE LOCAL DIFFERENCE','Access intelligence must remain place-aware.']]},
'073':{title:'Access for Whom?',proposition:'Ask who can actually use the service.',scenes:[['BUILD 073','ACCESS FOR WHOM?','Reform does not guarantee usability.'],['CONSTRAINTS','COST. PLACE. ELIGIBILITY. RISK.','Keep every practical barrier visible.'],['EXCLUSION','DISABILITY. LANGUAGE. CULTURE. WORKFORCE.','One favorable signal cannot erase another.'],['METHOD','NO COMPOSITE SCORE','Preserve separate signals and unknowns.'],['BOUNDARY','A MAP CANNOT DETERMINE EQUITY','Synthetic contexts only.'],['SAVE','WHO CAN ACTUALLY USE IT?','Begin there.']]},
'074':{title:'Is the System Actually Ready?',proposition:'Compare implementation. Keep evidence visible.',scenes:[['BUILD 074','THE LAW SAYS YES','Operations may still say no.'],['MEASURE','ENACTMENT ≠ IMPLEMENTATION','Test affordability, workforce, equity, safety, outcomes.'],['RULES','SOURCE. DATE. SCORE. WEIGHT.','Expose every illustrative calculation.'],['EVIDENCE','MISSING STAYS MISSING','Never substitute authorization for operations.'],['BOUNDARY','DEMO ORDER ≠ REAL RANKING','Synthetic jurisdictions only.'],['SAVE','COMPARE IMPLEMENTATION','Keep each readiness layer distinct.']]},
'075':{title:'Same Goal, Different Regulatory Machine',proposition:'Compare tradeoffs. Keep claims small.',scenes:[['BUILD 075','SAME GOAL. DIFFERENT MACHINE.','Regulatory designs create different work.'],['OPEN','GOVERNANCE. INSTITUTIONS. LICENSING.','Trace authority and entry.'],['FOLLOW','ENFORCEMENT. RIGHTS. DATA. FINANCING.','Each choice changes burdens and safeguards.'],['SWAP','CHANGE ONE DIMENSION','Hold seven fixed; inspect the tradeoff.'],['BOUNDARY','DESIGN ≠ CURRENT LAW','Synthetic models only.'],['SAVE','COMPARE TRADEOFFS','Keep claims small and connections visible.']]},
'076':{title:'What Is Actually Different Between These Laws?',proposition:'Trace the difference. Keep the source.',scenes:[['BUILD 076','SIMILAR LAWS. DIFFERENT SYSTEMS.','Labels can conceal structure.'],['QUESTION','WHO? WHAT AUTHORITY? WHEN?','Narrow the comparison first.'],['SOURCE','LOCATOR. ISSUED. EFFECTIVE. AS-OF.','Keep answers attached to evidence.'],['DISAGREEMENT','CONFLICT STAYS VISIBLE','Never guess missing dates.'],['BOUNDARY','A MAP IS NOT AUTHORITY','Fictional jurisdictions only.'],['SAVE','TRACE THE DIFFERENCE','Keep source, date, conflict, unknown.']]},
'077':{title:'What Does This Change Actually Do?',proposition:'Trace the consequence. Keep the claim narrow.',scenes:[['BUILD 077','A RULE CHANGES','What moves next?'],['GRAPH','CLAUSE → ACTOR → OBLIGATION → WORKFLOW','Connect change to triggered work.'],['TIME','NULL DATE STAYS NULL','Never calculate missing deadlines.'],['OPEN WORK','RISKS. OPPORTUNITIES. QUESTIONS.','Trace what still needs inspection.'],['BOUNDARY','CONSEQUENCE LINE ≠ LEGAL ADVICE','Synthetic changes only.'],['SAVE','TRACE THE CONSEQUENCE','Keep every claim narrow.']]},
'078':{title:'Translate the Evidence Without Breaking It',proposition:'Change the language. Keep the evidence intact.',scenes:[['BUILD 078','A STUDY TRAVELS','Evidence can fray.'],['ANCHORS','SOURCE. QUALITY. CLAIM. POPULATION. OUTCOME.','Fix what cannot change.'],['LIMITS','UNCERTAINTY TRAVELS TOO','Friendly language cannot upgrade evidence.'],['AUDIENCE','ADAPT THE EXPLANATION','Carry audience-specific caveats with it.'],['BOUNDARY','TRANSLATION ≠ ADVICE OR PROOF','Synthetic evidence only.'],['SAVE','CHANGE LANGUAGE, NOT EVIDENCE','Keep every limit attached.']]},
'079':{title:'Find the Evidence That Actually Answers Your Question',proposition:'Find what answers the question.',scenes:[['BUILD 079','SEARCH RESULT ≠ EVIDENCE MAP','Keywords can miss the question.'],['DIMENSIONS','QUESTION. POPULATION. CONTEXT. OUTCOME.','Test relevance explicitly.'],['QUALIFY','TYPE. QUALITY. APPLICABILITY.','Keep these judgments separate.'],['RETAIN','SOURCE. LIMIT. UNKNOWN.','Show what does not fit.'],['BOUNDARY','NAVIGATION DOES NOT DECIDE','Synthetic evidence only.'],['SAVE','FIND WHAT ANSWERS','Keep every source and limit attached.']]},
'080':{title:'Turn Reporting Into Public Infrastructure',proposition:'Reporting can become public infrastructure.',scenes:[['BUILD 080','THE ARTICLE WAS OUTPUT ONE','Reporting can keep working.'],['PIPELINE','STORY. INTERVIEW. FIELD. RECORD. QUESTION.','Preserve dates, rights, verification, limits.'],['ASSETS','DATASET. TOOL. TRACKER. TIMELINE.','Extract source-linked candidates.'],['MAINTENANCE','OWNER. UPDATE PATH. EVIDENCE GAP.','Public value needs upkeep.'],['BOUNDARY','PUBLICATION IS A BEGINNING','Candidates are not verified facts.'],['SAVE','BUILD PUBLIC INFRASTRUCTURE','Keep source, rights, and status attached.']]},
'081':{title:'What Are People Repeatedly Struggling With?',proposition:'Listen for the missing system.',scenes:[['BUILD 081','PEOPLE KEEP ASKING','A system may be missing.'],['SIGNALS','PRESERVE WORDS + CONTEXT','Do not collapse posts into identities.'],['CLASSIFY','SIGNAL ≠ NEED ≠ OPPORTUNITY','Keep hypotheses separate.'],['VERIFY','REPETITION. ALTERNATIVES. CONTRADICTIONS.','Require human research.'],['BOUNDARY','REPETITION CANNOT PROVE DEMAND','Synthetic posts only.'],['SAVE','LISTEN FOR THE MISSING SYSTEM','Then validate it.']]},
'082':{title:'How Does This Audience Actually Think?',proposition:'Understand the relationships.',scenes:[['BUILD 082','AUDIENCE ≠ DEMOGRAPHIC BOX','Personas cannot explain relationships.'],['GRAPH','NEED. LANGUAGE. CONTEXT.','Connect sources with caveats.'],['EDGES','SOURCE. EVIDENCE. UNKNOWN.','Never infer identity or personality.'],['CLAIMS','TRUST ≠ INFLUENCE ≠ ACTION','Keep evidence types separate.'],['BOUNDARY','A GRAPH DOES NOT DEFINE PEOPLE','No profiling or prediction.'],['SAVE','UNDERSTAND RELATIONSHIPS','Retain contradiction, change, and unknown.']]},
'083':{title:'Turn Real Work Into Public Proof Without Leaking the Work',proposition:'Turn real work into public proof—safely.',scenes:[['BUILD 083','WORK CONTAINS CONTENT','Extraction must not leak it.'],['FILTER','CONFIDENTIALITY. SOURCE. RIGHTS.','Admit, generalize, hold, or escalate.'],['CANDIDATES','INSIGHT. METHOD. VISUAL. TEACHING.','Only safe sources travel forward.'],['APPROVAL','EVIDENCE. CONTEXT. REVIEW STATE.','Keep publication human-controlled.'],['BOUNDARY','SAFE CANDIDATE ≠ PUBLISHED PROOF','Fictional work only.'],['SAVE','MAKE PROOF SAFELY','Retain source, rights, limits, review.']]}
};
