import Link from 'next/link';
import s from './object.module.css';

const build001={id:'001',title:'Human Review Design Framework',description:'An interactive framework for turning vague human-oversight claims into an explicit review design.',observation:'“Human in the loop” is often treated as if the presence of a person automatically creates meaningful oversight.',missing:'A practical way to specify who reviews an AI-assisted decision, what they review, against which standard, at what point, and what happens when review fails.'};

export function generateStaticParams(){return Array.from({length:100},(_,i)=>({id:String(i+1).padStart(3,'0')}));}

export default async function BuildDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;if(id!=='001')return <main className={s.page}><header className={s.mast}><Link href="/100-builds">← MAIN GALLERY</Link><span>ACCESSION {id} / 100</span></header><section className={s.planned}><div className={s.number}>PLANNED WORK</div><h1>ACCESSION<br/>{id}</h1><p>The work is held in the canonical sequence, but its A/B objects do not enter production until this cycle begins.</p></section></main>;
return <main className={s.page}><header className={s.mast}><Link href="/100-builds">← MAIN GALLERY</Link><span>ACCESSION 001 / 100 · ON VIEW</span></header><section className={s.wall}><div className={s.number}>ROOM 01<br/>WORK 001<br/>2026</div><div className={s.title}><h1>{build001.title}</h1><p>{build001.description}</p></div><aside className={s.label}>A / FUNCTIONAL SYSTEM<br/>B / VISUAL ARGUMENT<br/><br/>STATUS / ACTIVE PREVIEW<br/>PHASE / 01<br/><br/>QUESTION / WHEN IS A HUMAN ACTUALLY A CONTROL?</aside></section><section className={s.objects}><Link className={s.object} href="/100-builds/001/a"><span>OBJECT 001-A / FUNCTIONAL SYSTEM</span><h2>Human Review Design Framework</h2><p>Inspect reviewer competence, timing, evidence, authority, escalation, recordkeeping, practical capacity and control testing.</p><b>USE THE SYSTEM →</b></Link><Link className={s.object} href="/100-builds/001/b"><span>OBJECT 001-B / VISUAL ARGUMENT</span><h2>Human in the Loop</h2><p>The reassuring phrase breaks apart until the hidden architecture of meaningful review becomes visible.</p><b>ENTER SCREENING →</b></Link></section><section className={s.notes}><div><h3>Curatorial note / observation</h3><p>{build001.observation}</p></div><div><h3>The missing system</h3><p>{build001.missing}</p></div></section></main>}
