'use client';
import {useMemo,useState} from 'react';
import {assessCreatorOwnership,CREATOR_OWNERSHIP_ENGINE_VERSION,type CreatorAsset,type ControlClass,type RevocationRisk} from '../../../../../../packages/release/src/creator-ownership-engine';
import s from '../ownership.module.css';
const ev=(id:string,support:CreatorAsset['controlEvidence'][number]['supports'],locator:string)=>({id,locator,observedAt:'2026-08-19',reviewer:'Synthetic evidence reviewer',supports:support});
const seed:CreatorAsset[]=[
 {id:'AST-01',name:'Essay source files',kind:'Content archive',control:'OWN',legalBasis:'creator-origin-asserted',provider:'Creator-controlled storage',controlEvidence:[ev('CTRL-01','operational-custody','synthetic://records/source-custody')],legalEvidence:[ev('ORIGIN-01','creator-origin','synthetic://records/authorship-ledger')],exportControl:{available:true,evidence:[ev('EXPORT-01','export-test','synthetic://tests/source-export')],testedAt:'2026-08-19'},backupControl:{available:true,evidence:[ev('BACKUP-01','backup-restore','synthetic://tests/source-restore')],testedAt:'2026-08-19'},transferControl:{status:'operationally-tested',evidence:[ev('TRANSFER-01','transfer-test','synthetic://tests/source-transfer')],testedAt:'2026-08-19'},revocationRisk:'low',revocationEvidence:[],revocationConditions:'Creator controls storage credentials and local copies',revocationResponse:'Restore from independently tested backup',exitPlan:'Move the source archive to replacement creator-controlled storage',replacementChannel:'Local encrypted archive'},
 {id:'AST-02',name:'Newsletter subscriber relationship',kind:'Audience record',control:'RENT',legalBasis:'contract-right-documented',provider:'Synthetic newsletter platform',controlEvidence:[ev('CTRL-02','contractual-use','synthetic://records/newsletter-access')],legalEvidence:[ev('TERMS-02','contractual-use','synthetic://terms/newsletter-v1')],exportControl:{available:true,evidence:[ev('EXPORT-02','export-test','synthetic://tests/subscriber-export')],testedAt:'2026-08-19'},backupControl:{available:false,evidence:[],testedAt:''},transferControl:{status:'contractual-right',evidence:[ev('TRANSFER-02','contractual-use','synthetic://terms/newsletter-portability')],testedAt:''},revocationRisk:'medium',revocationEvidence:[ev('REVOKE-02','revocation-terms','synthetic://terms/newsletter-revocation')],revocationConditions:'Access may end for enumerated account or terms violations',revocationResponse:'Request export and invoke the documented account appeal route',exitPlan:'Migrate the verified export to a replacement newsletter service',replacementChannel:'Creator-controlled website and email domain'},
 {id:'AST-03',name:'Discovery reach',kind:'Distribution dependency',control:'DEPEND',legalBasis:'contract-right-documented',provider:'Synthetic social platform',controlEvidence:[ev('CTRL-03','account-access','synthetic://records/social-account-access')],legalEvidence:[ev('TERMS-03','contractual-use','synthetic://terms/social-v1')],exportControl:{available:false,evidence:[],testedAt:''},backupControl:{available:false,evidence:[],testedAt:''},transferControl:{status:'not-established',evidence:[],testedAt:''},revocationRisk:'high',revocationEvidence:[ev('REVOKE-03','revocation-terms','synthetic://terms/social-revocation')],revocationConditions:'Platform may restrict reach or terminate access under stated terms',revocationResponse:'Publish status and route audience to creator-controlled channels',exitPlan:'Shift distribution to the website, newsletter, and alternate platforms',replacementChannel:'Creator-controlled website and newsletter'}
];
const classes:ControlClass[]=['OWN','RENT','DEPEND'];const risks:RevocationRisk[]=['low','medium','high','unknown'];
export default function OwnershipLab(){
 const [assets,setAssets]=useState(seed);const input={assets,schemaVersion:'creator-ownership-map-v2',assessedAt:'2026-08-19'};const result=useMemo(()=>assessCreatorOwnership(input),[assets]);
 function update(id:string,patch:Partial<CreatorAsset>){setAssets(v=>v.map(x=>x.id===id?{...x,...patch}:x))}
 function strengthen(){setAssets(v=>v.map(x=>({...x,exportControl:{available:true,evidence:[ev(`EXPORT-${x.id}`,'export-test',`synthetic://tests/${x.id}/export`)],testedAt:'2026-08-19'},backupControl:{available:true,evidence:[ev(`BACKUP-${x.id}`,'backup-restore',`synthetic://tests/${x.id}/restore`)],testedAt:'2026-08-19'},transferControl:{status:'operationally-tested',evidence:[ev(`TRANSFER-${x.id}`,'transfer-test',`synthetic://tests/${x.id}/transfer`)],testedAt:'2026-08-19'},revocationResponse:x.revocationResponse||'Pause use, preserve records, invoke review, and shift to the recovery channel',exitPlan:x.exitPlan||'Use the tested export and restoration path to leave the provider',replacementChannel:x.replacementChannel||'Creator-controlled website'})))}
 function download(){const report={build:'027',schema:'creator-ownership-stack',version:CREATOR_OWNERSHIP_ENGINE_VERSION,fixture:'synthetic',generatedInBrowser:true,canonical:{title:'Creator Ownership Stack Mapper',job:'Show what a creator or founder owns, rents, depends on, licenses or could lose across platforms and assets.',bWeb:'Drag assets across OWN, RENT and DEPEND and watch exposure recalculate.',uses:['010','011'],creates:['cap:027']},input,result,semantics:{controlClass:'Operational relationship only; OWN does not establish legal title.',legalBasis:'Evidence state only; no contract or IP conclusion.',score:'Derived dependency-recovery index, not probability, value, or legal risk.'},privacy:'No data is transmitted or stored. Do not enter credentials, contracts, subscriber data, or confidential records.',boundary:'Inventory heuristic only; not legal ownership, IP clearance, contract interpretation, portability, continuity, or valuation.'};const href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=href;a.download='creator-ownership-stack.json';a.click();setTimeout(()=>URL.revokeObjectURL(href),0)}
 return <section className={s.lab}><header role="status" aria-live="polite" aria-atomic="true"><span>OWNERSHIP STACK / {assets.length} RELATIONSHIPS</span><h2>{result.status}</h2><p>{result.exposures.filter(x=>x.tier==='CRITICAL').length} critical · {result.exposures.filter(x=>x.tier==='EXPOSED').length} exposed · {result.exposures.filter(x=>x.tier==='UNRESOLVED').length} unresolved</p></header>
 <div className={s.actions}><button className={s.primary} onClick={strengthen}>RECORD SYNTHETIC RECOVERY TESTS</button><button onClick={()=>setAssets(seed)}>RESET</button><button onClick={download}>EXPORT OWNERSHIP MAP</button></div>
 <div className={s.assets} role="list" aria-label="Creator asset relationships">{assets.map(asset=>{const exposure=result.exposures.find(x=>x.id===asset.id)!;return <article key={asset.id} role="listitem"><small>{asset.id} / {asset.kind}</small><h3>{asset.name}</h3><div className={s.classify} aria-label={`${asset.name} operational control class`}>{classes.map(c=><button key={c} aria-label={`Classify ${asset.name} operationally as ${c}`} aria-pressed={asset.control===c} onClick={()=>update(asset.id,{control:c})}>{c}</button>)}</div><p><b>Operational custodian/provider:</b> {asset.provider}</p><p><b>Legal basis state:</b> {asset.legalBasis.replaceAll('-',' ')}</p><p><b>Control evidence:</b> {asset.controlEvidence.map(x=>`${x.id} (${x.supports})`).join(', ')||'Not attached'}</p><label><input type="checkbox" checked={asset.exportControl.available} onChange={e=>update(asset.id,{exportControl:{...asset.exportControl,available:e.target.checked}})}/> Usable export claimed</label><label><input type="checkbox" checked={asset.backupControl.available} onChange={e=>update(asset.id,{backupControl:{...asset.backupControl,available:e.target.checked}})}/> Restorable backup claimed</label><label>Revocation exposure<select value={asset.revocationRisk} onChange={e=>update(asset.id,{revocationRisk:e.target.value as RevocationRisk})}>{risks.map(r=><option key={r}>{r}</option>)}</select></label><div className={s.exposure}><b>{exposure.tier}</b><span>DEPENDENCY INDEX {exposure.score}</span></div>{exposure.reasons.length?<ul>{exposure.reasons.map(x=><li key={x}>{x}</li>)}</ul>:<p>No open exposure under this derived fixture.</p>}</article>})}</div>
 <section className={s.findings}><h3>Portfolio boundary</h3>{[...result.blocking,...result.portfolioRisks].length?<ul>{[...result.blocking,...result.portfolioRisks].map(x=><li key={x}>{x}</li>)}</ul>:<p>No open portfolio risk under this derived fixture.</p>}</section>
 <p className={s.note}><b>Boundary:</b> OWN, RENT, and DEPEND describe operational relationships, not legal title. Legal basis states record evidence posture, not a legal conclusion. All records are synthetic and client-local; enter no real account, contract, credential, subscriber, or confidential information.</p></section>
}
