'use client';
import {useState} from 'react';
import s from './governed-loop.module.css';
type Scenario='ONE-WAY'|'PARTIAL'|'GOVERNED'|'URGENT CORRECTION';
const scenarios:Scenario[]=['ONE-WAY','PARTIAL','GOVERNED','URGENT CORRECTION'];
const stages=['CAPTURE','QUALIFY','ROUTE','HUMAN DECIDE','CHANGE','VALIDATE','COMMUNICATE','MONITOR'] as const;
const copy:Record<Scenario,{status:string;active:number;note:string;urgent?:boolean}>={
'ONE-WAY':{status:'THE PRODUCT SHIPS. NOTHING RETURNS.',active:0,note:'Delivery is visible; use, outcomes, corrections and unmet needs have no accountable return path.'},
'PARTIAL':{status:'SIGNALS ARRIVE. AUTHORITY IS UNCLEAR.',active:3,note:'Feedback is captured and routed, but the person reviewing it lacks a complete evidence, authority, validation and communication contract.'},
'GOVERNED':{status:'THE LOOP CLOSES—WITH CONTROLS.',active:8,note:'Signals reach a named human control, changes are validated and communicated, and outcomes return to monitoring.'},
'URGENT CORRECTION':{status:'CORRECTION PAUSES THE ORDINARY QUEUE.',active:8,note:'A high-consequence correction routes directly to human triage, with pause, escalation, validation and notification visible.',urgent:true}
};
export default function GovernedLoopField(){const[scenario,setScenario]=useState<Scenario>('ONE-WAY');const state=copy[scenario];return <div className={s.app}><div className={s.controls} role="group" aria-label="Learning loop scenario">{scenarios.map(x=><button key={x} aria-pressed={scenario===x} onClick={()=>setScenario(x)}>{x}</button>)}</div><section className={s.field} data-urgent={!!state.urgent} aria-live="polite"><header><span>LOOP STATE / {scenario}</span><h2>{state.status}</h2><p>{state.note}</p></header><div className={s.loop} aria-label={scenario+' product learning loop'}><div className={s.product}><span>PRODUCT</span><strong>DELIVER</strong></div><div className={s.stages}>{stages.map((stage,index)=><article key={stage} data-active={index<state.active} data-human={stage==='HUMAN DECIDE'}><small>{String(index+1).padStart(2,'0')}</small><h3>{stage}</h3><p>{stage==='CAPTURE'?'Use · outcome · correction · unmet need':stage==='QUALIFY'?'Purpose · consent · consequence':stage==='ROUTE'?'Owner · urgency · affected group':stage==='HUMAN DECIDE'?'Evidence · authority · pause · record':stage==='CHANGE'?'Bounded improvement':stage==='VALIDATE'?'Test · compare · rollback':stage==='COMMUNICATE'?'Tell affected people':'Observe outcomes again'}</p></article>)}</div><div className={s.return} data-closed={state.active===8}><span>{state.active===8?'OUTCOMES RETURN TO THE PRODUCT':'RETURN PATH OPEN'}</span></div></div></section><section className={s.argument}><span>THE POINT</span><h2>Collection is not learning.</h2><p>A product learns only when multiple kinds of feedback can reach a person with evidence, authority, capacity and a safe route to validate and communicate change. A closed arrow without those controls is decoration.</p></section></div>}
