import Link from 'next/link';
import styles from './lab.module.css';

export default function Home(){return <div className={styles.page}><div className={styles.topography}/><header className={styles.top}><Link className={styles.brand} href="/">RN / SYSTEMS ATLAS</Link><nav><Link href="/100-builds">THE 100</Link><Link href="/100-builds/001/b">VISUAL BUILDS</Link><a href="#practice">PRACTICE</a></nav></header><main>
<section className={styles.hero}><div className={styles.heroGrid}><div className={styles.kicker}>PUBLIC ENGINEERING LAB · HONOLULU</div><h1>MAP THE<br/><span>INVISIBLE.</span></h1><p>I build systems for questions that sit between fields — AI × law × neuroscience × governance × place × independent work.</p><div className={styles.actions}><Link href="/100-builds">EXPLORE THE 100</Link><Link href="/100-builds/001/b">PLAY BUILD 001-B</Link></div></div><div className={styles.orbit}><div className={styles.core}>RN</div><span className={styles.o1}>AI</span><span className={styles.o2}>LAW</span><span className={styles.o3}>NEURO</span><span className={styles.o4}>PLACE</span><span className={styles.o5}>GOVERNANCE</span></div></section>
<section className={styles.ticker}><span>BUILD → REVEAL → REUSE → COMPOUND</span><span>100 FUNCTIONAL SYSTEMS</span><span>100 VISUAL SYSTEMS</span><span>1 LIVING LINEAGE</span></section>
<section className={styles.atlas}><div className={styles.atlasIntro}><span>ATLAS / 001</span><h2>Three ways into the work.</h2></div><div className={styles.routes}><Link href="/100-builds" className={styles.route}><b>01</b><h3>THE 100</h3><p>Move from small deterministic tools to integrated intelligence systems. Complexity rises on purpose.</p><i>SEQUENCE ↗</i></Link><Link href="/100-builds/001/b" className={styles.route}><b>02</b><h3>VISUAL BUILDS</h3><p>Ideas become motion, maps, data, diagrams, interaction, footage, and creative code.</p><i>VISUAL LANGUAGE ↗</i></Link><Link href="/100-builds/001" className={styles.route}><b>03</b><h3>LINEAGE</h3><p>Every build leaves behind infrastructure. Later systems inherit it visibly.</p><i>DEPENDENCY MAP ↗</i></Link></div></section>
<section className={styles.practice} id="practice"><div><span>PRACTICE</span><h2>Not a portfolio of outcomes.<br/>A map of how I think.</h2></div><div className={styles.practiceCopy}><p>Systems architecture, AI implementation, research infrastructure, legal-tech thinking, governance design, human-centered product work, and experimental communication — connected rather than siloed.</p><a href="mailto:hello@rncollins.com">START A CONVERSATION ↗</a></div></section>
</main><footer><span>RN COLLINS</span><span>SYSTEMS ATLAS</span><span>2026—</span></footer></div>}
