'use client';
import{useState}from'react';
import{buildPsychedelicCareContinuityRecord,CARE_CONTINUITY_SCENARIOS,CARE_CONTINUITY_ENGINE_VERSION,type ScenarioId}from'../../../../../../packages/release/src/psychedelic-care-continuity-engine';
import s from'../continuity.module.css';

const ids:ScenarioId[]=['CONTINUITY-CURRENT','HANDOFF-UNACCEPTED','PERMISSION-WITHDRAWN','FOLLOWUP-OVERDUE','CRISIS-OUTSIDE-SCOPE'];
const label=(value:string)=>value.replaceAll('-',' ');

export default function CareContinuityRecord(){
  const[id,setId]=useState<ScenarioId>('CONTINUITY-CURRENT'),input=CARE_CONTINUITY_SCENARIOS[id],result=buildPsychedelicCareContinuityRecord(input);
  const groups=[['EPISODE',result.episode],['BOUNDARIES',result.boundaries],['HANDOFFS',result.handoffs],['PERMISSIONS',result.permissions],['FOLLOWUPS',result.followups],['ACCOUNTABILITY',result.accountability],['SAFETY',result.safety],['CHANGES',result.changes],['PORTABILITY',result.portability],['RESILIENCE',result.resilience]]as const;
  function download(){const snapshot={build:'065',version:CARE_CONTINUITY_ENGINE_VERSION,fixture:'synthetic',exportedAt:new Date().toISOString(),canonical:{title:'Psychedelic Care Continuity Record',visualTitle:'The Care Does Not End When the Session Does',uses:['017','023','029','035','036'],creates:'cap:065'},privacy:{fixture:'SYNTHETIC ONLY',containsRealPeople:false,containsHealthData:false,persistence:'NONE'},input:structuredClone(input),result:structuredClone(result),replay:{engineVersion:CARE_CONTINUITY_ENGINE_VERSION,scenarioId:id,validation:'RECURSIVE EXACT SERIALIZATION-FREE'},exportDisposition:id==='PERMISSION-WITHDRAWN'?'HOLD — PERMISSION REVIEW':id==='CRISIS-OUTSIDE-SCOPE'?'NOT AN EMERGENCY RECORD OR RESPONSE SYSTEM':'FIXED SYNTHETIC DEMONSTRATION ONLY',boundaries:['Synthetic records only; no real person, patient, participant, provider, substance, treatment, diagnosis, risk assessment, referral, or clinical recommendation.','This record is not medical advice, clinical care, crisis response, emergency monitoring, diagnosis, treatment, or proof that any handoff occurred.','A permission state is not proof of consent validity, capacity, identity, authorization, or lawful basis.']};const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='synthetic-psychedelic-care-continuity-record.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
  return <section className={s.lab} aria-labelledby="continuity-status" data-continuity-state={id}>
    <header className={s.status} role="status" aria-live="polite" aria-atomic="true"><small>CONTINUITY STATE · {label(id)}</small><h2 id="continuity-status">{result.status}</h2><p>{result.handoffs[0]??result.followups[0]??'No open continuity action is recorded in this fixed state.'}</p></header>
    <div className={s.controls} aria-label="Continuity record controls"><label htmlFor="continuity-state">CONTINUITY STATE<select id="continuity-state" value={id} onChange={event=>setId(event.target.value as ScenarioId)}>{ids.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><button type="button" onClick={()=>setId('CONTINUITY-CURRENT')}>RESTORE RECORDED PATHWAY</button><button type="button" onClick={download}>EXPORT CONTINUITY RECORD</button></div>
    <aside className={s.emergency} aria-label="Emergency and crisis limitation"><h3>This is not emergency or crisis support.</h3><p>If someone may be in immediate danger, experiencing a medical emergency, or unable to remain safe, contact local emergency services or an appropriate crisis service now. Do not wait for this record, an alert, a referral state, or a handoff status.</p></aside>
    <div className={s.boundaryGrid} aria-label="Continuity record boundaries"><article><small>NOT CARE</small><p>A record does not assess, diagnose, monitor, treat, prescribe, or replace a qualified professional.</p></article><article><small>CONSENT</small><p>FICTIONAL POLICY RULE: record a declared permission state for each purpose, recipient, field and transfer. Any real consent validity or legal effect is unknown.</p></article><article><small>FICTIONAL FIELD MINIMIZATION</small><p>FICTIONAL FIELD-MINIMIZATION RULE: expose only fields declared necessary by this fixture. This is not a HIPAA or legal minimum-necessary determination.</p></article><article><small>HANDOFF</small><p>FICTIONAL STATE MODEL: sent, received, accepted, scheduled and completed remain distinct. These states do not prove continuity or assign real professional responsibility.</p></article></div>
    <div className={s.record} aria-label="Consent-governed synthetic continuity record">{groups.map(([title,items])=><article key={title} data-record-kind={title.toLowerCase()}><small>{title}</small>{items.length?<ul>{items.map(item=><li key={item}>{item}</li>)}</ul>:<p>None recorded.</p>}</article>)}</div>
    <aside className={s.provenance} aria-label="Continuity provenance"><h3>Recorded provenance</h3><ul>{result.provenance.map(item=><li key={item}>{item}</li>)}</ul></aside><aside className={s.unknowns} aria-label="Continuity unknowns"><h3>What this record does not know</h3><ul>{result.unknowns.map(item=><li key={item}>{item}</li>)}</ul></aside>
    <p className={s.note}><b>Boundary:</b> This fixed fictional record demonstrates interface states only. It is not a medical record, clinical workflow, emergency service, care standard, consent determination, disclosure authorization, professional-duty allocation, diagnosis, treatment recommendation, risk determination, provider verification, or completed referral.</p>
  </section>
}
