import {test,expect} from '@playwright/test';

const ids=['001','002','003','004','005','006'];

test.describe('001–006 durable archive backfill',()=>{
 test('program archive declares the website system-of-record policy',async({page})=>{await page.goto('/100-builds/archive');await expect(page.getByRole('heading',{name:'THE WORK DOES NOT LIVE IN CHAT.'})).toBeVisible();await expect(page.getByText(/Every numbered cycle should retain/i)).toBeVisible();for(const id of ids)await expect(page.getByRole('link',{name:new RegExp(`BUILD ${id}`)})).toBeVisible();});
 for(const id of ids)test(`Build ${id} archive preserves all durable record classes and downloadable film`,async({page,request})=>{await page.goto(`/100-builds/${id}/archive`);await expect(page.getByText('CHAT-INDEPENDENCE RULE')).toBeVisible();for(const label of ['01 / RESEARCH + EVIDENCE','02 / CREATED','03 / ARCHITECTURE + DECISIONS','04 / AUDIT + RELEASE','05 / PLANS + OPEN THREADS','06 / MEDIA','07 / CANONICAL SOURCE INVENTORY'])await expect(page.getByText(label,{exact:true})).toBeVisible();await expect(page.locator('code').first()).toBeVisible();const download=page.getByRole('link',{name:'DOWNLOAD MP4 ↓'});await expect(download).toHaveAttribute('href',`/media/builds/${id}/build-${id}-linkedin.mp4`);await expect(page.getByLabel(`Build ${id} LinkedIn film preview`)).toBeVisible();const media=await request.get(`/media/builds/${id}/build-${id}-linkedin.mp4`);expect(media.status()).toBe(200);expect(media.headers()['content-type']).toContain('video/mp4');expect((await media.body()).byteLength).toBeGreaterThan(1000);const poster=await request.get(`/media/builds/${id}/build-${id}-linkedin-poster.png`);expect(poster.status()).toBe(200);expect(poster.headers()['content-type']).toContain('image/png');});
 test('005 and 006 render as real lab rooms with working A/B/archive/media routes',async({page})=>{for(const id of ['005','006']){await page.goto(`/100-builds/${id}`);await expect(page.getByText(new RegExp(`BUILD ${id} / 100 · IN THE LAB`))).toBeVisible();await expect(page.getByRole('link',{name:/OPEN THE TOOL/})).toHaveAttribute('href',`/100-builds/${id}/a`);await expect(page.getByRole('link',{name:/ENTER THE VISUAL BUILD/})).toHaveAttribute('href',`/100-builds/${id}/b`);await expect(page.getByRole('link',{name:/Research \+ creation \+ decisions \+ audits \+ plans/})).toHaveAttribute('href',`/100-builds/${id}/archive`);await expect(page.getByRole('link',{name:/Take the 4:5 film/})).toHaveAttribute('href',`/media/builds/${id}/build-${id}-linkedin.mp4`);}});
 test('allowlisted full records are readable on the website',async({page})=>{await page.goto('/100-builds/archive/source/docs/build-release-standard-v1.md');await expect(page.getByText('FULL ARCHIVE RECORD')).toBeVisible();await expect(page.locator('pre')).toContainText('Archive-completeness gate');await expect(page.locator('pre')).toContainText('B-LinkedIn gate');});
 test('non-allowlisted records cannot be read through the archive reader',async({request})=>{const response=await request.get('/100-builds/archive/source/package.json');expect(response.status()).toBe(404);});
 for(const route of ['/100-builds/archive','/100-builds/001/archive','/100-builds/006/archive','/100-builds/archive/source/docs/build-release-standard-v1.md'])test(`${route} remains usable at 320px`,async({page})=>{await page.setViewportSize({width:320,height:900});await page.goto(route);const g=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(g.scroll-g.client,`${route}: ${JSON.stringify(g)}`).toBeLessThanOrEqual(1);});
});
