import {test,expect} from '@playwright/test';

test.describe('Build 004 B-Web intelligence chain',()=>{
 test.beforeEach(async({page})=>{await page.goto('/100-builds/004/b');await expect(page.getByRole('group',{name:'Intelligence chain stages'})).toBeVisible()});
 test('starts at raw material and exposes every stage as a named control',async({page})=>{await expect(page.getByRole('button',{name:/RAW/})).toHaveAttribute('aria-pressed','true');for(const name of ['COLLECT','SEPARATE','VERIFY','BRIEF'])await expect(page.getByRole('button',{name:new RegExp(name)})).toBeVisible();await expect(page.getByRole('heading',{name:'A pile of sources'})).toBeVisible()});
 test('collect reveals inspectable provenance fields',async({page})=>{await page.getByRole('button',{name:/COLLECT/}).click();await expect(page.getByRole('heading',{name:'Give every source a provenance record'})).toBeVisible();await expect(page.getByText('checked date').first()).toBeVisible();await expect(page.getByText('section / page').first()).toBeVisible()});
 test('separate makes source record and analyst claim visibly non-equivalent',async({page})=>{await page.getByRole('button',{name:/SEPARATE/}).click();await expect(page.getByText('SOURCE RECORD',{exact:true})).toBeVisible();await expect(page.getByText('ANALYST CLAIM',{exact:true})).toBeVisible();await expect(page.getByText('≠')).toBeVisible()});
 test('verify preserves four named evidence states',async({page})=>{await page.getByRole('button',{name:/VERIFY/}).click();for(const state of ['VERIFIED','CONTRADICTED','UNCERTAIN','UNVERIFIED'])await expect(page.getByText(state,{exact:true})).toBeVisible();await expect(page.getByText('note required')).toBeVisible()});
 test('brief keeps verified findings distinct from unresolved material',async({page})=>{await page.getByRole('button',{name:/BRIEF/}).click();for(const bucket of ['VERIFIED FINDINGS','CONTRADICTIONS','UNCERTAINTY','OPEN QUESTIONS'])await expect(page.getByText(bucket,{exact:true})).toBeVisible();await expect(page.getByText('decision-ready')).toBeVisible();await expect(page.getByText('preserved, not erased').first()).toBeVisible()});
 test('passive path states the complete method without interaction',async({page})=>{await expect(page.getByText(/collect the evidence, separate it from interpretation, verify the claim, then brief only what the record can support/i)).toBeVisible();await expect(page.getByRole('region',{name:'Passive intelligence-chain summary'})).toBeVisible()});
});
