import {test,expect} from '@playwright/test';

test.describe('Build 004 manual intelligence invariants',()=>{
 test.beforeEach(async({page})=>{await page.goto('/100-builds/004/a');await expect(page.getByRole('heading',{name:'Manual Intelligence Engine Method'})).toBeVisible()});
 test('unverified claim never appears as a verified finding',async({page})=>{await expect(page.getByText('No verified findings yet.')).toBeVisible();await expect(page.getByText('This is a demonstration claim and is not verified evidence.')).toBeVisible();const verifiedPanel=page.getByRole('heading',{name:'Verified findings'}).locator('..');await expect(verifiedPanel).not.toContainText('This is a demonstration claim and is not verified evidence.')});
 test('verified is unavailable until the reviewer records what they checked',async({page})=>{const status=page.getByLabel('Status for claim 1');await expect(status.locator('option[value="verified"]')).toBeDisabled();await expect(status).toHaveValue('unverified')});
 test('human verification with a recorded note promotes a claim into findings',async({page})=>{await page.getByLabel('Verification note for claim 1').fill('Checked the source text against the claim and recorded the relevant passage.');await page.getByLabel('Status for claim 1').selectOption('verified');const verifiedPanel=page.getByRole('heading',{name:'Verified findings'}).locator('..');await expect(verifiedPanel).toContainText('This is a demonstration claim and is not verified evidence.');await expect(page.getByText('No verified findings yet.')).toHaveCount(0)});
 test('clearing the verification note demotes a verified claim',async({page})=>{const note=page.getByLabel('Verification note for claim 1');await note.fill('Checked against source.');await page.getByLabel('Status for claim 1').selectOption('verified');await note.fill('');await expect(page.getByLabel('Status for claim 1')).toHaveValue('unverified');await expect(page.getByRole('heading',{name:'Verified findings'}).locator('..')).not.toContainText('This is a demonstration claim and is not verified evidence.')});
 test('contradicted claim is preserved separately rather than flattened into findings',async({page})=>{await page.getByLabel('Status for claim 1').selectOption('contradicted');const contradictionPanel=page.getByRole('heading',{name:'Contradictions'}).locator('..');const verifiedPanel=page.getByRole('heading',{name:'Verified findings'}).locator('..');await expect(contradictionPanel).toContainText('This is a demonstration claim and is not verified evidence.');await expect(verifiedPanel).not.toContainText('This is a demonstration claim and is not verified evidence.')});
 test('removing a source removes claims that depend on it',async({page})=>{await page.getByRole('button',{name:'Remove Example primary source'}).click();await expect(page.getByText('Add at least one source before creating a claim.')).toBeVisible();await expect(page.getByText(/0 TOTAL · 0 VERIFIED/)).toBeVisible();await expect(page.getByText('This is a demonstration claim and is not verified evidence.')).toHaveCount(0)});
 test('a new claim enters the queue unverified',async({page})=>{await page.getByLabel('Analyst claim').fill('A newly collected assertion.');await page.getByRole('button',{name:'ADD TO QUEUE'}).click();await expect(page.getByText('A newly collected assertion.')).toBeVisible();await expect(page.getByLabel('Status for claim 2')).toHaveValue('unverified')});
 test('a source cannot enter the register without a checked date',async({page})=>{await page.getByRole('button',{name:'RESET / START OVER'}).click();await page.getByLabel('Source title').fill('New source');await page.getByRole('button',{name:'ADD SOURCE'}).click();await expect(page.getByText('Add at least one source before creating a claim.')).toBeVisible();await page.getByLabel('Checked or retrieved date').fill('2026-08-15');await page.getByRole('button',{name:'ADD SOURCE'}).click();await expect(page.getByRole('heading',{name:'New source'})).toBeVisible();await expect(page.getByText('checked: 2026-08-15')).toBeVisible()});
 test('explicit provenance fields survive into the source record',async({page})=>{await page.getByRole('button',{name:'RESET / START OVER'}).click();await page.getByLabel('Source title').fill('Source with provenance');await page.getByLabel('Issuer or author').fill('Issuing body');await page.getByLabel('Publication or version').fill('v2.1');await page.getByLabel('Source date').fill('2026-08-01');await page.getByLabel('Checked or retrieved date').fill('2026-08-15');await page.getByLabel('Relevant section page or locator').fill('Section 4, p. 18');await page.getByRole('button',{name:'ADD SOURCE'}).click();const card=page.getByRole('heading',{name:'Source with provenance'}).locator('..').locator('..');await expect(card).toContainText('issuer: Issuing body');await expect(card).toContainText('version: v2.1');await expect(card).toContainText('source: 2026-08-01');await expect(card).toContainText('checked: 2026-08-15');await expect(card).toContainText('locator: Section 4, p. 18')});
 test('extreme unbroken user strings do not create horizontal overflow at 320px',async({page})=>{await page.setViewportSize({width:320,height:800});await page.getByRole('button',{name:'RESET / START OVER'}).click();const long='X'.repeat(240);await page.getByLabel('Source title').fill(long);await page.getByLabel('Issuer or author').fill(long);await page.getByLabel('Relevant section page or locator').fill(long);await page.getByLabel('Checked or retrieved date').fill('2026-08-15');await page.getByRole('button',{name:'ADD SOURCE'}).click();await page.getByLabel('Analyst claim').fill(long);await page.getByRole('button',{name:'ADD TO QUEUE'}).click();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1)});
 test('reset start over clears sources claims and derived brief',async({page})=>{await page.getByRole('button',{name:'RESET / START OVER'}).click();await expect(page.getByText(/0 TOTAL · 0 VERIFIED/)).toBeVisible();await expect(page.getByText('Add at least one source before creating a claim.')).toBeVisible();await expect(page.getByText('No verified findings yet.')).toBeVisible();await expect(page.getByText('This is a demonstration claim and is not verified evidence.')).toHaveCount(0)});
 test('the interface states its verification boundary',async({page})=>{await expect(page.getByText(/does not verify a source for you/i)).toBeVisible();await expect(page.getByText(/records what they checked and explicitly marks it verified/i)).toBeVisible()});
});
