import {test,expect} from '@playwright/test';
import {REPORTING_INFRASTRUCTURE_PRESETS,REPORTING_PACKETS,extractReportingInfrastructure} from '../packages/release/src/journalism-to-infrastructure-engine';

test('080 preserves exactly five packets with five sources, assets, and queued opportunities each',()=>{expect(REPORTING_PACKETS.map(x=>x.id)).toEqual(['REPORT-CEDAR','REPORT-HARBOR','REPORT-LATTICE','REPORT-MESA','REPORT-ORBIT']);for(const packet of REPORTING_PACKETS){expect(packet.sources.map(x=>x.kind)).toEqual(['PUBLISHED-STORY','INTERVIEW-NOTE','FIELD-OBSERVATION','PUBLIC-RECORD','READER-QUESTION']);expect(packet.assets.map(x=>x.kind)).toEqual(['DATASET','TOOL','TRACKER','TIMELINE','PUBLIC-RESOURCE']);expect(packet.opportunities).toHaveLength(5);expect(packet.opportunities.every(x=>x.priority==='UNASSESSED'&&x.decision==='HUMAN-REVIEW-REQUIRED')).toBeTruthy();expect(packet.assets.every(x=>x.status==='CANDIDATE-NOT-PUBLISHED')).toBeTruthy()}});

test('080 deterministically preserves provenance, source links, rights, limitations, gaps, and unknowns',()=>{const result=extractReportingInfrastructure(REPORTING_INFRASTRUCTURE_PRESETS['REPORT-CEDAR']);expect(result.pipeline.sourceIds).toHaveLength(5);expect(result.pipeline.assetIds).toHaveLength(5);expect(result.pipeline.opportunityIds).toHaveLength(5);expect(result.pipeline.edges.filter(x=>x.relation==='SUPPORTS')).toHaveLength(25);expect(result.pipeline.edges.filter(x=>x.relation==='ENTERS-QUEUE')).toHaveLength(5);expect(result.packet?.sources.every(x=>x.rightsStatus==='FICTIONAL-CLEARED'&&x.confidentiality==='PUBLIC-SYNTHETIC')).toBeTruthy();expect(result.packet?.assets.every(x=>x.sourceIds.length===5&&x.limitations.length>0)).toBeTruthy();expect(result.packet?.opportunities.every(x=>x.evidenceGap.length>0)).toBeTruthy();expect(result.packet?.unknowns.length).toBeGreaterThan(0);expect(result.audit).toContain('NO PUBLICATION, PRIORITIZATION, CLAIM VERIFICATION, OR REAL-WORLD INFERENCE')});

test('080 fails closed on drifted, real, publishing-authorized, rights-bearing, and hostile input',()=>{const fixture=REPORTING_INFRASTRUCTURE_PRESETS['REPORT-CEDAR'];expect(extractReportingInfrastructure(fixture)).toEqual(extractReportingInfrastructure(fixture));const hostile={...fixture};Object.defineProperty(hostile,'packets',{get(){throw new Error('hostile')}});const values=[null,undefined,[],{},'story',{...fixture,fixtureId:'REAL'},{...fixture,reportId:'OTHER'},{...fixture,extra:true},{...fixture,admission:{...fixture.admission,realPeopleData:true}},{...fixture,admission:{...fixture.admission,publishingAuthorized:true}},{...fixture,admission:{...fixture.admission,rightsClearedForRealUse:true}},{...fixture,inherited:{...fixture.inherited,contentProvenance:'cap:999'}},{...fixture,packets:[...fixture.packets,fixture.packets[0]]},hostile,new Proxy(fixture,{get(){throw new Error('proxy')}})];for(const value of values){expect(()=>extractReportingInfrastructure(value)).not.toThrow();const result=extractReportingInfrastructure(value);expect(result.status).toBe('INVALID');expect(result.packet).toBeNull();expect(result.pipeline).toEqual({sourceIds:[],assetIds:[],opportunityIds:[],edges:[]})}});

test('080-A exports exact admission, artifacts, lineage, and replay',async({page})=>{await page.goto('/100-builds/080/a');await page.getByLabel('REPORTING PACKET').selectOption('REPORT-ORBIT');await expect(page.getByRole('heading',{name:'REPORT-ORBIT INFRASTRUCTURE PIPELINE'})).toBeVisible();const event=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT INFRASTRUCTURE PACKET'}).click();const download=await event;expect(download.suggestedFilename()).toBe('synthetic-reporting-infrastructure-packet.json');const parsed=JSON.parse(await (await import('node:fs/promises')).readFile(await download.path() as string,'utf8'));expect(parsed.version).toBe('080.1.0');expect(parsed.canonical).toEqual({uses:['057','058','062','063'],creates:'cap:080'});expect(parsed.artifacts).toEqual(['Reporting Asset Extractor','Infrastructure Opportunity Queue']);expect(parsed.admission).toEqual({syntheticReportingOnly:true,exactPacketCount:5,exactSourcesPerPacket:5,exactAssetsPerPacket:5,fixedSourcesOnly:true,sourceProvenanceRightsDatesPreserved:true,assetSourceLinksLimitationsPreserved:true,opportunityGapsUnknownsHumanReviewPreserved:true,containsRealPeopleData:false,containsConfidentialData:false,publishingAuthorized:false,rightsClearedForRealUse:false,factualClaim:false,legalAdvice:'NONE',clinicalAdvice:'NONE',priorityDetermined:false,failClosed:true});expect(parsed.replay).toEqual({reportId:'REPORT-ORBIT',engineVersion:'080.1.0'});});

test('080 exposes reporting and rights boundaries, contains at 320px, and B unfolds the pipeline',async({page})=>{await page.goto('/100-builds/080/a');await expect(page.getByText('no real people',{exact:false}).first()).toBeVisible();await expect(page.getByText('publication',{exact:false}).first()).toBeVisible();await page.setViewportSize({width:320,height:760});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();await page.goto('/100-builds/080/b');await page.getByRole('button',{name:'UNFOLD STORY'}).click();await expect(page.getByRole('status')).toContainText('One story became a sourced infrastructure pipeline');});
