import {test,expect} from '@playwright/test';
test.describe('Build 024 privacy minimization engine',()=>{
 test('removes optional and prohibited collection without claiming compliance',async({page})=>{await page.goto('/100-builds/024/a');await expect(page.getByRole('heading',{name:'OVER-COLLECTING'})).toBeVisible();await page.getByRole('button',{name:'REMOVE OPTIONAL + PROHIBITED'}).click();await expect(page.getByRole('heading',{name:'CONTROL CHECK PASSED'})).toBeVisible();await expect(page.getByText(/not a legal or factual verification/i)).toBeVisible()});
 test('shows inspectable necessity and counterfactual evidence',async({page})=>{await page.goto('/100-builds/024/a');await expect(page.getByText('TEST-024-01 no-address delivery counterfactual')).toBeVisible();await expect(page.getByText(/Without a destination/)).toBeVisible()});
 test('matches sensitive permission to a purpose identifier',async({page})=>{await page.goto('/100-builds/024/a');await expect(page.getByText('granted · PUR-ELIGIBILITY')).toBeVisible();await expect(page.getByText('granted · PUR-PRIORITY')).toBeVisible()});
 test('restoring prohibited data restores over-collection',async({page})=>{await page.goto('/100-builds/024/a');await page.getByRole('button',{name:'REMOVE OPTIONAL + PROHIBITED'}).click();await page.getByRole('listitem').filter({hasText:'DAT-05'}).getByRole('button',{name:'EXCLUDED — RESTORE'}).click();await expect(page.getByRole('heading',{name:'OVER-COLLECTING'})).toBeVisible();await expect(page.getByText(/DAT-05: prohibited data/)).toBeVisible()});
 test('exports locally with explicit assurance boundary',async({page})=>{await page.goto('/100-builds/024/a');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT MINIMIZATION PLAN'}).click();const download=await dl;expect(download.suggestedFilename()).toBe('data-minimization-plan.json');const body=JSON.parse(await (await import('node:fs/promises')).readFile(await download.path() as string,'utf8'));expect(body.version).toBe('024.2.0');expect(body.limitations).toHaveLength(3);expect(body.boundary).toContain('not proof')});
 test('fits 320px',async({page})=>{await page.setViewportSize({width:320,height:800});await page.goto('/100-builds/024/a');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)});
 test('B advances accessibly',async({page})=>{await page.goto('/100-builds/024/b');await page.getByRole('button',{name:'RUN THE NEXT MINIMIZATION PASS'}).click();await expect(page.getByRole('status')).toContainText('PURPOSE TEST')});
});
