import {test,expect} from '@playwright/test';
async function range(page:any,label:string,value:number){await page.getByLabel(label).evaluate((el:HTMLInputElement,v)=>{el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}));},value)}
test.describe('Build 006 software-worthiness gates',()=>{
 test('default candidate exposes bounded form and decision-gap inheritance',async({page})=>{await page.goto('/100-builds/006/a');await expect(page.getByText('CANDIDATE FORM')).toBeVisible();await expect(page.getByText(/Inherited decision-gap signal/)).toBeVisible();await expect(page.getByText(/does not prove product-market fit/i)).toBeVisible();});
 test('weak value keeps an idea simple even if software looks attractive',async({page})=>{await page.goto('/100-builds/006/a');await range(page,'How much useful value does solving it create?',1);await expect(page.locator('section').filter({hasText:'CANDIDATE FORM'}).getByRole('heading',{name:'KEEP SIMPLE'})).toBeVisible();});
 test('expert judgment with weak software advantage points to service',async({page})=>{await page.goto('/100-builds/006/a');await range(page,'How much expert judgment remains central?',5);await range(page,'How much better is software than a simple template/process?',2);await expect(page.locator('section').filter({hasText:'CANDIDATE FORM'}).getByRole('heading',{name:'SERVICE'})).toBeVisible();});
 test('strong data asset with weak software advantage can point to dataset',async({page})=>{await page.goto('/100-builds/006/a');await range(page,'How much expert judgment remains central?',2);await range(page,'Does repeated use create a durable data/evidence asset?',5);await range(page,'How much better is software than a simple template/process?',2);await expect(page.locator('section').filter({hasText:'CANDIDATE FORM'}).getByRole('heading',{name:'DATASET'})).toBeVisible();});
 test('export is explicit and local',async({page})=>{await page.goto('/100-builds/006/a');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT RECORD'}).click();await dl;});
});
