import {test,expect} from '@playwright/test';
test.describe('Build 007 feedback loop architecture',()=>{
 test('default demo closes a governed loop through Build 001 control inheritance',async({page})=>{await page.goto('/100-builds/007/a');await expect(page.getByRole('heading',{name:'GOVERNED LOOP'})).toBeVisible();await expect(page.getByText(/Build 001 human-control inheritance:/)).toContainText('16/16 · Strong');await expect(page.getByText(/inspectable architecture heuristic/i)).toBeVisible();});
 test('missing event coverage remains visible',async({page})=>{await page.goto('/100-builds/007/a');const correction=page.getByRole('group',{name:'Correction event'});await correction.getByRole('button',{name:'REMOVE EVENT'}).click();await expect(page.getByRole('heading',{name:'PARTIAL LOOP'})).toBeVisible();await expect(page.getByText(/Missing: Correction/)).toBeVisible();});
 test('privacy purpose boundary prevents governed status',async({page})=>{await page.goto('/100-builds/007/a');await page.getByRole('checkbox').first().uncheck();await expect(page.getByRole('heading',{name:'PARTIAL LOOP'})).toBeVisible();await expect(page.getByText(/consent and retention rules are explicit/i)).toBeVisible();});
 test('reset reaches a truthful empty state and add restores editable schema',async({page})=>{await page.goto('/100-builds/007/a');await page.getByRole('button',{name:'RESET / START EMPTY'}).click();await expect(page.getByRole('heading',{name:'ONE-WAY PRODUCT'})).toBeVisible();await expect(page.getByText(/No product data was stored/)).toBeVisible();await page.getByRole('button',{name:'ADD EVENT'}).click();await expect(page.getByRole('group',{name:'Use event'})).toBeVisible();});
 test('export is explicit and local',async({page})=>{await page.goto('/100-builds/007/a');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT RECORD'}).click();const file=await dl;expect(file.suggestedFilename()).toBe('feedback-loop-architecture.json');});
 test('canonical room is publicly in the lab and links both artifacts',async({page})=>{await page.goto('/100-builds/007');await expect(page.getByText('BUILD 007 / 100 · IN THE LAB')).toBeVisible();await expect(page.getByRole('link',{name:/OPEN THE TOOL/})).toHaveAttribute('href',/\/100-builds\/007\/a\/?$/);await expect(page.getByRole('link',{name:/ENTER THE VISUAL BUILD/})).toHaveAttribute('href',/\/100-builds\/007\/b\/?$/);});
 test('functional room stays usable at 320 CSS pixels',async({page})=>{await page.setViewportSize({width:320,height:800});await page.goto('/100-builds/007/a');await expect(page.getByRole('button',{name:'EXPORT RECORD'})).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow).toBe(false);});
});
test.describe('Build 007 governed loop field',()=>{
 test('scenario controls close the real loop and expose human control',async({page})=>{await page.goto('/100-builds/007/b');await expect(page.getByRole('button',{name:'ONE-WAY'})).toHaveAttribute('aria-pressed','true');await expect(page.getByText('RETURN PATH OPEN')).toBeVisible();await page.getByRole('button',{name:'GOVERNED'}).click();await expect(page.getByText('OUTCOMES RETURN TO THE PRODUCT')).toBeVisible();const human=page.locator('article[data-human="true"]');await expect(human).toHaveAttribute('data-active','true');await expect(human.getByRole('heading',{name:'HUMAN DECIDE'})).toBeVisible();});
 test('urgent correction visibly changes routing state',async({page})=>{await page.goto('/100-builds/007/b');await page.getByRole('button',{name:'URGENT CORRECTION'}).click();await expect(page.getByRole('heading',{name:'CORRECTION PAUSES THE ORDINARY QUEUE.'})).toBeVisible();await expect(page.locator('section[data-urgent="true"]')).toBeVisible();});
});
