import {test,expect} from '@playwright/test';
test.describe('Build 025 implementation readiness',()=>{
 test('does not bypass inherited vendor verification with layer evidence',async({page})=>{await page.goto('/100-builds/025/a');await expect(page.getByRole('heading',{name:'NOT READY'})).toBeVisible();await page.getByRole('button',{name:'ADD MISSING CONTROL EVIDENCE'}).click();await expect(page.getByRole('heading',{name:'NOT READY'})).toBeVisible();await expect(page.getByText(/Build 021: inherited assessment is not closed/)).toBeVisible()});
 test('requires a traceable inherited vendor record before a bounded pilot',async({page})=>{await page.goto('/100-builds/025/a');await page.getByRole('button',{name:'ADD MISSING CONTROL EVIDENCE'}).click();await page.getByRole('button',{name:'ATTACH CLOSED VENDOR CLAIM RECORD'}).click();await expect(page.getByRole('heading',{name:'READY FOR BOUNDED PILOT'})).toBeVisible();await expect(page.getByText(/021-SYNTH-CLAIM-01/)).toBeVisible()});
 test('manual score cannot manufacture evidence',async({page})=>{await page.goto('/100-builds/025/a');await page.getByRole('button',{name:'Set Controls readiness to 2'}).click();await expect(page.getByRole('heading',{name:'NOT READY'})).toBeVisible();await expect(page.getByText(/Controls: a positive score requires a specific evidence statement/)).toBeVisible()});
 test('reset restores the blocked fixture',async({page})=>{await page.goto('/100-builds/025/a');await page.getByRole('button',{name:'ADD MISSING CONTROL EVIDENCE'}).click();await page.getByRole('button',{name:'ATTACH CLOSED VENDOR CLAIM RECORD'}).click();await page.getByRole('button',{name:'RESET'}).click();await expect(page.getByRole('heading',{name:'NOT READY'})).toBeVisible()});
 test('exports locally with privacy and version boundaries',async({page})=>{await page.goto('/100-builds/025/a');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT READINESS RECORD'}).click();const download=await dl;expect(download.suggestedFilename()).toBe('ai-implementation-readiness.json');const body=JSON.parse(await (await download.createReadStream()).read().then(x=>x.toString()));expect(body.version).toBe('025.2.0');expect(body.fixture).toBe('synthetic');expect(body.boundary).toMatch(/not deployment/i)});
 test('fits 320px',async({page})=>{await page.setViewportSize({width:320,height:800});await page.goto('/100-builds/025/a');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)});
 test('B advances accessibly',async({page})=>{await page.goto('/100-builds/025/b');await page.getByRole('button',{name:'REVEAL THE NEXT LAYER'}).click();await expect(page.getByRole('status')).toContainText('OPEN THE X-RAY')});
});
