import {test,expect} from '@playwright/test';
import {SOCIAL_LISTENING_CORPORA,SOCIAL_LISTENING_PRESETS,classifyUnmetNeed} from '../packages/release/src/social-listening-unmet-need-engine';

test('081 preserves exactly five synthetic corpora with six posts each',()=>{expect(SOCIAL_LISTENING_CORPORA.map(x=>x.id)).toEqual(['CORPUS-CEDAR','CORPUS-HARBOR','CORPUS-LATTICE','CORPUS-MESA','CORPUS-ORBIT']);for(const c of SOCIAL_LISTENING_CORPORA){expect(c.posts).toHaveLength(6);expect(c.posts.every(p=>p.author==='FICTIONAL-PUBLIC-ACCOUNT'&&p.verification==='SYNTHETIC-RECORD-CHECKED')).toBeTruthy();expect(c.alternatives.length).toBeGreaterThan(0);expect(c.contradictions.length).toBeGreaterThan(0);expect(c.missingEvidence.length).toBeGreaterThan(0)}});

test('081 keeps repetition as a bounded hypothesis and stops for human research',()=>{for(const corpus of SOCIAL_LISTENING_CORPORA){const result=classifyUnmetNeed(SOCIAL_LISTENING_PRESETS[corpus.id]);expect(result.hypothesis?.signalStatus).toBe('CORROBORATED-IN-SYNTHETIC-FIXTURE');expect(result.hypothesis?.needStatus).toBe('HYPOTHESIS-NOT-VALIDATED');expect(result.hypothesis?.repeatedPostIds).toEqual(corpus.posts.map(p=>p.id));expect(result.hypothesis?.alternatives).toEqual(corpus.alternatives);expect(result.hypothesis?.contradictions).toEqual(corpus.contradictions);expect(result.hypothesis?.missingEvidence).toEqual(corpus.missingEvidence);expect(result.hypothesis?.candidates.every(x=>x.status==='HUMAN-VALIDATION-REQUIRED')).toBeTruthy();const workflow=result.hypothesis?.validationWorkflow??[];expect(workflow[workflow.length-1]?.state).toBe('HUMAN-RESEARCH-REQUIRED')}expect(classifyUnmetNeed(SOCIAL_LISTENING_PRESETS['CORPUS-CEDAR']).audit).toContain('NO SCRAPING, IDENTITY LINKAGE, PROFILING, SENTIMENT, DEMOGRAPHIC, PROTECTED-TRAIT, SCORE, RANK, OR REAL-WORLD INFERENCE')});

test('081 fails closed on drifted, real-person, inference-enabled, validated-need, and hostile input',()=>{const fixture=SOCIAL_LISTENING_PRESETS['CORPUS-CEDAR'];expect(classifyUnmetNeed(fixture)).toEqual(classifyUnmetNeed(fixture));const hostile={...fixture};Object.defineProperty(hostile,'corpora',{get(){throw new Error('hostile')}});const values=[null,undefined,[],{},'posts',{...fixture,fixtureId:'REAL'},{...fixture,corpusId:'OTHER'},{...fixture,extra:true},{...fixture,admission:{...fixture.admission,realPeopleData:true}},{...fixture,admission:{...fixture.admission,identityInference:true}},{...fixture,admission:{...fixture.admission,protectedTraitInference:true}},{...fixture,admission:{...fixture.admission,needValidated:true}},{...fixture,inherited:{...fixture.inherited,retrieval:'cap:999'}},{...fixture,corpora:[...fixture.corpora,fixture.corpora[0]]},hostile,new Proxy(fixture,{get(){throw new Error('proxy')}})];for(const value of values){expect(()=>classifyUnmetNeed(value)).not.toThrow();const result=classifyUnmetNeed(value);expect(result.status).toBe('INVALID');expect(result.hypothesis).toBeNull()}});

test('081-A exports exact admission, artifacts, lineage, and replay',async({page})=>{await page.goto('/100-builds/081/a');await page.getByLabel('SIGNAL CORPUS').selectOption('CORPUS-ORBIT');await expect(page.getByRole('heading',{name:'CORPUS-ORBIT NEED HYPOTHESIS'})).toBeVisible();const event=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT NEED SIGNAL'}).click();const download=await event;expect(download.suggestedFilename()).toBe('synthetic-unmet-need-signal.json');const parsed=JSON.parse(await (await import('node:fs/promises')).readFile(await download.path() as string,'utf8'));expect(parsed.version).toBe('081.1.0');expect(parsed.canonical).toEqual({uses:['003','028','063'],creates:'cap:081'});expect(parsed.artifacts).toEqual(['Signal Classifier','Need Validation Workflow']);expect(parsed.admission).toEqual({syntheticConversationOnly:true,exactCorpusCount:5,exactPostsPerCorpus:6,fixedPostsOnly:true,alternativesContradictionsMissingEvidencePreserved:true,humanValidationRequired:true,networkRetrieval:false,containsRealPeopleData:false,identityInference:false,demographicInference:false,protectedTraitInference:false,sentimentInference:false,realNeedValidated:false,demandTrendPriorityDetermined:false,productOrPolicyRecommended:false,failClosed:true});expect(parsed.replay).toEqual({corpusId:'CORPUS-ORBIT',engineVersion:'081.1.0'});});

test('081 exposes privacy and research boundaries, contains at 320px, and B resolves hypotheses',async({page})=>{await page.goto('/100-builds/081/a');await expect(page.getByText('no real people',{exact:false}).first()).toBeVisible();await expect(page.getByText('protected-trait',{exact:false}).first()).toBeVisible();await page.setViewportSize({width:320,height:760});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();await page.goto('/100-builds/081/b');await page.getByRole('button',{name:'RESOLVE REPEATED SIGNALS'}).click();await expect(page.getByRole('status')).toContainText('Repeated posts became bounded need hypotheses');});
