import {test,expect} from '@playwright/test';

test.describe('Build 004 manual intelligence invariants',()=>{
 test.beforeEach(async({page})=>{await page.goto('/100-builds/004/a');await expect(page.getByRole('heading',{name:'Manual Intelligence Engine Method'})).toBeVisible()});
 test('unverified claim never appears as a verified finding',async({page})=>{await expect(page.getByText('No verified findings yet.')).toBeVisible();await expect(page.getByText('This is a demonstration claim and is not verified evidence.')).toBeVisible();const verifiedPanel=page.getByRole('heading',{name:'Verified findings'}).locator('..');await expect(verifiedPanel).not.toContainText('This is a demonstration claim and is not verified evidence.')});
 test('human verification explicitly promotes a claim into findings',async({page})=>{await page.getByLabel('Status for claim 1').selectOption('verified');const verifiedPanel=page.getByRole('heading',{name:'Verified findings'}).locator('..');await expect(verifiedPanel).toContainText('This is a demonstration claim and is not verified evidence.');await expect(page.getByText('No verified findings yet.')).toHaveCount(0)});
 test('contradicted claim is preserved separately rather than flattened into findings',async({page})=>{await page.getByLabel('Status for claim 1').selectOption('contradicted');const contradictionPanel=page.getByRole('heading',{name:'Contradictions'}).locator('..');const verifiedPanel=page.getByRole('heading',{name:'Verified findings'}).locator('..');await expect(contradictionPanel).toContainText('This is a demonstration claim and is not verified evidence.');await expect(verifiedPanel).not.toContainText('This is a demonstration claim and is not verified evidence.')});
 test('removing a source removes claims that depend on it',async({page})=>{await page.getByRole('button',{name:'Remove Example primary source'}).click();await expect(page.getByText('Add at least one source before creating a claim.')).toBeVisible();await expect(page.getByText(/0 TOTAL · 0 VERIFIED/)).toBeVisible();await expect(page.getByText('This is a demonstration claim and is not verified evidence.')).toHaveCount(0)});
 test('a new claim enters the queue unverified',async({page})=>{await page.getByLabel('Analyst claim').fill('A newly collected assertion.');await page.getByRole('button',{name:'ADD TO QUEUE'}).click();await expect(page.getByText('A newly collected assertion.')).toBeVisible();await expect(page.getByLabel('Status for claim 2')).toHaveValue('unverified')});
 test('the interface states its verification boundary',async({page})=>{await expect(page.getByText(/does not verify a source for you/i)).toBeVisible();await expect(page.getByText(/only when a human reviewer explicitly marks it verified/i)).toBeVisible()});
});
