import {test,expect} from '@playwright/test';
test.describe('Build 031 privacy-conscious measurement',()=>{
 test('uses max-aware exposure and does not call the plan minimized',async({page})=>{await page.goto('/100-builds/031/a');await expect(page.getByRole('heading',{name:'PLAN GAPS'})).toBeVisible();await expect(page.getByText(/high-risk combination/)).toBeVisible();await expect(page.getByRole('heading',{name:'MINIMIZED'})).toHaveCount(0)});
 test('derives minimum set from declared decision coverage',async({page})=>{await page.goto('/100-builds/031/a');await page.getByRole('button',{name:'APPLY DECLARED MINIMUM SET'}).click();await expect(page.getByRole('heading',{name:'DECLARED MINIMUM SET'})).toBeVisible();await expect(page.getByText(/not proof of necessity/)).toBeVisible();for(const label of ['page View','feature Used','task Completed','error Code'])await expect(page.getByLabel(label)).toBeChecked()});
 test('keeps consent, legal basis and deletion assertions distinct',async({page})=>{await page.goto('/100-builds/031/a');await page.getByLabel('Legal-basis review documented separately').uncheck();await expect(page.getByRole('heading',{name:'CONTROL BLOCKED'})).toBeVisible();await expect(page.getByText(/separately from consent/)).toBeVisible();await expect(page.getByLabel('Optional-measurement consent choice available')).toBeChecked()});
 test('detects dependency and purpose limitation failures',async({page})=>{await page.goto('/100-builds/031/a');await page.getByLabel('page View').uncheck();await expect(page.getByText(/taskCompleted requires pageView/)).toBeVisible();await page.getByLabel('precise Location').uncheck();await page.getByLabel('full Ip').check();await expect(page.getByText(/does not support a required named decision/)).toBeVisible()});
 test('exports deterministic original and derived replay state',async({page})=>{await page.goto('/100-builds/031/a');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT REPLAYABLE PLAN'}).click();const download=await pending;const stream=await download.createReadStream();let body='';for await(const chunk of stream)body+=chunk.toString();const record=JSON.parse(body);expect(record.engineVersion).toBe('031.2.0');expect(record.fixture).toContain('no observed telemetry');expect(record.originalState.enabled).toEqual(['pageView','featureUsed','taskCompleted','preciseLocation','sessionReplay']);expect(record.replay.eventOrder).toHaveLength(9);expect(record.derivedState.limitations).toHaveLength(4)});
 test('fits 320px',async({page})=>{await page.setViewportSize({width:320,height:760});await page.goto('/100-builds/031/a');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy()});
 test('B has ordered keyboard parity and audible honest states',async({page})=>{await page.goto('/100-builds/031/b');await page.getByRole('button',{name:'NEXT VIEW'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('status')).toContainText('PURPOSE REVIEW');await page.keyboard.press('Enter');await expect(page.getByRole('status')).toContainText('DECLARED MINIMUM SET');await page.getByRole('button',{name:'PREVIOUS VIEW'}).click();await expect(page.getByRole('status')).toContainText('PURPOSE REVIEW')});
});
