import {test,expect} from '@playwright/test';import {exploreChangeConsequences,type ChangeInput} from '../packages/release/src/change-consequence-engine';
test.describe('Build 029 change consequence explorer',()=>{
 test('shows exact-value changes and every registered path',async({page})=>{await page.goto('/100-builds/029/a');await expect(page.getByRole('heading',{name:'IMPACT REVIEW'})).toBeVisible();await expect(page.getByText(/DEC-ELIG → WF-FOLLOWUP/)).toBeVisible();await expect(page.getByText(/REC-NOTICE → EXP-REPORT/)).toBeVisible();await expect(page.getByText(/WF-FOLLOWUP → EXP-REPORT/)).toBeVisible();await expect(page.getByText(/EVID-REASON-01/)).toBeVisible()});
 test('does not invent a semantic change',async({page})=>{await page.goto('/100-builds/029/a');await page.getByLabel('Status').selectOption('pending');await page.getByLabel('Service address').fill('Island A');await expect(page.getByRole('heading',{name:'NO CHANGE'})).toBeVisible();await expect(page.getByText('No changed registered field.')).toBeVisible();await expect(page.getByText(/no registered exact-value field change/)).toBeVisible()});
 test('exports deterministic replay and semantic boundary',async({page})=>{await page.goto('/100-builds/029/a');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT CHANGE TRACE'}).click();const download=await dl;expect(download.suggestedFilename()).toBe('change-consequence-trace.json');const stream=await download.createReadStream();let text='';for await(const chunk of stream)text+=chunk.toString();const report=JSON.parse(text);expect(report.version).toBe('029.2.0');expect(report.semanticBoundary).toMatch(/does not infer meaning/);expect(report.result.replay.graphFingerprint).toMatch(/^[0-9a-f]{8}$/);expect(report.result.impacted.find((x:any)=>x.id==='EXP-REPORT').paths).toHaveLength(2)});
 test('cycles and unregistered dependencies block interpretation',async()=>{const base:ChangeInput={schema:{id:'schema-v2',entityType:'case',fields:[{id:'status',label:'Status',type:'string',materiality:'critical'}]},before:{entityId:'E-1',schemaVersion:'schema-v2',version:'v1',effectiveAt:'2026-08-01',fields:{status:'old'}},after:{entityId:'E-1',schemaVersion:'schema-v2',version:'v2',effectiveAt:'2026-08-02',fields:{status:'new'}},event:{id:'EV-1',actor:'Reviewer',occurredAt:'2026-08-02',reason:'Verified synthetic correction',authority:'May correct synthetic record',evidence:[{id:'R-1',locator:'synthetic://reason',observedAt:'2026-08-02',reviewer:'Reviewer',supports:'change-reason'},{id:'A-1',locator:'synthetic://authority',observedAt:'2026-08-02',reviewer:'Reviewer',supports:'change-authority'}]},downstream:[{id:'A',label:'Node A',kind:'record',fieldsUsed:['status'],dependsOn:['B'],owner:'Owner A',registryRef:'synthetic://registry/A'},{id:'B',label:'Node B',kind:'export',fieldsUsed:[],dependsOn:['A','MISSING'],owner:'Owner B',registryRef:'synthetic://registry/B'}],assessedAt:'2026-08-02'};const result=exploreChangeConsequences(base);expect(result.status).toBe('TRACE GAPS');expect(result.cycles.length).toBeGreaterThan(0);expect(result.blocking.join(' ')).toMatch(/not registered/);expect(result.impacted).toHaveLength(0)});
 test('fits 320px',async({page})=>{await page.setViewportSize({width:320,height:800});await page.goto('/100-builds/029/a');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)});
 test('B changes the registered review graph accessibly',async({page})=>{await page.goto('/100-builds/029/b');await page.getByRole('button',{name:'CHANGE STATUS'}).click();await expect(page.getByRole('status')).toContainText('STATUS');await expect(page.getByRole('status')).toContainText('Registered review nodes')});
});
