import {test,expect} from '@playwright/test';
test.describe('Build 027 creator ownership stack',()=>{
 test('exposes the dependent distribution layer',async({page})=>{await page.goto('/100-builds/027/a');await expect(page.getByRole('heading',{name:'CRITICAL DEPENDENCY'})).toBeVisible();await expect(page.getByText(/system the creator does not operationally control/)).toBeVisible()});
 test('a selected OWN label cannot reuse account-access evidence',async({page})=>{await page.goto('/100-builds/027/a');await page.getByRole('listitem').filter({hasText:'Discovery reach'}).getByRole('button',{name:/Classify Discovery reach operationally as OWN/}).click();await expect(page.getByRole('heading',{name:'MAP GAPS'})).toBeVisible();await expect(page.getByText(/attach current evidence supporting operational-custody/)).toBeVisible()});
 test('unchecked recovery claims remove evidence-backed capability',async({page})=>{await page.goto('/100-builds/027/a');const card=page.getByRole('listitem').filter({hasText:'Essay source files'});await card.getByLabel('Usable export claimed').uncheck();await expect(page.getByText('No verified usable export path.')).toBeVisible()});
 test('synthetic recovery tests preserve dependency semantics',async({page})=>{await page.goto('/100-builds/027/a');await page.getByRole('button',{name:'RECORD SYNTHETIC RECOVERY TESTS'}).click();const card=page.getByRole('listitem').filter({hasText:'Discovery reach'});await expect(card.getByText(/DEPENDENCY INDEX/)).toBeVisible();await expect(page.getByRole('heading',{name:'OWNERSHIP GAPS'})).toBeVisible()});
 test('exports complete semantics locally',async({page})=>{await page.goto('/100-builds/027/a');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT OWNERSHIP MAP'}).click();const download=await dl;expect(download.suggestedFilename()).toBe('creator-ownership-stack.json');const stream=await download.createReadStream();let text='';for await(const chunk of stream)text+=chunk.toString();const report=JSON.parse(text);expect(report.version).toBe('027.2.0');expect(report.semantics.controlClass).toMatch(/not establish legal title/i);expect(report.input.assets[0].backupControl.evidence[0].supports).toBe('backup-restore')});
 test('fits 320px',async({page})=>{await page.setViewportSize({width:320,height:800});await page.goto('/100-builds/027/a');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)});
 test('B has keyboard-operable alternatives and announces the move',async({page})=>{await page.goto('/100-builds/027/b');await page.getByRole('article').filter({hasText:'DISCOVERY REACH'}).getByRole('button',{name:'Move DISCOVERY REACH to OWN'}).click();await expect(page.getByRole('status')).toContainText('STACK EXPOSURE 2');await expect(page.getByRole('status')).toContainText('DISCOVERY REACH moved to OWN')});
});
