import {test,expect} from '@playwright/test';
import {EVIDENCE_TRANSLATION_CASES,EVIDENCE_TRANSLATION_PRESETS,translateCannabisEvidence} from '../packages/release/src/cannabis-evidence-translation-engine';

test('078 preserves exactly five synthetic evidence and audience cases',()=>{expect(EVIDENCE_TRANSLATION_CASES.map(x=>x.caseId)).toEqual(['EVIDENCE-CEDAR','EVIDENCE-HARBOR','EVIDENCE-LATTICE','EVIDENCE-MESA','EVIDENCE-ORBIT']);expect(EVIDENCE_TRANSLATION_CASES.map(x=>x.audience)).toEqual(['PUBLIC READER','CLINICAL EDUCATOR','POLICY ANALYST','PRODUCT TEAM','PATIENT ADVOCATE']);for(const item of EVIDENCE_TRANSLATION_CASES){expect(item.preservedFields).toEqual(['SOURCE TYPE','SOURCE QUALITY','CLAIM','POPULATION','INTERVENTION OR EXPOSURE','COMPARISON','OUTCOME','LIMITATIONS','UNCERTAINTY','AS-OF DATE']);expect(item.truthAnchor.limitations.length).toBeGreaterThan(0);expect(item.caveats.length).toBeGreaterThan(0)}});

test('078 preserves truth anchors and caveats without claim expansion',()=>{for(const item of EVIDENCE_TRANSLATION_CASES){const result=translateCannabisEvidence(EVIDENCE_TRANSLATION_PRESETS[item.caseId]);expect(result.translation?.truthAnchor).toEqual(item.truthAnchor);expect(result.translation?.caveats).toEqual(item.caveats);expect(result.audit).toContain('NO SOURCE UPGRADING, CLAIM EXPANSION, LIMIT REMOVAL, OR REAL-WORLD INFERENCE')}expect(translateCannabisEvidence(EVIDENCE_TRANSLATION_PRESETS['EVIDENCE-ORBIT']).translation?.truthAnchor.uncertainty).toContain('unknown');});

test('078 is deterministic and fails closed on drifted, real, authority-bearing, and hostile input',()=>{const fixture=EVIDENCE_TRANSLATION_PRESETS['EVIDENCE-CEDAR'];expect(translateCannabisEvidence(fixture)).toEqual(translateCannabisEvidence(fixture));const hostile={...fixture};Object.defineProperty(hostile,'cases',{get(){throw new Error('hostile')}});const values=[null,undefined,[],{},'study',{...fixture,fixtureId:'REAL'},{...fixture,caseId:'OTHER'},{...fixture,extra:true},{...fixture,admission:{...fixture.admission,realPatientData:true}},{...fixture,admission:{...fixture.admission,safetyEffectivenessClaim:true}},{...fixture,inherited:{...fixture.inherited,audienceProfiles:'cap:999'}},{...fixture,cases:[...fixture.cases,fixture.cases[0]]},hostile,new Proxy(fixture,{get(){throw new Error('proxy')}})];for(const value of values){expect(()=>translateCannabisEvidence(value)).not.toThrow();const result=translateCannabisEvidence(value);expect(result.status).toBe('INVALID');expect(result.translation).toBeNull()}});

test('078-A exports exact admission, artifacts, lineage, and replay',async({page})=>{await page.goto('/100-builds/078/a');await page.getByLabel('TRANSLATION CASE').selectOption('EVIDENCE-ORBIT');await expect(page.getByRole('heading',{name:'EVIDENCE-ORBIT TRANSLATION'})).toBeVisible();const event=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT TRANSLATION RECORD'}).click();const download=await event;expect(download.suggestedFilename()).toBe('synthetic-cannabis-evidence-translation.json');const parsed=JSON.parse(await (await import('node:fs/promises')).readFile(await download.path() as string,'utf8'));expect(parsed.version).toBe('078.1.0');expect(parsed.canonical).toEqual({uses:['002','031','051','058'],creates:'cap:078'});expect(parsed.artifacts).toEqual(['Evidence Translation Protocol','Audience Caveat Rules']);expect(parsed.admission).toEqual({syntheticEvidenceOnly:true,exactCaseCount:5,fixedAudiencePerCase:true,sourceTypeAndQualityPreserved:true,claimPopulationInterventionComparisonOutcomePreserved:true,limitationsUncertaintyAsOfCaveatsPreserved:true,containsRealPatientData:false,containsRealProductData:false,currentLawClaim:false,legalAdvice:'NONE',clinicalAdvice:'NONE',diagnosisTreatmentDosageClaim:false,safetyEffectivenessClaim:false,complianceDetermined:false,failClosed:true});expect(parsed.replay).toEqual({caseId:'EVIDENCE-ORBIT',engineVersion:'078.1.0'});});

test('078 exposes evidence boundaries, contains at 320px, and B preserves limits',async({page})=>{await page.goto('/100-builds/078/a');await expect(page.getByText('no real patients',{exact:false}).first()).toBeVisible();await expect(page.getByText('dosage',{exact:false}).first()).toBeVisible();await page.setViewportSize({width:320,height:760});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();await page.goto('/100-builds/078/b');await page.getByRole('button',{name:'PASS THROUGH AUDIENCE LENS'}).click();await expect(page.getByRole('status')).toContainText('Audience changed; evidence limits stayed attached');});
