import {test,expect} from '@playwright/test';
test.describe('Build 030 inclusive repair lab',()=>{
 test('describes mapped gaps without simulating a person',async({page})=>{await page.goto('/100-builds/030/a');await expect(page.getByRole('heading',{name:'MAPPED GAPS'})).toBeVisible();await expect(page.getByText(/not a person, diagnosis/)).toBeVisible();await expect(page.getByText(/keyboardOnly: enable mapped control visibleFocus/)).toBeVisible()});
 test('enabling every mapping does not claim proven repair',async({page})=>{await page.goto('/100-builds/030/a');await page.getByRole('button',{name:'ENABLE ALL MAPPED CONTROLS'}).click();await expect(page.getByRole('heading',{name:'MAPPED CONTROLS PRESENT'})).toBeVisible();await expect(page.getByText(/not evidence that the repairs work/)).toBeVisible();await expect(page.getByRole('heading',{name:'REPAIRED'})).toHaveCount(0)});
 test('reports a deterministic combined-condition interaction',async({page})=>{await page.goto('/100-builds/030/a');await page.getByLabel('low Vision').check();await expect(page.getByText(/Zoom and text scaling must remain usable/)).toBeVisible()});
 test('exports original, derived, privacy, evidence and replay state locally',async({page})=>{await page.goto('/100-builds/030/a');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT REPLAYABLE RECORD'}).click();const download=await pending;expect(download.suggestedFilename()).toBe('inclusive-repair-record.json');const stream=await download.createReadStream();let json='';for await(const chunk of stream)json+=chunk.toString();const record=JSON.parse(json);expect(record.engineVersion).toBe('030.2.0');expect(record.originalState.needs).toEqual(['colorIndependent','keyboardOnly','lowBandwidth']);expect(record.derivedState.status).toBe('MAPPED GAPS');expect(record.replay.mappingVersion).toBe('030-map-2');expect(record.privacy).toContain('no persistence')});
 test('fits 320px and retains native controls',async({page})=>{await page.setViewportSize({width:320,height:800});await page.goto('/100-builds/030/a');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);await expect(page.locator('fieldset input[type=checkbox]')).toHaveCount(7)});
 test('B provides keyboard-operable ordered parity and honest status copy',async({page})=>{await page.goto('/100-builds/030/b');await page.getByRole('button',{name:'NEXT VIEW'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('status')).toContainText('EXPOSE MAPPED CONSTRAINTS');await page.keyboard.press('Enter');await expect(page.getByRole('status')).toContainText('ENABLE DERIVED CONTROLS');await expect(page.getByLabel(/Synthetic interface view/)).toContainText('ACTION REQUIRED');await page.getByRole('button',{name:'PREVIOUS VIEW'}).click();await expect(page.getByRole('status')).toContainText('EXPOSE MAPPED CONSTRAINTS')});
});
