import {test,expect} from '@playwright/test';
test.describe('Build 026 messy data trust',()=>{
 test('keeps duplicate candidates in review',async({page})=>{await page.goto('/100-builds/026/a');await expect(page.getByRole('heading',{name:'REVIEW REQUIRED'})).toBeVisible();await expect(page.getByText(/duplicate group requires human review/)).toBeVisible()});
 test('records an exact keep-separate decision without merging',async({page})=>{await page.goto('/100-builds/026/a');await page.getByRole('button',{name:'RECORD KEEP-SEPARATE REVIEWS'}).click();await expect(page.getByRole('heading',{name:'TRACEABLE'})).toBeVisible();await expect(page.getByText(/SRC-101 \+ SRC-102 · keep-separate · source records remain separate/)).toBeVisible();await expect(page.getByText('SRC-101 / DUP-01')).toBeVisible();await expect(page.getByText('SRC-102 / DUP-01')).toBeVisible()});
 test('review becomes invalid when the candidate set changes',async({page})=>{await page.goto('/100-builds/026/a');await page.getByRole('button',{name:'RECORD KEEP-SEPARATE REVIEWS'}).click();await page.getByLabel('SRC-102 email').fill('other@example.org');await expect(page.getByRole('heading',{name:'TRUST GAPS'})).toBeVisible();await expect(page.getByText(/review does not match a current duplicate group/)).toBeVisible()});
 test('invalid email cannot drive duplicate grouping',async({page})=>{await page.goto('/100-builds/026/a');await page.getByLabel('SRC-103 email').fill('not-an-email');await expect(page.getByRole('heading',{name:'TRUST GAPS'})).toBeVisible();await expect(page.getByText(/cannot drive duplicate grouping/)).toBeVisible()});
 test('blank and malformed amounts are rejected rather than coerced',async({page})=>{await page.goto('/100-builds/026/a');await page.getByLabel('SRC-103 amount').fill('');await expect(page.getByText(/amount is blank or not a strict currency number/)).toBeVisible();await page.getByLabel('SRC-103 amount').fill('$1,2');await expect(page.getByText(/amount is blank or not a strict currency number/)).toBeVisible()});
 test('exports locally with version and non-merge boundary',async({page})=>{await page.goto('/100-builds/026/a');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT TRACE RECORD'}).click();const download=await dl;expect(download.suggestedFilename()).toBe('messy-data-trust-record.json');const stream=await download.createReadStream();let text='';for await(const chunk of stream)text+=chunk.toString();const report=JSON.parse(text);expect(report.version).toBe('026.2.0');expect(report.boundary).toMatch(/never merge or delete/i);expect(report.result.records[0].rawSnapshot).toBeTruthy()});
 test('fits 320px',async({page})=>{await page.setViewportSize({width:320,height:800});await page.goto('/100-builds/026/a');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)});
 test('B advances accessibly',async({page})=>{await page.goto('/100-builds/026/b');await page.getByRole('button',{name:'MOVE THROUGH THE LINE'}).click();await expect(page.getByRole('status')).toContainText('APPLY NAMED RULES')});
});
