import {test,expect} from '@playwright/test';
import {WORK_CONTENT_PACKETS,WORK_CONTENT_PRESETS,captureSafeContent} from '../packages/release/src/work-to-content-capture-engine';

test('083 preserves exactly five synthetic work packets and fixed filter counts',()=>{expect(WORK_CONTENT_PACKETS.map(x=>x.id)).toEqual(['WORK-CEDAR','WORK-HARBOR','WORK-LATTICE','WORK-MESA','WORK-ORBIT']);for(const packet of WORK_CONTENT_PACKETS){expect(packet.fragments).toHaveLength(6);expect(packet.fragments.filter(x=>x.classification==='PUBLIC-SYNTHETIC'&&x.rightsState==='OWNED-SYNTHETIC')).toHaveLength(2);expect(packet.fragments.filter(x=>x.classification!=='PUBLIC-SYNTHETIC')).toHaveLength(4);expect(packet.derivatives.map(x=>x.kind)).toEqual(['INSIGHT','METHOD','VISUAL','TEACHING-MATERIAL']);expect(packet.derivatives.every(x=>x.publicationStatus==='DRAFT-HUMAN-APPROVAL-REQUIRED')).toBeTruthy()}});

test('083 excludes blocked content and admits only public synthetic source IDs',()=>{for(const packet of WORK_CONTENT_PACKETS){const result=captureSafeContent(WORK_CONTENT_PRESETS[packet.id]);const admitted=packet.fragments.filter(x=>x.classification==='PUBLIC-SYNTHETIC').map(x=>x.id);const blocked=packet.fragments.filter(x=>x.classification!=='PUBLIC-SYNTHETIC');expect(result.admittedFragmentIds).toEqual(admitted);expect(result.blocked.map(x=>x.fragmentId)).toEqual(blocked.map(x=>x.id));expect(JSON.stringify(result.blocked)).not.toContain('DETAIL WITHHELD');expect(JSON.stringify(result.derivatives)).not.toContain('DETAIL WITHHELD');expect(result.derivatives.every(d=>d.sourceFragmentIds.every(id=>admitted.includes(id)))).toBeTruthy();expect(result.derivatives.every(d=>d.rightsReview==='HUMAN-REVIEW-REQUIRED'&&d.confidentialityReview==='HUMAN-REVIEW-REQUIRED')).toBeTruthy()}expect(captureSafeContent(WORK_CONTENT_PRESETS['WORK-CEDAR']).audit).toContain('RETURNED BLOCKED IDS, CLASSIFICATIONS, AND REASONS WITHOUT BLOCKED CONTENT')});

test('083 fails closed on drifted, real, publication-authorized, rights-cleared, and hostile input',()=>{const fixture=WORK_CONTENT_PRESETS['WORK-CEDAR'];expect(captureSafeContent(fixture)).toEqual(captureSafeContent(fixture));const hostile={...fixture};Object.defineProperty(hostile,'packets',{get(){throw new Error('hostile')}});const values=[null,undefined,[],{},'work',{...fixture,fixtureId:'REAL'},{...fixture,packetId:'OTHER'},{...fixture,extra:true},{...fixture,admission:{...fixture.admission,realConfidentialData:true}},{...fixture,admission:{...fixture.admission,publicationAuthorized:true}},{...fixture,admission:{...fixture.admission,rightsClearedForRealUse:true}},{...fixture,admission:{...fixture.admission,safeToPublishDetermined:true}},{...fixture,inherited:{...fixture.inherited,dataMinimization:'cap:999'}},{...fixture,packets:[...fixture.packets,fixture.packets[0]]},hostile,new Proxy(fixture,{get(){throw new Error('proxy')}})];for(const value of values){expect(()=>captureSafeContent(value)).not.toThrow();const result=captureSafeContent(value);expect(result.status).toBe('INVALID');expect(result.packetSummary).toBeNull();expect(result.admittedFragmentIds).toEqual([]);expect(result.blocked).toEqual([]);expect(result.derivatives).toEqual([])}});

test('083-A exports exact admission, artifacts, lineage, and replay',async({page})=>{await page.goto('/100-builds/083/a');await page.getByLabel('WORK PACKET').selectOption('WORK-ORBIT');await expect(page.getByRole('heading',{name:'WORK-ORBIT SAFE DERIVATIVES'})).toBeVisible();const event=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT SAFE DERIVATIVES'}).click();const download=await event;expect(download.suggestedFilename()).toBe('synthetic-work-to-content-capture.json');const parsed=JSON.parse(await (await import('node:fs/promises')).readFile(await download.path() as string,'utf8'));expect(parsed.version).toBe('083.1.0');expect(parsed.canonical).toEqual({uses:['024','057','060','080'],creates:'cap:083'});expect(parsed.artifacts).toEqual(['Confidentiality Filter','Content Opportunity Extractor']);expect(parsed.admission).toEqual({syntheticWorkOnly:true,exactPacketCount:5,exactFragmentsPerPacket:6,exactAdmittedPerPacket:2,exactBlockedPerPacket:4,exactDerivativesPerPacket:4,fixedFragmentsOnly:true,blockedContentExcludedFromResult:true,derivativeSourceLinksLimitationsReviewGatesPreserved:true,containsRealConfidentialData:false,containsRealPersonalData:false,thirdPartyContentUsed:false,publicationAuthorized:false,rightsClearedForRealUse:false,consentGrantedForRealUse:false,legalPrivilegeDetermined:false,safeToPublishDetermined:false,failClosed:true});expect(parsed.replay).toEqual({packetId:'WORK-ORBIT',engineVersion:'083.1.0'});});

test('083 exposes confidentiality and rights boundaries, contains at 320px, and B filters the work',async({page})=>{await page.goto('/100-builds/083/a');await expect(page.getByText('no real work',{exact:false}).first()).toBeVisible();await expect(page.getByText('safe to disclose',{exact:false}).first()).toBeVisible();await page.setViewportSize({width:320,height:760});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();await page.goto('/100-builds/083/b');await page.getByRole('button',{name:'FILTER WORK ARTIFACT'}).click();await expect(page.getByRole('status')).toContainText('Confidential work separated into reviewable public derivatives');});
