import {test,expect} from '@playwright/test';
import {EVIDENCE_NAVIGATION_PRESETS,EVIDENCE_NAVIGATION_QUESTIONS,EVIDENCE_NAVIGATION_RECORDS,navigatePsychedelicEvidence} from '../packages/release/src/psychedelic-evidence-navigation-engine';

test('079 preserves exactly five evidence records and three questions',()=>{expect(EVIDENCE_NAVIGATION_RECORDS.map(x=>x.id)).toEqual(['RECORD-CEDAR','RECORD-HARBOR','RECORD-LATTICE','RECORD-MESA','RECORD-ORBIT']);expect(EVIDENCE_NAVIGATION_QUESTIONS.map(x=>x.id)).toEqual(['Q-PREPARATION-OUTCOME','Q-CONTEXT-SUPPORT','Q-IMPLEMENTATION-EVIDENCE']);for(const q of EVIDENCE_NAVIGATION_QUESTIONS){const result=navigatePsychedelicEvidence(EVIDENCE_NAVIGATION_PRESETS[q.id]);expect(result.rows).toHaveLength(5);expect(result.rows.map(x=>x.record.id)).toEqual(EVIDENCE_NAVIGATION_RECORDS.map(x=>x.id));expect(result.facets).toEqual(['QUESTION','POPULATION','CONTEXT','OUTCOME','EVIDENCE TYPE','QUALITY BASIS','APPLICABILITY','LIMITATIONS','UNCERTAINTY','AS-OF DATE'])}});

test('079 preserves source anchors, out-of-scope results, and unknowns without ranking',()=>{const result=navigatePsychedelicEvidence(EVIDENCE_NAVIGATION_PRESETS['Q-PREPARATION-OUTCOME']);expect(result.rows[0].applicability).toBe('DIRECT-FOR-SYNTHETIC-QUESTION');expect(result.rows[1].applicability).toBe('OUTSIDE-SYNTHETIC-QUESTION');expect(result.rows[4].unknowns).toContain('CORPUS COMPLETENESS');for(const [i,row] of result.rows.entries()){expect(row.record).toEqual(EVIDENCE_NAVIGATION_RECORDS[i]);expect(row.record.limitations.length).toBeGreaterThan(0);expect(row.record.uncertainty.length).toBeGreaterThan(0)}expect(result.audit).toContain('NO NUMERIC SCORING, RANKING, IMPUTATION, OR REAL-WORLD APPLICABILITY DECISION');});

test('079 is deterministic and fails closed on drifted, real, scored, and hostile input',()=>{const fixture=EVIDENCE_NAVIGATION_PRESETS['Q-PREPARATION-OUTCOME'];expect(navigatePsychedelicEvidence(fixture)).toEqual(navigatePsychedelicEvidence(fixture));const hostile={...fixture};Object.defineProperty(hostile,'records',{get(){throw new Error('hostile')}});const values=[null,undefined,[],{},'study',{...fixture,fixtureId:'REAL'},{...fixture,questionId:'OTHER'},{...fixture,extra:true},{...fixture,admission:{...fixture.admission,realClinicalEvidence:true}},{...fixture,admission:{...fixture.admission,applicabilityDecision:true}},{...fixture,inherited:{...fixture.inherited,retrieval:'cap:999'}},{...fixture,records:[...fixture.records,fixture.records[0]]},hostile,new Proxy(fixture,{get(){throw new Error('proxy')}})];for(const value of values){expect(()=>navigatePsychedelicEvidence(value)).not.toThrow();const result=navigatePsychedelicEvidence(value);expect(result.status).toBe('INVALID');expect(result.question).toBeNull();expect(result.rows).toEqual([])}});

test('079-A exports exact admission, artifacts, lineage, and replay',async({page})=>{await page.goto('/100-builds/079/a');await page.getByLabel('NAVIGATION QUESTION').selectOption('Q-IMPLEMENTATION-EVIDENCE');await expect(page.getByRole('heading',{name:'Q-IMPLEMENTATION-EVIDENCE EVIDENCE MAP'})).toBeVisible();const event=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT EVIDENCE MAP'}).click();const download=await event;expect(download.suggestedFilename()).toBe('synthetic-psychedelic-evidence-map.json');const parsed=JSON.parse(await (await import('node:fs/promises')).readFile(await download.path() as string,'utf8'));expect(parsed.version).toBe('079.1.0');expect(parsed.canonical).toEqual({uses:['028','058','063'],creates:'cap:079'});expect(parsed.artifacts).toEqual(['Evidence Navigation Taxonomy','Applicability Filters']);expect(parsed.admission).toEqual({syntheticEvidenceOnly:true,exactRecordCount:5,exactQuestionCount:3,fixedQuestionsAndSourcesOnly:true,sourceTypeQualityClaimPopulationContextOutcomePreserved:true,limitationsUncertaintyAsOfLocatorPreserved:true,outOfScopeAndUnknownsPreserved:true,containsRealPeopleData:false,containsRealClinicalEvidence:false,legalAdvice:'NONE',clinicalAdvice:'NONE',diagnosisTreatmentDosageClaim:false,safetyEffectivenessClaim:false,realWorldApplicabilityDetermined:false,numericScoringOrRanking:false,failClosed:true});expect(parsed.replay).toEqual({questionId:'Q-IMPLEMENTATION-EVIDENCE',engineVersion:'079.1.0'});});

test('079 exposes safety boundaries, contains at 320px, and B builds the evidence map',async({page})=>{await page.goto('/100-builds/079/a');await expect(page.getByText('no real people',{exact:false}).first()).toBeVisible();await expect(page.getByText('dosage',{exact:false}).first()).toBeVisible();await page.setViewportSize({width:320,height:760});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();await page.goto('/100-builds/079/b');await page.getByRole('button',{name:'REORGANIZE RESULTS'}).click();await expect(page.getByRole('status')).toContainText('Search results became a qualified evidence map');});
