import {test,expect} from '@playwright/test';
import {AUDIENCE_CONTEXT_GRAPHS,AUDIENCE_GRAPH_PRESETS,mapAudienceIntelligence} from '../packages/release/src/audience-intelligence-knowledge-graph-engine';

const ontology=['AUDIENCE-CONTEXT','NEED','LANGUAGE','BEHAVIOR','TRUSTED-SOURCE','MISCONCEPTION','CHANNEL','RELATIONSHIP','CONVERSION-EVIDENCE'];
test('082 preserves exactly five context graphs with three sources, nine nodes, and nine edges',()=>{expect(AUDIENCE_CONTEXT_GRAPHS.map(x=>x.id)).toEqual(['GRAPH-CEDAR','GRAPH-HARBOR','GRAPH-LATTICE','GRAPH-MESA','GRAPH-ORBIT']);for(const graph of AUDIENCE_CONTEXT_GRAPHS){expect(graph.sources).toHaveLength(3);expect(graph.nodes).toHaveLength(9);expect(graph.nodes.map(x=>x.kind)).toEqual(ontology);expect(graph.edges).toHaveLength(9);expect(graph.unknowns.length).toBeGreaterThan(0);expect(graph.nodes.every(x=>x.evidenceIds.length>0&&x.caveat.length>0)).toBeTruthy();expect(graph.edges.every(x=>x.evidenceIds.length>0&&x.status==='DESCRIPTIVE-SYNTHETIC-EDGE')).toBeTruthy()}});

test('082 preserves evidence and caveats without trust, influence, or conversion prediction',()=>{for(const graph of AUDIENCE_CONTEXT_GRAPHS){const result=mapAudienceIntelligence(AUDIENCE_GRAPH_PRESETS[graph.id]);expect(result.graph).toEqual(graph);expect(result.ontology).toEqual(ontology);expect(result.nonClaims).toContain('NO TRUSTWORTHINESS, INFLUENCE, PREFERENCE, INTENT, DEMAND, OR CONVERSION DETERMINATION')}expect(mapAudienceIntelligence(AUDIENCE_GRAPH_PRESETS['GRAPH-CEDAR']).audit).toContain('NO PROFILING, TARGETING, PERSUASION, IDENTITY, PSYCHOGRAPHIC, DEMOGRAPHIC, PROTECTED-TRAIT, SCORE, RANK, OR PREDICTION')});

test('082 fails closed on drifted, real-person, profiling, targeting, inference-enabled, and hostile input',()=>{const fixture=AUDIENCE_GRAPH_PRESETS['GRAPH-CEDAR'];expect(mapAudienceIntelligence(fixture)).toEqual(mapAudienceIntelligence(fixture));const hostile={...fixture};Object.defineProperty(hostile,'graphs',{get(){throw new Error('hostile')}});const values=[null,undefined,[],{},'persona',{...fixture,fixtureId:'REAL'},{...fixture,graphId:'OTHER'},{...fixture,extra:true},{...fixture,admission:{...fixture.admission,realPeopleData:true}},{...fixture,admission:{...fixture.admission,protectedTraitData:true}},{...fixture,admission:{...fixture.admission,profiling:true}},{...fixture,admission:{...fixture.admission,targeting:true}},{...fixture,admission:{...fixture.admission,conversionPredicted:true}},{...fixture,inherited:{...fixture.inherited,messageTranslation:'cap:999'}},{...fixture,graphs:[...fixture.graphs,fixture.graphs[0]]},hostile,new Proxy(fixture,{get(){throw new Error('proxy')}})];for(const value of values){expect(()=>mapAudienceIntelligence(value)).not.toThrow();const result=mapAudienceIntelligence(value);expect(result.status).toBe('INVALID');expect(result.graph).toBeNull();expect(result.ontology).toEqual([])}});

test('082-A exports exact admission, artifacts, lineage, and replay',async({page})=>{await page.goto('/100-builds/082/a');await page.getByLabel('AUDIENCE CONTEXT').selectOption('GRAPH-ORBIT');await expect(page.getByRole('heading',{name:'GRAPH-ORBIT AUDIENCE GRAPH'})).toBeVisible();const event=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT AUDIENCE GRAPH'}).click();const download=await event;expect(download.suggestedFilename()).toBe('synthetic-audience-intelligence-graph.json');const parsed=JSON.parse(await (await import('node:fs/promises')).readFile(await download.path() as string,'utf8'));expect(parsed.version).toBe('082.1.0');expect(parsed.canonical).toEqual({uses:['002','011','028','062','081'],creates:'cap:082'});expect(parsed.artifacts).toEqual(['Audience Ontology','Trust & Influence Edges']);expect(parsed.admission).toEqual({syntheticContextsOnly:true,exactGraphCount:5,exactSourcesPerGraph:3,exactNodesPerGraph:9,exactEdgesPerGraph:9,fixedContextsOnly:true,sourceNodeEdgeEvidenceCaveatsPreserved:true,unknownsPreserved:true,containsRealPeopleData:false,containsDemographicData:false,containsProtectedTraitData:false,identityInference:false,psychographicInference:false,profiling:false,targeting:false,persuasionOptimization:false,trustworthinessDetermined:false,influencePredicted:false,conversionPredicted:false,scoreOrRank:false,failClosed:true});expect(parsed.replay).toEqual({graphId:'GRAPH-ORBIT',engineVersion:'082.1.0'});});

test('082 exposes privacy and audience boundaries, contains at 320px, and B expands the persona',async({page})=>{await page.goto('/100-builds/082/a');await expect(page.getByText('no real people',{exact:false}).first()).toBeVisible();await expect(page.getByText('protected-trait',{exact:false}).first()).toBeVisible();await page.setViewportSize({width:320,height:760});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();await page.goto('/100-builds/082/b');await page.getByRole('button',{name:'EXPAND PERSONA CARD'}).click();await expect(page.getByRole('status')).toContainText('One persona became a bounded relationship graph');});
