import {test,expect} from '@playwright/test';
test.describe('Build 028 transparent evidence search',()=>{
 test('shows weights, classification basis, freshness, and tie key',async({page})=>{await page.goto('/100-builds/028/a');await expect(page.getByRole('heading',{name:'RESULTS'})).toBeVisible();await page.getByText('Why this ranked here').first().click();await expect(page.getByText(/label supported by CLASS-01/).first()).toBeVisible();await expect(page.getByText(/zero ranking weight/).first()).toBeVisible();await expect(page.getByText(/TIE DOC-01/).first()).toBeVisible()});
 test('an empty or stopword query does not return the corpus',async({page})=>{await page.goto('/100-builds/028/a');await page.getByLabel('Question or search terms').fill('');await expect(page.getByRole('heading',{name:'QUERY NEEDED'})).toBeVisible();await page.getByLabel('Question or search terms').fill('the and or');await expect(page.getByText(/ignored connective words/)).toBeVisible();await expect(page.locator('ol.results > li')).toHaveCount(0)});
 test('rejects an adversarial oversized query deterministically',async({page})=>{await page.goto('/100-builds/028/a');await page.getByLabel('Question or search terms').fill('privacy '.repeat(30));await expect(page.getByRole('heading',{name:'QUERY INVALID'})).toBeVisible();await expect(page.locator('ol.results > li')).toHaveCount(0)});
 test('concept-map mode does not call unknown tokens meaning matches',async({page})=>{await page.goto('/100-builds/028/a');await page.getByLabel('Search mode').selectOption('meaning');await page.getByLabel('Question or search terms').fill('unmappedtoken');await expect(page.getByRole('heading',{name:'NO MATCH'})).toBeVisible()});
 test('facets filter before scoring and disclose eligibility',async({page})=>{await page.goto('/100-builds/028/a');await page.getByLabel('Topic facet').selectOption('privacy');await expect(page.getByText(/0 ranked · 1 facet-eligible/)).toBeVisible();await page.getByLabel('Question or search terms').fill('privacy');await expect(page.getByText('Data rights operating note')).toBeVisible();await expect(page.locator('ol.results > li')).toHaveCount(1)});
 test('exports a deterministic replay record',async({page})=>{await page.goto('/100-builds/028/a');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT SEARCH TRACE'}).click();const download=await dl;expect(download.suggestedFilename()).toBe('transparent-search-trace.json');const stream=await download.createReadStream();let text='';for await(const chunk of stream)text+=chunk.toString();const report=JSON.parse(text);expect(report.version).toBe('028.2.0');expect(report.result.rankingRuleVersion).toBe('transparent-ranking-v2');expect(report.result.replay.corpusFingerprint).toMatch(/^[0-9a-f]{8}$/);expect(report.result.replay.tieBreak).toMatch(/document ID ascending/)});
 test('fits 320px',async({page})=>{await page.setViewportSize({width:320,height:800});await page.goto('/100-builds/028/a');expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)});
 test('B reranks accessibly and exposes order as text',async({page})=>{await page.goto('/100-builds/028/b');await page.getByRole('button',{name:'PRIVACY'}).click();await expect(page.getByRole('status')).toContainText('PRIVACY');await expect(page.getByRole('status')).toContainText('DATA RIGHTS NOTE')});
});
