import {test,expect} from '@playwright/test';
test.describe('Build 015 legal product engine',()=>{
 test('identifies bounded product candidates and preserves prohibited judgment',async({page})=>{await page.goto('/100-builds/015/a');await expect(page.getByRole('heading',{name:'SAFE CANDIDATES IDENTIFIED'})).toBeVisible();await expect(page.getByText('PRODUCT CANDIDATE',{exact:true}).first()).toBeVisible();await expect(page.getByText('DO NOT PRODUCTIZE',{exact:true})).toBeVisible();});
 test('unsafe collapse is rejected',async({page})=>{await page.goto('/100-builds/015/a');await page.getByRole('button',{name:'COLLAPSE INTAKE INTO ADVICE'}).click();await expect(page.getByText('DO NOT PRODUCTIZE',{exact:true}).first()).toBeVisible();});
 test('reset exposes supervision gaps',async({page})=>{await page.goto('/100-builds/015/a');await page.getByRole('button',{name:'RESET / START EMPTY'}).click();await expect(page.getByRole('heading',{name:'SUPERVISION REQUIRED'})).toBeVisible();});
 test('exports candidate map',async({page})=>{await page.goto('/100-builds/015/a');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'EXPORT CANDIDATE MAP'}).click();expect((await dl).suggestedFilename()).toBe('legal-product-candidate-map.json');});
 test('canonical room is active and 016 remains planned',async({page})=>{await page.goto('/100-builds/015');await expect(page.getByText('BUILD 015 / 100 · IN THE LAB')).toBeVisible();await expect(page.getByRole('link',{name:/OPEN THE TOOL/})).toHaveAttribute('href',/\/100-builds\/015\/a\/?$/);await page.goto('/100-builds/016');await expect(page.getByText('BUILD 016 / 100 · COMING NEXT')).toBeVisible();});
 test('functional artifact fits 320 CSS pixels',async({page})=>{await page.setViewportSize({width:320,height:800});await page.goto('/100-builds/015/a');await expect(page.getByRole('button',{name:'EXPORT CANDIDATE MAP'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false);});
});
test('paired visual reaches governed product state',async({page})=>{await page.goto('/100-builds/015/b');await page.getByRole('button',{name:/05 GOVERN/}).click();await expect(page.getByText('GOVERNED INTERNAL PRODUCT')).toBeVisible();});
