import{expect,test}from'@playwright/test';
const IDS=Array.from({length:100},(_,i)=>String(i+1).padStart(3,'0'));
const ARCHIVE_IDS=IDS.slice(0,44);
const RECORD_IDS=IDS.slice(0,6);
const OVERVIEWS=['/','/100-builds','/100-builds/archive','/lineage'];
const PUBLIC_ROUTES=[...OVERVIEWS,...IDS.flatMap(id=>[`/100-builds/${id}`,`/100-builds/${id}/a`,`/100-builds/${id}/b`]),...ARCHIVE_IDS.map(id=>`/100-builds/${id}/archive`),...RECORD_IDS.map(id=>`/100-builds/${id}/record`)];
const UNPUBLISHED=[...IDS.slice(44).map(id=>`/100-builds/${id}/archive`),...IDS.slice(6).map(id=>`/100-builds/${id}/record`)];
async function batches<T>(values:T[],size:number,fn:(value:T)=>Promise<void>){for(let i=0;i<values.length;i+=size)await Promise.all(values.slice(i,i+size).map(fn))}
test('complete published route contract is anonymous, indexable and metadata-bearing',async({request})=>{expect(PUBLIC_ROUTES).toHaveLength(354);await batches(PUBLIC_ROUTES,16,async path=>{const response=await request.get(path,{maxRedirects:0});const location=response.headers().location??'';expect(response.status(),`${path} returned ${response.status()} ${location}`).toBe(200);expect(location.toLowerCase()).not.toContain('sso');expect((response.headers()['x-robots-tag']??'').toLowerCase()).not.toContain('noindex');const type=response.headers()['content-type']??'';if(type.includes('text/html')){const html=await response.text();expect(html,`${path} has no title`).toMatch(/<title>[^<]+<\/title>/i);expect(html,`${path} has no canonical`).toMatch(/<link[^>]+rel=["']canonical["'][^>]+href=["'][^"']+["']/i)}})});
test('unpublished archive and record URLs fail honestly rather than serving false records',async({request})=>{await batches(UNPUBLISHED,20,async path=>{const response=await request.get(path,{maxRedirects:0});expect(response.status(),`${path} should remain unpublished`).toBe(404)})});
test('every exposed internal link from overview, detail and archive surfaces resolves',async({request})=>{const sources=[...OVERVIEWS,...IDS.map(id=>`/100-builds/${id}`),...ARCHIVE_IDS.map(id=>`/100-builds/${id}/archive`)];const targets=new Set<string>();await batches(sources,12,async path=>{const response=await request.get(path);expect(response.status(),path).toBe(200);const html=await response.text();for(const match of html.matchAll(/href=["']([^"'#]+)["']/gi)){const href=match[1];if(href.startsWith('/')&&!href.startsWith('/_next/'))targets.add(href.split('?')[0])}});await batches([...targets].sort(),16,async path=>{const response=await request.get(path,{maxRedirects:0});expect(response.status(),`broken internal link ${path}`).toBe(200)})});
test('representative keyboard names and narrow layout remain intact across release layers',async({page})=>{await page.setViewportSize({width:320,height:900});for(const path of ['/100-builds','/100-builds/001','/100-builds/001/a','/100-builds/001/b','/100-builds/001/archive','/100-builds/001/record','/100-builds/100/a','/100-builds/100/b']){await page.goto(path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),path).toBeTruthy();const controls=page.locator('a,button,input,select,textarea');for(let i=0;i<await controls.count();i++){const node=controls.nth(i);if(await node.isVisible())expect((await node.getAttribute('aria-label'))?.trim()||await node.textContent()||await node.getAttribute('name')||'',`${path} unnamed control ${i}`).not.toBe('')}}});
