'use client';
import {useMemo,useState} from 'react';
import {decisionGapScore,decisionGapTier} from '../../../../../../packages/release/src/decision-engines';
import s from './software-worthiness.module.css';

type Signals={frequency:number;consequence:number;ambiguity:number;fragmentation:number;value:number;softwareAdvantage:number;dataAsset:number;buyerClarity:number;maintenance:number;serviceJudgment:number;networkScale:number};
type Form='SOFTWARE'|'SERVICE'|'DATASET'|'COMPANY'|'KEEP SIMPLE';
const initial:Signals={frequency:4,consequence:3,ambiguity:4,fragmentation:4,value:4,softwareAdvantage:4,dataAsset:3,buyerClarity:3,maintenance:2,serviceJudgment:2,networkScale:2};
const meta:[keyof Signals,string,string][]=[['frequency','How often does the decision recur?','Rare → constant'],['consequence','How much does getting it wrong matter?','Minor → serious'],['ambiguity','How unclear is the right answer?','Clear → ambiguous'],['fragmentation','How scattered is the needed information?','Together → fragmented'],['value','How much useful value does solving it create?','Low → high'],['softwareAdvantage','How much better is software than a simple template/process?','Little → major'],['dataAsset','Does repeated use create a durable data/evidence asset?','No → strongly'],['buyerClarity','Is there a clear buyer or accountable owner?','Unclear → clear'],['maintenance','How much ongoing maintenance burden will the product create?','Low → high'],['serviceJudgment','How much expert judgment remains central?','Low → high'],['networkScale','Does value increase meaningfully across many users/organizations?','No → strongly']];
function classify(v:Signals,description:string){const gap=decisionGapScore({frequency:v.frequency,consequence:v.consequence,ambiguity:v.ambiguity,fragmentation:v.fragmentation},3,description);let form:Form;const reasons:string[]=[];
 if(v.value<=2||gap<35){form='KEEP SIMPLE';reasons.push(v.value<=2?'The value signal is too weak to justify product overhead.':'The underlying decision gap is still weak; preserve the simple process until the problem is clearer.');}
 else if(v.serviceJudgment>=4&&v.softwareAdvantage<=3){form='SERVICE';reasons.push('Expert judgment remains the main source of value, while software adds limited advantage.');}
 else if(v.dataAsset>=4&&v.softwareAdvantage<=3){form='DATASET';reasons.push('The durable asset appears to be structured evidence/data rather than a full software product.');}
 else if(v.networkScale>=4&&v.buyerClarity>=4&&v.softwareAdvantage>=4){form='COMPANY';reasons.push('The opportunity combines a clear buyer, software advantage, and cross-user scale that may justify an operating company rather than a narrow tool.');}
 else if(v.softwareAdvantage>=4&&v.frequency>=3&&v.buyerClarity>=3&&v.maintenance<=3){form='SOFTWARE';reasons.push('The problem recurs, software materially improves the job, an owner is visible, and maintenance burden is not yet dominant.');}
 else {form='KEEP SIMPLE';reasons.push('The opportunity has not cleared enough form-specific gates to justify additional product structure.');}
 if(v.maintenance>=4)reasons.push('Maintenance burden is high enough to challenge the product case.');if(v.buyerClarity<=2)reasons.push('Buyer/owner clarity is weak; value may exist without a sustainable product path.');reasons.push(`Build 003 inheritance: decision gap ${gap}/100 · ${decisionGapTier(gap)}.`);return {form,reasons,gap};}
export default function SoftwareWorthinessLab(){const [idea,setIdea]=useState('A decision workspace that helps teams decide whether an AI workflow is safe enough to launch.');const [signals,setSignals]=useState<Signals>(initial);const [status,setStatus]=useState('');const result=useMemo(()=>classify(signals,idea),[signals,idea]);function reset(){setIdea('A decision workspace that helps teams decide whether an AI workflow is safe enough to launch.');setSignals(initial);setStatus('Reset to the demonstration idea.')}function exportRecord(){const payload={build:'006-A',engineVersion:'006.1.0',inherits:['003.1.0','005.1.0'],idea,signals,result,limitations:['form classification is a product-discovery heuristic','does not establish demand, market size, ROI, legal permission, technical feasibility, or investment readiness','SOFTWARE and COMPANY mean investigate/prototype, not launch']};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download='software-worthiness-record.json';a.click();URL.revokeObjectURL(href);setStatus('Software-worthiness record exported as JSON.')}
 function updateSignal(key:keyof Signals,value:number){setSignals(v=>({...v,[key]:value}))}
 return <div className={s.app}><section className={s.intro}><span>01 / START WITH THE JOB</span><h2>Software is a form. It is not the default answer.</h2><p>Test the problem first, then test whether software creates enough advantage to deserve its own maintenance, ownership, and operating burden.</p></section>{status&&<p className={s.status} role="status" aria-live="polite">{status}</p>}<section className={s.idea}><label>What are you thinking about building?<textarea rows={4} value={idea} onInput={e=>setIdea(e.currentTarget.value)} maxLength={2000}/></label></section><section className={s.gates}><span>02 / PASS THE FORM GATES</span>{meta.map(([key,label,hint])=><label key={key}><span><b>{label}</b><small>{hint}</small></span><input aria-label={label} type="range" min="1" max="5" value={signals[key]} onInput={e=>{const value=Number(e.currentTarget.value);updateSignal(key,value)}}/><strong>{signals[key]} / 5</strong></label>)}</section><section className={s.result} aria-live="polite"><span>CANDIDATE FORM</span><h3>{result.form}</h3><p>Inherited decision-gap signal: <strong>{result.gap}/100 · {decisionGapTier(result.gap)}</strong></p><ul>{result.reasons.map(x=><li key={x}>{x}</li>)}</ul></section><section className={s.forms}><span>03 / FIVE POSSIBLE FUTURES</span><div>{(['SOFTWARE','SERVICE','DATASET','COMPANY','KEEP SIMPLE'] as Form[]).map(x=><article data-active={result.form===x} key={x}><h3>{x}</h3><p>{x==='SOFTWARE'?'A repeatable interface/system materially improves the recurring job.':x==='SERVICE'?'Expert judgment remains the primary value and software should stay assistive.':x==='DATASET'?'The durable asset is structured evidence, records, or data—not the interface.':x==='COMPANY'?'The opportunity may require an operating system around product, buyer, delivery, and scale.':'A template, checklist, spreadsheet, or manual process is still the stronger answer.'}</p></article>)}</div></section><div className={s.actions}><button onClick={exportRecord}>EXPORT RECORD</button><button onClick={reset}>RESET / START OVER</button></div><p className={s.boundary}><strong>Boundary:</strong> this tool chooses a candidate form for investigation. It does not prove product-market fit, willingness to pay, feasibility, defensibility, legal permission, or investment readiness.</p></div>}
