'use client';
import {useMemo,useState} from 'react';
import s from './form-gate.module.css';
type Form='SOFTWARE'|'SERVICE'|'DATASET'|'COMPANY'|'KEEP SIMPLE';
type Mode='BASELINE'|'MORE JUDGMENT'|'STRONGER DATA'|'CLEARER BUYER'|'HEAVIER MAINTENANCE';
const modes:Mode[]=['BASELINE','MORE JUDGMENT','STRONGER DATA','CLEARER BUYER','HEAVIER MAINTENANCE'];
const base={value:4,software:4,data:3,buyer:3,maintenance:2,judgment:2,network:2};
function state(mode:Mode){const v={...base};if(mode==='MORE JUDGMENT'){v.judgment=5;v.software=2}if(mode==='STRONGER DATA'){v.data=5;v.software=2}if(mode==='CLEARER BUYER'){v.buyer=5;v.network=5;v.software=5}if(mode==='HEAVIER MAINTENANCE'){v.maintenance=5}return v}
function classify(v:ReturnType<typeof state>):Form{if(v.value<=2)return'KEEP SIMPLE';if(v.judgment>=4&&v.software<=3)return'SERVICE';if(v.data>=4&&v.software<=3)return'DATASET';if(v.network>=4&&v.buyer>=4&&v.software>=4)return'COMPANY';if(v.software>=4&&v.buyer>=3&&v.maintenance<=3)return'SOFTWARE';return'KEEP SIMPLE'}
const forms:Form[]=['SOFTWARE','SERVICE','DATASET','COMPANY','KEEP SIMPLE'];
export default function FormGateField(){const[mode,setMode]=useState<Mode>('BASELINE');const values=useMemo(()=>state(mode),[mode]);const result=classify(values);const signals=[['VALUE',values.value],['SOFTWARE ADVANTAGE',values.software],['DATA ASSET',values.data],['BUYER CLARITY',values.buyer],['MAINTENANCE',values.maintenance],['EXPERT JUDGMENT',values.judgment],['NETWORK SCALE',values.network]] as const;return <div className={s.app}><div className={s.controls} role="group" aria-label="Candidate form scenario">{modes.map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m}</button>)}</div><section className={s.field} aria-live="polite"><header><span>FORM FIELD / {mode}</span><h2>What form does the opportunity actually deserve?</h2><p>Software is only one possible destination. Change the conditions and watch the candidate form move.</p></header><div className={s.signalGrid}>{signals.map(([name,val])=><article key={name}><span>{name}</span><div aria-label={`${name} ${val} of 5`}><i style={{width:`${val*20}%`}}/></div><strong>{val}/5</strong></article>)}</div><div className={s.forms}>{forms.map(f=><article key={f} data-active={f===result}><small>{f===result?'CURRENT CANDIDATE':'ALTERNATIVE FORM'}</small><h3>{f}</h3><p>{f==='SOFTWARE'?'Use when software materially improves a recurring job and the ownership/maintenance burden is justified.':f==='SERVICE'?'Use when expert judgment is still the main source of value.':f==='DATASET'?'Use when the durable asset is structured evidence or data rather than an interface.':f==='COMPANY'?'Use when product, buyer, delivery and network scale imply a larger operating system.':'Use when extra product structure would create more burden than value.'}</p></article>)}</div></section><section className={s.argument}><span>THE POINT</span><h2>Build the form the problem earns.</h2><p>A sophisticated product decision can end with “keep it simple.” The technological ceiling is not the maximum amount of software you can add; it is the most appropriate system the problem can justify.</p></section></div>}
