'use client';
import {useState} from 'react';
import {EVIDENCE_TRANSLATION_CASES,EVIDENCE_TRANSLATION_ENGINE_VERSION,EVIDENCE_TRANSLATION_PRESETS,translateCannabisEvidence,type EvidenceCaseId} from '../../../../../../packages/release/src/cannabis-evidence-translation-engine';
import s from '../evidence-translation.module.css';
export default function EvidenceTranslationLayer(){
 const [caseId,setCaseId]=useState<EvidenceCaseId>('EVIDENCE-CEDAR');const input=EVIDENCE_TRANSLATION_PRESETS[caseId];const result=translateCannabisEvidence(input);const t=result.translation!;
 function download(){const snapshot={build:'078',version:EVIDENCE_TRANSLATION_ENGINE_VERSION,canonical:{uses:['002','031','051','058'],creates:'cap:078'},artifacts:['Evidence Translation Protocol','Audience Caveat Rules'],admission:{syntheticEvidenceOnly:true,exactCaseCount:5,fixedAudiencePerCase:true,sourceTypeAndQualityPreserved:true,claimPopulationInterventionComparisonOutcomePreserved:true,limitationsUncertaintyAsOfCaveatsPreserved:true,containsRealPatientData:false,containsRealProductData:false,currentLawClaim:false,legalAdvice:'NONE',clinicalAdvice:'NONE',diagnosisTreatmentDosageClaim:false,safetyEffectivenessClaim:false,complianceDetermined:false,failClosed:true},input:structuredClone(input),result:structuredClone(result),replay:{caseId,engineVersion:EVIDENCE_TRANSLATION_ENGINE_VERSION}};const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='synthetic-cannabis-evidence-translation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
 return <section className={s.layer}><header className={s.status} role="status" aria-live="polite" aria-atomic="true"><small>ACTIVE FIXED SYNTHETIC RECORD</small><h2>{result.status}</h2><p>Audience: {t.audience}. The claim boundary, evidence quality, limitations, uncertainty, and as-of date remain attached.</p></header><div className={s.controls} aria-label="Evidence translation controls"><label htmlFor="translation-case">TRANSLATION CASE<select id="translation-case" value={caseId} onChange={e=>setCaseId(e.target.value as EvidenceCaseId)}>{EVIDENCE_TRANSLATION_CASES.map(x=><option key={x.caseId} value={x.caseId}>{x.audience} · {x.truthAnchor.title}</option>)}</select></label><button type="button" onClick={()=>setCaseId('EVIDENCE-CEDAR')}>RESTORE CEDAR CASE</button><button type="button" onClick={download}>EXPORT TRANSLATION RECORD</button></div><aside className={s.boundary}><b>This is synthetic evidence, not medical or legal guidance.</b><p>No real patients, products, or research are present. It makes no current-law, compliance, diagnosis, treatment, dosage, safety, or effectiveness claim.</p></aside><article className={s.record}><small>{t.truthAnchor.sourceId} · {t.truthAnchor.syntheticStatus} · AS OF {t.truthAnchor.asOf}</small><h3>{t.truthAnchor.title}</h3><p><b>{t.truthAnchor.sourceType} · {t.truthAnchor.sourceQuality}</b></p><p>{t.truthAnchor.claim}</p></article><div className={s.translation}><article className={s.column}><small>01 · TRUTH ANCHOR</small><h3>What the fixture records</h3><ul><li><b>Population:</b> {t.truthAnchor.population}</li><li><b>Intervention/exposure:</b> {t.truthAnchor.interventionOrExposure}</li><li><b>Comparison:</b> {t.truthAnchor.comparison}</li><li><b>Outcome:</b> {t.truthAnchor.outcome}</li></ul></article><article className={s.column}><small>02 · AUDIENCE TRANSLATION</small><h3>{t.audience}</h3><p>{t.translatedExplanation}</p></article><article className={s.column}><small>03 · CAVEATS</small><h3>What must travel</h3><ul>{t.caveats.map(x=><li key={x}>{x}</li>)}</ul></article></div><div className={s.audit}><article><small>LIMITATIONS</small><ul>{t.truthAnchor.limitations.map(x=><li key={x}>{x}</li>)}</ul><p><b>Uncertainty:</b> {t.truthAnchor.uncertainty}</p></article><article><small>PRESERVED FIELDS</small><ul>{t.preservedFields.map(x=><li key={x}>{x}</li>)}</ul></article><article><small>TRANSLATION AUDIT</small><ol>{result.audit.map(x=><li key={x}>{x}</li>)}</ol></article></div><p className={s.note}><b>Boundary:</b> Fixed synthetic translation only. No patient-specific, product-specific, current-law, legal, medical, diagnosis, treatment, dosage, safety, effectiveness, or compliance claim.</p></section>
}
