'use client';
import{useState}from'react';
import{buildLegalKnowledgeGraph,LEGAL_KNOWLEDGE_SCENARIOS,LEGAL_KNOWLEDGE_GRAPH_ENGINE_VERSION,type LegalKnowledgeScenarioId}from'../../../../../../packages/release/src/legal-knowledge-graph-engine';
import s from'../legal-memory.module.css';

const ids:LegalKnowledgeScenarioId[]=['MEMORY-CONNECTED','AUTHORITY-UNVERIFIED','ACCESS-RESTRICTED','CONFLICTING-OUTCOME','LESSON-UNREVIEWED'];
const label=(value:string)=>value.replaceAll('-',' ');

export default function LegalKnowledgeGraph(){
 const[id,setId]=useState<LegalKnowledgeScenarioId>('MEMORY-CONNECTED'),input=LEGAL_KNOWLEDGE_SCENARIOS[id],result=buildLegalKnowledgeGraph(input);
 const groups=[['MATTERS',result.matters],['AUTHORITIES',result.authorities],['ARGUMENTS',result.arguments],['DOCUMENTS',result.documents],['EXPERTS',result.experts],['OUTCOMES',result.outcomes],['WORKFLOWS',result.workflows],['LESSONS',result.lessons]]as const;
 function download(){const snapshot={build:'066',version:LEGAL_KNOWLEDGE_GRAPH_ENGINE_VERSION,fixture:'synthetic',exportedAt:new Date().toISOString(),canonical:{title:'Legal Knowledge Graph / Institutional Memory System',visualTitle:'The Firm Knows More Than Its Folders',uses:['028','029','058','059','063'],creates:'cap:066'},admission:{containsRealClients:false,containsRealMatters:false,containsRealPeople:false,currentLawClaim:false,citationValidityClaim:false,privilegeDetermination:false,legalAdvice:false,persistence:'NONE'},input:structuredClone(input),result:structuredClone(result),boundaries:['No legal advice or attorney-client relationship.','No determination of privilege, confidentiality, current law, citation validity, identity, or authorization to reuse.','A graph edge is a declared synthetic relationship, not proof of legal or factual relevance.']};const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='synthetic-legal-knowledge-graph.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
 return <section className={s.lab} aria-labelledby="graph-status" data-graph-state={id}>
  <header className={s.status} role="status" aria-live="polite" aria-atomic="true"><small>KNOWLEDGE STATE · {label(id)}</small><h2 id="graph-status">{result.status}</h2><p>{result.relationships[0]??'No open graph relationship is recorded in this fixed state.'}</p></header>
  <div className={s.controls} aria-label="Legal knowledge graph controls"><label htmlFor="graph-state">KNOWLEDGE STATE<select id="graph-state" value={id} onChange={event=>setId(event.target.value as LegalKnowledgeScenarioId)}>{ids.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><button type="button" onClick={()=>setId('MEMORY-CONNECTED')}>RESTORE RECORDED GRAPH</button><button type="button" onClick={download}>EXPORT KNOWLEDGE GRAPH</button></div>
  <aside className={s.warning} aria-label="Legal and confidentiality limitations"><h3>A connection is not clearance.</h3><p>Do not enter real client, matter, person, confidential, privileged, sealed, protected, or identifying information. Verify law, citations, access, purpose, privilege, confidentiality, and reuse authority outside this demonstration.</p></aside>
  <div className={s.boundaryGrid} aria-label="Graph governance boundaries"><article><small>NO LEGAL ADVICE</small><p>This demonstration does not provide advice, analysis, representation, or create an attorney-client relationship.</p></article><article><small>ACCESS</small><p>Visibility does not establish authorization. Purpose, role, matter, and field-level access remain separate questions.</p></article><article><small>AUTHORITY</small><p>Linked does not mean current, valid, controlling, cited correctly, or applicable.</p></article><article><small>REUSE</small><p>Similarity does not establish permission to copy, rely on, disclose, or reuse.</p></article></div>
  <div className={s.graph} aria-label="Fixed synthetic matter relationship graph">{groups.map(([title,items])=><article key={title} data-node-kind={title.toLowerCase()}><small>{title}</small>{items.length?<ul>{items.map(item=><li key={item}>{item}</li>)}</ul>:<p>None recorded.</p>}</article>)}</div>
  <aside className={s.provenance} aria-label="Graph provenance"><h3>Recorded provenance</h3><ul>{result.provenance.map(item=><li key={item}>{item}</li>)}</ul></aside><aside className={s.unknowns} aria-label="Graph unknowns"><h3>What the graph does not know</h3><ul>{result.unknowns.map(item=><li key={item}>{item}</li>)}</ul></aside>
  <p className={s.note}><b>Boundary:</b> Fixed synthetic fixtures only. This graph does not determine legal relevance, current law, citation validity, privilege, confidentiality, identity, factual accuracy, professional duties, or whether any access, disclosure, reliance, or reuse is authorized.</p>
 </section>
}
