import type {Metadata} from 'next';
import ReconstructionCaseStudy,{type ReconstructionData} from '../../_components/ReconstructionCaseStudy';
export const metadata:Metadata={title:'Build 030 complete reconstruction: Inclusive Experience Repair Lab',description:'Technical reconstruction of Build 030: mapping engine, evidence, tests, limitations, reproduction, and release gates.',alternates:{canonical:'/100-builds/030/reconstruction'}};
const data:ReconstructionData={
 id:'030',title:'Inclusive Experience Repair Lab',decision:'REVISE',thesis:'A deterministic teaching and inspection tool that turns selected interface constraints into explicit repair controls, combined-condition warnings, and a replayable local record—without pretending to simulate a disabled person or prove accessibility.',decisionNote:'Keep as the second flagship, but retire “simulator” as the lead promise. Launch only after disabled-participant and assistive-technology review.',
 question:'Can a product team make its accessibility, language, bandwidth, motion, color, and density assumptions visible as inspectable interface controls—then understand why enabling controls is only the beginning of validation?',
 people:[['Product or design team','Selects synthetic constraints, inspects mapped controls, and owns implementation and follow-up testing.'],['Disabled participants','Provide experience the engine cannot infer. They are research partners, not generated profiles.'],['Accessibility specialist','Combines standards knowledge, manual inspection, assistive-technology testing, and participant findings.'],['Localization specialist','Evaluates language, cultural context, expansion, reading level, and target-market meaning.'],['Engineering owner','Implements controls, preserves semantics and performance, and links changes to an accountable trace.'],['Prototype','Applies declared mappings and two interactions. It does not diagnose, personalize, represent lived experience, or certify repair.']],
 authority:['The engine may report missing declared controls and invalid evidence metadata.','It cannot decide that an interface is accessible, inclusive, localized, usable, legally compliant, or repaired.','Release authority must combine standards evaluation with disabled-user, assistive-technology, device, network, language, and cultural testing.'],
 architecture:[['Transient selection','Seven checkboxes describe synthetic interface conditions: low vision, color-independent, keyboard-only, reduced motion, low bandwidth, plain language, and reduced density.'],['Control state','Nine toggles represent text scaling, contrast, non-color cues, focus, target size, motion, lightweight delivery, plain language, and density.'],['Evidence validation','Every source needs a unique ID, title, HTTPS URL, allowed scope, valid review date, no future date, and ≤366-day freshness.'],['Mapping engine','Selected conditions produce missing-control findings from a disclosed lookup table. No model, diagnosis, telemetry, or personalization is involved.'],['Interaction pass','Two declared combinations add warnings: low vision plus low bandwidth; keyboard-only plus reduced density.'],['Status and replay','Failures block; gaps report MAPPED GAPS; otherwise MAPPED CONTROLS PRESENT. Export preserves inputs, findings, versions, evidence, privacy, and replay.']],
 algorithm:['Order selected conditions using fixed NEED_ORDER.','Block when demonstration consent is absent, persistence is true, the change trace is blank, or the assessment date is invalid.','Validate evidence identity, title, HTTPS source, scope, uniqueness, review date, freshness, and future dating.','For each selected condition, emit a finding for every disabled mapped control.','Evaluate only two registered cross-condition interactions; do not infer others.','Order enabled controls using fixed REPAIR_ORDER.','Return CONTROL BLOCKED for control/evidence errors, MAPPED GAPS for remaining findings, otherwise MAPPED CONTROLS PRESENT.','Always return limits: synthetic fixture, controls do not prove outcomes, and manual testing remains required.'],
 states:[['CONTROL BLOCKED','Consent, privacy, trace, date, or evidence integrity is invalid.'],['MAPPED GAPS','At least one declared mapping or interaction remains unresolved.'],['MAPPED CONTROLS PRESENT','Every declared mapping is enabled. This deliberately does not say Repaired.'],['EXPORTED','The visitor downloaded original and derived state, versions, evidence, limits, and replay input.']],
 boundaries:[['REAL','A versioned pure engine, seven conditions, nine controls, two interactions, evidence validation, UI transformations, keyboard flow, and replay exist.'],['SYNTHETIC','The fixture and selections are invented interface conditions—not a person, disability, diagnosis, identity, culture, device, or lived experience.'],['RN MAPPING','The lookup table, interactions, fixture, statuses, and sequence are RN product design. WCAG does not prescribe this engine.'],['MISSING','No disabled-participant study, assistive-technology matrix, physical-device matrix, language evaluation, network field test, or efficacy evidence.'],['PROHIBITED','Do not claim disability simulation, empathy simulation, WCAG conformance, compliance, localization quality, usability, accessibility, or proven repair.'],['PRIVATE BY DESIGN','Selections remain component-local; persistence blocks and export is explicit.']],
 failures:[['False empathy from simulation','Lead with repair lab and explain that no configuration reproduces lived experience.'],['Checklist becomes certification','Use MAPPED CONTROLS PRESENT and require independent evaluation.'],['Mappings oversimplify needs','Treat them as a scaffold and revise with disabled participants.'],['Interaction explosion','Only two are known. Add interactions with evidence and tests.'],['Visual change lacks semantics','Test keyboard order, names, roles, announcements, and assistive output separately.'],['Plain language becomes localization','Require target-language and cultural review.'],['Lightweight mode becomes network proof','Measure actual payloads and field conditions.']],
 tests:['Initial fixture reports MAPPED GAPS and says selections are not a person or diagnosis.','All mappings report MAPPED CONTROLS PRESENT and never render Repaired.','Low-vision plus low-bandwidth emits the declared interaction warning.','Export verifies engine 030.2.0, ordering, derived status, mapping 030-map-2, privacy, and replay.','320px has no horizontal overflow and retains seven native checkboxes.','B-route forward/backward sequence works by keyboard with live, honest status.'],
 reproduce:['Define a small list of interface conditions; never label them diagnoses or personas.','Define observable repair controls separately.','Write and version an explicit condition-to-control table.','Declare interactions individually; never imply completeness.','Fail closed on framing consent, persistence, trace, date, and evidence metadata.','Return states separating invalid context, unresolved mappings, and complete declared mappings.','Render a synthetic fixture while testing semantics separately.','Keep selections transient and export explicit.','Export original input, findings, ordering, versions, evidence, privacy, and limits.','Test incomplete, complete, interaction, invalid evidence/privacy, keyboard, motion, and narrow width.','Run manual assistive-technology, device, network, language, and cultural tests.','Evaluate the model with disabled participants before launch.'],
 sources:[{title:'W3C — Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/',locator:'Guidelines 1.3, 1.4, 2.1–2.5, 3.1, 3.3; Conformance §5',use:'Criteria for adaptable content, contrast, keyboard, focus, targets, motion, readable content, and input assistance.',limit:'WCAG does not simulate disability, prescribe this mapping engine, or make toggles conformant.'},{title:'W3C WAI — Making Content Usable for People with Cognitive and Learning Disabilities',url:'https://www.w3.org/TR/coga-usable/',locator:'Objectives, design patterns, document status, and scope',use:'Guidance for understandable content, assistance, focus, and cognitive burden.',limit:'Not a conformance claim and not representative of every cognitive or learning disability.'},{title:'W3C WAI — Involving Users in Evaluating Web Accessibility',url:'https://www.w3.org/WAI/test-evaluate/involving-users/',locator:'Introduction; range of evaluation; throughout development',use:'Counterevidence to the idea that standards inspection or simulation replaces disabled participants.',limit:'Participant work complements standards evaluation; one participant cannot represent everyone.'},{title:'W3C WAI — Using Combined Expertise to Evaluate Web Accessibility',url:'https://www.w3.org/WAI/test-evaluate/combined-expertise/',locator:'Introduction and types of expertise',use:'Combining technical, disability, usability, and other perspectives.',limit:'It does not validate this prototype or specify these mappings.'}],
 research:[['COMPLETE','Mapping behavior, evidence validation, deterministic replay, privacy guard, automated keyboard, and 320px fixture.'],['NOT CONDUCTED','Observed sessions with disabled participants.'],['NOT CONDUCTED','Manual screen-reader and assistive-technology matrix.'],['NOT CONDUCTED','Physical touch-device, zoom, and constrained-network field testing.'],['NOT CONDUCTED','Representative-language and cultural-context evaluation.'],['NOT CONDUCTED','Understanding of “mapped controls present” versus “accessible.”']],
 production:['Rename the public artifact Inclusive Experience Repair Lab; retain the historical title only in the record.','Recruit and pay disabled participants with varied access methods to test premise, categories, controls, and result language.','Review relevant WCAG criteria and document technique, result, and scope.','Test keyboard, two screen-reader/browser pairs, 200–400% zoom, reflow, targets, forced colors, reduced motion, and status announcements.','Measure transfer size and interaction on constrained networks and lower-powered devices.','Test plain language separately from translation and cultural adaptation.','Revise or delete misleading or falsely reassuring mappings.','Version participant-informed changes and rerun all tests.','Only then compare creative territories and launch around visible assumptions—not simulated disability.'],
 creative:['THE ASSUMPTION GRID — hidden defaults occupy a rigid Dutch-modernist grid; each tested condition interrupts it.','ONE INTERFACE, MANY CONDITIONS — one object is recomposed through input, bandwidth, language, motion, contrast, and density.','PRESENT ≠ PROVEN — enabled controls confront validated experience; the gap is the hook.'],
 evidence:['A working A-route repair lab and interactive B-route exist.','The engine and mapping versions are explicit and deterministic.','The export contains original state, derived state, evidence, privacy, limitations, and replay.','The false-assurance label Repaired was replaced by MAPPED CONTROLS PRESENT.','Automated behavior, keyboard, export, and 320px fixtures exist.'],
 open:['Disabled-participant evaluation.','Assistive-technology and device matrix.','Mapping completeness and interaction review.','Localization and cultural-context evaluation.','Public rename and canonical-title treatment.','Creative territory comparison and selection.']
};
export default function Page(){return <ReconstructionCaseStudy data={data}/>}
