'use client';
import {useMemo,useState} from 'react';
import s from './feasibility-field.module.css';
const scenarios={
 metro:{name:'Connected metro office',values:{connectivity:5,power:5,access:4,workforce:5,authority:3},authority:'Worker council + service owner',note:'Infrastructure is strong; authority and access still require evidence.'},
 island:{name:'Remote island service region',values:{connectivity:2,power:3,access:3,workforce:2,authority:2},authority:'Affected-community council + local operator',note:'Offline continuity, maintenance, and local approval reshape the design.'},
 emergency:{name:'Post-disruption field site',values:{connectivity:1,power:1,access:2,workforce:3,authority:4},authority:'Incident lead + community representative',note:'Fallback and stop conditions dominate; cloud-first assumptions fail.'}
} as const;
type Key=keyof typeof scenarios.metro.values;const labels:Record<Key,string>={connectivity:'Network',power:'Power',access:'Accessible use',workforce:'Local support',authority:'Local authority'};
export default function FeasibilityField(){const[mode,setMode]=useState<keyof typeof scenarios>('metro');const[values,setValues]=useState<Record<Key,number>>({...scenarios.metro.values});const scenario=scenarios[mode];const score=useMemo(()=>Math.round(Object.values(values).reduce((a,b)=>a+b,0)/25*100),[values]);const status=score>=80?'PILOT PATH OPEN':score>=50?'ADAPT BEFORE PILOT':'TRANSFER ASSUMPTION FAILS';
 function choose(k:keyof typeof scenarios){setMode(k);setValues({...scenarios[k].values})}
 return <div className={s.stage}><nav aria-label="Place scenarios">{(Object.keys(scenarios) as (keyof typeof scenarios)[]).map(k=><button key={k} aria-pressed={mode===k} onClick={()=>choose(k)}>{scenarios[k].name}</button>)}</nav><section className={s.map}><header><span>SAME TECHNOLOGY / DIFFERENT PLACE</span><h2>{scenario.name}</h2><p>{scenario.note}</p></header><div className={s.radar} aria-label="Feasibility dimensions">{(Object.keys(values) as Key[]).map((k,i)=><label key={k} style={{'--level':values[k],'--index':i} as React.CSSProperties}><span>{labels[k]}</span><input aria-label={labels[k]} type="range" min="0" max="5" value={values[k]} onChange={e=>setValues(v=>({...v,[k]:Number(e.currentTarget.value)}))}/><output>{values[k]}/5</output></label>)}</div><aside aria-live="polite"><span>FEASIBILITY FIELD</span><strong>{status}</strong><b>{score}%</b></aside></section><section className={s.authority}><span>LOCAL HUMAN AUTHORITY</span><h2>{scenario.authority}</h2><p>The map can reveal a weak assumption. Only people with local knowledge and legitimate authority can accept conditions, require adaptation, pause, or stop the pilot.</p></section><section className={s.readout}><h2>What changed?</h2><ol><li>Infrastructure changes the operating form.</li><li>Access needs change the interface and support model.</li><li>Local authority changes whether a pilot may proceed at all.</li><li>A fallback and stop condition matter more as capacity falls.</li></ol><p><strong>Color is never the only signal:</strong> every state is named, scored, and structurally labeled.</p></section></div>}
