'use client';
import{useMemo,useState}from'react';
import{exportScenario,runScenario,type Intervention,type Shock}from'../../../../../../packages/release/src/build100-scenario-engine';
import s from'../scenario.module.css';
const labels={food:'Food access',power:'Power continuity',care:'Care continuity'};
type CopyState='idle'|'copied'|'failed';
export default function DecisionRoom(){
 const[shock,setShock]=useState<Shock>('PORT_INTERRUPTION');const[action,setAction]=useState<Intervention>('RESTORE_PORT');const[units,setUnits]=useState(3);const[owner,setOwner]=useState(true);const[copyState,setCopyState]=useState<CopyState>('idle');
 const input={shock,intervention:action,units,ownerConfirmed:owner};const r=useMemo(()=>runScenario(input),[shock,action,units,owner]);
 async function copyRecord(){try{if(!navigator.clipboard)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(exportScenario(input));setCopyState('copied')}catch{setCopyState('failed')}}
 return <section className={s.room} aria-label="Scenario decision rehearsal"><div className={s.controls}><label>Shock<select value={shock} onChange={e=>setShock(e.target.value as Shock)}><option value="PORT_INTERRUPTION">Port interruption</option><option value="GRID_OUTAGE">Grid outage</option><option value="STORM">Severe storm</option></select></label><label>Intervention<select value={action} onChange={e=>setAction(e.target.value as Intervention)}><option value="RESTORE_PORT">Restore port flow</option><option value="MICROGRID">Deploy microgrid</option><option value="COMMUNITY_HUBS">Open community hubs</option></select></label><label>Capacity units: <output>{units}</output><input type="range" min="0" max="5" value={units} onChange={e=>setUnits(Number(e.target.value))}/></label><label className={s.check}><input type="checkbox" checked={owner} onChange={e=>setOwner(e.target.checked)}/> Accountable owner confirmed</label></div><div className={s.outcome}><p className={s.status} data-status={r.decision} aria-live="polite">{r.decision} · {r.fit}</p><h2>Cascading consequence index</h2><div className={s.meters}>{Object.entries(r.consequences).map(([k,v])=><div key={k}><span>{labels[k as keyof typeof labels]}</span><meter min="0" max="4" value={v}/><b>{v}/4</b></div>)}</div><ol>{r.trace.map(x=><li key={x.id} data-status={x.status}><b>{x.status}</b> {x.id}</li>)}</ol><button onClick={copyRecord}>Copy decision record</button><p className={s.copyStatus} role="status">{copyState==='copied'?'Decision record copied.':copyState==='failed'?'Copy failed. Select and copy the exported record another way.':''}</p><p className={s.note}>{r.notice} No external effect.</p></div></section>
}