import type {Metadata} from 'next';
import Link from 'next/link';

export const metadata:Metadata={
 title:'Netherlands 2026 pilot-build forensics — The 100',
 description:'Evidence-bounded technical reconstructions of Builds 001, 017, and 100 for the Dutch Design Week × AI & Big Data editorial pilot.',
 alternates:{canonical:'/100-builds/netherlands-2026/pilot-builds'},
 robots:{index:true,follow:true}
};

const page={maxWidth:'76rem',margin:'0 auto',padding:'clamp(1rem,4vw,4rem)',fontFamily:'Arial,Helvetica,sans-serif',color:'#111',background:'#f2f0e8'} as const;
const rule={borderTop:'3px solid #111',paddingTop:'1rem',marginTop:'3rem'} as const;
const card={border:'2px solid #111',padding:'clamp(1rem,2vw,1.5rem)',background:'#fff'} as const;
const code={fontFamily:'ui-monospace,SFMono-Regular,Menlo,monospace',fontSize:'.9rem',lineHeight:1.55} as const;
const builds=[
 {id:'001',title:'Human Review Design Framework',state:'Implemented interactive browser diagnostic + paired visual',links:[['Tool','/100-builds/001/a'],['Visual','/100-builds/001/b'],['Evidence','/100-builds/001/evidence'],['Making','/100-builds/001/making'],['Method','/100-builds/001/method']]},
 {id:'017',title:'Regulated-Market Handoff Mapper',state:'Implemented local architecture demonstration; registry still says Planned',links:[['Tool','/100-builds/017/a'],['Visual','/100-builds/017/b']]},
 {id:'100',title:'Island Resilience Scenario & Decision Platform',state:'Implemented synthetic local rehearsal; registry still says Planned',links:[['Tool','/100-builds/100/a'],['Visual','/100-builds/100/b']]}
] as const;
function Sources({items}:{items:string[]}){return <ul>{items.map(x=><li key={x}>{x}</li>)}</ul>}
function Links({items}:{items:readonly (readonly [string,string])[]}){return <p>{items.map(([label,href],i)=><span key={href}>{i?' · ':''}<Link href={href}>{label}</Link></span>)}</p>}
export default function PilotBuilds(){
 return <main id="main-content" tabIndex={-1} style={page}>
  <nav aria-label="Breadcrumb"><Link href="/100-builds/">100 BUILDS</Link> / NETHERLANDS 2026 / PILOT FORENSICS</nav>
  <header style={{...rule,marginTop:'1rem'}}>
   <p style={code}>TECHNICAL FRONTIER × DESIGN FRONTIER · EVIDENCE-BOUNDED RECORD · 2026-10-01</p>
   <h1 style={{fontSize:'clamp(3rem,9vw,7rem)',lineHeight:.84,letterSpacing:'-.065em',margin:'1rem 0'}}>How three builds actually work.</h1>
   <p style={{fontSize:'clamp(1.15rem,2vw,1.6rem)',lineHeight:1.35,maxWidth:'54rem'}}>This is the engineering substrate for the Dutch Design Week × AI &amp; Big Data pilot. It separates implemented behavior from intention, inference, and unsupported claims. “AI-themed” does not mean “AI-powered”: all three inspected runtimes are deterministic client-side systems.</p>
  </header>

  <section style={rule} aria-labelledby="method"><h2 id="method">How to read this record</h2>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(16rem,1fr))',gap:'1rem'}}>
    <article style={card}><b>IMPLEMENTED</b><p>Visible in source and reachable in the shipped interface.</p></article>
    <article style={card}><b>DOCUMENTED</b><p>Stated in a registry, evidence record, or making record, but not necessarily executed at runtime.</p></article>
    <article style={card}><b>NOT EVIDENCED</b><p>No inspected code or record proves it. The page names the gap instead of filling it with a guess.</p></article>
   </div>
  </section>

  {builds.map(b=><section key={b.id} style={rule} aria-labelledby={'b'+b.id}>
   <p style={code}>BUILD {b.id} · {b.state}</p><h2 id={'b'+b.id} style={{fontSize:'clamp(2.2rem,5vw,4.5rem)',lineHeight:.95,letterSpacing:'-.045em'}}>{b.title}</h2><Links items={b.links}/>
   {b.id==='001'&&<div>
    <h3>1. Provocation, people and capability</h3><p><b>Problem:</b> “human in the loop” often names a person without proving that person has evidence, time, authority, a fallback path, or a durable record. The intended users are people inspecting an AI-assisted decision in education, employment, health, law, business, content or another consequential workflow. The tool converts answers into eight scored dimensions, a Strong/Partial/Weak grade, prioritized repairs and a copyable review protocol.</p>
    <h3>2. What the user does</h3><ol><li>Choose Quick Check or Detailed Design.</li><li>Describe the decision and possible impact.</li><li>Answer structured questions about reviewer competence, capacity, timing, evidence access, authority, escalation, recording and testing.</li><li>Submit the form.</li><li>Read an eight-dimension result, total score out of 16, grade, repair priorities and generated protocol.</li></ol>
    <h3>3. Architecture and data</h3><p><b>Components:</b> Next.js App Router page → React client form in <code>@rn/forms</code> → deterministic scoring → <code>ProtocolResult</code> renderer. The paired visual uses a client component and an imported <code>HumanLoopReveal</code>; reduced-motion users receive manual tabs instead of autoplay.</p><p><b>Input:</b> browser form strings and selected values. <b>Transformation:</b> each of eight dimensions becomes 0, 1 or 2; total determines Strong (13–16), Partial (8–12), or Weak (0–7). High-risk answers prepend timing, authority and evidence warnings when weak. <b>State:</b> React memory only. <b>Output:</b> assessment object and formatted protocol. <b>Retention:</b> the inspected implementation does not send or persist answers; page copy says answers stay in the browser.</p>
    <h3>4. Intelligence boundary</h3><p><b>Deterministic:</b> all scoring, grade thresholds, gap text, priority ordering and protocol assembly. <b>AI/model/agent calls:</b> none found. <b>External APIs or database:</b> none found in the runtime path. This tool evaluates the design of AI oversight; it does not itself use AI to evaluate the answers.</p>
    <h3>5. Workflow, branches and safeguards</h3><p>The main branches are Quick versus Detailed intake, three-level answers per dimension, high-risk priority elevation, result generation, and the reduced-motion visual path. Missing or low-quality answers score down rather than triggering retries. Human intervention happens outside the software: a responsible team must change the real workflow. Safeguards include no account requirement, browser-local processing, explicit non-compliance boundary, keyboard-native form controls, focus styling, semantic fieldsets, live result navigation and a manual reduced-motion experience.</p>
    <h3>6. Build process and evaluation</h3><p>The public making record documents five stages: v0 expert-language form; v1 eight-dimension diagnostic; v2 plain-language rewrite; v3 exhibition worktable and screening-room presentation; v4 release gates for provenance, freshness, accessibility, fixtures, parity, lineage, privacy/security and performance. The structural rejection was v0: it required users to perform the analysis the tool was supposed to provide.</p>
    <h3>7. Reproduce it exactly enough to test the logic</h3><ol><li>Create a Next.js page containing a client-side React form.</li><li>Define the eight dimensions and three answer levels for each.</li><li>Map each answer to 0, 1 or 2.</li><li>Sum to 16 and apply the published thresholds.</li><li>Collect every dimension below 2 into repair priorities.</li><li>If risk is High, move weak timing, authority and evidence repairs to the front.</li><li>Assemble the protocol from the submitted facts and dimension notes.</li><li>Keep processing local; add no network request.</li><li>Add a reduced-motion manual equivalent for the paired visual.</li><li>Test every answer branch, empty selections, keyboard use, 200% text zoom and the no-network claim.</li></ol>
    <h3>8. Evidence and unresolved gaps</h3><Sources items={['Implemented source: 001-A page; packages/forms/src/index.tsx; 001-B reduced-motion component.','Primary-source map: NIST AI RMF 1.0, Regulation (EU) 2024/1689 Article 14, and UK ICO human-review guidance, checked 2026-08-15.','The composite score is explicitly a product heuristic, not a legal or safety grade.','Not evidenced in the inspected runtime: server storage, authentication, telemetry, model calls, automated source checking, or production security testing results.','Registry metadata still describes version 0.1 / Building while the public routes contain later v1.0-style implementation language; release status needs reconciliation.']}/>
   </div>}
   {b.id==='017'&&<div>
    <h3>1. Provocation, people and capability</h3><p><b>Problem:</b> two organizations can each appear controlled while responsibility disappears during transfer. The demonstration maps five actors—product owner, contract operation, data service, authorized provider and affected person—and four handoffs. It checks whether responsibility, evidence, permission, acceptance, deadline, incident duty, record and recourse are explicit.</p>
    <h3>2. What the user does</h3><ol><li>Inspect the prefilled organization chain and four handoffs.</li><li>Read the status and coverage result.</li><li>Select “Remove data transfer controls” to blank permission, incident duty and recourse for X02.</li><li>Observe the chain fall from intact to responsibility gaps.</li><li>Export the current organizations, handoffs, assessment and boundary as JSON, or reset to an empty chain.</li></ol>
    <h3>3. Architecture and data</h3><p><b>Components:</b> Next.js page → React client demonstration → <code>assessRegulatedHandoffs</code> in the shared decision-engine package. <b>Input:</b> typed organization and handoff objects held in source. <b>Transformation:</b> a field is complete only when trimmed length is at least eight characters; identifiers must resolve; organizations must be linked. The engine translates the regulated map into Build 016’s legal-workflow schema and runs that inherited assessment too. <b>State:</b> React memory only. <b>Output:</b> status, percentage coverage, responsibility gaps, orphan organizations, inherited workflow status and version. <b>Export:</b> browser-generated JSON Blob.</p>
    <h3>4. Intelligence boundary</h3><p><b>Deterministic:</b> completeness checks, graph linkage, coverage calculation, status decision and inheritance into Build 016. <b>AI/model/agent calls:</b> none found. <b>External APIs/database:</b> none found. The regulatory examples are curated text, not retrieved or validated at runtime.</p>
    <h3>5. Ordered logic</h3><ol><li>Check every organization’s role, authority, accountable owner and governing source.</li><li>For each handoff, confirm both endpoint IDs exist.</li><li>Check nine required handoff fields.</li><li>Require market, bounded regulated activity and affected people.</li><li>Identify organizations that appear in no handoff.</li><li>Translate the map into Build 016 nodes and handoffs.</li><li>Run the inherited legal-workflow assessment.</li><li>Calculate complete objects divided by total objects.</li><li>Return CHAIN UNDEFINED, RESPONSIBILITY GAPS or ACCOUNTABILITY INTACT.</li></ol>
    <h3>6. Safeguards and evaluation</h3><p>The interface says no regulated, health, client or personal data is transmitted or retained. It labels itself an architecture demonstration—not legal advice, compliance certification, product-quality approval, consent validation or authority to act. The destructive-looking reset only clears in-memory demo state. Export is user-initiated and local. Native buttons and descriptive text support keyboard use; however, the page does not evidence a completed formal accessibility test report.</p>
    <h3>7. Reproduce it</h3><ol><li>Define the organization and handoff TypeScript types exactly.</li><li>Create a fixed organization list and a handoff list with stable IDs.</li><li>Implement the eight-character completeness function.</li><li>Validate endpoints before scoring a handoff.</li><li>Collect missing fields as human-readable gaps.</li><li>Map the data into the Build 016 workflow engine and preserve its status.</li><li>Calculate coverage and choose the three-state result.</li><li>Render every field so a person can see why the status occurred.</li><li>Add a controlled failure button and local JSON export.</li><li>Test full, broken, empty, unknown-ID and orphan-organization fixtures.</li></ol>
    <h3>8. Evidence and unresolved gaps</h3><Sources items={['Implemented source: RegulatedHandoffLab.tsx and assessRegulatedHandoffs in packages/release/src/decision-engines.ts.','Documented engine record: data/build-017-engine-v1.json, version 017.1.0.','Named sources: FDA Contract Manufacturing Arrangements for Drugs: Quality Agreements; 45 CFR 164.504; both recorded checked 2026-08-17.','The source record classifies the inherited workflow and responsibility-gap rubric as product heuristics.','Registry says Planned, version 0.0, with null URLs even though /017/a and /017/b are implemented. This is a canonical-status defect, not proof that the runtime is absent.','Not evidenced: real market configuration, jurisdiction engine, authentication, data storage, automated legal updates, real incident routing, unit-test results, or review by counsel/regulator.']}/>
   </div>}
   {b.id==='100'&&<div>
    <h3>1. Provocation, people and capability</h3><p><b>Problem:</b> island shocks create connected effects across food, power and care, while decisions can hide weak ownership or invalid allocations. The current build is a bounded rehearsal for choosing one of three synthetic shocks, one of three interventions, zero to five capacity units and whether an accountable owner is confirmed.</p>
    <h3>2. What the user does</h3><ol><li>Select port interruption, grid outage or severe storm.</li><li>Select restore port flow, deploy microgrid or open community hubs.</li><li>Choose capacity units from zero to five.</li><li>Confirm or remove the accountable owner.</li><li>Read BLOCKED or REHEARSED, direct fit or tradeoff, three consequence meters and a gate trace.</li><li>Copy the JSON decision record.</li><li>In the paired visual, open the decision room and reveal the 17 declared direct dependencies within the 001–100 sequence.</li></ol>
    <h3>3. Architecture and data</h3><p><b>Components:</b> Next.js page → React DecisionRoom → pure TypeScript scenario engine. The paired Convergence component imports the engine’s lineage constant. <b>Input:</b> four local values. <b>Static data:</b> a three-row shock table, expected intervention per shock, fixed clock and 17 build IDs. <b>Transformation:</b> three gates run in sequence; after the first failure, later gates become NOT_RUN. A matching intervention reduces each consequence only if no gate stopped execution. <b>State:</b> React memory only. <b>Output:</b> frozen result object and JSON export copied to the clipboard.</p>
    <h3>4. Intelligence boundary</h3><p><b>Deterministic:</b> every output. <b>AI/model/agent/data pipeline:</b> none found. <b>Forecasting:</b> none. <b>External action:</b> hard-coded false. “Scenario platform” currently means a small synthetic rule engine and interface, not a digital twin, optimization model, live data system or emergency tool.</p>
    <h3>5. Ordered logic</h3><ol><li>Validate capacity is an integer from 0 through 5.</li><li>Require accountable owner.</li><li>Require at least two capacity units.</li><li>Stop evaluation after the first failed gate; mark subsequent gates NOT_RUN.</li><li>Look up the shock’s base food, power and care values.</li><li>Compare the selected intervention with the one fixed match for that shock.</li><li>If gates pass and intervention matches, reduce each consequence by <code>min(2, units − 1)</code>.</li><li>Clamp each consequence at zero.</li><li>Return BLOCKED or REHEARSED, DIRECT or TRADEOFF, trace, consequences, lineage and the non-operational notice.</li></ol>
    <h3>6. Safeguards and accessibility</h3><p>Fail-closed sequential gates prevent a rehearsal from passing with invalid capacity, no owner or inadequate capacity. The result explicitly states it has no external effect and is not a forecast or emergency instruction. The copy operation handles missing clipboard access and exposes success/failure through a status region. Form labels, output and meter elements are present. No evidence was found for real emergency data handling, threat modeling, disaster-professional review or a formal accessibility report.</p>
    <h3>7. Reproduce it</h3><ol><li>Define the four-value scenario input union types.</li><li>Create the shock consequence table and intervention-fit table.</li><li>Implement the three ordered gates and NOT_RUN behavior.</li><li>Apply the reduction only after all gates pass and fit is direct.</li><li>Freeze and export the result with the explicit external-effect false flag.</li><li>Build labeled controls and render the three consequence meters plus trace.</li><li>Add clipboard failure handling.</li><li>Render all 100 build IDs and mark the 17 declared lineage dependencies.</li><li>Test all 3×3×6×2 = 108 input combinations.</li><li>Verify no network request or external action occurs.</li></ol>
    <h3>8. Evidence and unresolved gaps</h3><Sources items={['Implemented source: DecisionRoom.tsx, Convergence.tsx and packages/release/src/build100-scenario-engine.ts.','The fixed direct lineage is 001, 020, 030, 034, 038, 040, 046, 047, 058, 063, 069, 071, 074, 077, 084, 095 and 099.','Registry says Planned, version 0.0, with null URLs even though /100/a and /100/b are implemented.','No build-100 engine JSON record was found at the parallel data path used by Build 017.','Not evidenced: source justification for numeric consequence values, causal model, live island data, probability, geospatial data, optimization, multi-intervention allocation, cost, uncertainty, user accounts, persistence, collaboration, APIs, agents or external effects.','“Complete preceding capability stack” is a registry aspiration. The inspected runtime directly imports only the scenario engine and its fixed lineage list; it does not execute 99 earlier builds.']}/>
   </div>}
  </section>)}

  <section style={rule}><h2>Cross-pilot finding</h2><p style={{fontSize:'clamp(1.3rem,2.4vw,2rem)',lineHeight:1.25}}>The strongest Netherlands editorial opportunity is not to pretend these prototypes are more autonomous than they are. It is to expose the exact line between <b>designed intelligence</b>—rules, thresholds, evidence, gates and human authority—and machine intelligence. That line is both a technical architecture decision and a design position.</p></section>
  <footer style={rule}><p style={code}>SOURCE SCOPE: rn-collins/rn-portfolio default branch, public build routes, registry, engine records and inspected runtime source. No claim on this page should be read as independent security, legal, scientific or operational certification.</p></footer>
 </main>
}