import type {Metadata} from 'next';
import Link from 'next/link';
export const metadata:Metadata={title:'100 Builds carousel asset operations',description:'Download and verify the canonical 700-slide Canva, Instagram, and LinkedIn production packages.',alternates:{canonical:'/100-builds/carousel-operations'},robots:{index:false,follow:true}};
const batches=Array.from({length:10},(_,i)=>{const first=i*10+1,last=first+9,pad=(n:number)=>String(n).padStart(3,'0');return {n:i+1,label:`Builds ${pad(first)}–${pad(last)}`,url:`/100-builds/carousel-packages/canva-batch-${String(i+1).padStart(2,'0')}-builds-${pad(first)}-${pad(last)}.zip`}});
const card={border:'1px solid currentColor',padding:'1rem'} as const;
export default function CarouselOperations(){return <><a className="skip-link" href="#main-content">Skip to main content</a><main id="main-content" tabIndex={-1} style={{maxWidth:'72rem',margin:'0 auto',padding:'clamp(1rem,4vw,3rem)',fontFamily:'system-ui'}}>
 <p><Link href="/100-builds/">← 100 BUILDS</Link></p><p><b>ASSET OPERATIONS · 700 CANONICAL SLIDES</b></p><h1>Carousel production downloads</h1>
 <p>One hundred builds, seven ordered slides each. Every package is generated deterministically from the canonical blueprint and carries alt text, visual guidance, credit, source, rights, claim boundaries, and SHA-256 integrity records.</p>
 <section aria-labelledby="canva"><h2 id="canva">Canva-ready batches</h2><p>Import batches 01–10, then preserve ascending build and slide order.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(14rem,1fr))',gap:'1rem'}}>{batches.map(b=><article key={b.n} style={card}><h3>Batch {String(b.n).padStart(2,'0')}</h3><p>{b.label} · 70 SVG slides</p><a href={b.url} download>Download ZIP ↓</a>{b.n>=4&&b.n<=9&&<p><a href={`/100-builds/carousel-operations/batch-${String(b.n).padStart(2,'0')}-certification`}>Certified · 73/73 checks passed</a></p>}</article>)}</div></section>
 <section aria-labelledby="platform"><h2 id="platform">Platform packages</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(18rem,1fr))',gap:'1rem'}}><article style={card}><h3>Instagram portrait</h3><p>700 PNGs · 1200×1500 · metadata and checksums.</p><a href="/100-builds/carousel-packages/rn-100-builds-700-slides-instagram-portrait.zip" download>Download Instagram ZIP ↓</a></article><article style={card}><h3>LinkedIn portrait</h3><p>700 PNGs · 1200×1500 · metadata and checksums.</p><a href="/100-builds/carousel-packages/rn-100-builds-700-slides-linkedin-portrait.zip" download>Download LinkedIn ZIP ↓</a></article></div></section>
 <section aria-labelledby="records"><h2 id="records">Records and verification</h2><ul><li><a href="/100-builds/carousel-packages/inventory.json">JSON inventory</a></li><li><a href="/100-builds/carousel-packages/inventory.csv">CSV inventory</a></li><li><a href="/100-builds/carousel-packages/PACKAGE-CHECKSUMS.json">Package checksums</a></li><li><a href="/100-builds/carousel-packages/README.md">Import instructions</a></li>{[4,5,6,7,8,9].map(n=><li key={n}><a href={`/100-builds/carousel-operations/batch-${String(n).padStart(2,'0')}-certification`}>Batch {String(n).padStart(2,'0')} certification</a></li>)}</ul><p>Package creation does not change approval, HOLD, source, rights, or live-cover status.</p></section>
 </main></>}
