'use client';
import {useMemo,useState} from 'react';
import {assessConsentRights,type ConsentEvent,type ConsentPurpose} from '../../../../../../packages/release/src/consent-rights-engine';
import s from '../rights.module.css';
const initial:ConsentPurpose[]=[
{id:'PUR-01',purpose:'Evaluate an application for the requested service',data:'Contact details and application evidence',recipient:'Authorized program review team only',retention:'Delete 90 days after final disposition unless a verified rule requires longer',downstreamUse:'No model training, sale, advertising, or unrelated reuse',granted:true,evidence:'Synthetic permission record created for this demonstration'},
{id:'PUR-02',purpose:'Optional service-improvement research',data:'De-identified interaction and correction feedback',recipient:'Named internal research team only',retention:'Delete after the documented twelve-month study period',downstreamUse:'No external transfer or new purpose without a new permission request',granted:false,evidence:'Synthetic optional-purpose record; permission is not granted'}
];
const controls={access:'Named request route returns the person’s stored record',correction:'Named route accepts evidence and appends a correction record',deletion:'Named owner executes deletion or records the governing exception',withdrawal:'Withdrawal stops future processing for the selected purpose',retention:'Purpose-level deadline and deletion evidence are recorded',downstreamUse:'New recipients or purposes require a separate permission record',owner:'Named privacy and program owner receives every request',responseTime:'Receipt, deadline, status, outcome, and escalation are recorded'};
export default function ConsentRightsLab(){
 const [purposes,setPurposes]=useState(initial);const [events,setEvents]=useState<ConsentEvent[]>([]);const [selected,setSelected]=useState(0);const current=purposes[selected];
 const assessment=useMemo(()=>assessConsentRights({personLabel:'Synthetic service participant',purposes,controls,events}),[purposes,events]);
 function change(){const next=!current.granted;const event:ConsentEvent={id:`EVT-${String(events.length+1).padStart(3,'0')}`,at:new Date().toISOString(),actor:'Synthetic participant acting in this browser',action:next?'GRANTED':'WITHDRAWN',purposeId:current.id,prior:current.granted,next,reason:next?'Participant grants this specific optional purpose':'Participant withdraws this specific purpose'};setPurposes(v=>v.map((p,i)=>i===selected?{...p,granted:next}:p));setEvents(v=>[...v,event])}
 function download(){const report={build:'023',schema:'consent-rights-record',version:'023.1.0',fixture:'synthetic',generatedInBrowser:true,canonical:{title:'Consent & Data Rights Manager',job:'Let people understand and control consent, access, correction, deletion, retention and downstream use.',bWeb:'A static checkbox becomes a living rights and permission surface.',uses:['010','020']},purposes,controls,events,assessment,boundary:'This demonstration records product controls. It does not determine whether consent is legally valid or whether a requested right applies.'};const href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=href;a.download='consent-rights-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(href),0)}
 return <section className={s.lab}><header role="status" aria-live="polite" aria-atomic="true"><span>RIGHTS STATUS / {assessment.gaps.length} OPEN GAPS</span><h2>{assessment.status}</h2><p>{assessment.activePurposeCount} active · {assessment.withdrawnPurposeCount} withheld or withdrawn</p></header><div className={s.grid}><aside aria-label="Specific purposes">{purposes.map((p,i)=><button key={p.id} aria-pressed={i===selected} className={i===selected?s.selected:''} onClick={()=>setSelected(i)}><small>{p.id}</small><b>{p.purpose}</b><span>{p.granted?'GRANTED':'NOT GRANTED'}</span></button>)}</aside><article><p className={s.kicker}>SPECIFIC PURPOSE</p><h3>{current.purpose}</h3><dl><div><dt>Data</dt><dd>{current.data}</dd></div><div><dt>Recipient</dt><dd>{current.recipient}</dd></div><div><dt>Retention</dt><dd>{current.retention}</dd></div><div><dt>Downstream use</dt><dd>{current.downstreamUse}</dd></div><div><dt>Evidence</dt><dd>{current.evidence}</dd></div></dl><button className={s.primary} onClick={change}>{current.granted?'WITHDRAW THIS PURPOSE':'GRANT THIS PURPOSE'}</button></article></div><section className={s.events}><h3>Append-only permission events</h3>{events.length?events.map(e=><p key={e.id}><b>{e.id} · {e.action}</b><span>{e.purposeId} · {e.prior?'granted':'not granted'} → {e.next?'granted':'not granted'} · {e.at}</span></p>):<p>No state change recorded in this session.</p>}</section><footer><button onClick={()=>{setPurposes(initial);setEvents([]);setSelected(0)}}>RESET</button><button onClick={download}>EXPORT RIGHTS RECORD</button></footer><p className={s.note}><b>Boundary:</b> title, job, B-Web sentence, and lineage are frozen canon. Fixtures, thresholds, question, thesis, and interface copy are derived. Everything runs client-locally; use no real personal data.</p></section>
