'use client';
import {useMemo,useState} from 'react';
import {assessConsentRights,type ConsentEvent,type ConsentPurpose} from '../../../../../../packages/release/src/consent-rights-engine';
import s from '../rights.module.css';
const initial:ConsentPurpose[]=[
{id:'PUR-01',purpose:'Evaluate an application for the requested service',data:'Contact details and application evidence',recipient:'Authorized program review team only',retention:'Delete 90 days after final disposition unless a verified rule requires longer',downstreamUse:'No model training, sale, advertising, or unrelated reuse',granted:true,evidence:'Synthetic initial permission record: FIX-023-PUR-01'},
{id:'PUR-02',purpose:'Optional service-improvement research',data:'De-identified interaction and correction feedback',recipient:'Named internal research team only',retention:'Delete after the documented twelve-month study period',downstreamUse:'No external transfer or new purpose without a new permission request',granted:false,evidence:'Synthetic optional-purpose record: FIX-023-PUR-02; permission withheld'}
];
const controls={access:'Privacy Desk route ACCESS-01 logs receipt, scope, status, result, and escalation',correction:'Privacy Desk route CORRECT-01 appends evidence and preserves the superseded value',deletion:'Privacy Desk route DELETE-01 records deletion or a specific governing exception',withdrawal:'Route WITHDRAW-01 stops future processing that relies on this permission',retention:'Route RETAIN-01 records deadline, governing exception, disposition, and evidence',downstreamUse:'Route REUSE-01 requires a separate purpose, recipient, scope, and permission record',owner:'Synthetic Privacy Desk owner is accountable for triage and resolution',responseTime:'Every route records receipt, applicable deadline, status, outcome, and escalation'};
export default function ConsentRightsLab(){
 const [purposes,setPurposes]=useState(initial);const [events,setEvents]=useState<ConsentEvent[]>([]);const [selected,setSelected]=useState(0);const current=purposes[selected];
 const assessment=useMemo(()=>assessConsentRights({personLabel:'Synthetic service participant',purposes,controls,events}),[purposes,events]);
 function change(){const next=!current.granted;const event:ConsentEvent={id:`EVT-${String(events.length+1).padStart(3,'0')}`,at:new Date().toISOString(),actor:'Synthetic participant acting in this browser',action:next?'GRANTED':'WITHDRAWN',purposeId:current.id,prior:current.granted,next,reason:next?'Participant grants this specific purpose':'Participant withdraws this specific purpose'};setPurposes(v=>v.map((p,i)=>i===selected?{...p,granted:next}:p));setEvents(v=>[...v,event])}
 function download(){const report={build:'023',schema:'consent-rights-record',version:'023.2.0',fixture:'synthetic',generatedInBrowser:true,containsRealPersonalData:false,canonical:{title:'Consent & Data Rights Manager',job:'Let people understand and control consent, access, correction, deletion, retention and downstream use.',bWeb:'A static checkbox becomes a living rights and permission surface.',uses:['010','020']},purposes,controls,events,assessment,boundary:'Product-control demonstration only. It does not determine consent validity, applicable law, lawful basis, whether a right applies, identity, authorization, deadlines, exemptions, or whether withdrawal requires deletion of prior records.'};const href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=href;a.download='consent-rights-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(href),0)}
 return <section className={s.lab}><header role="status" aria-live="polite" aria-atomic="true"><span>RIGHTS STATUS / {assessment.gaps.length} OPEN GAPS</span><h2>{assessment.status}</h2><p>{assessment.activePurposeCount} active · {assessment.withdrawnPurposeCount} withheld or withdrawn · {assessment.validEventCount} valid session event(s)</p></header><div className={s.grid}><aside aria-label="Specific purposes">{purposes.map((p,i)=><button key={p.id} aria-pressed={i===selected} className={i===selected?s.selected:''} onClick={()=>setSelected(i)}><small>{p.id}</small><b>{p.purpose}</b><span>{p.granted?'GRANTED':'NOT GRANTED'}</span></button>)}</aside><article><p className={s.kicker}>SPECIFIC PURPOSE</p><h3>{current.purpose}</h3><dl><div><dt>Data</dt><dd>{current.data}</dd></div><div><dt>Recipient</dt><dd>{current.recipient}</dd></div><div><dt>Retention</dt><dd>{current.retention}</dd></div><div><dt>Downstream use</dt><dd>{current.downstreamUse}</dd></div><div><dt>Evidence</dt><dd>{current.evidence}</dd></div></dl><button className={s.primary} onClick={change}>{current.granted?'WITHDRAW THIS PURPOSE':'GRANT THIS PURPOSE'}</button><p className={s.caution}>Withdrawal changes future processing that relies on this permission. It does not itself decide deletion, another lawful basis, an exception, or a legal deadline.</p></article></div><section className={s.events} aria-label="Append-only permission history"><h3>Append-only permission events</h3>{events.length?events.map(e=><p key={e.id}><b>{e.id} · {e.action}</b><span>{e.purposeId} · {e.prior?'granted':'not granted'} → {e.next?'granted':'not granted'} · {e.at}</span><span>{e.actor} · {e.reason}</span></p>):<p>No session event yet. The two synthetic initial states remain evidenced in their purpose records.</p>}</section><footer><button onClick={()=>{setPurposes(initial);setEvents([]);setSelected(0)}}>RESET SYNTHETIC SESSION</button><button onClick={download}>EXPORT RIGHTS RECORD</button></footer><p className={s.note}><b>Boundary:</b> this is a client-local product-control demonstration, not legal advice or a determination that consent is valid, a right applies, identity is verified, or a request must be fulfilled. Use no real personal data.</p></section>
}
