'use client';
import{useState}from'react';
import{buildPsychedelicCareContinuityRecord,CARE_CONTINUITY_SCENARIOS,type ScenarioId}from'../../../../../../packages/release/src/psychedelic-care-continuity-engine';
import s from'../continuity.module.css';

const ids:ScenarioId[]=['CONTINUITY-CURRENT','HANDOFF-UNACCEPTED','PERMISSION-WITHDRAWN','FOLLOWUP-OVERDUE','CRISIS-OUTSIDE-SCOPE'];
const stages=[['01','PREPARE'],['02','SESSION'],['03','CHECK IN'],['04','INTEGRATE'],['05','REFER'],['06','HAND OFF'],['07','FOLLOW THROUGH']];

export default function ContinuityStory(){const[index,setIndex]=useState(0),id=ids[index],result=buildPsychedelicCareContinuityRecord(CARE_CONTINUITY_SCENARIOS[id]);return <section className={s.story} data-continuity-state={id}><div className={s.status} role="status" aria-live="polite" aria-atomic="true"><small>PATHWAY STATE {index+1}/5 · {id}</small><h2>{result.status}</h2><p>{result.nonClaims[0]}</p></div><ol className={s.pathway} aria-label="Longitudinal continuity pathway">{stages.map(([number,stage])=><li key={stage}><span aria-hidden="true">{number}</span><b>{stage}</b><i aria-hidden="true"/></li>)}</ol><div className={s.storyAction}><button type="button" onClick={()=>setIndex(value=>(value+1)%ids.length)}>ADVANCE CARE CLOCK</button><p>{result.handoffs[0]??result.followups[0]??result.permissions[0]??'The fixed pathway has no open continuity action.'}</p></div><div className={s.handoffEquation} aria-label="A safe handoff requires specific recorded states"><span>PERMISSION</span><b aria-hidden="true">+</b><span>MINIMUM RECORD</span><b aria-hidden="true">+</b><span>ACCEPTANCE</span><b aria-hidden="true">+</b><span>FOLLOW-THROUGH</span></div><aside className={s.emergency}><h3>A pathway is not a lifeline.</h3><p>For immediate danger, a medical emergency, or an urgent safety concern, contact local emergency services or an appropriate crisis service. Do not rely on this demonstration.</p></aside><p className={s.note}>A continuity record can preserve declared handoff states. It cannot deliver care, verify a provider, determine risk, confirm safety, establish consent validity, guarantee follow-through, or replace emergency and crisis services.</p></section>}
