'use client';
import {useMemo,useState} from 'react';import {assessLegalProductCandidates,type LegalTaskCandidate} from '../../../../../../packages/release/src/decision-engines';import s from './legal-product.module.css';
const initial:LegalTaskCandidate[]=[
 {id:'intake',label:'Issue intake checklist',frequency:5,consistency:5,reviewability:5,reuseValue:5,judgmentIntensity:2,confidentialityRisk:2,matterSpecificity:2,evidence:'Repeated omissions found in supervised intake quality review.',owner:'Supervising matter attorney',reviewGate:'Lawyer confirms scope, conflicts, urgency, facts, and requested action.',safeOutput:'Blank internal checklist with source, version, owner, and escalation fields.'},
 {id:'authority',label:'Authority verification table',frequency:5,consistency:4,reviewability:5,reuseValue:5,judgmentIntensity:3,confidentialityRisk:2,matterSpecificity:3,evidence:'Recurring need to record authority, locator, currency, treatment, and proposition.',owner:'Supervising matter attorney',reviewGate:'Lawyer verifies every relied-upon authority and legal proposition.',safeOutput:'Internal research table; never a final legal conclusion or client advice.'},
 {id:'strategy',label:'Matter strategy recommendation',frequency:4,consistency:2,reviewability:3,reuseValue:2,judgmentIntensity:5,confidentialityRisk:5,matterSpecificity:5,evidence:'Strategy changes with facts, objectives, law, credibility, cost, timing, and risk.',owner:'Responsible licensed attorney',reviewGate:'Lawyer exercises independent judgment and advises the client.',safeOutput:'No reusable recommendation; retain only a blank options-and-assumptions frame.'},
 {id:'status',label:'Deadline and status tracker',frequency:5,consistency:5,reviewability:5,reuseValue:5,judgmentIntensity:2,confidentialityRisk:3,matterSpecificity:3,evidence:'Repeated dates and handoffs benefit from structured ownership and escalation.',owner:'Matter team owner designated by supervising attorney',reviewGate:'Responsible lawyer validates legal deadlines, dependencies, and escalation.',safeOutput:'Access-controlled internal tracker with source, owner, confidence, and audit log.'}
];
export default function LegalProductLab(){const [tasks,setTasks]=useState(initial);const result=useMemo(()=>assessLegalProductCandidates(tasks),[tasks]);const makeUnsafe=()=>setTasks(xs=>xs.map(x=>x.id==='intake'?{...x,judgmentIntensity:5,confidentialityRisk:5,safeOutput:'Automated client-specific legal advice'}:x));const reset=()=>setTasks(xs=>xs.map(x=>({...x,evidence:'',owner:'',reviewGate:'',safeOutput:''})));const exportMap=()=>{const blob=new Blob([JSON.stringify({assessment:result,tasks,boundary:'Educational product architecture—not legal advice, a substitute for supervision, or authorization to deliver legal services.'},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='legal-product-candidate-map.json';a.click();URL.revokeObjectURL(a.href)};
return <section className={s.wrap}><div className={s.head}><p>PRODUCTIZATION READOUT</p><h2>{result.status}</h2><span>Human review: <b>{result.humanReview.grade}</b></span></div><div className={s.grid}>{result.candidates.map(c=><article key={c.id} data-state={c.disposition}><div><span>{c.score}/100</span><b>{c.disposition}</b></div><h3>{c.label}</h3><p>{c.safeOutput}</p><ul>{c.reasons.map(r=><li key={r}>{r}</li>)}</ul></article>)}</div><aside className={s.boundary}><h2>THE REUSABLE PART IS THE STRUCTURE—NOT THE JUDGMENT.</h2><p>Productize stable inputs, prompts, fields, source rules, verification steps, handoffs, records, and review gates. Keep matter-specific conclusions, professional judgment, approval, confidential information, and client decisions with the authorized humans.</p>{result.gaps.length?<ul>{result.gaps.map(g=><li key={g}>{g}</li>)}</ul>:null}<div><button onClick={makeUnsafe}>COLLAPSE INTAKE INTO ADVICE</button><button onClick={exportMap}>EXPORT CANDIDATE MAP</button><button onClick={reset}>RESET / START EMPTY</button></div><small>No entered information is transmitted or retained by this local demonstration. Applicable law, ethics rules, engagement terms, court orders, organizational policy, and supervising counsel control.</small></aside></section>}
