'use client';
import {useMemo,useState} from 'react';
import {decisionGapScore,decisionGapTier} from '../../../../../../../packages/release/src/decision-engines';
import s from './service-software.module.css';

type Signals={frequency:number;consequence:number;ambiguity:number;fragmentation:number;value:number;repeatability:number;ruleClarity:number;judgment:number;exceptions:number};
type Disposition='AUTOMATE'|'KEEP HUMAN'|'REMOVE';
type Step={id:number;name:string;description:string;signals:Signals};
const defaults:Signals={frequency:4,consequence:3,ambiguity:3,fragmentation:3,value:4,repeatability:4,ruleClarity:4,judgment:2,exceptions:2};
const seed:Step[]=[
 {id:1,name:'Collect intake details',description:'Gather the same structured facts before the expert begins.',signals:{...defaults,ambiguity:2,fragmentation:4}},
 {id:2,name:'Interpret unusual facts',description:'Decide what an exceptional situation means for the client.',signals:{...defaults,consequence:5,ambiguity:5,ruleClarity:2,judgment:5,exceptions:5}},
 {id:3,name:'Copy status into a second tracker',description:'Duplicate information that already exists elsewhere.',signals:{...defaults,value:1,frequency:5,repeatability:5,ruleClarity:5,judgment:1,exceptions:1}}
];
const signalMeta:[keyof Signals,string,string][]=[
 ['frequency','How often does this recur?','Rare → constant'],['consequence','How much does a mistake matter?','Minor → serious'],['ambiguity','How unclear is the right answer?','Clear → ambiguous'],['fragmentation','How scattered is the needed information?','Together → fragmented'],['value','How much useful value does this step add?','Low → high'],['repeatability','How similar is the step each time?','Different → repeatable'],['ruleClarity','How explicit are the rules?','Tacit → explicit'],['judgment','How much expert judgment is required?','Low → high'],['exceptions','How often do unusual cases break the normal path?','Rare → frequent']
];
function classify(step:Step){const v=step.signals;const gap=decisionGapScore({frequency:v.frequency,consequence:v.consequence,ambiguity:v.ambiguity,fragmentation:v.fragmentation},3,step.description);let disposition:Disposition;const reasons:string[]=[];
 if(v.value<=2){disposition='REMOVE';reasons.push('The step adds little value relative to the work it creates.');if(v.repeatability>=4)reasons.push('Repeating low-value work faster would automate waste rather than remove it.');}
 else if(v.judgment>=4||v.exceptions>=4||(v.consequence>=4&&v.ambiguity>=4)){disposition='KEEP HUMAN';if(v.judgment>=4)reasons.push('Expert judgment is central to the step.');if(v.exceptions>=4)reasons.push('Exceptions are common enough that a rigid path would be brittle.');if(v.consequence>=4&&v.ambiguity>=4)reasons.push('High consequence plus high ambiguity warrants human responsibility.');}
 else if(v.repeatability>=4&&v.ruleClarity>=4&&v.frequency>=3){disposition='AUTOMATE';reasons.push('The step repeats and its rules are explicit enough to encode.');if(v.judgment<=2)reasons.push('Most of the work does not depend on expert judgment.');}
 else {disposition='KEEP HUMAN';reasons.push('The step is not yet stable or explicit enough to justify software.');}
 if(gap>=55)reasons.push(`Build 003 inheritance: the recurring decision gap is ${decisionGapTier(gap)} (${gap}/100), so systematization is worth investigating.`);else reasons.push(`Build 003 inheritance: the decision-gap signal is ${decisionGapTier(gap)} (${gap}/100), so software may be premature.`);
 return {disposition,reasons,gap};}
export default function ServiceSoftwareLab(){const [steps,setSteps]=useState<Step[]>(seed);const [selected,setSelected]=useState(1);const [name,setName]=useState('');const [description,setDescription]=useState('');const [announcement,setAnnouncement]=useState('');const current=steps.find(x=>x.id===selected)??steps[0];const assessments=useMemo(()=>steps.map(step=>({step,...classify(step)})),[steps]);
 function updateSignal(key:keyof Signals,value:number){if(!current)return;setSteps(prev=>prev.map(x=>x.id===current.id?{...x,signals:{...x.signals,[key]:value}}:x));}
 function addStep(){if(!name.trim()){setAnnouncement('Step not added. Give the service step a name.');return}const id=Math.max(0,...steps.map(x=>x.id))+1;setSteps(prev=>[...prev,{id,name:name.trim(),description:description.trim()||'Describe what happens in this step.',signals:{...defaults}}]);setSelected(id);setName('');setDescription('');setAnnouncement(`Step ${id} added and ready to classify.`)}
 function removeStep(id:number){setSteps(prev=>prev.filter(x=>x.id!==id));const next=steps.find(x=>x.id!==id);setSelected(next?.id??0);setAnnouncement(`Step ${id} removed.`)}
 function reset(){setSteps(seed);setSelected(1);setName('');setDescription('');setAnnouncement('Service map reset to the demonstration workflow.')}
 function exportMap(){const payload={build:'005-A',engineVersion:'005.1.0',inherits:{build:'003',engine:'003.1.0',primitive:'decisionGapScore'},exportedAt:new Date().toISOString(),steps:assessments.map(({step,disposition,reasons,gap})=>({...step,assessment:{disposition,reasons,decisionGapScore:gap}})),limitations:['classification is a product-discovery heuristic','AUTOMATE means investigate a software candidate, not deploy without evaluation','KEEP HUMAN does not prohibit assistive tooling','REMOVE requires validation that the step is truly unnecessary']};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download='service-to-software-map.json';a.click();URL.revokeObjectURL(href);setAnnouncement('Service-to-software map exported as JSON.')}
 const activeAssessment=current?classify(current):null;
 return <div className={s.app}>
  <section className={s.intro}><span>01 / MAP THE SERVICE</span><h2>Do not automate the service. Separate the steps first.</h2><p>Describe what actually happens. Then test each step for value, recurrence, rules, judgment, consequence, ambiguity, fragmentation, and exceptions.</p></section>
  {announcement&&<p className={s.status} role="status" aria-live="polite">{announcement}</p>}
  <section className={s.add}><label>Service step name *<input value={name} onInput={e=>setName(e.currentTarget.value)} placeholder="Example: Prepare the weekly status email"/></label><label>What happens in this step?<textarea rows={3} value={description} onInput={e=>setDescription(e.currentTarget.value)} placeholder="Describe the work in ordinary language."/></label><button onClick={addStep}>ADD STEP</button></section>
  <section className={s.workspace}><aside className={s.steps} aria-label="Service steps">{assessments.map(({step,disposition})=><button key={step.id} aria-pressed={selected===step.id} onClick={()=>setSelected(step.id)}><small>STEP {String(step.id).padStart(2,'0')}</small><strong>{step.name}</strong><span data-disposition={disposition}>{disposition}</span></button>)}</aside>{current&&activeAssessment&&<div className={s.detail}><header><div><span>02 / CLASSIFY THE STEP</span><h2>{current.name}</h2><p>{current.description}</p></div><button className={s.remove} onClick={()=>removeStep(current.id)}>REMOVE STEP</button></header><div className={s.signals}>{signalMeta.map(([key,label,hint])=><label key={key}><span><b>{label}</b><small>{hint}</small></span><input aria-label={label} type="range" min="1" max="5" value={current.signals[key]} onInput={e=>updateSignal(key,Number(e.currentTarget.value))}/><strong>{current.signals[key]} / 5</strong></label>)}</div><section className={s.result} aria-live="polite"><span>CANDIDATE DISPOSITION</span><h3 data-disposition={activeAssessment.disposition}>{activeAssessment.disposition}</h3><p>Decision-gap signal inherited from Build 003: <strong>{activeAssessment.gap}/100 · {decisionGapTier(activeAssessment.gap)}</strong></p><ul>{activeAssessment.reasons.map(r=><li key={r}>{r}</li>)}</ul></section></div>}</section>
  <section className={s.summary}><span>03 / SEE THE SERVICE AS A PORTFOLIO</span><h2>Software is only one possible outcome.</h2><div className={s.lanes}>{(['AUTOMATE','KEEP HUMAN','REMOVE'] as Disposition[]).map(lane=><article key={lane}><h3>{lane}</h3>{assessments.filter(x=>x.disposition===lane).map(x=><button key={x.step.id} onClick={()=>setSelected(x.step.id)}>{x.step.name}<small> gap {x.gap}</small></button>)}{!assessments.some(x=>x.disposition===lane)&&<p>No steps here yet.</p>}</article>)}</div><div className={s.actions}><button onClick={exportMap}>EXPORT MAP</button><button onClick={reset}>RESET / START OVER</button></div></section>
  <p className={s.boundary}><strong>Boundary:</strong> this is a product-discovery instrument, not an automatic software business case. “Automate” means the step has characteristics worth prototyping and validating. It does not establish demand, ROI, safety, legal permission, or implementation readiness.</p>
 </div>}
