'use client';
import {useMemo,useState} from 'react';
import {assessImplementationReadiness,IMPLEMENTATION_READINESS_ENGINE_VERSION,type InheritedAssessment,type ReadinessLayer} from '../../../../../../packages/release/src/implementation-readiness-engine';
import s from '../readiness.module.css';
const seed:ReadinessLayer[]=[
 {key:'people',label:'People',score:2,owner:'Clinical operations lead',ownerAuthority:'May assign reviewers and pause the pilot',evidence:'Role matrix documents reviewer coverage for every pilot session',evidenceRefs:[{id:'PEOPLE-01',locator:'synthetic://records/people-role-matrix',observedAt:'2026-08-18',reviewer:'Evaluation lead'}],validationMethod:'Capacity walk-through against twenty synthetic cases',gap:''},
 {key:'data',label:'Data',score:1,owner:'Data steward',ownerAuthority:'May deny access and require dataset correction',evidence:'Dataset inventory defines the synthetic-data and access boundary',evidenceRefs:[{id:'DATA-01',locator:'synthetic://records/dataset-inventory',observedAt:'2026-08-18',reviewer:'Privacy reviewer'}],validationMethod:'Inventory reconciled against the pilot input schema',gap:'Drift baseline is not approved'},
 {key:'workflow',label:'Workflow',score:2,owner:'Service owner',ownerAuthority:'May change handoffs and restore the manual fallback',evidence:'Current-state map records handoffs, review, fallback, and release authority',evidenceRefs:[{id:'FLOW-01',locator:'synthetic://records/current-state-map',observedAt:'2026-08-18',reviewer:'Operations reviewer'}],validationMethod:'Tabletop walkthrough including fallback and boundary breach',gap:''},
 {key:'controls',label:'Controls',score:0,owner:'',ownerAuthority:'',evidence:'',evidenceRefs:[],validationMethod:'',gap:'Stop authority and incident route are not assigned'},
 {key:'evidence',label:'Evidence',score:1,owner:'Evaluation lead',ownerAuthority:'May reject the test result and require a new protocol',evidence:'Task-specific validation protocol defines material-error seeds',evidenceRefs:[{id:'EVAL-01',locator:'synthetic://records/validation-protocol',observedAt:'2026-08-18',reviewer:'Independent evaluator'}],validationMethod:'Protocol review against the bounded use and success measure',gap:'Independent result is pending'}
];
const inheritedSeed:InheritedAssessment[]=[
 {buildId:'012',assessmentId:'012-SYNTH-CTRL-01',engineVersion:'012.1.0',outcome:'CONTROLLED USE',closed:true,reviewedAt:'2026-08-18',unresolvedGaps:[]},
 {buildId:'013',assessmentId:'013-SYNTH-FLOW-01',engineVersion:'013.1.0',outcome:'WORKFLOW SCANNED',closed:true,reviewedAt:'2026-08-18',unresolvedGaps:[]},
 {buildId:'021',assessmentId:'',engineVersion:'',outcome:'NOT ATTACHED',closed:false,reviewedAt:'',unresolvedGaps:['Vendor claim verification record is not attached.']}
];
export default function ReadinessLab(){
 const [layers,setLayers]=useState(seed);const [inheritedAssessments,setInherited]=useState(inheritedSeed);
 const input={useCase:'Synthetic drafting assistant for non-final service summaries',decisionSupported:'Whether to authorize a twenty-case synthetic pilot',layers,inheritedAssessments,pilot:{boundary:'Twenty synthetic cases; no real records and no autonomous action',excludedData:'No personal, confidential, privileged, health, employment, or production data',excludedActions:'No final decision, external release, procurement, or autonomous action',deploymentOwner:'Service operations director',ownerAuthority:'May authorize only the synthetic pilot and must stop it on trigger',successMeasure:'Reviewer catches every seeded material error before release',stopCondition:'Stop on one uncaught material error or any boundary breach',incidentPath:'Pause, preserve trace, notify owner, investigate, and document decision',rollback:'Return immediately to the documented manual workflow',expiresAt:'2026-09-30',approvalRecord:'SYNTH-PILOT-APPROVAL-025'}};
 const result=useMemo(()=>assessImplementationReadiness(input),[layers,inheritedAssessments]);
 function addEvidence(){setLayers(v=>v.map(x=>({...x,score:2 as const,owner:x.owner||'Implementation control owner',ownerAuthority:x.ownerAuthority||'May pause the pilot and initiate incident response',evidence:x.evidence||'Signed control test confirms stop authority and incident ownership',evidenceRefs:x.evidenceRefs.length?x.evidenceRefs:[{id:`${x.key.toUpperCase()}-02`,locator:`synthetic://records/${x.key}-control-test`,observedAt:'2026-08-18',reviewer:'Independent control reviewer'}],validationMethod:x.validationMethod||'Tabletop test against stop and incident scenarios',gap:''})))}
 function attachVendor(){setInherited(v=>v.map(x=>x.buildId==='021'?{buildId:'021',assessmentId:'021-SYNTH-CLAIM-01',engineVersion:'021.2.0',outcome:'VERIFICATION PATH CLOSED',closed:true,reviewedAt:'2026-08-18',unresolvedGaps:[]}:x))}
 function reset(){setLayers(seed);setInherited(inheritedSeed)}
 function download(){const report={build:'025',schema:'implementation-readiness-record',version:IMPLEMENTATION_READINESS_ENGINE_VERSION,fixture:'synthetic',generatedInBrowser:true,canonical:{title:'AI Implementation Readiness X-Ray',job:'Test whether an organization can actually implement an AI use safely and operationally.',bWeb:'Readiness layers reveal missing people, data, workflows, controls and evidence.',uses:['012','013','021'],creates:['cap:025']},input,result,privacy:'No data is transmitted or stored by this demonstration. Do not enter real or confidential data.',boundary:'Demonstration only; not deployment, procurement, safety, compliance, or legal authorization.'};const href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=href;a.download='ai-implementation-readiness.json';a.click();setTimeout(()=>URL.revokeObjectURL(href),0)}
 return <section className={s.lab}><header role="status" aria-live="polite" aria-atomic="true"><span>IMPLEMENTATION READINESS / {result.score} OF {result.maxScore}</span><h2>{result.status}</h2><p>{result.blocking.length} blocking findings</p></header>
 <div className={s.actions}><button className={s.primary} onClick={addEvidence}>ADD MISSING CONTROL EVIDENCE</button><button onClick={attachVendor} disabled={inheritedAssessments.find(x=>x.buildId==='021')?.closed}>ATTACH CLOSED VENDOR CLAIM RECORD</button><button onClick={reset}>RESET</button><button onClick={download}>EXPORT READINESS RECORD</button></div>
 <div className={s.layers} role="list" aria-label="Organizational readiness layers">{layers.map(layer=><article key={layer.key} role="listitem"><small>{layer.key.toUpperCase()} / {layer.score} OF 2</small><h3>{layer.label}</h3><p><b>Owner:</b> {layer.owner||'Not assigned'}</p><p><b>Authority:</b> {layer.ownerAuthority||'Not defined'}</p><p><b>Evidence:</b> {layer.evidence||'Not provided'}</p><p><b>Evidence record:</b> {layer.evidenceRefs.map(x=>x.id).join(', ')||'Not linked'}</p><p><b>Validation:</b> {layer.validationMethod||'Not tested'}</p><p><b>Gap:</b> {layer.gap||'No open gap in this fixture'}</p><div className={s.score}>{[0,1,2].map(n=><button key={n} aria-label={`Set ${layer.label} readiness to ${n}`} aria-pressed={layer.score===n} onClick={()=>setLayers(v=>v.map(x=>x.key===layer.key?{...x,score:n as 0|1|2}:x))}>{n}</button>)}</div></article>)}</div>
 <section className={s.findings} aria-labelledby="inherited-title"><h3 id="inherited-title">Inherited assessment records</h3><ul>{inheritedAssessments.map(x=><li key={x.buildId}><b>Build {x.buildId}:</b> {x.outcome} · {x.assessmentId||'record missing'}{x.unresolvedGaps.length?` · ${x.unresolvedGaps.join(' ')}`:''}</li>)}</ul></section>
 <section className={s.findings}><h3>Blocking findings</h3>{result.blocking.length?<ul>{result.blocking.map(x=><li key={x}>{x}</li>)}</ul>:<p>No blocker under this derived rubric. The result authorizes only the stated bounded synthetic pilot.</p>}</section>
 <p className={s.note}><b>Boundary:</b> title, job, B-Web sentence, and lineage are frozen canon. The fixture, rubric, and thresholds are derived. Evidence IDs are synthetic demonstrations, not verified real-world records. Runs client-locally; enter no real or confidential data.</p></section>
}
