'use client';
import {useMemo,useState} from 'react';
import s from './decision-gap.module.css';

type Source='articles'|'spreadsheets'|'dashboards'|'experts'|'forums'|'meetings'|'search'|'other';
type Signals={frequency:number;consequence:number;ambiguity:number;fragmentation:number};
type Availability='available'|'downloadable'|'downloading'|'unavailable';
type LocalSession={prompt:(prompt:string)=>Promise<string>;destroy?:()=>void};
type LocalLanguageModel={availability:()=>Promise<Availability>;create:(options:{initialPrompts:{role:string;content:string}[]})=>Promise<LocalSession>};
type BrowserAI=typeof globalThis&{LanguageModel?:LocalLanguageModel};
const SOURCES:Source[]=['articles','spreadsheets','dashboards','experts','forums','meetings','search','other'];
const scales=[['frequency','How often does this decision recur?'],['consequence','How much does getting it wrong matter?'],['ambiguity','How unclear is the right answer?'],['fragmentation','How scattered is the information?']] as const;
const DEFAULT_SITUATION='A team has many AI governance documents but still struggles to decide whether a proposed workflow is safe enough to launch.';
const DEFAULT_DECISION='What has to be true before we should launch this workflow?';
const DEFAULT_SIGNALS:Signals={frequency:4,consequence:5,ambiguity:4,fragmentation:5};
function score(v:Signals,sources:number,decision:string){const core=(v.frequency+v.consequence+v.ambiguity+v.fragmentation)/4;const infoPenalty=Math.min(20,sources*3);const unresolved=decision.trim().length>18?15:5;return Math.max(0,Math.min(100,Math.round(core*17+infoPenalty+unresolved-30)))}
function tier(n:number){return n>=75?'strong gap':n>=55?'promising gap':n>=35?'investigate':'weak signal'}
function hypotheses(decision:string,v:Signals){const out=[] as string[];if(v.fragmentation>=4)out.push('One place that assembles the evidence needed for this decision.');if(v.ambiguity>=4)out.push('A comparison or scenario tool that makes tradeoffs explicit.');if(v.consequence>=4)out.push('A decision protocol that shows assumptions, uncertainty, and escalation points.');if(v.frequency>=4)out.push('A reusable workflow that remembers prior decisions and what happened afterward.');if(!out.length)out.push('Interview people who face this situation and identify the exact moment information stops being enough.');return out.map(x=>decision?`${x} Decision focus: ${decision}`:x)}
export default function DecisionGapLab(){
 const [situation,setSituation]=useState(DEFAULT_SITUATION);const [decision,setDecision]=useState(DEFAULT_DECISION);const [selected,setSelected]=useState<Source[]>(['articles','spreadsheets','experts']);const [vals,setVals]=useState<Signals>(DEFAULT_SIGNALS);const [aiIdeas,setAiIdeas]=useState<string[]>([]);const [aiState,setAiState]=useState('not run');const [recordState,setRecordState]=useState('');
 const gap=useMemo(()=>score(vals,selected.length,decision),[vals,selected,decision]);const ideas=useMemo(()=>hypotheses(decision,vals),[decision,vals]);
 function toggle(x:Source){setSelected(p=>p.includes(x)?p.filter(v=>v!==x):[...p,x])}
 async function askLocalAI(){setAiState('checking browser…');setAiIdeas([]);try{const LM=(globalThis as BrowserAI).LanguageModel;if(!LM){setAiState('Local LanguageModel is unavailable; deterministic hypotheses remain active.');return}const availability=await LM.availability();if(availability==='unavailable'){setAiState('This device cannot run the local model.');return}setAiState(availability==='downloadable'?'downloading browser-managed model…':'generating locally…');const session=await LM.create({initialPrompts:[{role:'system',content:'You are a product-discovery analyst. Given a recurring situation, the unresolved decision, existing information substitutes, and scores, propose exactly three bounded product hypotheses. Each hypothesis must name the user decision it improves. Do not claim market demand; label assumptions.'}]});const result=await session.prompt(`Situation: ${situation}\nUnresolved decision: ${decision}\nExisting substitutes: ${selected.join(', ')}\nScores 1-5: ${JSON.stringify(vals)}\nReturn three short lines.`);setAiIdeas(result.split(/\n+/).map(x=>x.replace(/^[-\d.\s]+/,'').trim()).filter(Boolean).slice(0,3));setAiState('generated locally; still hypotheses, not demand evidence');session.destroy?.()}catch(e){setAiState(`Local AI could not run: ${e instanceof Error?e.message:'unknown error'}`)}}
 function exportRecord(){const payload={build:'003-A',engineVersion:'003.1.0',createdAt:new Date().toISOString(),classification:'product-heuristic',situation,decision,informationSubstitutes:selected,signals:vals,score:gap,tier:tier(gap),deterministicHypotheses:ideas,optionalLocalAIHypotheses:aiIdeas,limitations:['does not prove demand','does not prove willingness to pay','does not prove the proposed product is correct'],nextEvidenceDependency:'004'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='build-003-decision-gap-record.json';a.click();URL.revokeObjectURL(url);setRecordState('JSON record exported')}
 function reset(){setSituation(DEFAULT_SITUATION);setDecision(DEFAULT_DECISION);setSelected(['articles','spreadsheets','experts']);setVals(DEFAULT_SIGNALS);setAiIdeas([]);setAiState('not run');setRecordState('reset')}
 return <div className={s.app}>
  <section className={s.inputs}><div><span>01 / SITUATION</span><h2>Where does the decision happen?</h2><textarea aria-label="Recurring situation" rows={5} maxLength={3000} value={situation} onChange={e=>setSituation(e.target.value)}/></div><div><span>02 / MISSING DECISION</span><h2>What can people still not decide?</h2><textarea aria-label="Unresolved decision" rows={5} maxLength={1500} value={decision} onChange={e=>setDecision(e.target.value)}/></div></section>
  <section className={s.sources}><span>03 / WHAT THEY ALREADY HAVE</span><h2>Information is not the same as a decision tool.</h2><div>{SOURCES.map(x=><button type="button" key={x} aria-pressed={selected.includes(x)} onClick={()=>toggle(x)}>{x}</button>)}</div></section>
  <section className={s.scales}><span>04 / GAP SIGNALS</span><h2>How structurally painful is the missing decision?</h2>{scales.map(([key,label])=><label key={key}><b>{label}</b><input aria-label={label} type="range" min="1" max="5" value={vals[key]} onChange={e=>setVals(v=>({...v,[key]:Number(e.target.value)}))}/><strong aria-live="polite">{vals[key]} / 5</strong></label>)}</section>
  <section className={s.output} aria-live="polite"><div className={s.gauge}><span>DECISION GAP</span><strong>{gap}</strong><b>{tier(gap)}</b></div><div><h2>The empty space</h2><p>People already have <strong>{selected.length||'few'}</strong> information substitutes, but the unresolved job is still: <strong>{decision||'define the decision'}</strong></p><div className={s.ideas}>{ideas.map((x,i)=><article key={x}><span>HYPOTHESIS {i+1}</span><p>{x}</p></article>)}</div><button type="button" className={s.ai} onClick={askLocalAI}>CHALLENGE WITH BROWSER-LOCAL AI</button><small aria-live="polite">{aiState}</small>{aiIdeas.length>0&&<div className={s.aiIdeas}>{aiIdeas.map((x,i)=><p key={i}>{x}</p>)}</div>}</div></section>
  <section className={s.output}><div className={s.gauge}><span>PORTABLE RECORD</span><strong>003</strong><b>v1</b></div><div><h2>Keep the assumptions visible.</h2><p>The export records the inputs, formula version, score, hypotheses, limitations, and the fact that external evidence retrieval belongs to Build 004.</p><button type="button" className={s.ai} onClick={exportRecord}>EXPORT JSON RECORD</button> <button type="button" className={s.ai} onClick={reset}>RESET</button><small aria-live="polite">{recordState}</small></div></section>
  <p className={s.note}><strong>This is discovery, not validation.</strong> A high gap score means the situation has characteristics worth investigating. It does not prove people want a product, will pay, or that the proposed solution is correct. The next step is evidence from the people living the decision.</p>
 </div>}
