'use client';
import {useEffect,useMemo,useState} from 'react';
import s from './meaning.module.css';

type Audience='general public'|'teenager'|'customer'|'regulator'|'investor'|'patient'|'lawyer';
type Tone='plain'|'formal'|'warm'|'concise';
type Event={at:string;engine:string;action:string;detail:string};
type Availability='available'|'downloadable'|'downloading'|'unavailable';
type LocalSession={prompt:(prompt:string)=>Promise<string>;destroy?:()=>void};
type LocalLanguageModel={availability:()=>Promise<Availability>;create:(options:{initialPrompts:{role:string;content:string}[]})=>Promise<LocalSession>};
type LocalTranslatorInstance={translate:(text:string)=>Promise<string>;destroy?:()=>void};
type LocalTranslator={availability:(options:{sourceLanguage:string;targetLanguage:string})=>Promise<Availability>;create:(options:{sourceLanguage:string;targetLanguage:string})=>Promise<LocalTranslatorInstance>};
type BrowserAI=typeof globalThis&{LanguageModel?:LocalLanguageModel;Translator?:LocalTranslator};
const AUDIENCES:Audience[]=['general public','teenager','customer','regulator','investor','patient','lawyer'];
const LANGS=[['en','English'],['es','Spanish'],['fr','French'],['de','German'],['ja','Japanese']] as const;
const profiles:Record<Audience,{lead:string;focus:string;avoid:string}>={
'general public':{lead:'In plain language:',focus:'what it means and why it matters',avoid:'specialist shorthand'},'teenager':{lead:'The simplest way to say it:',focus:'one concrete idea at a time',avoid:'adult-professional jargon'},'customer':{lead:'What this means for you:',focus:'practical value, limits, and next step',avoid:'internal process language'},'regulator':{lead:'Core proposition:',focus:'scope, evidence, uncertainty, controls, and accountability',avoid:'marketing claims'},'investor':{lead:'The underlying claim:',focus:'value mechanism, evidence, uncertainty, and what would falsify it',avoid:'unsupported certainty'},'patient':{lead:'What you should know:',focus:'meaning, uncertainty, choices, and what this does not establish',avoid:'technical language that hides uncertainty'},'lawyer':{lead:'Proposition:',focus:'scope, defined terms, conditions, uncertainty, and support',avoid:'rhetorical overstatement'}};
const filler=/\b(very|really|basically|actually|just|simply|clearly|obviously)\b/gi;
const STOP=new Set('a an the and or but if then than to of in on at for from with by as is are was were be been being it this that these those they them their we our you your i its do does did can could may might will would should have has had'.split(' '));
const DEFAULT_SOURCE='A human reviewer may reduce risk only if they can see enough evidence, intervene before the outcome, and actually change or stop the decision.';
function sentences(v:string){return v.trim().split(/(?<=[.!?])\s+/).filter(Boolean)}
function nums(v:string){return v.match(/\b\d+(?:\.\d+)?%?\b/g)||[]}
function negs(v:string){return v.match(/\b(no|not|never|without|cannot|can't|doesn't|does not|isn't|is not|won't|will not)\b/gi)||[]}
function uncertainty(v:string){return v.match(/\b(may|might|could|suggests?|uncertain|approximately|about|likely|unlikely|associated|correlat\w*)\b/gi)||[]}
function proper(v:string){return v.match(/\b[A-Z][A-Za-z0-9&.-]{2,}(?:\s+[A-Z][A-Za-z0-9&.-]{2,})*\b/g)||[]}
function uniq(xs:string[]){return [...new Set(xs.map(x=>x.trim()).filter(Boolean))]}
function words(v:string){return v.toLowerCase().match(/[a-z0-9%.-]+/g)||[]}
function contentWords(v:string){return uniq(words(v).filter(w=>w.length>3&&!STOP.has(w)&&!/^\d/.test(w)))}
function simplify(v:string,a:Audience,t:Tone){let body=v.replace(filler,'').replace(/\s{2,}/g,' ').trim();if(t==='concise')body=sentences(body).slice(0,2).join(' ');if(a==='teenager'||a==='general public'||a==='patient')body=body.replace(/\butilize\b/gi,'use').replace(/\bapproximately\b/gi,'about').replace(/\bsubsequent\b/gi,'later').replace(/\bprior to\b/gi,'before').replace(/\btherefore\b/gi,'so');return `${profiles[a].lead} ${body}`}
function claimGraph(v:string){return sentences(v).map((text,i)=>({id:i+1,text,numbers:uniq(nums(text)),negation:uniq(negs(text)),uncertainty:uniq(uncertainty(text)),names:uniq(proper(text)).filter(x=>!['In','The','This','What'].includes(x)),terms:contentWords(text).slice(0,8)}))}
function auditMeaning(source:string,target:string,locks:string[]){
 const checks:{label:string;ok:boolean;detail:string}[]=[];const t=target.toLowerCase();
 const n=uniq(nums(source));checks.push({label:'Numbers preserved',ok:n.every(x=>target.includes(x)),detail:n.length?n.join(', '):'No numeric anchors'});
 const ng=uniq(negs(source));checks.push({label:'Negation preserved',ok:ng.length===0||ng.some(x=>t.includes(x.toLowerCase())),detail:ng.length?ng.join(', '):'No negation anchors'});
 const u=uniq(uncertainty(source));checks.push({label:'Uncertainty preserved',ok:u.length===0||u.some(x=>t.includes(x.toLowerCase())),detail:u.length?u.join(', '):'No uncertainty anchors'});
 const names=uniq(proper(source)).filter(x=>!['In','The','This','What'].includes(x));checks.push({label:'Named anchors preserved',ok:names.every(x=>t.includes(x.toLowerCase())),detail:names.length?names.join(', '):'No named anchors'});
 checks.push({label:'Locked facts preserved',ok:locks.every(x=>t.includes(x.toLowerCase())),detail:locks.length?locks.join(' · '):'No locked facts'});
 const srcTerms=contentWords(source);const trgTerms=new Set(contentWords(target));const coverage=srcTerms.length?Math.round(srcTerms.filter(x=>trgTerms.has(x)).length/srcTerms.length*100):100;
 checks.push({label:'Concept coverage',ok:coverage>=55,detail:`${coverage}% of source content terms remain verbatim`});
 const sourceLen=Math.max(1,words(source).length);const added=Math.max(0,words(target).length-sourceLen);const expansion=Math.round(added/sourceLen*100);
 checks.push({label:'Expansion controlled',ok:expansion<=75,detail:`${expansion}% net word expansion`});
 const failures=checks.filter(c=>!c.ok).length;const anchorPct=Math.round(checks.filter(c=>c.ok).length/checks.length*100);const risk=failures>=2?'high':failures===1||coverage<70?'review':'low';
 return {checks,pct:anchorPct,coverage,risk};
}
function encodeState(value:unknown){const bytes=new TextEncoder().encode(JSON.stringify(value));let raw='';bytes.forEach(b=>raw+=String.fromCharCode(b));return btoa(raw)}
function decodeState<T>(value:string):T|null{try{const raw=atob(value);const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes)) as T}catch{return null}}

export default function MeaningArchitecture(){
 const [source,setSource]=useState(DEFAULT_SOURCE);const [audience,setAudience]=useState<Audience>('general public');const [tone,setTone]=useState<Tone>('plain');const [lockText,setLockText]=useState('');const [draft,setDraft]=useState(()=>simplify(DEFAULT_SOURCE,'general public','plain'));
 const [engine,setEngine]=useState('deterministic local');const [aiState,setAiState]=useState('not run');const [targetLang,setTargetLang]=useState('es');const [translated,setTranslated]=useState('');const [translationState,setTranslationState]=useState('not run');const [events,setEvents]=useState<Event[]>([]);const [shareState,setShareState]=useState('');
 const locks=useMemo(()=>uniq(lockText.split('\n')),[lockText]);const claims=useMemo(()=>claimGraph(source),[source]);const audit=useMemo(()=>auditMeaning(source,draft,locks),[source,draft,locks]);const sourceSet=useMemo(()=>new Set(words(source)),[source]);const outWords=draft.split(/\s+/);
 function log(engineName:string,action:string,detail:string){setEvents(prev=>[{at:new Date().toISOString(),engine:engineName,action,detail},...prev].slice(0,20))}
 function deterministic(nextSource=source,nextAudience=audience,nextTone=tone){setDraft(simplify(nextSource,nextAudience,nextTone));setEngine('deterministic local');setTranslated('')}
 function changeSource(next:string){setSource(next);deterministic(next,audience,tone)}
 function changeAudience(next:Audience){setAudience(next);deterministic(source,next,tone)}
 function changeTone(next:Tone){setTone(next);deterministic(source,audience,next)}
 useEffect(()=>{const hydrate=()=>{const parsed=decodeState<{source?:string;audience?:Audience;tone?:Tone;locks?:string;targetLang?:string}>(location.hash.replace(/^#state=/,''));if(!parsed)return;const nextSource=parsed.source||DEFAULT_SOURCE;const nextAudience=parsed.audience||'general public';const nextTone=parsed.tone||'plain';setSource(nextSource);setAudience(nextAudience);setTone(nextTone);setDraft(simplify(nextSource,nextAudience,nextTone));setEngine('deterministic local');if(typeof parsed.locks==='string')setLockText(parsed.locks);if(parsed.targetLang)setTargetLang(parsed.targetLang)};queueMicrotask(hydrate)},[]);
 async function adaptWithLocalAI(){setAiState('checking browser…');try{const LM=(globalThis as BrowserAI).LanguageModel;if(!LM){setAiState('Local Prompt API is not available here. Deterministic mode remains active.');return}const availability=await LM.availability();if(availability==='unavailable'){setAiState('This device cannot run the local language model.');return}setAiState(availability==='downloadable'?'downloading browser-managed local model…':'adapting locally…');const session=await LM.create({initialPrompts:[{role:'system',content:'Rewrite text for the requested audience. Preserve every factual proposition, number, negation, uncertainty marker, named entity, and explicitly locked fact. Do not add evidence, claims, examples, legal conclusions, medical conclusions, or certainty. Return only the rewritten text.'}]});const prompt=`Audience: ${audience}\nStyle: ${tone}\nAudience priority: ${profiles[audience].focus}\nAvoid: ${profiles[audience].avoid}\nLocked facts: ${locks.join(' | ')||'none'}\nSOURCE:\n${source}`;const result=await session.prompt(prompt);setDraft(result.trim());setEngine('Chrome local LanguageModel');setAiState('adapted locally; independent checks rerun below');log('Chrome local LanguageModel','audience adaptation',`${audience} / ${tone}`);session.destroy?.()}catch(e){setAiState(`Local AI could not run: ${e instanceof Error?e.message:'unknown error'}`)}}
 async function translateLocal(){setTranslationState('checking browser…');setTranslated('');try{const T=(globalThis as BrowserAI).Translator;if(!T){setTranslationState('Local Translator API is not available in this browser.');return}const availability=await T.availability({sourceLanguage:'en',targetLanguage:targetLang});if(availability==='unavailable'){setTranslationState('This language pair is unavailable on this device.');return}setTranslationState(availability==='downloadable'?'downloading local language model…':'translating locally…');const translator=await T.create({sourceLanguage:'en',targetLanguage:targetLang});const result=await translator.translate(draft);setTranslated(result);setTranslationState('translated on this device');log('Chrome local Translator',`translate en→${targetLang}`,`${audience} adaptation`);translator.destroy?.()}catch(e){setTranslationState(`Translation could not run: ${e instanceof Error?e.message:'unknown error'}`)}}
 async function copyShare(){const state=encodeState({source,audience,tone,locks:lockText,targetLang});const url=`${location.origin}${location.pathname}#state=${state}`;history.replaceState(null,'',`#state=${state}`);try{await navigator.clipboard.writeText(url);setShareState('share link copied')}catch{setShareState('share state saved in this URL')}}
 function exportRecord(){const payload={build:'002-A',engineVersion:'002.1.0',createdAt:new Date().toISOString(),source,audience,tone,locks,adaptation:draft,engine,audit,claims,translation:translated?{language:targetLang,text:translated}:null,provenance:events};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='build-002-meaning-record.json';a.click();URL.revokeObjectURL(url);log('browser','export record','JSON provenance package')}
 return <div className={s.app}>
 <section className={s.controls}><div className={s.step}><span>01 / SOURCE TRUTH</span><h2>What must stay true?</h2><textarea aria-label="Source truth" maxLength={5000} value={source} onChange={e=>changeSource(e.target.value)} rows={6}/><label>Optional locked facts — one per line<textarea value={lockText} maxLength={2500} onChange={e=>setLockText(e.target.value)} rows={3} placeholder="Exact phrase or fact that must survive"/></label></div><div className={s.step}><span>02 / DOOR</span><h2>Who needs to understand it?</h2><div className={s.chips}>{AUDIENCES.map(a=><button type="button" key={a} aria-pressed={a===audience} onClick={()=>changeAudience(a)}>{a}</button>)}</div><label>Style<select value={tone} onChange={e=>changeTone(e.target.value as Tone)}><option>plain</option><option>formal</option><option>warm</option><option>concise</option></select></label><div className={s.profile}><b>{audience}</b><p>Prioritize {profiles[audience].focus}. Avoid {profiles[audience].avoid}.</p></div><button type="button" className={s.aiButton} onClick={adaptWithLocalAI}>TRY BROWSER-LOCAL AI ADAPTATION</button><small className={s.engineState} aria-live="polite">{aiState}</small></div></section>
 <section className={s.claims}><div className={s.resultHead}><div><span>03 / CLAIM GRAPH</span><h2>Break the source into things that can drift.</h2></div><small>{claims.length} proposition{claims.length===1?'':'s'}</small></div><div className={s.claimGrid}>{claims.map(c=><article key={c.id}><b>CLAIM {String(c.id).padStart(2,'0')}</b><p>{c.text}</p><dl><div><dt>numbers</dt><dd>{c.numbers.join(', ')||'—'}</dd></div><div><dt>negation</dt><dd>{c.negation.join(', ')||'—'}</dd></div><div><dt>uncertainty</dt><dd>{c.uncertainty.join(', ')||'—'}</dd></div><div><dt>names</dt><dd>{c.names.join(', ')||'—'}</dd></div></dl></article>)}</div></section>
 <section className={s.result} aria-live="polite"><div className={s.resultHead}><div><span>04 / ADAPTATION</span><h2>Different door. Same factual core.</h2><small>engine / {engine}</small></div><div className={s.meter} data-risk={audit.risk}><strong>{audit.pct}</strong><small>{audit.risk} drift risk</small></div></div><div className={s.translation}>{outWords.map((w,i)=>{const key=w.toLowerCase().replace(/[^a-z0-9%.-]/g,'');return <mark key={`${w}-${i}`} data-new={!sourceSet.has(key)}>{w} </mark>})}</div><div className={s.audit}>{audit.checks.map(c=><div key={c.label} data-ok={c.ok}><b>{c.ok?'✓':'!'} {c.label}</b><small>{c.detail}</small></div>)}</div></section>
 <section className={s.result}><div className={s.resultHead}><div><span>05 / LANGUAGE</span><h2>Translate on the device when the browser can.</h2></div></div><div className={s.langRow}><select aria-label="Target language" value={targetLang} onChange={e=>setTargetLang(e.target.value)}>{LANGS.filter(([v])=>v!=='en').map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><button type="button" onClick={translateLocal}>TRANSLATE LOCALLY</button><small aria-live="polite">{translationState}</small></div>{translated&&<div className={s.translation} lang={targetLang}>{translated}</div>}<p className={s.micro}>Translation is another transformation layer, not proof of cultural equivalence. Consequential multilingual communication still requires competent human review.</p></section>
 <section className={s.compare}><div><span>SOURCE</span><p>{source}</p></div><div><span>{audience.toUpperCase()}</span><p>{draft}</p></div></section>
 <section className={s.provenance}><div><span>06 / PORTABLE RECORD</span><h2>Take the reasoning with you.</h2><p>The share state contains the source, audience, style, locks, and target language—not a server-side account. The JSON export adds the claim graph, audit and local provenance events.</p><div className={s.actionRow}><button type="button" onClick={copyShare}>COPY SHAREABLE STATE</button><button type="button" onClick={exportRecord}>EXPORT JSON RECORD</button><small aria-live="polite">{shareState}</small></div></div><div><span>LOCAL PROVENANCE</span>{events.length===0?<p>No optional model/translation actions yet.</p>:<ol>{events.map((e,i)=><li key={`${e.at}-${i}`}><b>{e.action}</b><small>{e.engine} · {e.detail}</small></li>)}</ol>}</div></section>
 <p className={s.note}><strong>What this prototype does:</strong> separates generation from verification. Deterministic checks remain independent even when a supported desktop Chrome browser supplies a local language model or translator. Passing automated checks is not proof of semantic, legal, scientific, clinical, or cultural equivalence.</p>
 </div>}
