from pathlib import Path
from xml.sax.saxutils import escape
import hashlib, json, textwrap

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "apps/web/public/media/100-builds/source-excerpts"
MANIFEST = ROOT / "docs/builds/visual-source-acquisition-001-100/RENDERED-CAPTURE-MANIFEST.json"

# Each excerpt is copied from the previously hash-verified source text. Ellipses
# are never inserted inside a quotation; separate source regions are visibly
# identified as a composite.
DATA = {
 "010": {"heading":"Shapes Constraint Language (SHACL)","body":["W3C Recommendation 20 July 2017","This document defines the SHACL Shapes Constraint Language, a language for validating RDF graphs against a set of conditions. These conditions are provided as shapes and other constructs expressed in the form of an RDF graph."],"source":"W3C SHACL Recommendation","url":"https://www.w3.org/TR/2017/REC-shacl-20170720/","notice":"Copyright © 2017 W3C®. Excerpt under the W3C Document License: https://www.w3.org/copyright/document-license-2023/","alt":"Sequential text excerpt containing the title, 20 July 2017 Recommendation status, and opening abstract sentences of the official W3C SHACL specification."},
 "030": {"heading":"Web Content Accessibility Guidelines (WCAG) 2.2","body":["W3C Recommendation 05 October 2023","Web Content Accessibility Guidelines (WCAG) 2.2 covers a wide range of recommendations for making Web content more accessible.","COMPOSITE — separate source section","Principles — At the top are four principles that provide the foundation for Web accessibility: perceivable, operable, understandable, and robust."],"source":"WCAG 2.2 — immutable 2023 Recommendation","url":"https://www.w3.org/TR/2023/REC-WCAG22-20231005/","notice":"Copyright © 2023 W3C®. Excerpt under the W3C Document License: https://www.w3.org/copyright/document-license-2023/","alt":"Sequential text composite from the immutable 5 October 2023 WCAG 2.2 Recommendation: title and status, one abstract sentence, then a separately labeled principles passage."},
 "036": {"heading":"Service Workers 1","body":["W3C Candidate Recommendation, 19 November 2019","The service worker is designed first to redress the balance between Web applications and native applications’ offline capabilities, and running background code to process events like push messages, even while offline."],"source":"Service Workers 1 — 2019 Candidate Recommendation","url":"https://www.w3.org/TR/2019/CR-service-workers-1-20191119/","notice":"Copyright © 2019 W3C®. Excerpt subject to the snapshot’s W3C Software and Document License notice.","alt":"Sequential text excerpt containing the title, 19 November 2019 Candidate Recommendation status, and offline-capability motivation passage from Service Workers 1."},
 "038": {"heading":"NIST AI RMF 1.0 — scope context","body":["The Framework is intended to be voluntary, rights-preserving, non-sector-specific, and use-case agnostic, providing flexibility to organizations of all sizes and in all sectors and throughout society to implement the approaches in the Framework.","CONTEXT LIMIT — This passage does not address benchmark scores or real-world performance."],"source":"NIST AI RMF 1.0, p. 2","url":"https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf","notice":"Official NIST publication excerpt; third-party material excluded. Publication notices and source control: https://www.nist.gov/open","alt":"NIST AI RMF 1.0 scope excerpt stating that the Framework is voluntary and use-case agnostic, followed by an editorial warning that it does not address benchmark performance."},
 "039": {"heading":"PROV-O: The PROV Ontology","body":["W3C Recommendation 30 April 2013","The PROV Ontology (PROV-O) expresses the PROV Data Model [PROV-DM] using the OWL2 Web Ontology Language (OWL2) [OWL2-OVERVIEW]. It provides a set of classes, properties, and restrictions that can be used to represent and interchange provenance information generated in different systems and under different contexts.","CONTEXT LIMIT — Provenance representation is not proof that a trace is true."],"source":"W3C PROV-O Recommendation","url":"https://www.w3.org/TR/2013/REC-prov-o-20130430/","notice":"Copyright © 2013 W3C®. Excerpt under the W3C Document License: https://www.w3.org/copyright/document-license-2023/","alt":"Sequential text excerpt containing the title, 30 April 2013 Recommendation status, and opening PROV-O abstract sentences, followed by an editorial warning that provenance is not proof of truth."},
 "040": {"heading":"NIST AI RMF 1.0 — trustworthiness tradeoffs","body":["Trustworthiness characteristics explained in this document influence each other. Highly secure but unfair systems, accurate but opaque and uninterpretable systems, and inaccurate but secure, privacy-enhanced, and transparent systems are all undesirable.","CONTEXT LIMIT — This passage does not itself define permission or authorization."],"source":"NIST AI RMF 1.0, p. 13","url":"https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf","notice":"Official NIST publication excerpt; third-party material excluded. Publication notices and source control: https://www.nist.gov/open","alt":"NIST AI RMF 1.0 excerpt about tradeoffs among trustworthiness characteristics, followed by an editorial warning that the passage does not define permission."},
 "041": {"heading":"NIST AI RMF 1.0 — GOVERN 2","body":["GOVERN 2: Accountability structures are in place so that the appropriate teams and individuals are empowered, responsible, and trained for mapping, measuring, and managing AI risks.","COMPOSITE — selected subcategories","GOVERN 2.1: Roles and responsibilities and lines of communication related to mapping, measuring, and managing AI risks are documented and are clear to individuals and teams throughout the organization.","GOVERN 2.3: Executive leadership of the organization takes responsibility for decisions about risks associated with AI system development and deployment."],"source":"NIST AI RMF 1.0, p. 23","url":"https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf","notice":"Official NIST publication excerpt; third-party material excluded. Publication notices and source control: https://www.nist.gov/open","alt":"Sequential text composite from NIST AI RMF GOVERN 2 containing the accountability statement and separately labeled subcategories 2.1 and 2.3 about roles and executive responsibility."},
 "049": {"heading":"NIST Privacy Framework 1.0 — Profiles","body":["Profiles can be used to describe the current state and the desired target state of specific privacy activities. A Current Profile indicates privacy outcomes that an organization is currently achieving, while a Target Profile indicates the outcomes needed to achieve the desired privacy risk management goals.","CONTEXT LIMIT — Organizational privacy Profiles are not individual user preferences."],"source":"NIST Privacy Framework 1.0, p. 8","url":"https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.01162020.pdf","notice":"Official NIST publication excerpt; third-party material excluded. Publication notices and source control: https://www.nist.gov/open","alt":"NIST Privacy Framework excerpt explaining current and target organizational privacy Profiles, followed by an editorial warning that Profiles are not individual user preferences."},
 "055": {"heading":"NISTIR 8259A — Cybersecurity State Awareness","body":["Capability: The IoT device can report on its cybersecurity state and make that information accessible to authorized entities only.","Common Elements: 1. The ability to report the device’s cybersecurity state. 2. The ability to differentiate between when a device will likely operate as expected from when it may be in a degraded cybersecurity state.","CONTEXT LIMIT — State reporting is narrower than natural-language explainability."],"source":"NISTIR 8259A, p. 10","url":"https://nvlpubs.nist.gov/nistpubs/ir/2020/NIST.IR.8259A.pdf","notice":"Official NIST publication excerpt; third-party material excluded. Publication notices and source control: https://www.nist.gov/open","alt":"NISTIR 8259A excerpt describing IoT cybersecurity state reporting and differentiation, followed by an editorial warning that state reporting is not natural-language explainability."},
 "057": {"heading":"PROV-O — Starting Point Terms","body":["The Starting Point category is a small set of classes and properties that can be used to create simple, initial provenance descriptions.","COMPOSITE — selected definitions","An prov:Entity is a physical, digital, conceptual, or other kind of thing with some fixed aspects; entities may be real or imaginary.","An prov:Activity is something that occurs over a period of time and acts upon or with entities; it may include consuming, processing, transforming, modifying, relocating, using, or generating entities."],"source":"W3C PROV-O Recommendation","url":"https://www.w3.org/TR/2013/REC-prov-o-20130430/","notice":"Copyright © 2013 W3C®. Excerpt under the W3C Document License: https://www.w3.org/copyright/document-license-2023/","alt":"Sequential text composite from PROV-O Starting Point Terms: the introductory provenance-description passage, then separately labeled Entity and Activity definitions."},
 "058": {"heading":"PROV-O — Starting Point Terms","body":["Entity: An prov:Entity is a physical, digital, conceptual, or other kind of thing with some fixed aspects; entities may be real or imaginary.","COMPOSITE — selected relations","wasGeneratedBy: Activities start and end at particular points in time and during their lifespan can use and generate a variety of Entities.","wasDerivedFrom: Provenance chains comprising only Entities can be formed using the prov:wasDerivedFrom property. A derivation is a transformation of one entity into another."],"source":"W3C PROV-O Recommendation","url":"https://www.w3.org/TR/2013/REC-prov-o-20130430/","notice":"Copyright © 2013 W3C®. Excerpt under the W3C Document License: https://www.w3.org/copyright/document-license-2023/","alt":"Sequential text composite from PROV-O Starting Point Terms containing an Entity definition and separately labeled generation and derivation relation passages."}
}

manifest = json.loads(MANIFEST.read_text())
records = {r["buildId"]: r for r in manifest["records"]}
for bid, d in DATA.items():
    spans=[]; y=112
    for line in textwrap.wrap(d["heading"], 34, break_long_words=False, break_on_hyphens=False):
        spans.append(f'<text x="84" y="{y}" class="head">{escape(line)}</text>'); y += 60
    y += 20
    for para in d["body"]:
        editorial = para.startswith(("COMPOSITE", "CONTEXT LIMIT"))
        cls = "note" if editorial else "body"
        for line in textwrap.wrap(para, 48, break_long_words=False, break_on_hyphens=False):
            spans.append(f'<text x="84" y="{y}" class="{cls}">{escape(line)}</text>'); y += 50
        y += 22
    if y > 1130:
        raise RuntimeError(f"{bid} body overflow: {y}")
    footer=[f'Source: {d["source"]}',d["url"],d["notice"],'Context excerpt only · No affiliation or endorsement.','HOLD · REVIEW RENDER · NOT SELECTED OR STAGED']
    fy=1190
    for item in footer:
        for line in textwrap.wrap(item, 66, break_long_words=False, break_on_hyphens=False):
            spans.append(f'<text x="84" y="{fy}" class="foot">{escape(line)}</text>'); fy += 42
    if fy > 1450:
        raise RuntimeError(f"{bid} footer overflow: {fy}")
    svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1500" viewBox="0 0 1200 1500" role="img" aria-labelledby="title desc"><title id="title">Build {bid} source excerpt review render</title><desc id="desc">{escape(d["alt"])}</desc><rect width="1200" height="1500" fill="#f7f4ed"/><rect x="48" y="48" width="1104" height="1404" rx="20" fill="#fff" stroke="#222" stroke-width="3"/><style>.head{{font:700 50px Arial,sans-serif;fill:#111}}.body{{font:40px Arial,sans-serif;fill:#1f2933}}.note{{font:italic 40px Arial,sans-serif;fill:#7c2d12}}.foot{{font:32px Arial,sans-serif;fill:#374151}}</style>{''.join(spans)}</svg>'''
    out=OUT/f"build-{bid}-source-excerpt-hold.svg"; out.write_text(svg)
    r=records[bid]
    r["sha256"]=hashlib.sha256(svg.encode()).hexdigest()
    r["alt"]=d["alt"]
    r["caption"]=f'{d["source"]}. Sequential context excerpt; any composite or contextual limit is visibly labeled. No affiliation or endorsement.'
    r["notice"]=d["notice"]
    r["gatesPassed"]=["source bytes matched recorded SHA-256","selected exact source wording preserved","composites and editorial context limits visibly labeled","sequential single-column reading order","minimum 40px body text and 32px notice text","excluded logos/figures/examples absent","accessible title and description present"]
    r["gatesOpen"]=["final rights/notice sufficiency review","final contextual-fit approval"]

MANIFEST.write_text(json.dumps(manifest,indent=2)+"\n")
print(json.dumps({"rendered":len(DATA),"maxBodyY":"<1130","minBodyFont":40,"minNoticeFont":32}))
