'use client';
import {useMemo,useState} from 'react';import {assessIdeaSkeleton,type IdeaSkeleton,type SkeletonEntity} from '../../../../../../packages/release/src/decision-engines';import s from './idea-skeleton.module.css';
const demo:IdeaSkeleton={idea:'Community resilience project record',entities:[{id:'place',label:'Place',description:'A governed geographic or community context.',fields:[{id:'name',label:'Name',type:'text',required:true,sourceRule:'Use the steward-approved place register.'},{id:'hazard',label:'Prevailing hazard',type:'text',required:true,sourceRule:'Cite the current local hazard plan.'}]},{id:'project',label:'Project',description:'A proposed resilience intervention.',fields:[{id:'title',label:'Title',type:'text',required:true,sourceRule:'Use the approved project record.'},{id:'status',label:'Status',type:'text',required:true,sourceRule:'Use the named decision ledger.'}]}],relationships:[{id:'located-in',from:'project',to:'place',label:'located in',cardinality:'many-to-many',required:true}],sources:[{id:'local-plan',label:'Local plan',authority:'Responsible local public or community steward',locatorRule:'Document, version, section and stable URL',freshnessRule:'Recheck on every revision or at least annually'}]};
export default function IdeaSkeletonLab(){const[data,setData]=useState<IdeaSkeleton>(demo);const[notice,setNotice]=useState('');const result=useMemo(()=>assessIdeaSkeleton(data),[data]);
 function entity(id:string,key:keyof SkeletonEntity,value:string){setData(v=>({...v,entities:v.entities.map(e=>e.id===id?{...e,[key]:value}:e)}))}
 function addEntity(){setData(v=>({...v,entities:[...v.entities,{id:'entity-'+(v.entities.length+1),label:'New entity',description:'',fields:[]}]}))}
 function reset(){setData({idea:'',entities:[],relationships:[],sources:[]});setNotice('Cleared. No schema data was stored.')}
 function exportRecord(){const blob=new Blob([JSON.stringify({build:'010-A',schema:data,assessment:result,boundary:'Structural validity is not factual truth or domain approval.'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='idea-skeleton.json';a.click();URL.revokeObjectURL(url);setNotice('Idea skeleton exported.')}
 return <div className={s.app}>{notice&&<p role="status">{notice}</p>}<section><span>01 / CONCEPT</span><label>What are you trying to make concrete?<textarea value={data.idea} onChange={e=>setData(v=>({...v,idea:e.currentTarget.value}))}/></label></section><section><header><div><span>02 / ENTITIES + FIELDS</span><h2>The things that exist</h2></div><button onClick={addEntity}>ADD ENTITY</button></header><div className={s.cards}>{data.entities.map(e=><fieldset key={e.id}><legend>{e.label||e.id}</legend><label>Stable ID<input value={e.id} onChange={x=>entity(e.id,'id',x.currentTarget.value)}/></label><label>Label<input value={e.label} onChange={x=>entity(e.id,'label',x.currentTarget.value)}/></label><label>Definition<textarea value={e.description} onChange={x=>entity(e.id,'description',x.currentTarget.value)}/></label><h3>Fields</h3>{e.fields.map(f=><article key={f.id}><strong>{f.id} / {f.label}</strong><span>{f.type} · {f.required?'required':'optional'}</span><p>{f.sourceRule||'No source rule'}</p></article>)}<button onClick={()=>setData(v=>({...v,entities:v.entities.filter(x=>x.id!==e.id)}))}>REMOVE ENTITY</button></fieldset>)}</div></section><section><span>03 / RELATIONSHIPS</span><h2>How the things connect</h2>{data.relationships.map(r=><article key={r.id}><strong>{r.from} — {r.label} → {r.to}</strong><p>{r.cardinality} · {r.required?'required':'optional'}</p></article>)}</section><section><span>04 / SOURCE RULES</span>{data.sources.map(src=><article key={src.id}><h3>{src.label}</h3><p><strong>Authority:</strong> {src.authority}</p><p><strong>Locator:</strong> {src.locatorRule}</p><p><strong>Freshness:</strong> {src.freshnessRule}</p></article>)}</section><section className={s.result} aria-live="polite"><span>VALIDATION / ENGINE {result.engineVersion}</span><h2>{result.status}</h2><p>Structural readiness <strong>{result.score}%</strong></p><div><article><h3>Errors</h3>{result.errors.length?<ul>{result.errors.map(x=><li key={x}>{x}</li>)}</ul>:<p>None.</p>}</article><article><h3>Warnings</h3>{result.warnings.length?<ul>{result.warnings.map(x=><li key={x}>{x}</li>)}</ul>:<p>None.</p>}</article></div></section><div className={s.buttons}><button onClick={exportRecord}>EXPORT SKELETON</button><button onClick={reset}>RESET / START EMPTY</button></div><p><strong>Boundary:</strong> a structurally valid skeleton can still be factually wrong, incomplete, misleading, incompatible, or inappropriate for the domain.</p></div>}
