'use client';
import {useMemo,useState} from 'react';import {assessDataMinimization,type DataField} from '../../../../../../packages/release/src/privacy-minimization-engine';import s from '../privacy.module.css';
const seed:DataField[]=[
{id:'DAT-01',label:'Service reply address',classification:'necessary',collected:true,purpose:'Return the requested service decision',necessityBasis:'A reply cannot be delivered without one destination',permissionState:'not-required',retentionDays:30,deletionTrigger:'Delete thirty days after the response closes',redactionRule:'Mask in reviewer exports'},
{id:'DAT-02',label:'Application evidence',classification:'sensitive',collected:true,purpose:'Evaluate the requested service application',necessityBasis:'Named evidence is required for the synthetic eligibility review',permissionState:'granted',retentionDays:90,deletionTrigger:'Delete ninety days after final disposition',redactionRule:'Remove direct identifiers before analytics'},
{id:'DAT-03',label:'Marketing interests',classification:'optional',collected:true,purpose:'Personalize future promotional messages',necessityBasis:'',permissionState:'withdrawn',retentionDays:365,deletionTrigger:'Delete when promotional permission is withdrawn',redactionRule:'Exclude from operational export'},
{id:'DAT-04',label:'Inferred vulnerability score',classification:'derived',collected:true,purpose:'Prioritize applications for review',necessityBasis:'',permissionState:'not-required',retentionDays:90,deletionTrigger:'Delete with the underlying application',redactionRule:'Do not expose the score outside authorized review',derivedFrom:'Application evidence and correction history',derivationLogic:'Synthetic rule maps documented urgency signals to review priority'},
{id:'DAT-05',label:'Unrelated household browsing history',classification:'prohibited',collected:true,purpose:'Improve generalized prediction',necessityBasis:'',permissionState:'withdrawn',retentionDays:null,deletionTrigger:'',redactionRule:'Do not collect'}
];
export default function PrivacyMinimizationLab(){const [fields,setFields]=useState(seed);const assessment=useMemo(()=>assessDataMinimization(fields),[fields]);
function toggle(id:string){setFields(v=>v.map(f=>f.id===id?{...f,collected:!f.collected}:f))}
function minimize(){setFields(v=>v.map(f=>(f.classification==='optional'||f.classification==='prohibited')?{...f,collected:false}:f))}
function download(){const report={build:'024',schema:'data-minimization-plan',version:'024.1.0',fixture:'synthetic',generatedInBrowser:true,canonical:{title:'Privacy & Data Minimization Engine',job:'Determines which data is necessary, optional, sensitive, derived, prohibited, retained, or deletable.',bWeb:'A bloated intake shrinks to its justified minimum.',uses:['023'],creates:['cap:024']},fields,assessment,boundary:'Product-control demonstration, not a legal determination of necessity, consent, retention, or deletion duties.'};const href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=href;a.download='data-minimization-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(href),0)}
return <section className={s.lab}><header role="status" aria-live="polite" aria-atomic="true"><span>DATA MINIMIZATION / {assessment.gaps.length} OPEN GAPS</span><h2>{assessment.status}</h2><p>{assessment.collectedCount} collected · {assessment.excludedCount} excluded</p></header><div className={s.actions}><button className={s.primary} onClick={minimize}>REMOVE OPTIONAL + PROHIBITED</button><button onClick={()=>setFields(seed)}>RESET</button><button onClick={download}>EXPORT MINIMIZATION PLAN</button></div><div className={s.table} role="list" aria-label="Synthetic data field inventory">{fields.map(f=><article key={f.id} role="listitem" className={f.collected?s.kept:s.excluded}><div><small>{f.id} / {f.classification}</small><h3>{f.label}</h3></div><dl><div><dt>Purpose</dt><dd>{f.purpose||'No bounded purpose'}</dd></div><div><dt>Necessity basis</dt><dd>{f.necessityBasis||'Not provided'}</dd></div><div><dt>Permission</dt><dd>{f.permissionState}</dd></div><div><dt>Retention</dt><dd>{f.retentionDays===null?'Not bounded':`${f.retentionDays} days`}</dd></div><div><dt>Deletion</dt><dd>{f.deletionTrigger||'No trigger'}</dd></div><div><dt>Redaction</dt><dd>{f.redactionRule||'No rule'}</dd></div></dl><button aria-pressed={f.collected} onClick={()=>toggle(f.id)}>{f.collected?'COLLECTED — EXCLUDE':'EXCLUDED — RESTORE'}</button></article>)}</div><section className={s.gaps}><h3>Unresolved rules</h3>{assessment.gaps.length?<ul>{assessment.gaps.map(g=><li key={g}>{g}</li>)}</ul>:<p>Every collected field has passed this demonstration’s deterministic rules.</p>}</section><p className={s.note}><b>Boundary:</b> title, job, B-Web sentence, and lineage are frozen canon. The fixture, question, thesis, thresholds, and interface copy are derived. Everything runs client-locally; use no real personal data.</p></section>}