'use client';
import {useMemo,useState} from 'react';
import {assessDataMinimization,PRIVACY_MINIMIZATION_ENGINE_VERSION,type DataField} from '../../../../../../packages/release/src/privacy-minimization-engine';
import s from '../privacy.module.css';
const seed:DataField[]=[
{id:'DAT-01',label:'Service reply address',classification:'necessary',collected:true,purposeId:'PUR-REPLY',purpose:'Return the requested service decision',necessityBasis:'A reply cannot be delivered without one destination',evidenceRefs:['TEST-024-01 no-address delivery counterfactual'],permissionState:'not-required',retentionDays:30,retentionBasis:'Synthetic response-close schedule',deletionTrigger:'Thirty days after the response closes',deletionMethod:'Queue verified account-record deletion',redactionRule:'Mask in reviewer exports',decisionOwner:'Service data steward',counterfactualTested:true,functionalityImpact:'Without a destination, the service cannot return its decision.'},
{id:'DAT-02',label:'Application evidence',classification:'sensitive',collected:true,purposeId:'PUR-ELIGIBILITY',purpose:'Evaluate the requested service application',necessityBasis:'Named evidence is required for this synthetic eligibility review',evidenceRefs:['REQ-024-02 synthetic eligibility evidence rule'],permissionState:'granted',permissionPurposeId:'PUR-ELIGIBILITY',retentionDays:90,retentionBasis:'Synthetic appeal-window schedule',deletionTrigger:'Ninety days after final disposition',deletionMethod:'Delete primary record and expire indexed replicas',redactionRule:'Remove direct identifiers before analytics',decisionOwner:'Eligibility data steward',counterfactualTested:true,functionalityImpact:'Removing all evidence prevents this fixture from evaluating eligibility.'},
{id:'DAT-03',label:'Marketing interests',classification:'optional',collected:true,purposeId:'PUR-MARKETING',purpose:'Personalize future promotional messages',necessityBasis:'',evidenceRefs:[],permissionState:'withdrawn',permissionPurposeId:'PUR-MARKETING',retentionDays:365,retentionBasis:'',deletionTrigger:'When promotional permission is withdrawn',deletionMethod:'Delete marketing profile and downstream audience membership',redactionRule:'Exclude from operational export',decisionOwner:'Marketing data steward',counterfactualTested:false,functionalityImpact:''},
{id:'DAT-04',label:'Inferred vulnerability score',classification:'derived',collected:true,purposeId:'PUR-PRIORITY',purpose:'Prioritize applications for review',necessityBasis:'The synthetic queue requires a documented priority order',evidenceRefs:['TEST-024-04 manual-queue comparison'],permissionState:'granted',permissionPurposeId:'PUR-PRIORITY',retentionDays:90,retentionBasis:'Matches the synthetic source-record schedule',deletionTrigger:'When the underlying application is deleted',deletionMethod:'Recompute indexes, then delete score and cached copies',redactionRule:'Do not disclose outside authorized review',decisionOwner:'Review operations steward',counterfactualTested:true,functionalityImpact:'Without this score the fixture uses manual chronological review.',derivedFrom:'Application evidence and correction history',derivationLogic:'Synthetic rule maps documented urgency signals to review priority',sourceSensitivity:'sensitive'},
{id:'DAT-05',label:'Unrelated household browsing history',classification:'prohibited',collected:true,purposeId:'PUR-GENERALIZED',purpose:'Improve generalized prediction',necessityBasis:'',evidenceRefs:[],permissionState:'withdrawn',retentionDays:null,retentionBasis:'',deletionTrigger:'',deletionMethod:'',redactionRule:'Do not collect',decisionOwner:'Privacy data steward',counterfactualTested:false,functionalityImpact:''}
];
export default function PrivacyMinimizationLab(){
 const [fields,setFields]=useState(seed);const assessment=useMemo(()=>assessDataMinimization(fields),[fields]);
 function toggle(id:string){setFields(v=>v.map(f=>f.id===id?{...f,collected:!f.collected}:f))}
 function minimize(){setFields(v=>v.map(f=>(f.classification==='optional'||f.classification==='prohibited')?{...f,collected:false}:f))}
 function download(){const report={build:'024',schema:'data-minimization-plan',version:PRIVACY_MINIMIZATION_ENGINE_VERSION,fixture:'synthetic',generatedInBrowser:true,verificationState:assessment.status,canonical:{title:'Privacy & Data Minimization Engine',job:'Determines which data is necessary, optional, sensitive, derived, prohibited, retained, or deletable.',bWeb:'A bloated intake shrinks to its justified minimum.',uses:['023'],creates:['cap:024']},fields,assessment,limitations:['Evidence references are synthetic fixture identifiers, not independently verified evidence.','Deletion methods are planned controls, not proof that deletion occurred.','Permission state is a synthetic Build 023 inheritance demonstration, not a legal basis determination.'],boundary:assessment.assuranceBoundary};const href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=href;a.download='data-minimization-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(href),0)}
 return <section className={s.lab}><header role="status" aria-live="polite" aria-atomic="true"><span>DATA MINIMIZATION / {assessment.gaps.length} OPEN GAPS</span><h2>{assessment.status}</h2><p>{assessment.collectedCount} collected · {assessment.excludedCount} excluded</p></header><div className={s.actions}><button className={s.primary} onClick={minimize}>REMOVE OPTIONAL + PROHIBITED</button><button onClick={()=>setFields(seed)}>RESET</button><button onClick={download}>EXPORT MINIMIZATION PLAN</button></div><div className={s.table} role="list" aria-label="Synthetic data field inventory">{fields.map(f=><article key={f.id} role="listitem" className={f.collected?s.kept:s.excluded}><div><small>{f.id} / {f.classification}</small><h3>{f.label}</h3></div><dl><div><dt>Purpose</dt><dd>{f.purposeId}: {f.purpose||'No bounded purpose'}</dd></div><div><dt>Necessity basis</dt><dd>{f.necessityBasis||'Not provided'}</dd></div><div><dt>Evidence</dt><dd>{f.evidenceRefs.join(', ')||'No evidence reference'}</dd></div><div><dt>Counterfactual</dt><dd>{f.counterfactualTested?f.functionalityImpact:'Not tested'}</dd></div><div><dt>Permission</dt><dd>{f.permissionState}{f.permissionPurposeId?` · ${f.permissionPurposeId}`:''}</dd></div><div><dt>Retention</dt><dd>{f.retentionDays===null?'Not bounded':`${f.retentionDays} days · ${f.retentionBasis}`}</dd></div><div><dt>Deletion</dt><dd>{f.deletionTrigger&&f.deletionMethod?`${f.deletionTrigger} · ${f.deletionMethod}`:'No complete deletion plan'}</dd></div><div><dt>Redaction</dt><dd>{f.redactionRule||'No rule'}</dd></div><div><dt>Owner</dt><dd>{f.decisionOwner}</dd></div></dl><button aria-pressed={f.collected} onClick={()=>toggle(f.id)}>{f.collected?'COLLECTED — EXCLUDE':'EXCLUDED — RESTORE'}</button></article>)}</div><section className={s.gaps}><h3>Unresolved rules</h3>{assessment.gaps.length?<ul>{assessment.gaps.map((g,i)=><li key={`${i}-${g}`}>{g}</li>)}</ul>:<p>All collected fields passed this fixture’s deterministic control checks. This is not a legal or factual verification.</p>}</section><p className={s.note}><b>Boundary:</b> {assessment.assuranceBoundary} Everything runs client-locally; use no real personal data.</p></section>
}
