import type {Metadata} from 'next';
import Link from 'next/link';
import s from '../story.module.css';
import DossierNav from '../DossierNav';


export const metadata:Metadata={title:'Build 001 evidence: Human Review Design Framework',description:'Claim-to-source evidence map, provenance, and limits for Build 001, the Human Review Design Framework.',alternates:{canonical:'/100-builds/001/evidence'},robots:{index:true,follow:true}};
const sources=[
 {id:'NIST-AI-RMF-1.0',body:'NIST',title:'AI Risk Management Framework 1.0 — Core + Human-AI Interaction',date:'2023-01-26',checked:'2026-08-15',href:'https://airc.nist.gov/airmf-resources/airmf/5-sec-core/',sections:'GOVERN 2.1; GOVERN 3.2; MAP 2.2; MAP 3.4–3.5; MEASURE 1.2–1.3; Appendix C',status:'AI RMF 1.0 remains published; NIST states a revision is in progress.',supports:'defined roles and responsibilities; differentiated human-AI oversight roles; sufficient information for human decisions; operator proficiency; defined/assessed oversight; evaluation of control effectiveness; independent/domain review.'},
 {id:'EU-AI-ACT-ART14',body:'European Union',title:'Regulation (EU) 2024/1689 — Article 14, Human oversight',date:'2024-07-12',checked:'2026-08-15',href:'https://eur-lex.europa.eu/eli/reg/2024/1689/oj/eng',sections:'Article 14; related deployer-information requirements in Article 13',status:'Binding EU regulation; applicability depends on system, role, jurisdiction, and dates of application.',supports:'effective oversight of high-risk AI; appropriate human-machine interfaces; understanding capabilities/limitations; awareness of automation bias; correct interpretation; ability to disregard/override/reverse output or interrupt the system where provided by Article 14.'},
 {id:'ICO-HUMAN-REVIEW',body:'UK Information Commissioner’s Office',title:'Artificial intelligence audit toolkit — Human review',date:'current web guidance',checked:'2026-08-15',href:'https://ico.org.uk/for-organisations/advice-and-services/audits/data-protection-audit-framework/toolkits/artificial-intelligence/human-review/',sections:'Human review control measures, expectations, and options',status:'ICO explicitly says this guidance is under review following the Data (Use and Access) Act and may change.',supports:'meaningful review; reviewer qualifications/training; manageable workload/time; independence; ability to influence decisions; logging overrides/reasons; fallback/manual paths; standardized review procedures; testing review effectiveness.'}
];
const mappings=[
 ['Defined reviewer role','SYNTHESIS','NIST GOVERN 2.1 + GOVERN 3.2; ICO reviewer responsibility/qualification guidance','001 asks whether a real reviewer is identified and capable of carrying the role.'],
 ['Enough information / evidence','DIRECT + SYNTHESIS','NIST MAP 2.2; EU AI Act Arts. 13–14; ICO meaningful-review guidance','001 asks whether the reviewer can see enough context to interpret and challenge the AI-supported decision.'],
 ['Timing before consequence','SYNTHESIS','EU AI Act Art. 14 intervention/override/stop concepts; NIST MAP 3.5; ICO appropriate review stages','001 treats timing as a design condition: a safeguard cannot affect an outcome after the relevant intervention window has closed.'],
 ['Authority to disagree / override / stop','DIRECT + SYNTHESIS','EU AI Act Art. 14; ICO meaningful influence/authority; NIST human-oversight roles','001 distinguishes observation/advice from operative power to change the decision or trigger a fallback/escalation.'],
 ['Escalation / fallback','DIRECT + PRODUCT TRANSLATION','ICO fallback/manual options; NIST risk-response and oversight processes','001 recommends a path when the reviewer cannot safely resolve the issue themselves.'],
 ['Record of review / override','DIRECT','ICO override logs; NIST documentation and monitoring functions','001 treats a review record as evidence that review occurred and as input to later evaluation.'],
 ['Composite score / priority ordering','PRODUCT HEURISTIC','No source mandates the product score used by 001.','The score is a design aid created for this tool. It is not a legal, regulatory, safety, or compliance score.']
];

export default function Evidence(){return <main className={s.page}><header className={s.mast}><Link href="/100-builds/001">← BUILD 001</Link><span>PUBLIC BUILD RECORD / EVIDENCE</span></header><DossierNav/><section className={s.hero}><span>EVIDENCE + LIMITS</span><h1>Why the tool asks what it asks.</h1><p>001 translates recurring human-oversight concepts into a practical diagnostic. This record distinguishes direct source support, cross-source synthesis, and product heuristics instead of presenting the whole framework as if one authority prescribed it.</p></section><section className={s.cards}>{mappings.map(([name,type,source,meaning])=><article key={name}><b>{type}</b><h2>{name}</h2><p>{meaning}</p><strong>Claim-to-source map</strong><p>{source}</p></article>)}</section><section className={s.takeaway}><span>PRIMARY SOURCES / CHECKED 2026-08-15</span><h2>Exact provenance used for Build 001</h2>{sources.map(src=><article key={src.id}><b>{src.id}</b><h3>{src.body} — {src.title}</h3><p><strong>Published/version:</strong> {src.date}<br/><strong>Relevant sections:</strong> {src.sections}<br/><strong>Supports:</strong> {src.supports}<br/><strong>Current-status note:</strong> {src.status}</p><p><a href={src.href} target="_blank" rel="noreferrer">Open primary source ↗</a></p></article>)}<p><strong>Important:</strong> these sources do not collectively certify 001 as a compliance instrument. Applicability is context- and jurisdiction-dependent, and the tool intentionally labels its composite score and prioritization logic as product heuristics.</p></section></main>}
