'use client';
import {useMemo,useState} from 'react';
import {assessFeedbackLoop,type FeedbackControl,type FeedbackEventKind,type FeedbackSignal} from '../../../../../../packages/release/src/decision-engines';
import s from './feedback-loop.module.css';
const kinds:FeedbackEventKind[]=['use','outcome','correction','unmet-need'];
const labels:Record<FeedbackEventKind,string>={use:'Use',outcome:'Outcome',correction:'Correction','unmet-need':'Unmet need'};
const demoSignals:FeedbackSignal[]=[
{id:'use-1',kind:'use',description:'People abandon the review screen before completing it.',source:'Aggregated completion pattern',affectedGroup:'New reviewers',urgency:'routine',consentConfirmed:true},
{id:'outcome-1',kind:'outcome',description:'Teams report fewer unresolved launch decisions.',source:'Post-use outcome check',affectedGroup:'Product teams',urgency:'important',consentConfirmed:true},
{id:'correction-1',kind:'correction',description:'A reviewer flags a recommendation as unsafe for their context.',source:'In-product correction control',affectedGroup:'People affected by the recommendation',urgency:'urgent',consentConfirmed:true},
{id:'need-1',kind:'unmet-need',description:'Users need a way to compare evidence across review rounds.',source:'Research interview synthesis',affectedGroup:'Returning reviewers',urgency:'important',consentConfirmed:true}
];
const demoControl:FeedbackControl={owner:'Named product owner and domain reviewer',reviewTrigger:'Weekly review plus immediate urgent-correction triage',evidenceStandard:'Two corroborating signals or one documented high-consequence correction',changeAuthority:'Product owner may pause and rollback; domain reviewer approves consequential changes',validationRule:'Test with affected users before broader release and record the result',escalationPath:'Urgent harm signals pause the feature and reach the accountable lead',notificationRule:'Notify affected users when feedback materially changes behavior',retentionRule:'Keep minimized records for 90 days, then aggregate or delete',reviewCapacity:'Two reviewers have protected weekly capacity and a backup owner'};
const emptyControl:FeedbackControl={owner:'',reviewTrigger:'',evidenceStandard:'',changeAuthority:'',validationRule:'',escalationPath:'',notificationRule:'',retentionRule:'',reviewCapacity:''};
export default function FeedbackLoopLab(){
 const[product,setProduct]=useState('An AI-assisted launch review that helps teams inspect evidence before release.');
 const[signals,setSignals]=useState<FeedbackSignal[]>(demoSignals);const[control,setControl]=useState<FeedbackControl>(demoControl);const[status,setStatus]=useState('');
 const result=useMemo(()=>assessFeedbackLoop(signals,control),[signals,control]);
 function updateSignal(id:string,key:keyof FeedbackSignal,value:string|boolean){setSignals(all=>all.map(x=>x.id===id?{...x,[key]:value}:x))}
 function addSignal(){const id='signal-'+Date.now();setSignals(all=>[...all,{id,kind:'use',description:'',source:'',affectedGroup:'',urgency:'routine',consentConfirmed:false}]);setStatus('Blank feedback event added.')}
 function exportRecord(){const payload={build:'007-A',product,signals,control,assessment:result,inherits:['001.1.0'],limitations:['architecture assessment is a product heuristic','does not prove representativeness, causality, safety, compliance, demand, or consent sufficiency','does not deploy, train, or rank people']};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download='feedback-loop-architecture.json';a.click();URL.revokeObjectURL(href);setStatus('Feedback-loop record exported as JSON.')}
 function reset(){setProduct('');setSignals([]);setControl(emptyControl);setStatus('Cleared. No product data was stored.')}
 const controlFields:[keyof FeedbackControl,string][]=[['owner','Named owner'],['reviewTrigger','Review trigger'],['evidenceStandard','Evidence standard'],['changeAuthority','Change / pause authority'],['validationRule','Validation before release'],['escalationPath','Escalation / rollback path'],['notificationRule','User notification rule'],['retentionRule','Retention / deletion rule'],['reviewCapacity','Review capacity']];
 return <div className={s.app}><p className={s.privacy}><strong>Local workspace:</strong> do not enter personal, identifying, or confidential feedback. Nothing is sent or stored; export is your action.</p>{status&&<p className={s.status} role="status" aria-live="polite">{status}</p>}
 <section className={s.intro}><span>01 / NAME THE PRODUCT</span><label>Product or feature<textarea rows={3} value={product} onInput={e=>setProduct(e.currentTarget.value)} maxLength={2000}/></label></section>
 <section className={s.events}><header><div><span>02 / DEFINE WHAT IT CAN HEAR</span><h2>Feedback event schema</h2></div><button onClick={addSignal}>ADD EVENT</button></header>{kinds.map(kind=><div className={s.kind} key={kind}><h3>{labels[kind]}</h3><p>{kind==='use'?'What people do—not who they are.':kind==='outcome'?'What changed after use.':kind==='correction'?'A way to contest or repair an output.':'A job the current product still cannot serve.'}</p>{signals.filter(x=>x.kind===kind).map(signal=><fieldset key={signal.id}><legend>{labels[kind]} event</legend><label>Description<input value={signal.description} onInput={e=>updateSignal(signal.id,'description',e.currentTarget.value)}/></label><label>Source<input value={signal.source} onInput={e=>updateSignal(signal.id,'source',e.currentTarget.value)}/></label><label>Affected group<input value={signal.affectedGroup} onInput={e=>updateSignal(signal.id,'affectedGroup',e.currentTarget.value)}/></label><label>Urgency<select value={signal.urgency} onChange={e=>updateSignal(signal.id,'urgency',e.currentTarget.value)}><option>routine</option><option>important</option><option>urgent</option></select></label><label className={s.check}><input type="checkbox" checked={signal.consentConfirmed} onChange={e=>updateSignal(signal.id,'consentConfirmed',e.currentTarget.checked)}/> Collection is within the stated consent/purpose boundary</label><button onClick={()=>setSignals(all=>all.filter(x=>x.id!==signal.id))}>REMOVE EVENT</button></fieldset>)}</div>)}</section>
 <section className={s.controls}><span>03 / GOVERN THE LEARNING</span><h2>Human control architecture</h2><div>{controlFields.map(([key,label])=><label key={key}>{label}<textarea rows={2} value={control[key]} onInput={e=>setControl(v=>({...v,[key]:e.currentTarget.value}))}/></label>)}</div></section>
 <section className={s.result} aria-live="polite"><span>LOOP ASSESSMENT / ENGINE {result.engineVersion}</span><h2>{result.status}</h2><p>Event coverage: <strong>{result.coverage.length}/4</strong> · Build 001 human-control inheritance: <strong>{result.humanControl.score}/16 · {result.humanControl.grade}</strong></p>{result.missing.length>0&&<p>Missing: {result.missing.map(x=>labels[x]).join(' · ')}</p>}<h3>Priorities</h3>{result.priorities.length?<ol>{result.priorities.map(x=><li key={x}>{x}</li>)}</ol>:<p>All tested architecture gates are present. Validate the real operating process before relying on it.</p>}<h3>Improvement backlog rules</h3><ol>{result.backlogRules.map(x=><li key={x}>{x}</li>)}</ol></section>
 <div className={s.actions}><button onClick={exportRecord}>EXPORT RECORD</button><button onClick={reset}>RESET / START EMPTY</button></div><p className={s.boundary}><strong>Boundary:</strong> this is an inspectable architecture heuristic. It does not prove that feedback is representative, that a change caused an outcome, or that the product is safe, compliant, desirable, or ready to deploy.</p></div>
}
