'use client';
import {useMemo,useState} from 'react';
import {assessDecisionDashboard,type ActionState,type DashboardMetric} from '../../../../../../packages/release/src/decision-engines';
import s from './decision-dashboard.module.css';
const demoMetrics:DashboardMetric[]=[
{id:'m1',label:'Cases waiting beyond service target',value:'18%',source:'Case register · weekly extract',freshness:'Updated 16 Aug 2026',comparison:'Target ≤ 10%; prior week 14%',uncertainty:'Three cases have incomplete timestamps',decisionUse:'Determines whether the owner adds review capacity this week'},
{id:'m2',label:'High-consequence cases without assigned reviewer',value:'7 cases',source:'Assignment register',freshness:'Updated today at 09:00',comparison:'Trigger is any value above 0',uncertainty:'One classification is under review',decisionUse:'Triggers immediate assignment or escalation'}
];
const demoState:ActionState={decision:'Should we add reviewer capacity and reassign high-consequence cases this week?',owner:'Service operations lead',trigger:'Backlog exceeds 10% or any high-consequence case lacks a reviewer',action:'Assign backup reviewer and rebalance the current queue',deadline:'Decision by 15:00 today; action complete within one business day',authority:'Owner may reassign staff and pause lower-consequence intake',nextState:'No high-consequence case unassigned and backlog returns below 10%',escalation:'If capacity remains insufficient, escalate to the accountable director with the conflicting evidence'};
const blank:ActionState={decision:'',owner:'',trigger:'',action:'',deadline:'',authority:'',nextState:'',escalation:''};
export default function DecisionDashboardLab(){const[title,setTitle]=useState('Weekly case-review dashboard');const[metrics,setMetrics]=useState<DashboardMetric[]>(demoMetrics);const[state,setState]=useState<ActionState>(demoState);const[notice,setNotice]=useState('');const result=useMemo(()=>assessDecisionDashboard(metrics,state),[metrics,state]);
 function update(id:string,key:keyof DashboardMetric,value:string){setMetrics(all=>all.map(m=>m.id===id?{...m,[key]:value}:m))}
 function add(){setMetrics(all=>[...all,{id:'m-'+Date.now(),label:'',value:'',source:'',freshness:'',comparison:'',uncertainty:'',decisionUse:''}]);setNotice('Blank metric added.')}
 function reset(){setTitle('');setMetrics([]);setState(blank);setNotice('Cleared. No dashboard data was stored.')}
 function exportRecord(){const payload={build:'008-A',dashboard:title,metrics,actionState:state,assessment:result,inherits:['001.1.0'],limitations:['product heuristic','does not prove data quality, causality, authority, compliance, or decision correctness','does not execute action']};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='decision-ready-dashboard.json';a.click();URL.revokeObjectURL(url);setNotice('Decision-ready dashboard record exported.')}
 const fields:[keyof DashboardMetric,string][]=[['label','Metric'],['value','Current value'],['source','Source'],['freshness','Freshness'],['comparison','Comparison / threshold'],['uncertainty','Uncertainty / caveat'],['decisionUse','How can this change the decision?']];
 const action:[keyof ActionState,string][]=[['decision','Decision'],['owner','Accountable owner'],['trigger','Review trigger'],['action','Authorized action'],['deadline','Deadline'],['authority','Authority / pause power'],['nextState','Observable next state'],['escalation','Escalation path']];
 return <div className={s.app}>{notice&&<p role="status" className={s.notice}>{notice}</p>}<section className={s.start}><span>01 / START WITH THE DECISION</span><label>Dashboard name<input value={title} onChange={e=>setTitle(e.currentTarget.value)}/></label><label>Decision<textarea rows={3} value={state.decision} onChange={e=>setState(v=>({...v,decision:e.currentTarget.value}))}/></label></section><section className={s.metrics}><header><div><span>02 / JUSTIFY EVERY METRIC</span><h2>Evidence that can change the decision</h2></div><button onClick={add}>ADD METRIC</button></header>{metrics.map((m,i)=><fieldset key={m.id}><legend>Metric {i+1}</legend>{fields.map(([key,label])=><label key={key}>{label}<textarea rows={key==='decisionUse'?2:1} value={m[key]} onChange={e=>update(m.id,key,e.currentTarget.value)}/></label>)}<button onClick={()=>setMetrics(all=>all.filter(x=>x.id!==m.id))}>REMOVE METRIC</button></fieldset>)}</section><section className={s.action}><span>03 / MAKE THE ACTION STATE EXPLICIT</span><h2>Decision → owner → action → next state</h2><div>{action.filter(([k])=>k!=='decision').map(([key,label])=><label key={key}>{label}<textarea rows={2} value={state[key]} onChange={e=>setState(v=>({...v,[key]:e.currentTarget.value}))}/></label>)}</div></section><section className={s.result} aria-live="polite"><span>DECISION READINESS / ENGINE {result.engineVersion}</span><h2>{result.status}</h2><p>Metric readiness: <strong>{result.metricReadiness}%</strong> · Build 001 human-control inheritance: <strong>{result.humanControl.score}/16 · {result.humanControl.grade}</strong></p><h3>Action state</h3><ol>{result.actionState.map(x=><li key={x}>{x}</li>)}</ol><h3>Gaps</h3>{result.gaps.length?<ol>{result.gaps.map(x=><li key={x}>{x}</li>)}</ol>:<p>All tested gates are present. Verify the real data and operating authority before relying on the dashboard.</p>}</section><div className={s.buttons}><button onClick={exportRecord}>EXPORT RECORD</button><button onClick={reset}>RESET / START EMPTY</button></div><p className={s.boundary}><strong>Boundary:</strong> completeness is not correctness. This standard cannot prove data quality, causal attribution, organizational authority, compliance, or that the decision is right.</p></div>}
