'use client';
import {useMemo,useState} from 'react';
import {assessHumanConsequences,type HumanImpactNode} from '../../../../../../packages/release/src/human-consequence-engine';
import s from '../consequence.module.css';

const basePeople:HumanImpactNode[]=[
 {id:'P-01',label:'Benefit applicants',proximity:'DIRECT',consequence:'A delayed or incorrect eligibility recommendation can interrupt access to support.',severity:5,reversibility:4,notice:true,represented:false,recourse:true},
 {id:'P-02',label:'Household members',proximity:'HOUSEHOLD',consequence:'A decision about one applicant can change food, housing, care, or financial stability for a household.',severity:4,reversibility:4,notice:false,represented:false,recourse:false},
 {id:'P-03',label:'Eligibility workers',proximity:'WORKFORCE',consequence:'Automation can shift workload, discretion, accountability, and pressure onto frontline staff.',severity:3,reversibility:3,notice:true,represented:true,recourse:false},
 {id:'P-04',label:'Affected communities',proximity:'COMMUNITY',consequence:'Repeated workflow errors can distribute access barriers unevenly across a community.',severity:4,reversibility:4,notice:false,represented:false,recourse:false}
];
function fixtures(people:HumanImpactNode[]){
 const complete='Named accountable public-benefits program owner';
 const workflow={name:'Synthetic benefits triage',purpose:'Prioritize applications for authorized human review',affectedPeople:people.map(p=>p.label).join(', '),stages:[
  {id:'intake',label:'Application intake',kind:'intake' as const,owner:complete,input:'Synthetic application fields',output:'Structured intake record',control:'Required-field and source checks',stopAuthority:'Intake supervisor may stop processing',monitoring:'Missing-field and rejection monitoring'},
  {id:'model',label:'AI triage',kind:'model' as const,owner:complete,input:'Structured intake record',output:'Priority recommendation',control:'Versioned test and threshold controls',stopAuthority:'Program owner may disable triage',monitoring:'Outcome and subgroup monitoring'},
  {id:'review',label:'Human review',kind:'decision' as const,owner:complete,input:'Recommendation and source record',output:'Authorized review disposition',control:'Reviewer sees evidence and may change outcome',stopAuthority:'Authorized reviewer may stop or reverse',monitoring:'Override and correction monitoring'}
 ],edges:[{from:'intake',to:'model'},{from:'model',to:'review'}],risks:[{id:'R-1',label:'Access delayed by incorrect priority',entryStage:'model',severity:5 as const,likelihood:2 as const,evidence:'Synthetic test condition; real frequency is unknown'}],useMap:{useName:'Synthetic benefits triage',purpose:'Prioritize applications for authorized human review',affectedPeople:people.map(p=>p.label).join(', '),dimensions:[{key:'severity',label:'Severity',score:5 as const,evidence:'Essential-support interruption'},{key:'rights',label:'Rights',score:4 as const,evidence:'Eligibility and procedural interests'},{key:'essential-service',label:'Essential service',score:5 as const,evidence:'Benefits access'},{key:'reversibility',label:'Reversibility',score:4 as const,evidence:'Delay may be partly repairable'},{key:'uncertainty',label:'Uncertainty',score:3 as const,evidence:'Synthetic fixture'}],controls:{owner:complete,reviewTrigger:'Every recommendation receives authorized review',authority:'Reviewer can change, stop, and escalate',evidence:'Source record and recommendation rationale',testing:'Versioned pre-use performance test',monitoring:'Outcome and subgroup monitoring',appeal:'Applicant correction and appeal path',stopRule:'Program owner can disable and rollback',incidentResponse:'Named investigation and notification duty',record:'Append-only decision evidence record',notice:'Plain-language notice of AI-assisted triage'},model:{idea:'AI-assisted benefits triage',entities:[{id:'use',label:'AI use',description:'A bounded application of AI in a workflow.',fields:[{id:'purpose',label:'Purpose',type:'text' as const,required:true,sourceRule:'Record approved purpose and owner.'}]},{id:'person',label:'Affected person',description:'A person affected by the workflow.',fields:[{id:'outcome',label:'Outcome',type:'text' as const,required:true,sourceRule:'Record observed outcomes.'}]}],relationships:[{id:'affects',from:'use',to:'person',label:'affects',cardinality:'many-to-many' as const,required:true}],sources:[{id:'record',label:'Governance record',authority:'Accountable program owner',locatorRule:'Stable record ID',freshnessRule:'Review on material change'}]}}};
 const organizations=[{id:'agency',name:'Benefits agency',role:'Owns eligibility process',authority:'Governing program authority must be verified',accountableOwner:'Named benefits program owner',governingSource:'Applicable program rules and procedure'},{id:'review',name:'Authorized review unit',role:'Reviews recommendation and evidence',authority:'May change, stop, correct, and escalate',accountableOwner:'Named review supervisor',governingSource:'Applicable review and appeal procedure'}];
 const handoffs={market:'Public-benefits service delivery',regulatedActivity:'AI-assisted application prioritization',affectedPeople:people.map(p=>p.label).join(', '),organizations,handoffs:[{id:'H-1',from:'agency',to:'review',subject:'Recommendation plus source evidence',responsibility:'Agency preserves evidence; reviewer owns disposition',evidencePackage:'Intake record, rationale, version, and test status',permissionBasis:'Applicable program purpose and authority',acceptanceTest:'Reviewer confirms identity, evidence, version, and scope',deadline:'Review before any consequential action',incidentDuty:'Stop, investigate, notify, and correct',record:'Append-only decision and correction record',recourse:'Applicant correction, review, and appeal path'}]};
 return {workflow,handoffs};
}
export default function HumanConsequenceLab(){
 const [people,setPeople]=useState(basePeople);const [selected,setSelected]=useState(0);const current=people[selected];
 const assessment=useMemo(()=>{const inherited=fixtures(people);return assessHumanConsequences({...inherited,people})},[people]);
 function toggle(key:'notice'|'represented'|'recourse'){setPeople(v=>v.map((p,i)=>i===selected?{...p,[key]:!p[key]}:p))}
 function download(){const report={build:'022',engineVersion:assessment.engineVersion,fixture:'synthetic',generatedInBrowser:true,canonical:{title:'Human Consequence Map for AI Workflows',job:'Show who can be affected by an AI workflow and how consequences travel to them.',bWeb:'Human impact nodes light up as workflow assumptions change.',uses:['012','013','017']},derivedInterfaceCopy:true,people,assessment,boundary:'This map identifies investigation and design gaps; it does not predict individual harm, establish causation, or determine legal compliance.'};const href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=href;a.download='human-consequence-map.json';a.click();setTimeout(()=>URL.revokeObjectURL(href),0)}
 return <section className={s.lab}><div className={s.summary} role="status" aria-live="polite" aria-atomic="true"><span>MAP STATUS / {assessment.affectedNodeCount} IMPACT NODES</span><h2>{assessment.status}</h2><p>Exposure signal {assessment.exposureScore}/100 · {assessment.gaps.length} disclosed gaps. This prioritization signal is a derived product heuristic, not a prediction of harm.</p></div><div className={s.workspace}><aside aria-label="Human impact nodes"><h3>AFFECTED PEOPLE / SYNTHETIC FIXTURE</h3>{people.map((p,i)=><button key={p.id} className={i===selected?s.selected:''} aria-pressed={i===selected} onClick={()=>setSelected(i)}><small>{p.id} · {p.proximity}</small><b>{p.label}</b><span>{[p.notice,p.represented,p.recourse].filter(Boolean).length}/3 protections recorded</span></button>)}</aside><article><p className={s.kicker}>TRACE / {current.proximity}</p><h3>{current.label}</h3><p>{current.consequence}</p><fieldset><legend>Can these people see and shape the path?</legend><label><input type="checkbox" checked={current.notice} onChange={()=>toggle('notice')}/><span><b>Meaningful notice exists</b><small>They can understand where AI affects the workflow and what the notice means.</small></span></label><label><input type="checkbox" checked={current.represented} onChange={()=>toggle('represented')}/><span><b>Affected-person knowledge is represented</b><small>Design and review include lived or directly affected expertise rather than assuming it.</small></span></label><label><input type="checkbox" checked={current.recourse} onChange={()=>toggle('recourse')}/><span><b>Correction or recourse exists</b><small>A named, usable path can correct evidence, challenge an outcome, and obtain response.</small></span></label></fieldset><dl><div><dt>Consequence controls · Build 012</dt><dd>Severity and affected-person controls rise with the bounded use.</dd></div><div><dt>Workflow propagation · Build 013</dt><dd>The map inherits the workflow path and its uncontrolled propagation checks.</dd></div><div><dt>Institutional transfer · Build 017</dt><dd>Notice, responsibility, evidence, acceptance, incident duty, and recourse survive the handoff.</dd></div></dl></article></div><footer className={s.footer}><p>{assessment.inheritedWorkflowStatus} · {assessment.inheritedHandoffStatus}</p><div><button onClick={()=>{setPeople(basePeople);setSelected(0)}}>RESET</button><button onClick={download}>EXPORT MAP</button></div></footer><p className={s.note}><b>Canon boundary:</b> title, job, B-Web sentence, and lineage are frozen canon. The question, thesis, fixture, exposure formula, thresholds, labels, and explanatory interface copy are derived implementation copy. Everything runs client-locally; no data is submitted or retained.</p></section>
}
