'use client';
import{useState}from'react';
import{buildPersonalKnowledgeModel,PERSONAL_KNOWLEDGE_SCENARIOS,PERSONAL_KNOWLEDGE_MODEL_ENGINE_VERSION,type PersonalKnowledgeScenarioId}from'../../../../../../packages/release/src/personal-knowledge-model-engine';
import s from'../personal-model.module.css';

const ids:PersonalKnowledgeScenarioId[]=['MODEL-BOUNDARIES-CLEAR','CONSENT-WITHHELD','CONTEXT-EXPIRED','OWNERSHIP-UNDECLARED','INFERENCE-BLOCKED'];
const label=(value:string)=>value.replaceAll('-',' ');

export default function PersonalKnowledgeModel(){
 const[id,setId]=useState<PersonalKnowledgeScenarioId>('MODEL-BOUNDARIES-CLEAR'),input=PERSONAL_KNOWLEDGE_SCENARIOS[id],result=buildPersonalKnowledgeModel(input);
 const groups=[['KNOWLEDGE',result.knowledge],['PREFERENCES',result.preferences],['VALUES',result.values],['ROLES',result.roles],['RELATIONSHIPS',result.relationships],['PERMISSIONS',result.permissions],['CONTEXT',result.contexts]]as const;
 function download(){const snapshot={build:'067',version:PERSONAL_KNOWLEDGE_MODEL_ENGINE_VERSION,fixture:'synthetic',exportedAt:input.assessedAt,canonical:{title:'Personal Knowledge Model & Digital Identity Layer',visualTitle:'A Digital Twin Should Know What It Does Not Own',uses:['023','024','029','035','036','058'],creates:'cap:067'},admission:{containsRealPeople:false,containsPersonalData:false,identityVerified:false,persistence:'NONE',surveillance:'NONE',ownershipDetermination:false,consentDetermination:false,psychologicalProfiling:false,undeclaredInference:false,legalRightsDetermination:false,truthClaim:false,authorityClaim:false,authorizationClaim:false},input:structuredClone(input),result:structuredClone(result),replay:{scenarioId:id,engineVersion:PERSONAL_KNOWLEDGE_MODEL_ENGINE_VERSION},boundaries:['Declared and inferred information remain distinct.','Withheld permission, expired context, undeclared ownership, and blocked inference remain held.','A model entry is not proof of identity, ownership, consent validity, legal rights, truth, authority, or authorization.']};const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='synthetic-personal-knowledge-model.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
 return <section className={s.lab} aria-labelledby="model-status" data-model-state={id}>
  <header className={s.status} role="status" aria-live="polite" aria-atomic="true"><small>MODEL STATE · {label(id)}</small><h2 id="model-status">{result.status}</h2><p>{result.nonClaims[0]??'No claim is made beyond this fixed synthetic fixture.'}</p></header>
  <div className={s.controls} aria-label="Personal knowledge model controls"><label htmlFor="model-state">MODEL STATE<select id="model-state" value={id} onChange={event=>setId(event.target.value as PersonalKnowledgeScenarioId)}>{ids.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><button type="button" onClick={()=>setId('MODEL-BOUNDARIES-CLEAR')}>RESTORE BOUNDED MODEL</button><button type="button" onClick={download}>EXPORT PERSONAL MODEL</button></div>
  <aside className={s.warning} aria-label="Personal model limitations"><h3>A model entry is not a right to use it.</h3><p>Do not enter real, identifying, private, sensitive, clinical, legal, employment, financial, relationship, or account information. This fixed demonstration stores nothing and watches no one.</p></aside>
  <div className={s.boundaryGrid} aria-label="Model governance boundaries"><article><small>DECLARED</small><p>What the synthetic subject explicitly stated remains labeled as declared.</p></article><article><small>INFERRED</small><p>Inference remains separate, contestable, and blocked unless the fixture permits it.</p></article><article><small>PERMISSION</small><p>Scope, purpose, recipient, context, and state travel with each permission.</p></article><article><small>OWNERSHIP</small><p>Possession or visibility does not establish ownership, rights, or authority.</p></article></div>
  <div className={s.model} aria-label="Fixed synthetic personal knowledge model">{groups.map(([title,items])=><article key={title}><small>{title}</small>{items.length?<ul>{items.map(item=><li key={item}>{item}</li>)}</ul>:<p>None recorded.</p>}</article>)}</div>
  <section className={s.split} aria-label="Usable and held model connections"><article><h3>Usable in this fixture</h3><ul>{result.usable.length?result.usable.map(item=><li key={item}>{item}</li>):<li>None.</li>}</ul></article><article><h3>Held from use</h3><ul>{result.held.length?result.held.map(item=><li key={item}>{item}</li>):<li>None.</li>}</ul></article></section>
  <aside className={s.provenance} aria-label="Model provenance"><h3>Recorded provenance</h3><ul>{result.provenance.map(item=><li key={item}>{item}</li>)}</ul></aside><aside className={s.unknowns} aria-label="Model unknowns"><h3>What the model does not know</h3><ul>{result.unknowns.map(item=><li key={item}>{item}</li>)}</ul></aside>
  <p className={s.note}><b>Boundary:</b> This fixed synthetic model does not verify identity and does not persist, monitor, score, or surveil. It makes no ownership or consent determination, legal-rights decision, psychological profile, truth claim, authority claim, or authorization.</p>
 </section>
}
