export const publicArchiveDocuments=[
 'docs/100-cycle-master-syllabus.md',
 'docs/100-build-execution-feasibility-architecture-audit.md',
 'docs/100-builds-strategic-value-audit.md',
 'docs/canonical-sequence-completeness-audit.md',
 'docs/CANONICAL-100-V1-FROZEN.md',
 'docs/build-release-standard-v1.md',
 'docs/build-archive-standard-v1.md',
 'docs/exhibition-space-design-system.md',
 'docs/public-site-reskin-architecture.md',
 'docs/visual-builds-handoff.md',
 'docs/infrastructure-manifest.json',
 'data/build-001-evidence-v1.json',
 'data/build-001-003-acceptance-v1.json',
 'data/build-001-003-artifacts-v1.json',
 'data/build-001-003-freshness-performance-v1.json',
 'data/build-001-003-privacy-support-v1.json',
 'docs/builds/001/SPEC.md',
 'docs/builds/001-release-record.md',
 'docs/builds/001-003-certification-ledger.md',
 'docs/builds/001-003-linkedin-artifact-manifest.json',
 'docs/builds/001-003-linkedin-production-specs.md',
 'docs/builds/001-003-security-review.md',
 'data/build-002-engine-v1.json',
 'docs/builds/002-public-record.md',
 'docs/builds/002-release-record.md',
 'data/build-003-engine-v1.json',
 'docs/builds/003-public-record.md',
 'docs/builds/003-release-record.md',
 'data/build-004-engine-v1.json',
 'data/build-004-acceptance-v1.json',
 'data/build-004-artifacts-v1.json',
 'data/build-004-privacy-support-v1.json',
 'data/build-004-freshness-performance-v1.json',
 'docs/builds/004-release-record.md',
 'docs/builds/004-linkedin-production.md',
 'tests/build004.spec.ts',
 'tests/build004-story.spec.ts',
 'tests/build004-routing.spec.ts',
 'data/build-005-engine-v1.json',
 'data/build-005-acceptance-v1.json',
 'data/build-005-privacy-support-v1.json',
 'data/build-005-freshness-performance-v1.json',
 'docs/builds/005-release-record.md',
 'docs/builds/005-linkedin-production.md',
 'tests/build005.spec.ts',
 'data/build-006-engine-v1.json',
 'data/build-006-privacy-support-v1.json',
 'data/build-006-freshness-performance-v1.json',
 'docs/builds/006-linkedin-production.md',
 'tests/build006.spec.ts',
 'data/linkedin-film-specs-v1.json',
 'docs/builds/linkedin-media-manifest-v2.json',
 'docs/builds/001-006-archive-media-backfill-certification.md'
] as const;

export const publicArchiveDocumentSet=new Set<string>(publicArchiveDocuments);
export function archiveSourceHref(path:string){return publicArchiveDocumentSet.has(path)?`/100-builds/archive/source/${path}`:null;}
