#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const root=path.resolve(process.argv[2]||'repo-media-generator/output');const failures=[],manifest=[];
const words=s=>s.match(/[\p{L}\p{N}]+(?:[’'-][\p{L}\p{N}]+)*/gu)||[];
for(let n=1;n<=100;n++){const id=String(n).padStart(3,'0'),dir=path.join(root,id),prefix=`build-${id}-linkedin`,names=[`${prefix}.mp4`,`${prefix}-poster.png`,`${prefix}-captions.vtt`,`${prefix}-transcript.txt`];
  if(!fs.existsSync(dir)){failures.push(`${id}: missing directory`);continue}const actual=fs.readdirSync(dir);if(actual.length!==4||actual.some(x=>!names.includes(x)))failures.push(`${id}: output is not exactly four public assets`);for(const name of names)if(!fs.existsSync(path.join(dir,name)))failures.push(`${id}: missing ${name}`);if(names.some(x=>!fs.existsSync(path.join(dir,x))))continue;
  const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_entries','format=duration:stream=codec_name,pix_fmt,width,height','-of','json',path.join(dir,names[0])],{encoding:'utf8'})),duration=Number(probe.format.duration),stream=probe.streams[0];
  const video=fs.readFileSync(path.join(dir,names[0])),poster=fs.readFileSync(path.join(dir,names[1]));if(Math.abs(duration-30)>0.001)failures.push(`${id}: duration ${duration}, expected 30.000`);if(stream.codec_name!=='h264'||stream.pix_fmt!=='yuv420p'||stream.width!==720||stream.height!==900)failures.push(`${id}: invalid video format`);if(video.indexOf(Buffer.from('moov'))>video.indexOf(Buffer.from('mdat')))failures.push(`${id}: MP4 is not fast-start`);if(poster.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')failures.push(`${id}: invalid PNG poster`);
  const vtt=fs.readFileSync(path.join(dir,names[2]),'utf8'),transcript=fs.readFileSync(path.join(dir,names[3]),'utf8'),cues=[...vtt.matchAll(/\d+\n\d\d:\d\d:\d\d\.\d{3} -->/g)],scenes=[...transcript.matchAll(/^(?:SCENE\s+)?\d+(?:[.:]|$)/gm)];if(cues.length!==6)failures.push(`${id}: ${cues.length} VTT cues`);if(scenes.length!==6)failures.push(`${id}: ${scenes.length} transcript scenes`);
  const cueTexts=vtt.split(/\n\n/).slice(1).map(x=>x.split(/\n/).slice(2).join(' '));cueTexts.forEach((x,i)=>{if(words(x).length>15)failures.push(`${id}: cue ${i+1} has ${words(x).length} words`)});
  manifest.push({id,assets:Object.fromEntries(names.map(name=>[name,{bytes:fs.statSync(path.join(dir,name)).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,name))).digest('hex')}]))});}
fs.writeFileSync(path.join(root,'generated-manifest.json'),JSON.stringify({schemaVersion:1,builds:manifest,failures},null,2)+'\n');console.log(JSON.stringify({builds:manifest.length,failures},null,2));if(failures.length)process.exit(1);
